### ISSUE TITLE
Apple Mail Module 3.0.0: signature no longer inserted into Composed messages

### ISSUE THREAD

**Issue by genegoykhman** [quicksilver/Quicksilver#1073]
In older versions of this plug-in, using the Apple Mail "Compose E-mail" action would open a new mail message with my default signature already inserted into the body of the message. After upgrading to B69 (64-bit) and Apple Mail Module 3.0.0, new messages are opened completely blank. It would be nice to restore the signature insertion if possible.

**Comment by pjrobertson** [comment]
Unfortunately Apple has restricted the use of Apple Mail for 'security' reasons. As such, we've had to disable the Apple Mail plugin. If Apple ever allow access to the Mail settings in the future, we can revisit this.
