### ISSUE TITLE
Convert user guide to HTML and possibly link to it from QS 

### ISSUE THREAD

**Issue by studgeek** [quicksilver/Quicksilver#1083]
I just thought I throw this idea out there for discussion. I personally I avoided the user guide because it was a "big, slow to download PDF". When I finally did read it I was amazed at how much knowledge was in it. I worry that many other new people are skipping this key introduction to QS because of its format and are instead thinking the documentation is limited since they just see the wiki. 

If we could get it converted to HTML (optimally as a wiki that can continue to be updated) we would have a linkable resource that could be referenced from forums and blogs. It also would bump SEO and therefore awareness of Quicksilver can do.

Longer term I could see arriving at a point where we could link object types, actions, catalogs, and plugins to their wiki page which be awesome for people just learning QS. They could just do F1 and be taken to a wiki page that starts to introduce them to what they can do with that item.

There seem to be some options for doing in an automated fashion. http://www.appropedia.org/Help:Porting_PDF_files_to_MediaWiki. I'll add I have Acrobat Pro (CS3) if you want me to do that step.

**Comment by pjrobertson** [comment]
See #2200 now for the latest info on the web-hosted user guide. It's being converted into Markdown and inserted into the GitHub wiki.
