### ISSUE TITLE
ß69 (3932) is unable to open a service app: /Library/Services/ejectEveryDisk.app

### ISSUE THREAD

**Issue by juanfal** [quicksilver/Quicksilver#1092]
You can open/execute it on the Terminal without problems:

  open /Library/Services/ejectEveryDisk.app

but dropping it as a new hotkey trigger in "select item" slot and then assigning a shortcut, when you press the shortcut it doesn't do anything.

**Comment by pjrobertson** [comment]
Hi @juanfal 

It's been a while since we heard back from you on this issue, so we're going to close this now.

If you're still facing problems, feel free to open a new issue. Thanks!
