### ISSUE TITLE
 Quicksilver Search Invisible until relaunch or open another Quicksilver Window

### ISSUE THREAD

**Issue by cjguitar** [quicksilver/Quicksilver#1170]
Since Lion, and now in Mountain Lion, the Quicksilver Search Window is invisible after starting up a computer (I have Quicksilver enable to launch on startup), even when invoking the key command to bring it to the front (for me it's Control+Space). In order to get it to show again I have to go to the menu item and click About Quicksilver, or I relaunch Quicksilver. I keep thinking this will get fixed in an update and it never does, it's been happening for almost two years for me. I also thought it was my computer, but I now have 4 computers showing this behaviour (One new MacBook Pro and 3 New MacPro towers). All of them are on Mountain Lion here.

**Comment by ascomycota** [comment]
Maybe you should uncheck this checkbox when installing your app?
