### ISSUE TITLE
"Open" uses wrong application for a particular file

### ISSUE THREAD

**Issue by lorin** [quicksilver/Quicksilver#1202]
I have a file called inbox.taskpaper that I want to be opened by default using the TaskPaper app. When I open it using the "Open" action in Quicksilver, it uses FoldingText instead. 

I have confirmed that the file is associated with TaskPaper in Finder, and it opens in TaskPaper when I double-click the file in Finder or do `open inbox.taskpaper` at a shell prompt. In addition, I don't have this problem with any other files with the taskpaper extension.

How do I tell QuickSilver to change the default app associated with that file?

(Note that "Open with..." "Taskpaper" works just fine).

**Comment by joshgold22** [comment]
I have a pretty similar problem that was not cured by deleting the caches and restarting.  When I open the ~/Downloads folder with QS, Powerpoint launches and opens a new document.  As above, Open with... works fine (and defaults to Finder), as does double-clicking in Finder.  This is a new problem, about a week old, never seen in years of use.

**Comment by pjrobertson** [comment]
Hi @joshgold22  - this issue is over 14 years old and may no longer apply. Can you please open a new issue and provide as much information as possible. screenshots and step-by-step processes y ou are taking to see the issue will help
