### ISSUE TITLE
"Run at time" action cannot schedule tasks past midnight!

### ISSUE THREAD

**Issue by calc** [quicksilver/Quicksilver#1220]
If I schedule a task at a time that does not lie between the current time and midnight, it executes immediately. Hence a task scheduled, say at 1am, when the current time is 11pm, does not work. Another example is scheduling a task at 1pm, when the current time is 2pm.

**Comment by pjrobertson** [comment]
It took us a while, but this will be fixed in the next version. Thanks for the report @calc  :)
