### ISSUE TITLE
Groups (i.e. folders) for Triggers don’t work at all

### ISSUE THREAD

**Issue by jackbrannen** [quicksilver/Quicksilver#135]
For instance, in the Triggers window, trying to move a trigger into a group has no effect.

**Comment by gdvine** [comment]
This appears to still be broken. User can create a group, but cannot drag Triggers into it.

**Comment by MonkeyBars3k** [comment]
This issue still exists... going on nearly 12 years

**Comment by pjrobertson** [comment]
For the meantime, we have removed the option to create 'groups' for triggers, as it still does not work.

**Comment by MonkeyBars3k** [comment]
Shouldn't the status be "Won't fix" rather than Closed?

**Comment by pjrobertson** [comment]
Sure, that makes sense. Thanks

**Comment by borgo1971** [comment]
R.I.P... If they was working, they could be very nice to organise triggers...
Note: I'm here because using QS 2.2.2, I wanted to open the issue. Now I'll update :-(
