### ISSUE TITLE
Restoring focus

### ISSUE THREAD

**Issue by skurfer** [quicksilver/Quicksilver#1351]
Continuing a [discussion](https://groups.google.com/forum/#!topic/blacktree-quicksilver/xpFqxGy0wfc) from the mailing list…
### What gets an application into this state?
- Running the Get Selection service
- Opening the preferences window
### What can we do about it?

When this happens, it seems to be the case that Quicksilver has focus (with no visible windows), regardless of what the menubar shows. I've been able to fix it by running `Previous Application ⇥ Open`, so the question is: Can we do the same thing when automatically when certain windows close (in `windowDidClose` or something)?

We can't do it across the board for all QS windows. For instance, if you had the Task Viewer set to show automatically, it would open then close and switch applications at random times. Same for the built-in notifier.

Another complication is that running the service triggers the main interface, but switching applications when the main interface closes is _usually_ not the right thing, so we can't do it unconditionally. Checking to see if Quicksilver is the current application might help, but you could have multiple windows open when closing one, so that won't always work either.

**Comment by pjrobertson** [comment]
Note: the above change fixed the bug when you use the the service (⌘⎋), however it still appears to be an issue if you select the 'Current Selection' proxy object in the 1st pane. This will be more tricky to solve, since the interface is already visible.
