### ISSUE TITLE
Plugin Renaming Suggestions

### ISSUE THREAD

**Issue by hmelman** [quicksilver/Quicksilver#1355]
All plugins should end with one of: Interface, Notifier, Plugin, Ranker, Support, Triggers

As such, the following changes need to be made:
- [x] Google Chrome -> Google Chrome Plugin
- [x] QSQRCode -> QRCode Plugin
- [x] iTerm2 -> iTerm2 Plugin
- [x] OpenMeta File Tagging -> OpenMeta Tagging Plugin
- [x] Remember The Milk -> Remember The Milk Plugin

---
- [x] Calculator Module -> Calculator Plugin
- [x] Developer Module -> Developer Plugin
- [x] File Compression Module -> File Compression Plugin
- [x] Firefox Module -> Firefox Plugin
- [x] Yojimbo Module -> Yojimbo Plugin

---
- [x] File Attribute Actions -> File Attribute Plugin
- [x] Image Manipulation Actions -> Image Manipulation Plugin
- [x] Process Manipulation Actions -> Process Manipulation Plugin
- [x] Screen Capture Actions -> Screen Capture Plugin
- [x] Text Manipulation Actions -> Text Manipulation Plugin

---
- [x] Mini-Bezel -> Mini-Bezel Interface
- [ ] Notification Hub -> Notification Support
- [x] Command Line Tool (qs) -> Command Line Tool

**Comment by pjrobertson** [comment]
All these plugins have since been renamed, the changes will show up as we work through updating the plugins for Apple Silicon.

Thanks!
