### ISSUE TITLE
Typo in iTerm 2 doc

### ISSUE THREAD

**Issue by hmelman** [quicksilver/Quicksilver#1372]
The documentation for the iTerm 2 plugin lists the action Open Directory in iTerm twice. I think the second should be Open Directory in iTerm Tab.

**Comment by pjrobertson** [comment]
This was fixed and released by ndreas all that time ago. We just never got round to closing this :)

https://github.com/quicksilver/iTerm2-qsplugin/commit/829c0e8bdf4400bb3972cab86777e0b9aecdc662
