### ISSUE TITLE
Displaying Contacts with nicknames truncated in most interfaces

### ISSUE THREAD

**Issue by hmelman** [quicksilver/Quicksilver#1391]
The recent (B71?) changes to displaying labels vs names has made contacts with nicknames display oddly in most interfaces, particularly Bezel.

As an example. I have a Contact:
First: Mike
Last: Daninhirsch
Nickname: Doof

If I search for Mike the result in bezel's first pane is "Mike Daninhirsch"
If I search for Doof the result in bezel's first pane is "Mike Danin…f Daninhirsch" which is kinda useless.

It used to show "Doof Daninhirsch" (it does in the manual :) and I think it should again. If the nickname has a space in it, then it should just show the nickname, without appending the last name.

I've always found it odd that Contacts displayed "company" in the details field. In this case perhaps that could be used to display the full name. Also it seems QS doesn't index Maiden name. That would be nice and it should display similar to how I'm describing nickname.

This isn't a problem in wide interfaces like Primer, Nostromo and Window but it is in all the rest (Bezel, Bezel Classic, Cube, Flashlight, Menu, Mini and Mini-Bezel).

![Screen Shot 2013-02-13 at 3 30 09 PM](https://f.cloud.github.com/assets/1999190/154453/a3d9a534-761c-11e2-9d3d-a7d5f78b9b91.png)

**Comment by skurfer** [comment]
OK, @hmelman. If you set the update type to Developer Previews and get the latest update, there should be a new preference to take care of this.

Go to Preferences → Appearance and uncheck “Always Show Name”.

**Comment by hmelman** [comment]
Fantastic.
