### ISSUE TITLE
No reindexing with 10.6.8 and Beta71 (3942)

### ISSUE THREAD

**Issue by Jurek-Raben** [quicksilver/Quicksilver#1392]
Since some weeks, Quicksilver does not reindexing my Applications at all. Even I click on the indexing arrow for manual reindexing under catalog tab, nothing happens :(

So I disabled the default "Applications" search location and added Applications under user sub-tab. Also only searching for "app" and dir depth of 3. Now Quicksilver finds my new apps :)  

Maybe there is something wrong with the directory depth of the default applications search location?

**Comment by pjrobertson** [comment]
Hi @Jurek-Raben 

It's been a while since we heard back from you on this issue, so we're going to close this now.

If you're still facing problems, feel free to open a new issue. Thanks!
