### ISSUE TITLE
Freeze on launch

### ISSUE THREAD

**Issue by benjythehunted** [quicksilver/Quicksilver#1393]
Updated QS as prompted a few days ago, and now I just get the QS start logo, and then app freezes.  Console.app says:

2/15/13 10:51:26.141 PM Quicksilver[4842]: An error ocurred while scanning "Chrome Bookmarks": -[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x1078cbf20

What can I do?

Thanks...

MBP Retina running 10.8.2

**Comment by pjrobertson** [comment]
Hi @benjythehunted 

It's been a while since we heard back from you on this issue, so we're going to close this now.

If you're still facing problems, feel free to open a new issue. Thanks!
