### ISSUE TITLE
"Get Current Selection" has been accidentally renamed "Get Current Selection (Do Not Change Shortcut)"

### ISSUE THREAD

**Issue by clarkewd** [quicksilver/Quicksilver#1400]
For some reason "Get Current Selection" has been accidentally renamed "Get Current Selection (Do Not Change Shortcut)" which has broken my custom shortcut that I use ( Cmd+G) since I remapped it using the Keyboard Shortcut Pref Pane

<img src="http://img405.imageshack.us/img405/4166/screenshot20130219at104.png" alt="Screen shot 2013-02-19 at 10.49.33 PM.png" />

No longer works because the menu item named changed:

<img src="http://img11.imageshack.us/img11/5673/picture1ivn.png" />

**Comment by Calorion** [comment]
So what do I do about the fact that this item appears in my Services menu?

**Comment by skurfer** [comment]
> So what do I do about the fact that this item appears in my Services menu?

If you don’t want it there, you can disable it under System Preferences → Keyboard → Shortcuts → Services (but I think that will prevent it from working).

If you just don’t like the name, I would be open to removing “ (Do Not Change Shortcut)” from the end if you want to submit a pull request. I don’t know how many people we’re saving from a broken service by having that there.
