### ISSUE TITLE
Miscellaneous hang up, sample taken

### ISSUE THREAD

**Issue by mburer** [quicksilver/Quicksilver#1421]
Quicksilver had a bad hang up on me recently, taking over 5GB of memory. I do not remember anything particular I did which caused it, nor has it reoccurred. Here is a link to the process sample I took with Activity Monitor.

https://dl.dropbox.com/u/9767614/Sample%20of%20Quicksilver.txt

Thanks!

**Comment by pjrobertson** [comment]
It took us a while to get to this, sorry. Unfortunately the original file is no longer available.

If you're still experiencing this problem, please open a new issue with a newer sample. Thanks!
