### ISSUE TITLE
Update doesn't seem to actually install

### ISSUE THREAD

**Issue by Hedrik** [quicksilver/Quicksilver#1423]
MacOS X 10.8.2
QuickSilver ß70 (3935)

Every hour or so (?) and/or every reboot, QuickSilver asks to update itself.  Even after I allowed it to update already.  Also, if I cancel the update request, the 'Task Viewer' modal dialog remains open and I cannot close it.  I mention that here rather than as a new issue because it may be related.

**Comment by pjrobertson** [comment]
There were various issues with the updater in earlier versions of Quicksilver. Please try the latest version, and if you're still experiencing the problem then create a new issue on GitHub

Thanks!
