### ISSUE TITLE
Terminal Plugin Issues

### ISSUE THREAD

**Issue by bwaang** [quicksilver/Quicksilver#1427]
In the latest 2.3.0, whatever changes were made has broke the following - these seem to be regressions as they were working in the previous version.  (Also in the meantime is there a possible way to have older Terminal plugin available, this is hindering a lot of automation that I do on my machine... it would help greatly if I could revert to an older version)
- Executable shell files (chmod +x) that do not have a specific extension is not recognized by the plugin as a runnable files, thus Run [...] or Run in Terminal [...] does not show up as valid actions anymore - files need to have explicit (e.g. *.sh) extension it seems, which is not the case for any of the built in Terminal commands.

![cant-run-script](https://f.cloud.github.com/assets/3912116/276872/0887223a-90b8-11e2-97c3-dcbbd14f0581.png)
- Executing scripts that require arguments no longer works, it seems to be executing the scripts without any arguments even if I supply arguments in the third pane.

![ignored-arg](https://f.cloud.github.com/assets/3912116/276876/1f9150b8-90b8-11e2-9a17-badbb583dd52.png)
- The *.scpt files, Apple Script files no longer have AppleScript Editor as a valid action, even though AppleScript Editor application still exists on the system

![no-editor-action](https://f.cloud.github.com/assets/3912116/276877/226d582c-90b8-11e2-9241-833314fcfd5c.png)
![apple-script-editor-exists](https://f.cloud.github.com/assets/3912116/276881/304375f8-90b8-11e2-9b28-c485395f231e.png)

Thank you for continuing development on this product, but I would hate to see things get worse and less useable as development continues, especially regressions would be the most tragic thing to see when things stop working as it once did.

**Comment by pjrobertson** [comment]
This is fixed in later versions of Quicksilver. Thanks!
