### ISSUE TITLE
Altering colors in custom appearance causes crash

### ISSUE THREAD

**Issue by mgbellaire** [quicksilver/Quicksilver#1445]
I was customizing my theme (currently in the Flashlight interface option) and while I was changing the darkness in the color of the first of the "headers", the app crashed.  

If you need any other important information that might help diagnose the problem, i'll try my best to check this issue.

-- Mark "Justin"

**Comment by pjrobertson** [comment]
We'd really need a crash report to fix this, so I'll close this now. Hopefully the crash has been fixed over the past 3 years. If you're still having problems then please submit the crash report!
