### ISSUE TITLE
Command Window in Text Mode trigger only works once Reset Search After delay has expired

### ISSUE THREAD

**Issue by Sesquipedalian** [quicksilver/Quicksilver#1458]
If I invoke QS normally and type into the first pane to bring up a catalogue item, the Command Window in Text Mode trigger will not work until the Reset Search After timeout period has passed. Invoking the trigger during this time fails, producing the attached error messages in the log.

Now, if the delay is set to something short, like 1.0 seconds, this error is rarely noticeable. But if the Reset Search After option is turned off completely, it can be a real pain in the butt, because the trigger remains nonfunctional until the user clears the first pane manually.

Error messages from Console:

2013-04-02 2:53:15.742 PM Quicksilver[39454]: **\* Assertion failure in -[NSEvent charactersIgnoringModifiers], /SourceCache/AppKit/AppKit-1187.37/AppKit.subproj/NSEvent.m:1904
2013-04-02 2:53:15.743 PM Quicksilver[39454]: An uncaught exception was raised
2013-04-02 2:53:15.744 PM Quicksilver[39454]: Invalid message sent to event "NSEvent: type=SysDefined loc=(602,373) time=550033.4 flags=0x1c0129 win=0x0 winNum=0 ctxt=0x0 subtype=6 data1=22829792 data2=22829792"
2013-04-02 2:53:15.745 PM Quicksilver[39454]: (
    0   CoreFoundation                      0x00007fff96d2bb06 __exceptionPreprocess + 198
    1   libobjc.A.dylib                     0x00007fff961e03f0 objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff96d2b948 +[NSException raise:format:arguments:] + 104
    3   Foundation                          0x00007fff90a0dc82 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 189
    4   AppKit                              0x00007fff9243e96f -[NSEvent charactersIgnoringModifiers] + 179
    5   QSInterface                         0x000000010017703d -[QSSearchObjectView transmogrifyWithText:] + 476
)

**Comment by pjrobertson** [comment]
This appears to be related or similar to the issue discussed [here](https://github.com/quicksilver/Quicksilver/issues/2111#issuecomment-163249670).

If you're still facing an issue with the latest version of Quicksilver, please create a new issue.

Thanks!
