### ISSUE TITLE
Move Plugin Development Reference to Wiki?

### ISSUE THREAD

**Issue by lgarron** [quicksilver/Quicksilver#1463]
I suppose this is mostly up to @skurfer, but would it be reasonable to move the reference at http://projects.skurfer.com/QuicksilverPlug-inReference.mdown to http://qsapp.com/wiki/Plugin_Development_Reference ?

It's the only external link in [Developer Information](http://qsapp.com/wiki/Developer_Information) that "doesn't need to be".

A [simple conversion using pandoc](http://archive.garron.us/text/2013/Plugin_Development_Reference.mediawiki.txt) seems to work okay: [rendered preview](http://archive.garron.us/text/2013/Editing%20Plugin%20Development%20Reference%20-%20Quicksilver%20Wiki.html).

I don't mind too much (well, the rendering on skurfer's site is broken in Chrome for me right now, but that's minor), but I thought I'd bring it up.

**Comment by pjrobertson** [comment]
The Plugin Dev Ref is now available in Github, here: https://github.com/quicksilver/PluginDevelopmentReference/blob/master/QuicksilverPlug-inReference.md

I've also just published it as a Github pages, here: https://quicksilver.github.io/PluginDevelopmentReference/QuicksilverPlug-inReference

I think this is good enough for now, although I'd love to see it have an Index and Table of Contents. I think `jekyll` would be needed for that.

I'll close this for now

**Comment by n8henrie** [comment]
@pjrobertson This should be `QuicksilverPluginReference` or `QuicksilverPlugin-Reference` instead of `QuicksilverPlug-inReference`, right?  <https://github.com/quicksilver/PluginDevelopmentReference/blob/master/QuicksilverPlug-inReference.md>

**Comment by n8henrie** [comment]
Also we should probably 301 redirect <https://qsapp.com/wiki/PluginReference>

**Comment by n8henrie** [comment]
Also, <https://quicksilver.github.io/PluginDevelopmentReference/QuicksilverPlug-inReference> looks great!
