### ISSUE TITLE
Better support for Notes

### ISSUE THREAD

**Issue by skurfer** [quicksilver/Quicksilver#1466]
Options:
1. Teach the Mail plug-in about Notes so it can display them in a more useful way.
2. Tell the Mail plug-in to hide Notes folders just like the regular Mail interface does, then implement a separate Notes plug-in that indexes Notes and allows searching for them by name (and shows them when right-arrowing into `Notes.app`, etc.).

The latter is ideal for a number of reasons, but might take a bit longer.

**Comment by skurfer** [comment]
Notes aren’t in Mail any more.

**Comment by n8henrie** [comment]
Looked into this a little more -- there doesn't seem to be a MacOS API for accessing Notes. A few projects that have pretty hacky ways of accessing the sqlite database in which they're stored (`sqlite3 ~/Library/Group\ Containers/group.com.apple.notes/NoteStore.sqlite`).

Don't see a good way to use Notes.app with QS. ¯\\\_(ツ)_/¯

**Comment by pjrobertson** [comment]
Makes sense. I wouldn't expect Apple to come up with any decent API for this.

AppleScript is normally your best bet in this case, or Scripting Bridge. Rob's got a good writeup on that: https://github.com/quicksilver/PluginDevelopmentReference/blob/main/QuicksilverPlug-inReference.md#scripting-bridge

Here's the Notes.h file to get you started :) (change the extension to .h after downloading)


[Notes.h.txt](https://github.com/quicksilver/Quicksilver/files/9050967/Notes.h.txt)
