### ISSUE TITLE
support for context menu?

### ISSUE THREAD

**Issue by fly2never** [quicksilver/Quicksilver#1478]
As "Show menu items" supported in QS, can QS support context menu? Get the location of mouse cursor and show context menu items ?

**Comment by pjrobertson** [comment]
You can do this with cliclick: https://github.com/BlueM/cliclick

1. Download cliclick
2. Copy cliclick to a known folder on your computer (e.g. `/usr/local/bin/cliclick`)
3. Set up a trigger to run the following (assuming you chose `/usr/local/bin/cliclick` in the following step, if not - replace the path)
 * 1st Pane text: cliclick kd:ctrl c:+0,+0
 * 2nd pane: run command in shell

Alternatively, if you don't want it as a trigger, add the command to your Quicksilver catalog.

However, setting this up as a trigger is recommended. It will allow you to right click from anywhere using a keyboard shortcut:
![Screenshot 2022-02-22 at 14 53 38](https://user-images.githubusercontent.com/150431/155078431-df0bc920-6113-4e5b-b099-34b9f82a691e.png)
