### ISSUE TITLE
Changing Keyboard Layouts Doesn't Bring Trigger Bindings Along With It

### ISSUE THREAD

**Issue by timvisher** [quicksilver/Quicksilver#1482]
As we know, I'm a Dvorak user. I'm not sure what changed recently (I think it was actually an update to OS X), but lately if I switch keyboard layouts from Dvorak to Qwerty or vice versa, my triggers don't respond to the right keypress. Instead, they correspond to the positional key of the trigger.

For example:

I bind `⌘⌥^G` to Google Search. If I switch to Qwerty from Dvorak, I cannot press that keysequenc, but instead have to press `⌘⌥^U`. `U`, positionally, is where `G` is located in Dvorak.

I have not been able to tie down the exact context that this happens in either. Initially, I thought that it was related to Quicksilver being started up while the system was in Qwerty or Dvorak, but doing `⌘^Q` after having switched doesn't seem to fix things.

To make matters more interesting, the triggers, depending on what mode they're stuck in, will actually report themselves as being bound to the keycap of the key, rather than the logical key that I'm pressing.

FWIW, Moom.app also appears to be suffering from this problem.

Anything I can send along, just let me know!

Thanks as always for the second most impressive piece of software I've ever used.

**Comment by timvisher** [comment]
And I've been hit again. :)

Just got my fancy new Code keyboard and set it to Dvorak mode because how awesome is that? and then realized none of my triggers were working.

How're things going with this?

**Comment by robacarp** [comment]
@timvisher I see you've commented on most of the keyboard layout bugs...did you ever get an answer to the possible resolution of this bug? I recently started using a hardware dvorak keyboard as well, but when I unplug and switch to the system keyboard I have to relaunch quicksilver. The problem feels to me like triggers are being bound at the hardware level instead of the character level, but I suppose that could be just the way the ~~OSX~~ macOS handles things. 😢

**Comment by timvisher** [comment]
@robacarp There's no good answer in sight, afaict.

**Comment by skurfer** [comment]
We were pretty close to merging #1147 which should fix this, but there are some small things to work out still.

**Comment by pjrobertson** [comment]
Should be fixed by #2594
