### ISSUE TITLE
QS ignores certain keystrokes in first pane

### ISSUE THREAD

**Issue by highfalutin** [quicksilver/Quicksilver#1486]
Sometimes, Quicksilver does not register the typing of certain keyboard letters in the first pane. For example, it will ignore the "s" key: when I invoke QS and type "safari", only "afari" appears and QS searches for catalog items matching "afari".

Another example, with QS treating the "w" key strangely: When I invoke QS and type "download" (at normal speed), "do" appears normally, then nothing seems to happen when I hit the "w" key, but the rest of the word ("nload") appears on its own as if text entry had been reset (as if I had pressed the delete key).

Restarting QS fixes the problem temporarily.

Changing to a different keyboard layout (for example, Dvorak) does not change which keys are affected. In other words, if I am having a problem with the letter "w" in the USA keyboard layout, and I switch to Dvorak, I type a different key to get "w", and "w" appears in Quicksilver, but pressing the original key still results in problem behavior.

I have noticed this problem with the  s and w keys, and not with others, but I can't guarantee these are the only problem letters.

Using: QS 1.0.0 (4000) on 10.8.3

**Comment by pjrobertson** [comment]
Should be fixed by #2594
