### ISSUE TITLE
qs refuses to follow symlinks located in /applications

### ISSUE THREAD

**Issue by chdiza** [quicksilver/Quicksilver#1498]
Put some app outside of /applications, like ~/test/foo.app.  Now do:

    cd /applications
    ln -s ~/test/foo.app

And reload the catalog manually.  Observe that QS refuses to bring up 'foo.app' for opening.

Of course, if you add `~/test` explicitly to the catalog manually, QS will work.  But that defeats the purpose of symlinks.

Is there a good reason QS won't follow symlinks?  It seems awfully silly from the outside perspective.  By the same token, QS won't descend into folders that being with a dot, e.g., `/applications/.mystuff`, to discover applications like `/applications/.mystuff/something.app`.  Equally silly on the face of it.

**Comment by skurfer** [comment]
Fixed by #2142
