### ISSUE TITLE
QSCatalogEntry deadlock

### ISSUE THREAD

**Issue by tiennou** [quicksilver/Quicksilver#1513]
I'm ashamed to report that but...

https://www.dropbox.com/s/g00r2ke5uwz4pt2/QSCatalogEntry%20deadlock.txt

Deadlock between the main thread and the background scan queue.

I was fiddling with an Abracadabra trigger while it happened, but this seems unrelated, given the main thread is doing a catalog refresh from `VDKQueue`, and the background thread — most likely [this](https://github.com/quicksilver/Quicksilver/blob/master/Quicksilver/Code-QuickStepCore/QSObject_FileHandling.m#L529).

**Comment by skurfer** [comment]
I believe this was addressed by #2698
