### ISSUE TITLE
Event Triggers 'restrictions' need implementing

### ISSUE THREAD

**Issue by jxpx777** [quicksilver/Quicksilver#1557]
I created an event trigger to fire on the "Application Quit" event. I set the scope to only apply to Skype. What I want is for the trigger to fire when I quit Skype, to launch Dropbox when I am done using Skype. This is the other half of a trigger pair. The other, "Quit Dropbox when Skype launches" works great. Seems maybe the scope isn't properly catching because the application is quitting?

**Comment by skurfer** [comment]
The Match Items and Ignore Items for event triggers have been working for a long time now.
