### ISSUE TITLE
list of actions is slow and unresponsive

### ISSUE THREAD

**Issue by BeeryHolstein** [quicksilver/Quicksilver#1672]
1. Object: verbatim string
2. Type "Large Type" and wait(!) until you see list optional actions (in this case you will see only one option)
3. Ctrl-Enter

In the Object pane you now have Show "xxxxxx", and in the action you see list of actions (For me the first is "Run" and "Save Command to File ...."). 

Try to scroll down/up the options for actions. You will get the spinning wheel.

see https://groups.google.com/forum/#!searchin/blacktree-quicksilver/wheel/blacktree-quicksilver/0sOgSrYWWiA/Bmt3GOgjMs8J

**Comment by pjrobertson** [comment]
1.2.0 has since been released, and this issue should now be fixed.

Please try using the latest version of Quicksilver, and report back if you're still experiencing issues.

Thanks!
