### ISSUE TITLE
paste action beeps with Dvorak keyboard

### ISSUE THREAD

**Issue by treyharris** [quicksilver/Quicksilver#1679]
How I can reproduce:
1.  Install the Clipboard plugin
2.  Copy at least two things to the clipboard so there is a clipboard history
3.  Invoke Quicksilver
4.  Press a number to select an older clipboard item.

Expected result:
-  Item is pasted.

Actual result:
-  Item is pasted, but then there is a system beep.

This may be related to https://github.com/quicksilver/Quicksilver/issues/626. I, like the reporter of that closed issue, use a Dvorak keyboard, but switching to QWERTY did not change this behavior. (However, it's necessary to quit Quicksilver, switch keyboard layouts, then re-open Quicksilver to get it to use the correct key combo; switching layouts while Quicksilver is running seems to result in the Clipboard plugin becoming nonfunctional until you switch back.)

I am running 1.1.3 (4007) on Mavericks 10.9 on a Retina MBP 13", but I have gotten the same behavior on Mountain Lion on a Mac mini for quite some time. Since it's just a cosmetic (well, audible) issue and doesn't affect the functionality, I didn't bother to report it until now. Just the fact that it happened on a new, clean install made me wonder.

**Comment by pjrobertson** [comment]
Should be fixed by #2594
