### ISSUE TITLE
Quicksilver slow to "wake up" / "not responding"

### ISSUE THREAD

**Issue by hanspetermeyer** [quicksilver/Quicksilver#1687]
Quicksilver is slow to become active once I wake or restart my machine. Activity Monitor shows it's "not responding." After a while, it starts to work. 
If I quit QS and restart it, things are fine, until the next time.

I've deleted cache files, as instructed via @LoveQuicksilver on Twitter. Again, it helps. Until the next time.

This problem started when I moved to Mavericks.

hpm

**Comment by skoczen** [comment]
Another +1 to disabling contacts plugin makes things fast again here.  On 1.2.2.  

I dig that it's an unknown issue, but FWIW, I never use the contacts plugin.  I'm just happy to have the speed back!

**Comment by skurfer** [comment]
Can one or more of you try this experimental build (based on quicksilver/com.apple.AddressBook-qsplugin#10) and see if it fixes the problem?

If so, I’ll release a new official version.

**Comment by alien8ion** [comment]
Recently I've been seeing the same kind of behavior. I think it's been since upgrading to 10.10.4 but don't have any solid data to say it's definitely related to that.

The only plugins I have installed are:
Bezel Interface
Calendar Plugin
Firefox Plugin
Growl Notifier
HotKey Triggers
iTunes Plugin
Primer Interface

I've just tried disabling the Firefox Plugin, but I rely heavily on the iTunes Plugin (and likely the Growl Notifier)

the problem seems to happen randomly.

**Comment by ar-rm** [comment]
I think I'm running into something similar.

- Just upgraded to [1.5.2 (401D)](https://github.com/quicksilver/Quicksilver/releases/tag/build401D)
- Noticing there's now a ~1s delay before the QS window is dismissed.
- system.log:
```
Jan 19 12:59:44 WindowServer[225]: disable_update_timeout: UI updates were forcibly disabled by application "Quicksilver" for over 1.00 seconds. Server has re-enabled them.
Jan 19 12:59:45 WindowServer[225]: common_reenable_update: UI updates were finally reenabled by application "Quicksilver" after 1.50 seconds [0.67fps] (server forcibly re-enabled them after 1.00 seconds [1.00fps])
 ```
- Tried disabling "Contacts" plugin, running a `Force Catalog Rescan`, and restarting QS. Nothing helped.

I'm tempted to downgrade to [401A](https://github.com/quicksilver/Quicksilver/releases/tag/build401A), but I'll wait for a little bit to see if anyone has any other suggestions and debugging ideas.

Thanks.
