### ISSUE TITLE
Generic application icons haunt me

### ISSUE THREAD

**Issue by siracusa** [quicksilver/Quicksilver#1701]
I still get intermittent generic application icons shown when using Quicksilver 1.1.3 (4007), as described in <a href="https://github.com/quicksilver/Quicksilver/issues/1552">issue 1552</a>, but now sometimes they don't disappear.  I took the attached screenshot after partially typing to launch Interarchy.  The generic icon just stayed there—long enough for me to take a screenshot.  It never resolved to the actual Interarchy icon.  It just sat there, taunting me.  Down with generic application icons!

![screen shot 2013-12-04 at 10 58 40 am](https://f.cloud.github.com/assets/305253/1674752/ddce78aa-5cfd-11e3-9d1b-e2169f127a69.png)

**Comment by pjrobertson** [comment]
This is an old issue that should have been fixed in subsequent versions of Quicksilver. Thanks!
