### ISSUE TITLE
Preference window position broken after disconnecting external monitor

### ISSUE THREAD

**Issue by purcell** [quicksilver/Quicksilver#1720]
How to reproduce:
- With a large external monitor connected to a laptop, bring up QS preferences for the first time: window is in center of larger monitor.
- Close the preferences window
- Disconnect external monitor
- Open QS preferences

Expected result: preferences window should be displayed in the center of the laptop screen

Actual result: prefs window appears in the top right of the laptop screen, with the title bar off the screen and therefore not draggable.

Cheers!

-Steve

**Comment by tiennou** [comment]
Fixed by #2182. Please reopen if that's not the case !
