### ISSUE TITLE
Interface not centered after switching to/from external display (Cube interface)

### ISSUE THREAD

**Issue by randot** [quicksilver/Quicksilver#1744]
If Cube is centered on my 15" laptop, & then I connect 27" display, the next time I open QS it appears in lower left. If I recenter on the external display, the next time I launch it on the laptop it moves to the far top right. http://pic.twitter.com/66nkmtD9uf

Bezel interface works fine, maybe because it isn't draggable like Cube is? I'd be happy to lose draggability in Cube to keep it centered - don't want to drag it anyway.

Using QS 1.1.3 (4007) on OS X 10.9.1
I'd be comfortable copying and pasting code from another interface to patch my copy of Cube if that's possible, but I don't know how without instructions...

Thanks!

**Comment by pjrobertson** [comment]
Unfortunately Cube interface is no longer officially supported, and so will no longer be updated.
