### ISSUE TITLE
Can't type to get 'Finder Selection' or 'Current Selection' in pane 1

### ISSUE THREAD

**Issue by philostein** [quicksilver/Quicksilver#1781]
1.2.0 (4009) – but this has been happening for many versions.

This is what I see when typing 'Finder Selection' or 'Current Selection' in pane 1:

![window 2014-02-15 at 08 29 09](https://f.cloud.github.com/assets/535331/2176577/c72216c6-95d7-11e3-912c-9a166df6bfb2.png)
![window 2014-02-15 at 08 29 31](https://f.cloud.github.com/assets/535331/2176579/d1042bd4-95d7-11e3-9fc3-2e7cb0442c85.png)

The proxy objects are checked in the catalog:
![screen shot 2014-02-15 at 08 31 36](https://f.cloud.github.com/assets/535331/2176583/fbfc65ae-95d7-11e3-99c8-69d7db5022a4.png)

I can double-click the catalog entries in the Contents pane of Proxy Objects and have the proxies appear in pane 1, which enables me to create triggers with them (that stick). 

It'd be nice to be able to type 'cs' or 'fs' and have the proxies show up in pane 1 for general use. :)

**Comment by pjrobertson** [comment]
This issue is fixed in #2670

It should be in version 2.1.0 of Quicksilver
