### ISSUE TITLE
regular crashing on Mavericks

### ISSUE THREAD

**Issue by malhal** [quicksilver/Quicksilver#1782]
Thread 10 Crashed:: Dispatch queue: com.apple.root.low-priority
0   libobjc.A.dylib                 0x00007fff89c0f097 objc_msgSend + 23
1   com.apple.CoreFoundation        0x00007fff89e47be8 -[__NSSetM addObject:] + 408
2   com.blacktree.QSCore            0x000000010618d8ad -[QSObject(Icon) loadIcon] + 94
3   com.blacktree.QSCore            0x00000001061856b6 __25-[QSIconLoader loadIcons]_block_invoke + 440
4   libdispatch.dylib               0x00007fff889941d7 _dispatch_call_block_and_release + 12
5   libdispatch.dylib               0x00007fff889912ad _dispatch_client_callout + 8
6   libdispatch.dylib               0x00007fff8899309e _dispatch_root_queue_drain + 326
7   libdispatch.dylib               0x00007fff88994193 _dispatch_worker_thread2 + 40
8   libsystem_pthread.dylib         0x00007fff8f598ef8 _pthread_wqthread + 314
9   libsystem_pthread.dylib         0x00007fff8f59bfb9 start_wqthread + 13

**Comment by pjrobertson** [comment]
Hi @malhal ,

It's been a while since we've heard from you, and the information here isn't complete. If you're still facing an issue with the latest version of Quicksilver, please create a new issue and make sure to post the full crash report.

Thanks!
