### ISSUE TITLE
10.9 QS lockup on app's that start with #'s

### ISSUE THREAD

**Issue by sandinak** [quicksilver/Quicksilver#1790]
I can successfully lock up QS every time I try an app search for 1Password.app.  I've tried clearing the cache.... and replicated by renaming an app to start with a # and it similarly locks up. Usually lockup requires forced kill.

**Comment by pjrobertson** [comment]
Hi @sandinak,

It's been a while since we've heard from you, so I'm going to close this due to inactivity. If you're still facing an issue with the latest version of Quicksilver, please create a new issue.

Thanks!
