### ISSUE TITLE
Repeated lockups with apparent sqlite access problem

### ISSUE THREAD

**Issue by eejd** [quicksilver/Quicksilver#1793]
Quicksilver has been consistently locking up, perhaps correlated with a recent MacOS X update, but while the cause is unknown the result is that when quicksilver is restarted it operates correctly for a period of time, then slows its response time, then eventually locks up (spinning disk on hover, not responding via activity monitor, etc). Sampling the process shows apparent sqllite access. I can provide an example sample of the process during a lockup.

Process:         Quicksilver [620]
Path:            /Applications/Utilities/Quicksilver.app/Contents/MacOS/Quicksilver
Load Address:    0x10d49f000
Identifier:      com.blacktree.Quicksilver
Version:         1.1.3 (4007)
Code Type:       X86-64
Parent Process:  launchd [274]

Date/Time:       2014-03-10 09:57:19.604 +0000
OS Version:      Mac OS X 10.9.2 (13C64)

**Comment by pjrobertson** [comment]
This may well be fixed by the update to the Firefox plugin. If we are using `sqlite3.c` anywhere else in our code/plugins, then we should make sure to update it. 

sqlite3 is now thread-safe and the code much more robust than before.
