### ISSUE TITLE
Modification of sort order when browsing directory

### ISSUE THREAD

**Issue by wfaulk** [quicksilver/Quicksilver#1799]
I have a screenshots folder.  Screenshots are named by the date and time they were taken.  This means that the newest screenshot is always at the bottom of the list of files in that directory when I browse it with QS.

It would be nice if I could have QS sort in the opposite direction so that the one that I'm almost certainly searching for would be at the top.

**Comment by wfaulk** [comment]
[Karabiner](https://pqrs.org/osx/karabiner/)

**Comment by pjrobertson** [comment]
See #178 for the active discussion on this.
