### ISSUE TITLE
AppleScript actions should know about all the types used internally by ObjC actions

### ISSUE THREAD

**Issue by daniels220** [quicksilver/Quicksilver#1817]
Not sure if the title is clear—basically, I would like the "on get (in)direct types" handlers in AppleScript actions to be able to return strings corresponding to any type QS knows, not just a few specifically made available to AppleScript. I would greatly appreciate a "Get QS Types" action that could be run on an object and would return the relevant types to QS, as well.

The use case here is writing AppleScript actions with extremely specific requirements for their parameters, and allowing the user to drag them high up in the priority list without affecting stuff that they don't actually apply to. There are a number of types this makes sense for, such that it makes more sense IMO to do it generically.

**Comment by studgeek** [comment]
Sorry, hadn't noticed you asked me to file a issue. Now filed as #2199.
