### ISSUE TITLE
Install new version dialog should include version number

### ISSUE THREAD

**Issue by hmelman** [quicksilver/Quicksilver#1849]
I'm holding off installing 1.2.0 because I had problems. I still have QS set to check for updates since a fix will come someday. So once a day QS checks, finds a new version, downloads and prompts me to install. I'm fine with that, but it would help if the install dialog included the version number so that I could immediately see if 1.2.1 is out.

![screen shot 2014-05-23 at 9 50 34 pm](https://cloud.githubusercontent.com/assets/1999190/3073327/27d0aec8-e2e6-11e3-8e08-35b1cea1e7eb.png)

**Comment by pjrobertson** [comment]
I've just pushed a fix for this **straight to master**. I noticed that updates in the background were broken by 13c0dd4, and when debugging I also got similar crashes to those that Rob fixed here 9746468 so I thought pushing straight to master would be the best thing.
