### ISSUE TITLE
Console spewing "Quicksilver: enable failed"

### ISSUE THREAD

**Issue by brodkewitz** [quicksilver/Quicksilver#1850]
Quicksilver behaves as normal so I wouldn't know there was any problem until I pull up my console. Apparently, every time any window or app changes focus, I get this error 3 times. I don't dig through logs very often so I can't say exactly when this issue started, but I started noticing this about 2 months ago. Any thoughts?

QS 1.1.3 (4007) bezel interface on a first gen rMBP running 10.8.5 (2.7Ghz, 16GB)

5/27/14 9:02:25.765 PM Quicksilver[265]: enable failed 
5/27/14 9:02:25.765 PM Quicksilver[265]: enable failed 
5/27/14 9:02:25.765 PM Quicksilver[265]: enable failed 
5/27/14 9:02:27.411 PM Quicksilver[265]: enable failed 
5/27/14 9:02:27.412 PM Quicksilver[265]: enable failed 
5/27/14 9:02:27.412 PM Quicksilver[265]: enable failed 
5/27/14 9:02:28.906 PM Quicksilver[265]: enable failed 
5/27/14 9:02:28.907 PM Quicksilver[265]: enable failed 
5/27/14 9:02:28.907 PM Quicksilver[265]: enable failed 
5/27/14 9:02:32.425 PM Quicksilver[265]: enable failed 
5/27/14 9:02:32.425 PM Quicksilver[265]: enable failed 
5/27/14 9:02:32.426 PM Quicksilver[265]: enable failed 
5/27/14 9:02:33.674 PM Quicksilver[265]: enable failed 
5/27/14 9:02:33.674 PM Quicksilver[265]: enable failed 
5/27/14 9:02:33.674 PM Quicksilver[265]: enable failed 
5/27/14 9:03:00.358 PM Quicksilver[265]: enable failed 
5/27/14 9:03:00.358 PM Quicksilver[265]: enable failed 
5/27/14 9:03:00.358 PM Quicksilver[265]: enable failed 
5/27/14 9:03:02.000 PM Quicksilver[265]: enable failed 
5/27/14 9:03:02.000 PM Quicksilver[265]: enable failed 
5/27/14 9:03:02.001 PM Quicksilver[265]: enable failed 
5/27/14 9:03:18.329 PM Quicksilver[265]: enable failed 
5/27/14 9:03:18.329 PM Quicksilver[265]: enable failed 
5/27/14 9:03:18.330 PM Quicksilver[265]: enable failed 
5/27/14 9:03:21.395 PM Quicksilver[265]: enable failed 
5/27/14 9:03:21.396 PM Quicksilver[265]: enable failed 
5/27/14 9:03:21.396 PM Quicksilver[265]: enable failed

**Comment by petonic** [comment]
At the very least, let's have a "defaults" command that can stifle that debug output.  Just being pragmatic here.

**Comment by pjrobertson** [comment]
This may well be fixed by #2594 . If you're still experiencing extraneous log messages, then please re-open this issue. Otherwise, I'll close it for now.

Thanks!
