### ISSUE TITLE
Cant open Chrome

### ISSUE THREAD

**Issue by cliffwalker** [quicksilver/Quicksilver#1862]
Hi

I have used Quicksilver for quite a while and it has always workde great. However just recently I find it will not open Chrome. It always used to work fine.  Can you advise what to do to fix this?

Thanks

**Comment by pjrobertson** [comment]
Hi @cliffwalker ,

It's been a while since we've heard from you, so I'm going to close this due to inactivity. If you're still facing an issue with the latest version of Quicksilver, please create a new issue.

Thanks!
