### ISSUE TITLE
Running firefox bookmarklets wont work

### ISSUE THREAD

**Issue by tristan-k** [quicksilver/Quicksilver#1888]
Hi there,

it isnt possible to run firefox bookmarklets which are synced through the firefox add-on because there is no proper action available or it seems that quicksilver isnt getting the current firefox webpage (but the proxy action is working) properly. The action "run javascript" does nothing.

See this threads for further information:

http://ask.metafilter.com/88148/Quicksilver-for-Bookmarklets

> I don't have an answer, but I can confirm the problem. My bookmarklets show up in QS's dictionary, but there aren't any appropriate actions available. If I type "Ask Metafilter" into QS, I get an "Open URL" action, but if I type "Post to del.icio.us", that action isn't available, just QS internals like "Show Source in Catalog."

https://groups.google.com/forum/#!topic/blacktree-quicksilver/ce7YGTgB28w

> I don't know the details of what it would take to get that working,  
> but in general, you're going to get better integration with  
> Quicksilver (and the rest of your system) from a Cocoa-based browser  
> like Safari or OmniWeb. For instance, both of those browsers provide a  
> proxy object for "the page I'm currently viewing" that I couldn't live  
> without.
> 
> Firefox won't work as well because it's a glorified Mac OS 9 app  
> (a.k.a. Carbon).

**Comment by fturcheti** [comment]
I'm having the same problem. The logs I got from the Console:

Pinboard:
```
21/5/15 16:27:32,528 Quicksilver[21695]: Run Script: plugin-container got an error: Can’t get URL "javascript:if(document.getSelection){s=document.getSelection();}else{s='';};document.location='https://pinboard.in/add?next=same&url='+encodeURIComponent(location.href)+'&description='+encodeURIComponent(s)+'&title='+encodeURIComponent(document.title)".
```
Pushbullet:
```
21/5/15 16:26:53,322 Quicksilver[21695]: Run Script: plugin-container got an error: Can’t get URL "javascript:(function(){javascript:window.open('http://pushbullet.com/push/link?title='+encodeURIComponent(document.title)+'&url='+encodeURIComponent(location.href),'Pushbullet','width=1050,height=500,location=no,toolbar=no,status=no,menubar=no,hotkeys=no,directories=no,resizable=yes,scrollbars=yes,screenX='+(screen.availWidth-410)+',screenY='+0);})();".
```
Pinterest:
```
21/5/15 16:42:45,011 Quicksilver[21695]: Run Script: plugin-container got an error: Can’t get URL "javascript:void((function(d){var e=d.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('charset','UTF-8');e.setAttribute('src','//assets.pinterest.com/js/pinmarklet.js?r='+Math.random()*99999999);d.body.appendChild(e)})(document));".
```
