### ISSUE TITLE
Display Arguments in 'Command' column of the Triggers Pane

### ISSUE THREAD

**Issue by chinchin96** [quicksilver/Quicksilver#1907]
I have several triggers setup to execute actions like 'move, copy, open with' etc. When working with these triggers, I have to click on each individually to get context on which arguments are being passed through. 

It would be great to have these arguments show in the Command column of the Triggers pane. See Image below:
![trigger visibility](https://cloud.githubusercontent.com/assets/2515460/3902873/a05b82dc-22c4-11e4-8e72-835250bea54c.png)

**Comment by pjrobertson** [comment]
This has now been fixed. Thanks!
