### ISSUE TITLE
Current Selection dismisses the interface

### ISSUE THREAD

**Issue by skurfer** [quicksilver/Quicksilver#1911]
I first ran into this when creating some test triggers, but it can be reproduced in the main interface more easily. You know the old complaint that Quicksilver sometimes takes focus from all windows, but the previous application itself still shows in the menu bar? Well, get an app into that state then try to call up Current Selection. This should do it:
1. Select some text in Safari or Terminal
2. ⌘⎋ (the application should still be active, but the window should lose focus)
3. Search for Current Selection, then don’t touch anything

After a few seconds (I think when the proxy gives up and attempts to just copy to the pasteboard), the interface will go away as if you dismissed it.

**Comment by pjrobertson** [comment]
This has been fixed by 5779b38b0fcf1a0079cc0cdee9d93e464b2e5fd4 - see #1351
