### ISSUE TITLE
Show Keyboard Shortcuts in ‘Show Menu Items’ as Quick Reference

### ISSUE THREAD

**Issue by chinchin96** [quicksilver/Quicksilver#1912]
I use a trigger to invoke the 'Show Menu Items' when I am using applications to access all the menu items I would otherwise have to use the mouse for (or have keyboard shortcuts memorized), however, it would be GREAT to have QS show what all the shortcuts are so that I can see those I use often and memorize them, saving even more time. 
![qsshortcuts](https://cloud.githubusercontent.com/assets/2515460/3945409/7ab12572-263f-11e4-9858-661e6cf0043b.png)

**Comment by pjrobertson** [comment]
Hi @chinchin96 - did you come up with an alternative solution for this, to fix Philostein's issue?

If not, I'll close this issue for now. But please feel free to provide more suggestions, and thanks for your input on Quicksilver!
