### ISSUE TITLE
Install on OS X 10.9.4 (13E28) fails silently

### ISSUE THREAD

**Issue by DougHockin** [quicksilver/Quicksilver#1923]
This is what's in the console log:

9/13/14 8:05:56.493 AM Quicksilver[8681]: Installing Quicksilver at: /Applications
9/13/14 8:05:56.510 AM Quicksilver[8681]: releaseFromQuarantine
9/13/14 8:06:06.419 AM launchservicesd[78]: Application App:"Quicksilver" asn:0x0-a40a4 pid:8681 refs=7 @ 0x7fc883e915a0 tried to be brought forward, but isn't in fPermittedFrontApps ( ( "LSApplication:0x0-0xa50a5 pid=8688 "SecurityAgent"")), so denying. : LASSession.cp #1481 SetFrontApplication() q=LSSession 100004/0x186a4 queue
9/13/14 8:06:06.419 AM WindowServer[94]: [cps/setfront] Failed setting the front application to Quicksilver, psn 0x0-0xa40a4, securitySessionID=0x186a4, err=-13066
9/13/14 8:06:06.432 AM Quicksilver[8681]: chown -R 0:80 /Volumes/Quicksilver/Quicksilver.app failed.

**Comment by pjrobertson** [comment]
It's been a while since you reported this issue, and macOS 10.9 is no longer supported. Hopefully this is now working for you @DougHockin !
