### ISSUE TITLE
Firefox plugin crash

### ISSUE THREAD

**Issue by tiennou** [quicksilver/Quicksilver#1929]
```
Quicksilver[18928:303] Exception raised: *** -[JKArray objectAtIndex:]: index (18446744073709551615) beyond bounds (0)
```

[Here](https://github.com/quicksilver/Firefox-qsplugin/blob/master/QSFirefoxPlugIn.m#L34), [here](https://github.com/quicksilver/Firefox-qsplugin/blob/master/QSFirefoxPlugIn.m#L37).

Just found out while doing something completely unrelated. Maybe I'll do a PR if I don't deadlock myself first ;-).

**Comment by pjrobertson** [comment]
Fixed
