### ISSUE TITLE
Problems with Current Selection -> Append To

### ISSUE THREAD

**Issue by arezeeman** [quicksilver/Quicksilver#1936]
Hi. I brought this up in the forum and it was suggested that I flag it as an issue. I'm trying to make a trigger that appends the current selection to a file, which seems like it should be pretty easy.

Current Selection -> Append To... -> the_file

Nothing appears in the file, though. It doesn't matter if I run it as a trigger or form it directly in the interface.

These things do work:

Current Selection -> Large Type
some_text -> Append To... -> the_file

Rob McBroom's theory is that "the process of getting the Current Selection from most apps ends up stealing focus from the window." That rings true to me.

I have qs 1.1.3 and OS 10.9.5

Thanks.

**Comment by pjrobertson** [comment]
There was an issue with the 'Text Manipulation' plugin, in that the 3rd pane was not correctly showing files to 'append to'. But this has just been fixed.

I cannot reproduce the original issue, however.
