### ISSUE TITLE
Some Safari Bookmarks not showing up in Catalog

### ISSUE THREAD

**Issue by hmelman** [quicksilver/Quicksilver#1949]
I have a Safari bookmark 3 folders down: Interests -> Film -> Local Theaters -> Kendall Square Landmark.

It was named something else, and I renamed it. I refreshed the Quicksilver catalog and if I look in the Safari Bookmarks catalog source info pane, I see the updated name (and it's checked indicating it's enabled). However, when I activate QS and type "Kendall Square" this bookmark does not appear in the results list at all. Some (but not all) bookmarks in the same folder appear when I type to select them.

If I select Safari Bookmarks (catalog) and right-arrow into it, I can find the "Kendall Square Landmark" bookmark!

QS 1.2.0 (400E) Safari Plugin 2.1.6, OS X 10.9.4, 3.4 GHz i7 iMac, 8GB RAM
I'm using the built-in string ranker though the textmate one is installed
My results list is set to Filter Catalog and I see the same results using the other settings.

**Comment by skurfer** [comment]
I don’t have many bookmarks, so it might not be a valid test, but I tried creating a bookmark with an identical folder structure. Changes appear in the catalog pref instantly (we must be watching that one with FSEvents or something), and I can search the new name in the main interface.

Have you been able to discover any more about this bug?

The fact that the catalog prefs update, but you can’t search it is somewhat worrisome. Are you using the default string ranker or TextStart?

**Comment by hmelman** [comment]
The problem as described still exists for me. I haven't found more instances but I haven't been looking. I did have TextStart installed but the default string ranker was selected in Handlers. I unchecked the TextStart plugin and restarted QS and got the same behavior. If there's other debugging info I can give or run just let me know.
