### ISSUE TITLE
Custom Catalog no longer refreshes

### ISSUE THREAD

**Issue by hrprplx** [quicksilver/Quicksilver#1960]
On the last two versions, my custom catalog never refreshes. I'm running Mavericks and currently Quicksilver 1.2.0 400F. Files and folders created after a Catalog scan never appear in the search and clicking the refresh button in the Catalog preferences does nothing. The only way to get new files to show up is to remove my custom catalog entry and re-add it, waiting for another scan. Prior to the last two beta versions, this functioned perfectly.

This is a major part of my daily workflow as I use QS exclusively to search a folder structure of over 50,000 files. Please help. Thanks.

**Comment by louabill** [comment]
i would like to add a 'me too' where I'm noticing that I sometimes need to manually rescan individual catalog items to get them up to date. Rescanning the entire catalog does not update them. Here are two situations where I've seen the catalog not automatically update:
  moving an application from one cataloged folder to another cataloged folder
  ejecting and then remounting a disk image which has catalogued items in it
I have noticed this behavior only since I updated to version 1.2.2.

**Comment by hrprplx** [comment]
To update:  auto refresh does not occur on my large catalog, only manual
refresh does, even at program launch.

**Comment by skurfer** [comment]
My best guess is that Quicksilver doesn’t think it needs to rescan. That decision is made by this method:

https://github.com/quicksilver/Quicksilver/blob/master/Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSFileSystemObjectSource.m#L393

I can’t reproduce it, but if anyone can, and feels comfortable stepping through the code, that’s probably where the answer lies.

**Comment by Kvantti** [comment]
I'm having this issue too. Workaround I did is to create a custom trigger, using Event Triggers plugin, to "Execute Force Catalog Rescan" on "Computer Will Sleep" event, which works for laptop use. Doesn't remedy the problem though.

**Comment by TheCGCy** [comment]
Guess I'm not alone in this, I'm too having the same issues where QS doesnt scan custom added file and folders, also I'm restrict to folder only too.

**Comment by lebigot** [comment]
Same here, one year later: I have a Custom Catalog that reads my home (to depth 6). There is no automatic refresh ("every 10 minutes", normally).

I set the Task viewer do display any activity, and I see the progress bar stop at ~20 % : maybe QuickSilver fails to read something and aborts?

I'd be happy to investigate more and help nail this problem down.

**Comment by skurfer** [comment]
> I have a Custom Catalog that reads my home (to depth 6).

That sounds painful. 😃  Did you know you can access files deeper down by selecting a top-level folder and hitting `→` or `/`?

Having said that, it _should_ be possible to do what you’re doing. Next time you see it stall during scanning, open Activity Monitor, select Quicksilver, and choose Sample Process from the gear menu. That will hopefully tell us where it gets stuck.

**Comment by lebigot** [comment]
Yep, I do know about navigating inside folders in Quicksilver, thanks. But I am not sure how this can help with the rescan that fails?

I am attaching a Sample Process. Contacts are for instanced scanned quickly, but Quicksilver stops as soon as it starts scanning Home. I am attaching the 
[trace](https://github.com/quicksilver/Quicksilver/files/902336/Sample.of.Quicksilver.txt). It'd be great someone can figure out what happens, because I gather I am not the only one with this problem. :)

**Comment by skurfer** [comment]
> Yep, I do know about navigating inside folders in Quicksilver, thanks. But I am not sure how this can help with the rescan that fails?

It’s not related to the scan. Just general advice. You’re adding tens of thousands of things to the catalog that you’ll never access, which slows everything down.

Strange that contacts appear to get scanned quickly. Almost all of the activity in that sample comes from the Contacts plug-in. It appears to be scanning contacts multiple times simultaneously (which shouldn’t be possible). Could you try temporarily disabling the Contacts plug-in and see if it has any effect on scanning Home?

**Comment by lebigot** [comment]
I did disable Contacts, but _my Home is still not scanned_ during the automatic refresh. Other things are apparently scanned, and then when Home is hit (while the Task window still shows a largely incomplete progress bar), the tasks stops brutally (the Task window disappears).

I am attaching a [process sample](https://github.com/quicksilver/Quicksilver/files/923872/Sample.of.Quicksilver_no_Contacts.txt) from before and during the refresh.

Let me know if you want me to take more samples, or better timed samples. There is obviously a big bug lurking somewhere.

**Comment by kevinlawler** [comment]
Same problem
