### ISSUE TITLE
Keychain plugin catalog doesn't include iCloud Keychain

### ISSUE THREAD

**Issue by query** [quicksilver/Quicksilver#1963]
Drilling down into Keychain Access shows only local keychains (`login`, `system`).

I imagine iCloud Keychain's data is stored differently and therefore requires extra work to get at, but support for it would be a nice feature, especially as Safari defaults to only saving new passwords on iCloud if it's enabled.

Plugin version 1.1.3, OS X 10.9.5.

**Comment by pjrobertson** [comment]
It seems this may now be possible, adding the key/value pair: `kSecAttrSynchronizable: kSecAttrSynchronizableAny` to [the query](https://github.com/quicksilver/Keychain-qsplugin/blob/master/QSKeychainSource.m#L55) may well do the trick.

**Comment by klmr** [comment]
Hi, is there any progress on this? It would definitely be very nice to have. (But please feel free to disregard this nagging message.)
