### ISSUE TITLE
occasional hangs 

### ISSUE THREAD

**Issue by heikohaller** [quicksilver/Quicksilver#1977]
since upgrading to 1.2.0 (400F), QS becomes unresponsive every couple of days.
Task Manager does not show it a unresponsive though – It simply does not activate on shourtcut, also application triggers do not work. 
Workaround: Quitting from Activity Monitor and restarting QS helps.

OS: Mavericks (10.9.5)

Installed Plugins:
- contacts
- evernote
- cyberduck
- Keychain
- Safari
- Shelf
- Terminal

(Disabled all plugins now, will report back)

**Comment by 1-61803** [comment]
See also this thread https://groups.google.com/forum/#!topic/blacktree-quicksilver/Xo2YXiAFiB4

**Comment by skurfer** [comment]
So I don’t forget… Look into `NSURLBookmarkResolutionWithoutMounting`

**Comment by tiennou** [comment]
(Note there's a [commit](663ffb4c9a758427424cdc5382ed699c0421b788) in #2075 that tries to make the NSURL stuff a little easier to use).

**Comment by ethanbeyer** [comment]
Hey there, I have been having a very similar issue to what @heikohaller was describing, and my ticket, #2132, was closed. No biggy, but @skurfer said to me in that thread:

"Until then, check your catalog for links or aliases to files on network drives that aren’t available."

I have none in my catalog. I've even reset the preferences and such. Seemed to help for about a day, but the problem has sporadically persisted.
I'll take a sample from the Activity Monitor next time it happens and will report back.

Thanks!

**Comment by ethanbeyer** [comment]
Follow-up: I was wrong.

![screen shot 2015-10-29 at 09 35 41](https://cloud.githubusercontent.com/assets/6864684/10819797/7162c342-7e20-11e5-9a58-f2a11d483251.png)

I didn't realize that "Recent Items" was caching the `smb://` server I connect to for work.

But *now* on to what I find really odd: some of the most recent occurrences of this problem have been while I am connected to this server.

Scratching my head, yo.

**Comment by skurfer** [comment]
Fixed by #2142
