### ISSUE TITLE
Plugin update window doesn't show changelog

### ISSUE THREAD

**Issue by nach0** [quicksilver/Quicksilver#1987]
When new plugin updates are available a window pops up and shows the new plugin versions available and a dropdown menu to see the changes with an arrowhead to display the menu. When clicking the arrowhead the window enlarges a bit (to make room for the text describing the changelog, I suppose) but no text is displayed.

This is an example for a popup window informing about 3 new plugin updates. The 3 arrowheads have been clicked to show the changelogs, there is extra white space at the bottom of the window to fit the changelog text, but no text shows up.
![screen shot 2014-11-15 at 03 05 37](https://cloud.githubusercontent.com/assets/1169440/5058713/3e56b4a8-6cfc-11e4-92f0-cb7d039ee027.png)

**Comment by skurfer** [comment]
I can confirm that this used to happen, but I’ve seen the details on the last two plug-in releases. Anyone else?

**Comment by tiennou** [comment]
The last plugin update did that here (Text Manipulation I think). The arrow is visible, but clicking it shows nothing (unless you count weird animation behaviors as "something" ;-)).

**Comment by pjrobertson** [comment]
I made this, so let me look into this.

**Comment by pjrobertson** [comment]
Wait, seems to be working here right now...

Anyone else still having problems, or can I close?

**Comment by tiennou** [comment]
Not here. I've had some "no plugin changelog" a few releases ago, but not recently.
