### ISSUE TITLE
Web history not indexed for Safari 8.0 (the Yosemite version)

### ISSUE THREAD

**Issue by Sesquipedalian** [quicksilver/Quicksilver#1994]
Quicksilver gets the web history for Safari from the file ~/Library/Safari/History.plist. However, it appears that Safari 8.0 no longer stores its history in that property list file. I see several other files in ~/Library/Safari that look relevant and that have been modified recently, including History.db, History.db-wal, and HistoryIndex.sk. The old plist file is still present, but it has not been modified since I installed Yosemite.

So, I think the Safari plugin needs to be updated to pull in Safari history from whichever of these new history files is appropriate.

**Comment by hmelman** [comment]
Just want to say, I really miss this functionality (and I'm still not quite up to being able to fix it myself) :)

**Comment by elmart** [comment]
Any progress on this?

**Comment by pjrobertson** [comment]
See quicksilver/com.apple.Safari-qsplugin#9

**Comment by skurfer** [comment]
I completely forgot about this. Maybe I’ll see if I can fix whatever I was complaining about myself.
