### ISSUE TITLE
Blurring on the re-entry of text

### ISSUE THREAD

**Issue by docbiz** [quicksilver/Quicksilver#2004]
If you hit "." and enter plain text, the appearance of any text that is then entered is 'correct' (see, e.g., http://i.imgur.com/wBAe1xT.png). However, if you then hit tab, shift+tab, and ".", the text then becomes very subtly blurred (see, e.g., http://i.imgur.com/6UhKuDq.png).

This is on OS X 10.10.1, running on a MacBook Pro (Retina, 13", mid-2014).

**Comment by pjrobertson** [comment]
I can reproduce with WhiteBezel (@mikker) as well as Primer. The blur seems to appear and disappear in an alternating manner with every keystroke

**Comment by mikker** [comment]
I see the same thing in Primer but not in my Yosemite-style themes. Might give some clue as I have no idea?

**Comment by skurfer** [comment]
I think this was fixed in 1.3.3. Can one of you confirm?

**Comment by docbiz** [comment]
It seems to be fixed—thanks!
