### ISSUE TITLE
Clipboard Plugin no more working QS 1.2.0(400F) / OSX 10.7.5

### ISSUE THREAD

**Issue by efficientbaxter** [quicksilver/Quicksilver#2006]
Hi,

there is an issue with the current Clipboard Plugin. I've reinstalled it already (incl. Shelf) twice but to no avail.

Here the log:

`2014-12-19 19:19:00.972 Quicksilver: Error loading /Users/USER/Library/Application Support/Quicksilver/PlugIns/com.blacktree.Quicksilver.QSClipboardPlugIn.141.qsplugin/Contents/MacOS/Clipboard Plugin:  dlopen(/Users/USER/Library/Application     Support/Quicksilver/PlugIns/com.blacktree.Quicksilver.QSClipboardPlugIn.141.qsplugin/Contents/MacOS/Clipboard Plugin, 265): Symbol not found: _OBJC_CLASS_$_NSObject
  Referenced from: /Users/USER/Library/Application Support/Quicksilver/PlugIns/com.blacktree.Quicksilver.QSClipboardPlugIn.141.qsplugin/Contents/MacOS/Clipboard Plugin
  Expected in: /usr/lib/libobjc.A.dylib
 in /Users/USER/Library/Application Support/Quicksilver/PlugIns/com.blacktree.Quicksilver.QSClipboardPlugIn.141.qsplugin/Contents/MacOS/Clipboard Plugin`

In the list of plugins, ClipboardPlugin is stated as version 1.4.3. Don't know, but since there seems to be no QS 1.2.1 for Lion – perhaps it is some dependency issue? 

Thank you!

Baxter

**Comment by pjrobertson** [comment]
This issue was created over 7 years ago. Please try updating to the latest versions of Quicksilver and the Clipboard plugin
