### ISSUE TITLE
Contact Nicknames not in Catalog in 10.10.1

### ISSUE THREAD

**Issue by hmelman** [quicksilver/Quicksilver#2007]
Not sure how long this has been happening but I just noticed that my Contact's nicknames are not in the QS catalog. They are there by first and last name. I fear something changed in the Contacts app in Yosemite and the plugin needs to be updated. 

This is a really useful feature to me (I know a lot of Mike's and use nicknames) and something that made QS feel friendly. 

QS 1.2.1 (4010) 10.10.1, 3.4 GHz i7 iMac, 16GB RAM, 1TB Fusion
Contacts Plugin 2.2.0
Contacts stored in iCloud only, no Facebook integration.

**Comment by hmelman** [comment]
THANK YOU

**Comment by skurfer** [comment]
I really need to stop running the fixed versions of plug-ins before they’re merged. Keeps me from feeling the pain and allows me to forget it’s still broken for the rest of the world. 😀

**Comment by hmelman** [comment]
:) Safari plugin (missing History items and #1949) would be my next biggest issues. You wouldn't happen to be running a fixed version of that would you? ;)
