### ISSUE TITLE
Cannot make alias from files & folders with forward slash in their name

### ISSUE THREAD

**Issue by 1-61803** [quicksilver/Quicksilver#2009]
1. Select file or folder with forward slash in their name
2. Select action Make Alias in…
3. Select folder of destination
4. Failing of operation doesn't log a message

QS 1.2.0, OS X 10.9.5

NB that selecting a destination folder with / in its name works as long as the source doesn't have it.

**Comment by pjrobertson** [comment]
This is an issue with the underlying NDAlias code, specifically at NDResourceFork.m:134 - returning an error.

```FSCreateResFile( &theParentFsRef, theNameLength, theUnicodeName, 0, NULL, NULL, NULL );		// doesn't replace if already exists
```

correct fix will be to replace all NDAlias code with the NSURL as per: https://stackoverflow.com/questions/1619073/how-do-you-create-an-alias-in-cocoa-is-a-symlink-good-enough
