### ISSUE TITLE
Custom Icon for Actions no longer appearing

### ISSUE THREAD

**Issue by jdhealy** [quicksilver/Quicksilver#2010]
The custom AppleScript actions I created in `~/Library/Application Support/Quicksilver/Actions` now (as of *4011*) show the generic gear icon instead of the custom icons.

Custom icons are visible in the Finder, set via the Info pane.

I pulled *4010* out of the trash and the custom icons appear correctly.

*Possibly related to #2003 ?*

**Comment by skurfer** [comment]
This was fixed by #2026
