### ISSUE TITLE
1Password plugin not working with iCloud Drive

### ISSUE THREAD

**Issue by Vinz87** [quicksilver/Quicksilver#2011]
I've just turned on iCloud Drive, and I therefore switched the 1Password synchronization service from Dropbox to iCloud.

The problem is that with Dropbox I could easily point the folder in which the 1Password keychain is stored, while now Quicksilver asks me its location and I don't know how to tell it to search the 1Password keychain in iCloud.

Someone has the same issue?

**Comment by ruvinsky** [comment]
I can repro this.  It doesn't look like the 1Password QS plugin supports 1Password bookmark integration.

**Comment by skurfer** [comment]
I think with 3rd Party Integration enabled in 1Password, it doesn’t matter what sync back-end you’re using.

Locating the keychain hasn’t worked with Quicksilver since 1Password 3 anyway. It if worked at all, you were probably seeing left-over data from that ancient version. There’s an updated plug-in compatible with  1Password 4/5/6 and 3rd Party Integration in the works.

**Comment by skurfer** [comment]
An updated version of the plug-in has been released. If you enable 3rd Party Integration in 1Password, then tell Quicksilver where the file is in its preferences, it should work. For me, it’s at `~/Library/Application Support/1Password 4/3rd Party Integration/bookmarks-default.json`.

**Comment by ruvinsky** [comment]
Thanks @skurfer! That default path to the json file doesn't exist on my system. I'm on Mac with the latest version of 1P v6.0.1 (from the Mac App Store, using iCloud sync). I found it here:

~/Library/Containers/SOMEHASH.com.agilebits.onepassword-osx-helper/Data/Library/3rd Party Integration/bookmarks-default.json

Wondering if the value of SOMEHASH in that path is unique per install.  Perhaps the AgileBits folks could provide guidance on detecting the path dynamically to avoid manually configuring the QS 1P plug-in.
