### ISSUE TITLE
Remember the milk plugin not working

### ISSUE THREAD

**Issue by samaybar** [quicksilver/Quicksilver#2013]
RTM plugin has stopped working in the last week -- will not pull up my remember the milk lists and if I try to reauthorize I get a message that says: 
No callback URL specified for this API key. Your frob value is [long hexadecimal number]

**Comment by pjrobertson** [comment]
@binaryminded - do you still have access to [login](https://www.rememberthemilk.com/login/) to the RTM API?

I think that's all that's needed to add a callback URL

**Comment by BinaryMinded** [comment]
I do have access and I found the form I'd have to fill out, but it sounds more like something is wrong with how the plugin is doing authentication. It should be able to suffice without a callback URL based on the "User authentication for desktop applications" instructions here: https://www.rememberthemilk.com/services/api/authentication.rtm. That approach sounds like how it's supposed to work and has worked for the last many years. If all we need is a dummy URL that'll never be used, I could put that in but if that's the case it's really a bug on RTM's part that it's required for non-website auth.

I'm not supporting the plugin anymore and I can't do any development on it at the moment. Would it be possible for someone to take control of the existing API key?

**Comment by richtack** [comment]
Yes, having the same problem. From a user perspective, if there is a workaround someone could provide as a temp-fix; I loved this functionality and used it all the time. sorely missed! thanks.

**Comment by tiennou** [comment]
I was looking at that, and after seeing some posts in RTM developer group, it seems callback URLs have become mandatory at some point, I'd say because iOS uses those extensively.

@BinaryMinded I can take over the API key (though I'm wary it's a little too *visible* in any case :-S). Feel free to email me directly to the email in my GH profile so we can discuss the details !

**Comment by tiennou** [comment]
After some more tinkering, I found the issue ;-). The endpoint was moved and returned a nginx error instead of some yummy XML data.

**Comment by skurfer** [comment]
I’ve released the updated plug-in.

**Comment by StuartRob** [comment]
I think the API problem with the Remember the Milk pPlugin has reappeared. The plugin fails to authenticate and get the list of tasks and lists. When I try to re-authenticate I get the webpage that says 'No callback URL specified for this API key. Your frob value' and then a long string of numbers and letters. I think this happened in the past and was fixed; I hope it can be again.

**Comment by samaybar** [comment]
@skurfer this problem seems to have reappeared. Are you able to remedy again?

**Comment by skurfer** [comment]
The fix will be a lot more involved this time, I think. There are other things in the QS world more pressing for me personally, so I don’t expect to get to it any time soon.
