### ISSUE TITLE
Memory Leak in v1.2.2

### ISSUE THREAD

**Issue by synfinatic** [quicksilver/Quicksilver#2014]
After upgrading to v1.2.2 I'm seeing a rather aggressive memory leak.  After a few hours, the Activity Monitor is showing QS is using over 2GB of memory.
![2015-01-11 05 12 52 pm](https://cloud.githubusercontent.com/assets/1075352/5697971/1ea1e282-99b5-11e4-9fd0-0de189252664.png)

**Comment by skurfer** [comment]
I’m not seeing this, which makes me wonder if it’s a particular plug-in. (Though I have most of them installed, so maybe not.) Could you do some trial and error, disabling plug-ins a few at a time, to see if you can narrow it down? Thanks.

**Comment by synfinatic** [comment]
So the problem has seem to have gone away or at least isn't as severe.  I had restarted QS probably about 10 times over the last 3-4 days and each time the memory leak returned very quickly- causing QS to grow to 1GB in just a few hours.  But after disabling the Contacts & Twitter plugins the problem as mostly went away.  

I've tried re-enabling both plugins and restarting QA, etc but so far at least the memory usage has only gone from 100MB to 300MB over the past few hours.  So either it's just leaking a lot slower or this memory usage pattern is normal (honestly I don't know).

**Comment by synfinatic** [comment]
So it's definitely still leaking memory, but just a lot more slowly. QS had grown to over 500MB by this evening.  I'm going to play with the plugin list some to see if I can track it down, but it's going to take a while I think.

**Comment by skurfer** [comment]
I ran it in Instruments to check for leaks, and the majority *by far* come from the the iTunes plug-in, so maybe start there.

**Comment by synfinatic** [comment]
So I've been playing with this for a few weeks now and for whatever reason, I haven't seen the memory leak as fast as I did earlier.  I am seeing a slow memory leak with the iTunes plugin enabled, but the Twitter plugin seems worse.  Generally speaking I find the iTunes plugin pretty useful, but I can't say the same for the Twitter plugin so I've disabled the latter.

**Comment by skurfer** [comment]
Has this repeated at all?

**Comment by synfinatic** [comment]
As long as I don't enable the Twitter plugin it seems reasonable.  iTunes seems to leak some memory, but it's slow enough and I've got 16GB so it's not bad enough to worry about 99% of the time.

**Comment by skurfer** [comment]
OK, thanks.
