### ISSUE TITLE
Some Scripts for Safari

### ISSUE THREAD

**Issue by hmelman** [quicksilver/Quicksilver#2018]
These two apple scripts would be useful additions to the Extra Scripts plugin or the Safari plugin or something. With these in QS you could have keybindings to move to the first tab or last tab.

tell app "Safari" to tell window 1 to set current tab to tab 1

tell app "Safari" to tell window 1 to set current tab to last tab

**Comment by skurfer** [comment]
Good candidates for trigger presets in the Safari plug-in, I’d say.
