### ISSUE TITLE
Keyboard shortcut not working after MacOSX fresh boot

### ISSUE THREAD

**Issue by ascomycota** [quicksilver/Quicksilver#2019]
I have quicksilver in the toolbar on top of MacOSX and defined Apple+Space as keyboard shortcut (I deactivated that shortcut for spotlight). It works as pretty good as any other combination. But always after a fresh boot nothing happens with my shortcut until I open the "about dialog" from the Quicksilver toolbar icon.

Once another dialog of Quicksilver was opened, the shortcut works from then on until the next boot of the computer.

I hope you can reproduce an fix it. Thanks.

**Comment by skurfer** [comment]
See #1170 or one of the dozens of other duplicates. :smiley:
