### ISSUE TITLE
Jenkins builds failing

### ISSUE THREAD

**Issue by pjrobertson** [quicksilver/Quicksilver#2022]
Something about needing to agree to the Xcode license.

Since I'm trying out Travis again in #2021 maybe Jenkins tests should just be removed entirely?

**Comment by pjrobertson** [comment]
@HenningJ

**Comment by skurfer** [comment]
Sounds fine to me.

**Comment by pjrobertson** [comment]
I have a confession to make... I've already stopped Jenkins for the time being.

**Comment by HenningJ** [comment]
hehe. If Travis works now, that's better. :-)

**Comment by pjrobertson** [comment]
Fingers crossed that PR gets merged... ;-)
