### ISSUE TITLE
Adobe Illustrator Crash upon Copy operation

### ISSUE THREAD

**Issue by awaiters** [quicksilver/Quicksilver#2028]
Adobe Illustrator crashes on Copy operation if the document has Arabic text.

I have added Adobe Illustrator and all Adobe products in the ignore list of the Clipboard preferences, that solved the issue.

I am using OS X 10.10.2, on a MacBook Pro and latest QuickSilver and plugins as I have it updating continuously.

**Comment by tiennou** [comment]
Care to share some arabic text that trigger the crash ?
