### ISSUE TITLE
URLs for All Music Guide in Web Searches are obsolete.  

### ISSUE THREAD

**Issue by totallyGreg** [quicksilver/Quicksilver#2031]
all music artist search for "Deep Purple" from Web Searches plugin fails:
 http://wm01.allmusic.com/cg/amg.dll?SQL=Deep%20Purple&OPT1=2&Submit=Go&P=amg

Searching directly on website for "Deep Purple" gives this url and works.  
http://www.allmusic.com/artist/deep-purple-mn0000192382

Album and Song searches are similarly affected by the deprecation of the wm01 host.

**Comment by pjrobertson** [comment]
Fixed.

Please try refreshing the entry in the Catalog prefs.

Thanks for reproting this
