### ISSUE TITLE
Quicksilver randomly stops running Applescripts on triggers

### ISSUE THREAD

**Issue by ingling** [quicksilver/Quicksilver#2032]
I'm at a company and we've had about 25 people using Quicksilver to run scripts off key commands for a couple of years. Just in the past few days, a whole bunch of us have had scripts (randomly as far as we can tell) not run sometimes off the key command. I've tried opening the script being called, modifying it to make the first line be:
tell application Finder to display dialog "Made it here"
and confirm that it's not a problem with any individual scripts, they are not being run. That is, if I open the same script in Script Editor, and press run, it runs fine, but even making the script just display a dialog first thing, it doesn't even make it there when being run from Quicksilver.
When this happens, that particular script/keybinding continues to fail until Quicksilver is quit, but quitting and relaunching Quicksilver always makes it work again. Until it stop at some random time... in minutes or in hours... and we have to quit and relaunch again.
When one trigger quits functioning, other triggers that also run Applescripts often continue to function fine... any random subset of triggers can go out together while others still work.
At our wits end... may need to look at another solution. Let me know if anyone has any ideas or tests I can run.
Thanks,

Tom.

**Comment by ingling** [comment]
FYI, I've talked to Quicksilver developers before about a way to share/sync Quicksilver preferences files through Dropbox, but we never got that working and none of us are on it. I'm not aware of any way we're an unusual setup here, other than having a lot of Applescripts on triggers.

**Comment by skurfer** [comment]
In a lot of cases, AppleScripts can go wrong because a key (from the trigger) is still being held when it’s run. You can usually work around that by having the trigger run “On Release” instead of “On Press”.

That wouldn’t explain it working after a restart, though, so I suspect something else is going on here. It cold be related to [something recently reported][1] on the mailing list.

Are there any messages on the console (`/Applications/Utilities/Console.app`) that might offer a clue?

[1]: https://groups.google.com/forum/#!topic/blacktree-quicksilver/G0b1-KpS-Wk

**Comment by ingling** [comment]
Could be related... I do have one script where one step of the script sometimes fails - telling Adobe Photoshop to save a file - when run from Quicksilver, but that step never fails when run from Applescript Editor or from Script Debugger, so it's been very hard to troubleshoot. But I haven't considered that to be related.

Aha! Yes, thanks for suggesting I look at Console, I should have thought of that earlier. It's getting a permissions error:
2/26/15 1:24:59.445 PM Finder[40079]: AppleEvents/sandbox: Returning errAEPrivilegeError/-10004 and denying dispatch of event syso/offs from process 'Quicksilver'/0x0-0x2398396, pid=87107, because it is not entitled to send an AppleEvent to this process.

So why isn't Quicksilver allowed to send these Apple events? And why does the exact same script work most of the time, then quit, and start working again if we restart quicksilver? Just in case, I'll repair permissions and see if that does anything. Thanks! Let me know if this gives you any insight.

**Comment by ingling** [comment]
Drat, repaired permissions, to no avail.

**Comment by tiennou** [comment]
From a quick Googling around, it seems we have to add [com.apple.security.temporary-exception.apple-events](https://developer.apple.com/library/ios/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/AppSandboxTemporaryExceptionEntitlements.html)" to QS's entitlements so `sandboxd` allows it to fire AppleEvents at any other process.

**Comment by ingling** [comment]
I wonder what on earth is going on that sometimes it has the appropriate permissions, and other times it gets stopped? It's always the exact same script on the same key. Also, until a few days ago, it always worked.
Any thoughts on how long it would take to have that added? Going nuts over here... but we could investigate temporarily binding the scripts to a key command through some other mechanism until Quicksilver has this entitlement.

**Comment by ingling** [comment]
And so incidentally, my first summing up the problem is incorrect, Quicksilver is trying to run the script. But my attempt to see if it was trying or not by making the first line have the Finder display a dialog was a bad choice to see if it's trying to run, because the problem is that the OS isn't letting Quicksilver tell the Finder to do things!

**Comment by ingling** [comment]
Oh, and skurfer, thanks for the suggestion re: "on press" vs "on release," but we've always had all the Applescripts set to "on release" due to that very problem.

**Comment by tiennou** [comment]
You say it worked "a few days ago". Was some kind of OS update involved at that same time ?

I'm concerned about the on-off description you're painted us — it looks like the sandbox somehow gets activated after some unspecified amount time, which is weird.

Were all of your triggers affected at some point ? Do they share some common structure (e.g. going through System Events to send keypresses) ? Can you post one of the *real* Console logs in case they're any difference ?

**Comment by tiennou** [comment]
Also, since we're not actually using the sandbox, we have no entitlements. Adding support for sandboxing would be *very* hard, given the breadth of things you can do with QS. To me this starts looking like a bug in `sandboxd`, which shouldn't enforce anything on us...

**Comment by ingling** [comment]
No, no OS update. Most of the people in this room started experiencing it at the same time, and some of us are on 10.9 and some on 10.10, and different versions of those, and we certainly didn't all install an OS update when it started. I can't think of anything the people having the problem could have all installed.
So, report this as a bug to Apple, because Quicksilver isn't supposed to be subject to Sandboxing restrictions?

**Comment by ingling** [comment]
I don't think all triggers have been effected, but several have.
How do you mean the "real" console logs? There's no line that regularly proceeds the one I sent, and the next one is just Applescript complaining that it didn't get the information it wanted, and then it's back to just whatever unrelated thing happens to show up next. I'm attaching the "Inspector" graphic on the issue from the log, let me know if you need something else.
![screen shot 2015-02-26 at 3 37 41 pm](https://cloud.githubusercontent.com/assets/8173803/6401332/a0ff56ec-bdcd-11e4-801b-a134d42cd296.png)

**Comment by ingling** [comment]
OK, we're trying out FastScripts now as an alternative. Seems to be working so far.

You guys think I should file a bug report with Apple over this? Or do you want to file it? I probably has more weight coming from a developer. Let me know anything else you need.

Thanks,

Tom.

**Comment by tiennou** [comment]
Let's both file a bug then, it'll have more "weight" ;-). I'll do that tomorrow, it's getting late here, but please tell me the rdar number so I can dup yours.

I haven't been able to reproduce here, but I can give you some hacky steps I tried ;-) :
AppleEvents are handled by `/System/Library/CoreServices/appleeventsd`, which has a few parameters (found thanks to `strings`), notably `--nosandbox`. What I tried was editing `/System/Library/LaunchDaemons/com.apple.coreservices.appleeventsd.plist`, adding that parameter to the list of arguments and unload/load it with `sudo launchctl` so it gets passed in. I haven't been able to see any difference (but it was working here :-S). Maybe you can get different results on your side ?

I'm on 10.9.5 here BTW.

**Comment by ingling** [comment]
I'm not sure I'm comfortable with all that.
- I open /System/Library/LaunchDaemons/com.apple.coreservices.appleeventsd.plist with a text editor or such and add the argument "--nosandbox"
- I go to terminal and enter "sudo launchctl" and enter my password?

First problem: this file:
/System/Library/LaunchDaemons/com.apple.coreservices.appleeventsd.plist
Doesn't exist.
I'm on 10.9.5 too.

**Comment by ingling** [comment]
Bug report filed - 19978459
