### ISSUE TITLE
Repeatedly see this error in Console: Quicksilver: AppleEvents: Send port for process has ...

### ISSUE THREAD

**Issue by wlow** [quicksilver/Quicksilver#2033]
I'm not a programmer and I have no idea what this means, but I've been going through Console to try to clean up repeating errors and this is one of my Console errors that keeps repeating. Is this a known issue?

Quicksilver: AppleEvents: Send port for process has no send right, port=( port:43259/0xa8fb rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) QSCatalogEntry scanQueue: QSPresetiTunesEQPresets

This will repeat 25x or so every 10 minutes.

**Comment by skurfer** [comment]
I’ve seen the same thing since, I think, 10.9 was released. I looked into it at the time and couldn’t find a cause. We’re not doing anything weird, and everything still works, so I don’t know what to make of it.
