### ISSUE TITLE
Keyboard Triggers not working on lock screen

### ISSUE THREAD

**Issue by natcl** [quicksilver/Quicksilver#2034]
I'm not sure this is possible but I was wondering if it would be possible for Hotkey triggers to work even when on the lock screen ?
I use hotkey triggers to control my TV via an Arduino, when I switch to TV I also lock the computer at the same time for security reasons, but since it's locked I cannot control it anymore because hotkeys won't work anymore.

Thanks !

**Comment by skurfer** [comment]
I don’t think this is possible. If it is, OS X has a major security hole. :smiley:
