### ISSUE TITLE
Sending multiple files to be opened with Preview.app

### ISSUE THREAD

**Issue by brumm** [quicksilver/Quicksilver#2035]
With Quicksilver, opening multiple files with Preview.app leads to each file being opened in a new window. As opposed to OSX behavior, which opens them in one window, with each file in a 'tabbed' sidebar.

...Just stumbled over that after accidentally opening ~250 images in a folder with Quicksilver :)

**Comment by skurfer** [comment]
This has come up before with other apps (like TextMate), but there [doesn’t seem to be a way][1] to open multiple files simultaneously.

[1]: https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSWorkspace_Class/index.html#//apple_ref/occ/instm/NSWorkspace/openFile:withApplication:

**Comment by brumm** [comment]
Aw, shoot. Thanks for getting back to me anyway!

**Comment by tiennou** [comment]
Maybe `-openURLs:withAppBundleIdentifier:options:additionalEventParamDescriptor:launchIdentifiers:` can do that ?

**Comment by skurfer** [comment]
Worth a look.
