### ISSUE TITLE
Relaunch action missing for applications installed by `brew cask`

### ISSUE THREAD

**Issue by timvisher** [quicksilver/Quicksilver#2036]
`brew cask` installs applications by symlinking them to `~/Applications`. This is fine and works to open them or to activate them, but it doesn't work to relaunch them.

I've discovered that 𝑄uıcĸsılⅴεʀ will Relaunch the full path to the application, which will often be the next entry in the results panel when searching for the app.

I'm guessing this is because of how qs is handling the symlink. It would be awesome if it could detect that the symlink is an application in some way and allow me to relaunch it via the symlink.

**Comment by BartlomiejSkwira** [comment]
+1, same situation here. Launching the manually helped but would be cool if Quicksilver would do that automagically

**Comment by izaakm** [comment]
+1
