### ISSUE TITLE
Unable to resize QS Results Window 

### ISSUE THREAD

**Issue by diiiv9** [quicksilver/Quicksilver#2037]
The results window has shrunk down to only the title and I am unable to resize it and see any results . Deleting all Cache , PList and Preference and Uninstalling and Re-Installing has helped either , the window height persists . 

Also unable to click the resize marker on the top right of the results window . 

Using resize window shortcuts ( BetterTouchTool ) also doesn't work .

![screenshot 2015-03-12 16 05 07](https://cloud.githubusercontent.com/assets/11439193/6616236/00bcfef4-c8d2-11e4-96bc-16618c588792.png)

**Comment by skurfer** [comment]
Try this:

  1. Quit Quicksilver
  2. In Terminal, run `defaults delete com.blacktree.Quicksilver "NSWindow Frame QSResultWindow"`
  3. Launch Quicksilver

10.9 and higher are pretty aggressive about caching preferences, so changes don’t always appear right away. If it doesn’t work, you might try a reboot for step 3 instead.

**Comment by diiiv9** [comment]
Fixed . Thanks ! 

Great App . Absolutely hooked to it . 

Also can you tell me any interface that changes how the Results window looks (Fonts and Borders etc .)  ? Something sleeker like Spotlight . 

Thanks Again .

**Comment by skurfer** [comment]
You can change the colors in Preferences → Appearance, but that’s about it.
