### ISSUE TITLE
UTI in applescript appears not to be working.

### ISSUE THREAD

**Issue by gleachkr** [quicksilver/Quicksilver#2040]
The [wiki](http://qsapp.com/wiki/AppleScript_Types) suggests that narrowing a set of results by UTI should be as simple as swapping in "public.folder" for "NSFilenamesPboardType", but this doesn't appear to narrow the matches at all. Others in the forum [here](https://groups.google.com/forum/#!topic/blacktree-quicksilver/80n6YBcfMCo)  have confirmed that this may be a bug.

If this is not a bug, could someone provide a minimal working example illustrating how to use UTIs in an applescript action?

**Comment by skurfer** [comment]
I’m pretty sure that discussion is what inspired #2039, so a fix is already in the works.
