### ISSUE TITLE
contacts plugin doesn't work in 10.7

### ISSUE THREAD

**Issue by jeanravin** [quicksilver/Quicksilver#2043]
I thinks it's since the last update (or at least a recent one). I can't find any contact and the catalog is empty.
![2015-04-05111425 quicksilver-catalog](https://cloud.githubusercontent.com/assets/1174299/6998650/e670a944-dbe9-11e4-8331-3f0b46f9d7a7.png)

I also have this in the console :

05/04/15 23:14:03,461 [0x0-0xdb0db].com.blacktree.Quicksilver: 2015-04-05 23:14:03.461 Quicksilver[1078:e07] Failed loading bundle NSBundle </Users/merlin/Library/Application Support/Quicksilver/PlugIns/com.blacktree.Quicksilver.QSAddressBookPlugIn.17D.qsplugin> (not yet loaded) error: Error Domain=NSCocoaErrorDomain Code=3588 "Le paquet « Contacts Plugin » n’a pas pu se charger." UserInfo=0x7f9e16789380 {NSLocalizedFailureReason=Le paquet n’a pas pu se charger., NSLocalizedRecoverySuggestion=Réinstallez le paquet., NSFilePath=/Users/merlin/Library/Application Support/Quicksilver/PlugIns/com.blacktree.Quicksilver.QSAddressBookPlugIn.17D.qsplugin/Contents/MacOS/QSAddressBookPlugin, NSDebugDescription=, NSBundlePath=/Users/merlin/Library/Application Support/Quicksilver/PlugIns/com.blacktree.Quicksilver.QSAddressBookPlugIn.17D.qsplugin, NSLocalizedDescription=Le paquet « Contacts Plugin » n’a pas pu se charger.}

I know I'm using an old dusty OS but is it at least possible to get an older version of the plugin ?

**Comment by skurfer** [comment]
I’ve updated the latest version of the plug-in to require 10.9. (I mean, it obviously already did, but I’ve made the update system aware of that so it won’t show up on 10.7.)

You might need to refresh the list of plug-ins, delete your local copy, and install it again. That should give you the previous version.

**Comment by jeanravin** [comment]
thanks!
