### ISSUE TITLE
After drilling into a folder, searching with keyboard searches catalog instead of folder contents

### ISSUE THREAD

**Issue by devburke** [quicksilver/Quicksilver#2046]
After right-arrowing into a folder in the first panel of QS, I see the folder's contents, as expected. However, if I try and type the name of some of the contents, QS searches the catalog instead of the contents. I'm not sure when this began, but I just noticed it. I'm running OS X 10.10.3.

**Comment by skurfer** [comment]
Should be an easy fix.

1. Right-arrow into a folder
2. Click the gear menu at the top of the results list
3. Under Search Mode, choose “Filter Results”

There are keyboard shortcuts to switch modes, so maybe you hit one by accident. A fresh install of Quicksilver used to behave that way, but I *thought* we fixed that.

**Comment by skurfer** [comment]
Yeah, I fixed it in #1456 (for a fresh install).

**Comment by devburke** [comment]
Thanks! Just seeing this now. That's a huge help!
