### ISSUE TITLE
installation on 10.10.2 fails silently

### ISSUE THREAD

**Issue by ruttenberg** [quicksilver/Quicksilver#2047]
I am an admin user.
I see this in the console log when the failure occurs:
4/12/15 9:02:40.853 PM Quicksilver[1039]: chown -R 0:80 /Volumes/Quicksilver/Quicksilver.app failed.

**Comment by skurfer** [comment]
That’s weird. It seems to think the disk image is the destination, not the source.

The “installation” is only there as a safety net anyway. If you install it the real way (by dragging it from the disk image to `/Applications` before you launch it,  then launching it from there) it should be fine.

**Comment by ruttenberg** [comment]
Thanks for the quick reply. I'll try the "real" way.

Regards,

--Jon Ruttenberg
