### ISSUE TITLE
Quicksilver kick start

### ISSUE THREAD

**Issue by yooperguy** [quicksilver/Quicksilver#2054]
The first time I call up Quicksilver after starting up my computer or bringing it out of sleep, the usual Control/space bar command does not activate it.  I must first click on the icon in the dock, which brings up a quick "screen flash" and then disappearance of the Quicksilver screen.  After that happens, I can initiate Quicksilver with the usual Control/space bar command, and the program operates normally.

**Comment by philostein** [comment]
Same here on startup, from sleep ok.
Yosemite 10.10.3 MBA mid-2011, Quicksilver 1.2.2

Quicksilver not set to hide on log in:

![screen region 2015-04-25 at 15 58 21](https://cloud.githubusercontent.com/assets/535331/7331977/00ec8502-eb64-11e4-8b7a-3a816810c58a.png)

**Comment by skurfer** [comment]
I (also on 10.10.3) rebooted yesterday, and I made sure to watch for this issue. No problem invoking QS. Can you think of anything else that might be involved?
