### ISSUE TITLE
Mini-Bezel result list height gets reset between restarts

### ISSUE THREAD

**Issue by brumm** [quicksilver/Quicksilver#2056]
After a restart of QS, the result list height is set to ~1 item height despite there being multiple results.
Dragging the bottom-right resize handle makes the result list jump to the right height and stay that way.

OSX 10.10.3 (14D136)
QS 1.2.2 (4011)

![qs](https://cloud.githubusercontent.com/assets/170500/7428736/f155671c-eff5-11e4-9065-a680cf5382a5.gif)

**Comment by lgarron** [comment]
I have a similar issue. I usually use Nostromo with the result list expanded to match the width of the interface, and with a bunch of results showing:

![screen shot 2015-05-26 at 17 33 06](https://cloud.githubusercontent.com/assets/248078/7826309/520dec92-03cd-11e5-8298-4e3739b5b6d0.png)

But every once in a while, the list resets to one row:

![screen shot 2015-05-26 at 17 24 54](https://cloud.githubusercontent.com/assets/248078/7826313/55a0c2bc-03cd-11e5-8571-a5ef22f50f18.png)

Unfortunately, this does *not* appear to be correlated with restarting Quicksilver, or with restarting the OS (I just double-checked both). It definitely takes away from the "don't think, just do" philosophy when  this changes on me.

**Comment by genegoykhman** [comment]
I have this issue as well, and it seems to reset from time to time while QS is running. I don't know what causes the height to reset but I don't think it has to do with catalog rescans. I've tried a number of themes and this doesn't affect the behaviour.

QS 1.3.0 (4012)
OS X 10.0.5

**Comment by skurfer** [comment]
It’s any interface that uses the standard results window (which is most of them). It has to do with the auto-resizing behavior. It sometimes things *you* made it 1 item high, instead of realizing it was automatic.

**Comment by lgarron** [comment]
> It has to do with the auto-resizing behavior. It sometimes things you made it 1 item high, instead of realizing it was automatic.

Could you expand on that? I'd love to debug this and squash it.

**Comment by skurfer** [comment]
Thanks for taking a look @lgarron. Digging through old pull requests, it looks like the behavior was introduced in #1446 and tweaked in #1565. That should lead you straight to the relevant code.

**Comment by pjrobertson** [comment]
Yea, It was my baby and it probably does have some bugs.
If you need any help with looking at this, let me know - but thanks for
stepping up!

**Comment by brumm** [comment]
This has long been fixed <3
