### ISSUE TITLE
can't change catalog entry depth

### ISSUE THREAD

**Issue by psifertex** [quicksilver/Quicksilver#2057]
I've created a custom catalog entry to search a specific folder, but I'm unable to change the depth, it's stuck at 1 and doesn't move at all. I've changed `include contents` to `Folder Contents` which made the slider show up at least, but it won't let me change it.

Am I missing something?

**Comment by skurfer** [comment]
I can reproduce this. Clicking another entry, then coming back allows me to change it, but that shouldn’t be necessary.

**Comment by psifertex** [comment]
Thanks, I hadn't noticed that work around yet -- at least I can get that entry configured correctly.

**Comment by awindsor** [comment]
I have the same problem on 1.3.2 under El Capitan. I cannot adjust the depth on custom folder items.

**Comment by psifertex** [comment]
Sorry for not replying earlier -- I no longer use quicksilver so can't test. Closing is appropriate, thanks.
