### ISSUE TITLE
Japanese Kotoeri input in the quicksilver panes is behaving very weirdly

### ISSUE THREAD

**Issue by solidfox** [quicksilver/Quicksilver#2059]
Reproduce by doing the following:
1. Activate Japanese Input Source.
2. Switch to Hiragana Input Source.
3. Type into quicksilver.
4. Compare with any other text field.

I assume this has something to do with quicksilver's input panes not being legit text fields. Still, very undesirable behaviour for those of us who use this input mode frequently.

**Comment by pjrobertson** [comment]
This may well have been fixed by #2395. However, if you're still facing issues using the latest version of Quicksilver, then please post a screenshot of the problem so we can debug further.

Thanks!
