### ISSUE TITLE
Recent QS 1.2.2 (4011) will hang on OSX 10.9.4 often

### ISSUE THREAD

**Issue by JurekRaben** [quicksilver/Quicksilver#2064]
Hi,

the recent version of QS quite often starts to hang as an unresponsive process and doesn't react on user actions anymore. Have to to force quit it using activity monitor. After reloading it works again... 

OSX 10.9.4

**Comment by skurfer** [comment]
This sounds similar to #1977.

Do you have any aliases or symbolic links in your home directory to files on a network drive?

**Comment by JurekRaben** [comment]
Yes, I have links to network drives on my desktop. These links are not accessible sometimes, if the network drive is offline.

**Comment by skurfer** [comment]
OK, thanks. I’ll close this as a duplicate. All these symbolic link issues are high on the list.
