### ISSUE TITLE
Compatibility issues with OS X 10.11 El Capitan: e.g. Open / Run action not shown

### ISSUE THREAD

**Issue by AlexanderWillner** [quicksilver/Quicksilver#2065]
Version: OS X 10.11 (15A178w)

Steps that will reproduce the problem?
1. Invoke QS
2. Select an App
3. Tab
4. Select Open / Run

What is the expected result?
Should be available

What happens instead?
Not in the list of possible actions

Possible workaround:
Use spotlight

Any additional information:
Not clear which actions are working. Some are available, others not.

**Comment by skurfer** [comment]
Time for a new label. :smiley:

I don’t have a VM running El Capitan yet. For one of the apps that doesn’t work, could you please run this in Terminal and post the result here?

```
mdls -name kMDItemContentTypeTree /Applications/Whatever.app
```

**Comment by n9yty** [comment]
$ mdls -name kMDItemContentTypeTree /Applications/Safari.app
kMDItemContentTypeTree = (
    "com.apple.application-bundle",
    "com.apple.application",
    "public.executable",
    "com.apple.localizable-name-bundle",
    "com.apple.bundle",
    "public.directory",
    "public.item",
    "com.apple.package"
)

**Comment by AlexanderWillner** [comment]
Confirmed: 
```
mdls -name kMDItemContentTypeTree /Applications/Utilities/Terminal.app/
kMDItemContentTypeTree = (
    "com.apple.application-bundle",
    "com.apple.application",
    "public.executable",
    "com.apple.localizable-name-bundle",
    "com.apple.bundle",
    "public.directory",
    "public.item",
    "com.apple.package"
)
```
Workaround: select action "Relaunch"

**Comment by n9yty** [comment]
But Relaunch isn't available for anything, is that only if the app in question is already running?  BBEdit, for example, is not running now and has no Relaunch option.

$ mdls -name kMDItemContentTypeTree /Applications/BBEdit.app/
kMDItemContentTypeTree = (
    "com.apple.application-bundle",
    "com.apple.application",
    "public.executable",
    "com.apple.localizable-name-bundle",
    "com.apple.bundle",
    "public.directory",
    "public.item",
    "com.apple.package"
)

**Comment by AlexanderWillner** [comment]
My fault. Workaround isn't working. Maybe the two apps I tested it with were already opened but minimized. Sorry.

**Comment by pjrobertson** [comment]
Yeah Rob is on the right track. It's a problem with UTIs. Currently `NSFilenamesPboardType` is translated as `public.data`, it should probably be `public.item`.

```
/*
 *  kUTTypeItem
 *
 *    generic base type for most things
 *    (files, directories)
 *
 *    UTI: public.item
```

**Comment by n9yty** [comment]
Just for the record, here is what my Mavericks system shows:

$ mdls -name kMDItemContentTypeTree /Applications/Safari.app
kMDItemContentTypeTree = (
    "com.apple.application-bundle",
    "com.apple.application",
    "public.executable",
    "com.apple.localizable-name-bundle",
    "com.apple.bundle",
    "public.directory",
    "public.item",
    "com.apple.package"
)

I don't see a difference... ??

**Comment by skurfer** [comment]
> Currently `NSFilenamesPboardType` is translated as `public.data`, it should probably be `public.item`.

Yeah, [we knew that][1] back when the change was made, but decided against it for reasons we never nailed down. I’ve got a build running with that change and haven’t seen any issues. I’ll run it for a while. When I’m on my super-fast work connection tomorrow, I’ll download El Capitan and see if it fixes the issue.

[1]: https://github.com/quicksilver/Quicksilver/pull/1740#issuecomment-34336226

**Comment by pjrobertson** [comment]
Yup, I remember that as well. I was trying to figure out again this morning why I'd done that but I couldn't remember.
I'll look into it again tonight (hopefully) if I get some time

**Comment by pjrobertson** [comment]
OK, I've looked over this again and I really can't see a reason not to use `public.item`. I guess we should switch. But then again, apparently the UTIs are identical for 10.10 and 10.11 (as per n9yty's post).

I guess we need a VM of 10.11 to test...

**Comment by skurfer** [comment]
Got a VM going. A build that uses `public.item` was no better. I’ll probably have to install Xcode in the VM so I can debug, which is a much more involved project.

**Comment by skurfer** [comment]
OK. It seems that if you ask for `NSURLLabelColorKey` or `NSURLLocalizedLabelKey` (as we do in `-[QSObject infoRecord]`), the entire dictionary comes back empty. Dropping those keys seems to get things working, but I’m not sure what the implications are elsewhere. And that’s gotta be a bug anyway, right?

Maybe they changed the way tags are implemented and made them real things instead of piggy-backing on the old label system, but still, the values should come back.

**Comment by skurfer** [comment]
I reported this to Apple. The number’s 21376326.

**Comment by AlexanderWillner** [comment]
fyi: same in the OS X El Capitan Developer Beta 2 10.11 (15A204h)

**Comment by n9yty** [comment]
For the record, I removed those keys and rebuilt QS and it seems to be funtioning for me. I'm not sure what I have broken or what will not work, but the primary job of launching applications/etc is now back up and running which is good enough for me for now. :)  Thanks for your great work, and for providing the answer to get it running in the short term until Apple fixes their bug(s).

**Comment by AlexanderWillner** [comment]
Works again under OS X 10.11 Beta (15A216g) and QS 1.2.2 (4011).

**Comment by skurfer** [comment]
I’ve updated my VM and the bug appears to be fixed. Thanks for the update.
