### ISSUE TITLE
when using quicksilver to switch between contacts in Contacts, one contact's notes overwrite other contact's notes

### ISSUE THREAD

**Issue by mica5** [quicksilver/Quicksilver#2066]
I searched current open issues for "contacts", and found no similar issue.
Plugin does not appear in http://qsapp.com/wiki/Unsupported_Plugins

REPRODUCE ISSUE:
open contacts
create contact "test1", with notes indicating that it's "test1"
create contact "test2", with notes indicating that it's "test2"
run and wait for quicksilver catalog rescan
open contact "test1" (method does not matter)
without entering "edit contact" mode, begin editing notes of "test1", something along the lines of "more test1 notes"
invoke quicksilver, find contact "test2", and allow it to "show contact"
NEW notes of "test1" will overwrite notes of "test2", and test1 notes will revert to pre-edit notes

![screen shot 2015-06-10 at 10 28 23 am](https://cloud.githubusercontent.com/assets/7075901/8089436/be851540-0f5c-11e5-8373-4582e0647942.jpg)

Quicksilver 1.2.2 (4011)
Mac OS X Yosemite 10.10.2 (14C109)
Contacts Version 9.0 (1563)
Contacts Plugin 2.2.1, updated 2015-03-20

**Comment by skurfer** [comment]
I can reproduce this, and it’s a weird one for sure, but it appears to be a bug in Contacts, not Quicksilver. I can do the same thing by searching for, and opening a contact using Spotlight.
