### ISSUE TITLE
Proxy cache time vs. icon loading

### ISSUE THREAD

**Issue by skurfer** [quicksilver/Quicksilver#2069]
I’ve noticed for a long time that some proxy object icons never update when the icon finishes loading. Finally tracked it down. (Now that I understand the cause, it’s not a new issue, but it became noticeable when the “Latest Download” cache time was lowered to 0.5s)

When the proxy cache expires, the proxy object stops observing icon change notifications. So if it expires before the final icon is loaded, the interface will never get updated.

We could just let the proxy observe icon changes indefinitely, but it could end up observing multiple objects pretty easily.

The correct solution is probably to prevent the cache from getting cleared if the proxy is visible in the interface, but that’s not so easy to pull off.

**Comment by tiennou** [comment]
I'd postpone the cache expiration until the icon actually loads ? I think that can be checked ?

**Comment by skurfer** [comment]
> I'd postpone the cache expiration until the icon actually loads

I don’t really like that idea. What if it doesn’t, or the notification delivery fails somehow? Maybe the expiration is there for a reason. I wouldn’t want to hold it hostage to icon loading.

That gives me an idea, though. Expire the cache when the interface is dismissed. That allows the icon to show, and also solves a more serious problem with functionality: Right now, there’s no guarantee that the object you see is the one an action will run on because it could expire and resolve to something different.

There’s already a notification for the interface hiding, I think. If we could get that working, we might not even need the expiration time any more.

(We do need to think about other things, like proxies used in triggers. In that case, wiping the cache when a command is executed should take care of it.)
