### ISSUE TITLE
El Capitan | Copy (Text) To Clipboard | Bezel (built-in) Bug

### ISSUE THREAD

**Issue by Guid0mcman** [quicksilver/Quicksilver#2074]
In El Capitan, running QS 1.2.2 (4011), with Bezel (built-in) interface, when I have text in the first panel, tab right, type "C" so the "Copy To Clipboard" action appears, the interface "whites out" disappears - apart from the dropdown. (See right hand side of attached image - it appears to have disappeared rather than whiting out in the pic).

There's no problem with any other interface, and no problem if anything other than text is in the first panel. ((See left hand side of attached image).

This has been present since DP1, just thought it might be linked to the other issue so decided to wait.
![bezel built-in copy to clipboard issue](https://cloud.githubusercontent.com/assets/897783/8583787/5c59afa2-25c8-11e5-81e5-ba25efd1e938.jpg)

**Comment by skurfer** [comment]
Is this still happening in the final release?

**Comment by Guid0mcman** [comment]
No - sorry, should have said sooner, it's been fixed a while now!
