### ISSUE TITLE
Chinese characters cannot be entered

### ISSUE THREAD

**Issue by lebigot** [quicksilver/Quicksilver#2076]
Trying to enter (simplified) Chinese characters (in the standard OS X way) results in _no character being displayed_ in the search window (after typing the usual confirmation with the space bar).

Switching back to a latin keyboard (e.g. French) then displays the _keys_ typed, but not the intended Chinese characters (e.g. qinghua, instead of the desired 清华).

**Comment by pjrobertson** [comment]
This appears to be working correctly, and may have been fixed by #2395 
![Screenshot 2022-02-12 at 09 52 48](https://user-images.githubusercontent.com/150431/153691769-94685a93-f528-46dd-9203-3026d04ef31c.png)

Please re-open if you're still facing issues. Thanks!
Please re-open i
