### ISSUE TITLE
Slash character doesn't navigate into folder if I type too quickly

### ISSUE THREAD

**Issue by lgarron** [quicksilver/Quicksilver#2077]
I have a folder called `src` in my index that contains the folder `net`. If I quickly type `src/net` into Quicksilver, it simply drops the slash:

![screen shot 2015-07-23 at 13 32 58](https://cloud.githubusercontent.com/assets/248078/8861474/5d601058-313f-11e5-88d2-ae7f4776037c.png)

If I wait for the `src` folder result to pop up before typing `/`, the correct sequence takes place:
![screen shot 2015-07-23 at 13 33 53](https://cloud.githubusercontent.com/assets/248078/8861500/8bfc67ea-313f-11e5-900b-79089f99dcbe.png)
![screen shot 2015-07-23 at 13 34 00](https://cloud.githubusercontent.com/assets/248078/8861501/8d8c62ea-313f-11e5-9faa-7cd8516cdeb2.png)

This is a bit annoying and surprising, because it doesn't happen if I use the right arrow key instead of `/`. I like `/` because it's nicer to type, but the fact that it fails if I don't pause makes Quicksilver feel unreliable.

**Comment by pjrobertson** [comment]
Confirmed. I've seen this and it's annoyed me a lot.

**Comment by pjrobertson** [comment]
I've made a PR to hopefully fix this. @lgarron if you can build that branch and test it, that would be appreciated. There have always been problems making sure that the / character is handled properly in all situations.

Thanks

**Comment by lgarron** [comment]
#2077 works marvelously! :-D

**Comment by juhucoding** [comment]
For me, the slash seems to have the same effect that the escape key has, no matter how fast I type. 

I'm on version 1.2.2 (4011), OS X 10.10.4

**Comment by lgarron** [comment]
@juhucoding You might need to specify his behaviorist in the preferences.
