### ISSUE TITLE
El Capitan Public Beta: Drill from app to recent documents broken

### ISSUE THREAD

**Issue by iandol** [quicksilver/Quicksilver#2079]
Hi, normally if I select an app in the first pane then press ➡︎ I get to select recent documents. This is not working for me at the moment with 10.11 Beta (15A225f) and QS 4011. I think this was default behaviour before.

**Comment by pwizla** [comment]
Not working for me either. 
Notice the "right arrow" symbol missing next to Numbers in the results list:
http://cl.ly/image/0u2O4229222S#

**Comment by skurfer** [comment]
It’s because this function isn’t getting any information back.

https://github.com/quicksilver/Quicksilver/blob/master/Quicksilver/Code-QuickStepCore/QSObject_FileHandling.m#L294

Hopefully there’s an alternative.

**Comment by skurfer** [comment]
Apple has a super detailed answer at the bottom of the [What’s New for El Capitan][1] under “Removed Frameworks”:

  * SharedFileList. Use ServiceManagement.framework instead.

I’ve looked at that framework and see nothing that helps us.

[1]: https://developer.apple.com/library/prerelease/mac/releasenotes/MacOSX/WhatsNewInOSX/Articles/MacOSX10_11.html#//apple_ref/doc/uid/TP40016227-SW1

**Comment by pjrobertson** [comment]
I suggest asking in the Apple dev forums/mailing list to try and get to the
bottom of it.

**Comment by skurfer** [comment]
Searching around, I saw that LaunchBar also ~~has~~ had this feature, so I tried it out and it’s also broken there. But there’s hope (for us as well, thanks to the very specific answer):

https://forums.obdev.at/viewtopic.php?f=4&t=9984&p=30133

**Comment by pjrobertson** [comment]
Awesome, nice detective work. Should be a pretty easy fix then, but I guess we need to look at the format of that file first.

**Comment by skurfer** [comment]
The format of the file is… unusually flat. Rather than try to make sense of it, I just hit it with a stick a few times.

**Comment by iandol** [comment]
Rob, I really appreciate you file bludgeoning skills!!! :sunglasses: Thanks for this fix!

**Comment by skurfer** [comment]
Glad we figured it out. Someone explained the format, so we’re actually reading it in the right way. Except that it’s private and we’re not supposed to be reading it at all. Other than that… :smiley:
