### ISSUE TITLE
QS hangs after receiving bad data for public.utf16-external-plain-text

### ISSUE THREAD

**Issue by AlexanderWillner** [quicksilver/Quicksilver#2085]
Version: 1.3.0 (4012)
Reproducible: no

Steps that will reproduce the problem?
1. Invoke QS
2. Type "Term" to start the Terminal.app

What is the expected result?
To be able to open Termial.app

What happens instead?
QS hangs w/o using CPU cycles

Possible workaround:
Restart QS via Activity Monitor

Any additional information:
The log states: `06/08/15 07:30:01,635 Quicksilver[411]: bad data for public.utf16-external-plain-text`

**Comment by skurfer** [comment]
I see that “bad data” error quite a bit. It’s probably a coincidence.

Next time it hangs, could you go to Activity Monitor, select Quicksilver, and choose “Sample Process” from the gear menu? Thanks.

**Comment by pjrobertson** [comment]
Hi @AlexanderWillner ,

It's been a while since we've heard from you, so I'm going to close this as we didn't get a hang report from you. If you're still facing an issue with the latest version of Quicksilver, please create a new issue.

Thanks!
