### ISSUE TITLE
Event trigger "External Display Changed" doesn't work for AirPlay

### ISSUE THREAD

**Issue by Sesquipedalian** [quicksilver/Quicksilver#2088]
I created an event trigger to run when I connect an external display, but it never fires when connecting to or disconnecting from an AirPlay display. 

If I use other event trigger criteria, e.g., Active Space Changed, then the trigger fires correctly, so it isn't a problem with the command that is supposed to run.

Due to a lack of hardware, I cannot test whether the External Display Changed works correctly when using a physical connection, so I am not sure if the problem is specific only to AirPlay displays or if it affects all displays.

QS version: 1.3.0 (4012)
Event triggers plugin version: 2.0.0

Computer info:
OS X 10.10.5
MacBook Air (13-inch, Mid 2012)
Intel HD Graphics 4000 1024 MB

**Comment by skurfer** [comment]
“External Display” means one that’s connected via some traditional physical means.

It’s already occurred to me that it would be nice to add AirPlay connect and disconnect to the Event Triggers plug-in, but the OS doesn’t appear to post notifications for these things. If I run across a way to add this, I will, but expect it to appear as a new type of event.

**Comment by Sesquipedalian** [comment]
Too bad. Okay, thanks anyway, Rob.
