### ISSUE TITLE
Find With ... default search changed?

### ISSUE THREAD

**Issue by hmelman** [quicksilver/Quicksilver#2089]
If I highlight text in a cocoa app and use command-esc it's brought into Quicksilver and the default action is Find With... as I expect (and have configured). However, the default web search is a google image search and I *think* it used to be just a google search. If I type g in the third pane a google search does appear as the first pick. If however I just move to the 3rd pane and type control-n to bring up the results list and then use right-click to see the scores of things; Image search has a score of 200 and scrolling down to Google search shows a score of 167 and unfortunately the Make Default option in the menu is greyed out.

1. Did something change with this or am I perhaps misremembering previous behavior (I usually use a trigger that does a google search on the current selection instead of command-escape, but in this case I was using an emacs command I wrote to send some text in an emacs buffer to quicksilver using the command line tool.)
2. Is there a way to set the score/rank/default of web searches for text in the 3rd pane (I didn't see anything in my manual about it :)
3. I'm using a custom Web Search List in my catalog and have disabled the plugins Web Searches (Full List) and (Simple). I don't think this should matter but I'll note, the results list in the 3rd pane shows each web search twice and I don't know why.

QS 1.3.0 (4012) , Web Search plugin 2.7.3, Bezel Interface
OS X 10.10.5, 3.4 GHz i7 iMac, 24GB RAM, 1TB Fusion

**Comment by skurfer** [comment]
1. I can’t think of anything that would explain that. If the entries are appearing more than once, it might be ranking the “new” ones higher than the old ones (assuming they’re different in the first place).

2. Not from the UI, but I actually just wrote up an explanation of how some of the ranking is determined.

  https://github.com/quicksilver/Quicksilver/blob/themap/The_Map.md#how-does-quicksilver-learn

  Basically, you want to find the searches under `implied` and goose the number(s) for the one you want as the default, or lower the number(s) for the others. (I’d probably do that when QS isn’t running.)

3. Me too, and I have no such problems. I had to lie about usage numbers as described above when switching from Google to DuckDuckGo, so I know it works. As for the double entries, I suppose you could right-click and copy then paste each of the duplicates to the first pane so you can run “Show Source in Catalog”.

**Comment by hmelman** [comment]
> On Aug 26, 2015, at 12:11 AM, Rob McBroom <notifications@github.com> wrote:
> 
> 	• I can’t think of anything that would explain that. If the entries are appearing more than once, it might be ranking the “new” ones higher than the old ones (assuming they’re different in the first place).

The duplicates are next to each other, with the same ranking.


> 
> 	• Not from the UI, but I actually just wrote up an explanation of how some of the ranking is determined.
> 
> https://github.com/quicksilver/Quicksilver/blob/themap/The_Map.md#how-does-quicksilver-learn
> 
> Basically, you want to find the searches under implied and goose the number(s) for the one you want as the default, or lower the number(s) for the others. (I’d probably do that when QS isn’t running.)

Took a quick look and I will need more time to investigate. Thanks.

> 	• Me too, and I have no such problems. I had to lie about usage numbers as described above when switching from Google to DuckDuckGo, so I know it works. As for the double entries, I suppose you could right-click and copy then paste each of the duplicates to the first pane so you can run “Show Source in Catalog”.

Copy didn’t work. When I right click on an item in the results shown I see something like:



Note the commands are disabled. This image is for the top Images. But the only difference I see on other entries is the value of score, everything is still greyed out. Having selected one of these, right-arrowing into it doesn’t work either (the pane just shakes a little which is cute).

Howard

**Comment by skurfer** [comment]
Not seeing an image, but I meant you should right-click on the third pane itself. But now that I think about it, ⌘C and ⌘V will work in the first and third panes. It’s just the second pane (when there’s an alternate action) where that doesn’t work.

**Comment by hmelman** [comment]
![screen shot 2015-08-26 at 12 25 54 am](https://cloud.githubusercontent.com/assets/1999190/9494563/968b3cb8-4bd4-11e5-9df0-56aac72ef374.png)

and 

![screen shot 2015-08-26 at 12 26 03 am](https://cloud.githubusercontent.com/assets/1999190/9494566/9bd637fe-4bd4-11e5-9da1-fd45f3ab8e60.png)

and yeah, I don't seem to be able to copy from the 3rd pane after changing the default value. Seems like a bug/misfeature.

**Comment by skurfer** [comment]
In trying it out, I found that I had three of each search URL in the third pane. Clearing caches fixed it, but it shouldn’t happen in the first place obviously.

But I was able to copy any entry I wanted from the third pane using either right-click or ⌘V.

**Comment by hmelman** [comment]
Clearing the caches removed the duplicates. I can now copy from 3rd pane using ⌘C, but of course I no longer need too :)

What should I have to do to increase the score of my google search? I've repeated the command several times and its score has gone up, but slowly. images has a score of 200. After a dozen uses I've gotten the score of google up to 193. Seems like it should go faster (is it just one per usage?). If I type g in the 3rd pane, google jumps to the top. Does that help the score even if I don't type g? I think it does, but I'd like it to move faster than it does. There are several other searches listed above google that I *must* use *way* less frequently (if more than twice ever), so I'm not sure how these scores happened.

**Comment by skurfer** [comment]
The number you see is a count of how many times you’ve used that object after typing that abbreviation. When you haven’t typed anything, the sum of all counts is used. I don’t know if that’s literally the “rank” number, but it’s the most influential thing.

It will go slowly if you try to do it through Quicksilver. Just edit the property list and change the numbers so the one you want has the highest total.

**Comment by hmelman** [comment]
Still not really sure what I'm looking for. The file is 43K lines long (the implied section is 12,500 lines long. Unfortunately "google" is particularly common in the file.

The search that's showing up as the default has one entry in implied:
		<key>http://images.google.com/images?btnG=Search+Images&amp;q=***</key>
		<dict>
			<key>i</key>
			<integer>685</integer>
			<key>image</key>
			<integer>4</integer>
		</dict>

The search I want appears once:
		<key>https://www.google.com/search?q=***</key>
		<dict>
			<key>g</key>
			<integer>13</integer>
			<key>goo</key>
			<integer>1</integer>
		</dict>

Though there's also

		<key>http://www.google.com/search?q=***</key>
		<dict>
			<key>g</key>
			<integer>1154</integer>
			<key>goog</key>
			<integer>2</integer>
			<key>googl</key>
			<integer>4</integer>
			<key>google</key>
			<integer>3</integer>
			<key>quicks</key>
			<integer>1</integer>
			<key>stock</key>
			<integer>2</integer>
			<key>stockq</key>
			<integer>2</integer>
		</dict>

Note the second is http and the first is https. I remember going through my custom web search and changing some urls from http to https, maybe that's the offending change. I also see old qss-http type searches in the file. Using the UI, the google search I want shows 185, but that number (nor any >18x< entry) doesn't appear in the file.

1. Are we sure these are used when these are in the 3rd pane and not just in the first?
2. The only occurrence of FindWith is this. I would have guessed this would point to something relevant but I can't decode it. ">544<" doesn't appear anywhere in the file, so it's not a reference.

		<key>QSURLFindWithAction</key>
		<dict>
			<key>QSActionMnemonic:NSStringPboardType</key>
			<integer>544</integer>
			<key>QSActionMnemonic:qs.contact.address</key>
			<integer>12</integer>
			<key>QSActionMnemonic:qs.contact.phone</key>
			<integer>1</integer>
			<key>f</key>
			<integer>36</integer>
			<key>fi</key>
			<integer>1</integer>
			<key>fin</key>
			<integer>6</integer>
			<key>find</key>
			<integer>9</integer>
			<key>fw</key>
			<integer>105</integer>
			<key>qsactionmnemonic:apple url pasteboard type</key>
			<integer>2</integer>
			<key>qsactionmnemonic:nsstringpboardtype</key>
			<integer>82</integer>
			<key>qsactionmnemonic:public.rtf</key>
			<integer>13</integer>
			<key>qsactionmnemonic:qs.contact.address</key>
			<integer>1</integer>
			<key>qsactionmnemonic:qs.contact.phone</key>
			<integer>2</integer>
			<key>w</key>
			<integer>3</integer>
		</dict>

**Comment by skurfer** [comment]
From your first two XML snippets above, the Images search has been used 685 times with the abbreviation `i` and 4 times with the abbreviation `image`, for a total of 689. The HTTPS Google search has been used only 14 times.

So what you want to do is change the Google search to something like this:

    <key>https://www.google.com/search?q=***</key>
    <dict>
        <key>g</key>
        <integer>1200</integer>
        <key>goo</key>
        <integer>1</integer>
    </dict>

In other words, lie about how many times you've used it.

The old Google search has a combined total of 1168 and would definitely show as the default, but I suspect it's no longer in your catalog. An alternate solution would be to just delete the `https://www.google.com/search?q=***` entry under `implied` and change the original `http://www.google.com/search?q=***` entry to `https` so all of its history will carry over.

> Are we sure these are used when these are in the 3rd pane and not just in the first?

Yes. I just tried fiddling with the numbers and was able to manipulate the order in the third pane. Strangely, I couldn't get Google back as the default for `g` in the *first* pane, so maybe there's more to that than I remember.

I'm not sure what the `QSActionMnemonic:NSStringPboardType` stuff is under `QSURLFindWithAction`. Maybe from a very old version of QS? Maybe a way to rank actions differently for different types? Anyway, the rest of the entries are the same: a count for each abbreviation used to find that action.

**Comment by hmelman** [comment]
Seems to have worked. Thanks very much.

I'm tempted to delete Mnemonics.plist and start over to remove the cruft, but I don't want to retrain everything.

**Comment by skurfer** [comment]
> I'm tempted to delete Mnemonics.plist and start over to remove the cruft, but I don't want to retrain everything.

I did it recently. I probably did a fair amount of “Assign Abbreviation…” at first, but you’d be surprised how quick it relearns. You can always keep a copy of the current file and put it back if it doesn’t work out.
