### ISSUE TITLE
El Capitan Command Line Tool's $PATH location not longer usable

### ISSUE THREAD

**Issue by brodkewitz** [quicksilver/Quicksilver#2095]
A quick search shows this issue as (I think) yet undocumented.

Rootless in El Capitan is preventing Quicksilver from installing its Command Line Tool to /usr/bin. Clicking install through the preferences prompts for admin password then fails silently. After relaunching QS it realizes the binary is missing and prompts to take you to the preferences again.

Hopefully moving it to /usr/local/bin won't cause any issues?

**Comment by skurfer** [comment]
> A quick search shows this issue as (I think) yet undocumented.

Undocumented, but not unknown. It’ll be good to have an issue open, so thanks.

> Hopefully moving it to `/usr/local/bin` won't cause any issues?

That’s where it’ll have to go. The only reason we didn’t do that sooner is that `/usr/local/bin` doesn’t exist by default, so there are a lot more scenarios to worry about.
