### ISSUE TITLE
Freeze on applescript action

### ISSUE THREAD

**Issue by CKHarwood** [quicksilver/Quicksilver#2098]
With a file in the first panel, type "mo" to bring up "Move to. . ." in the second panel.
The "m" is entered and QS brings up custom "Move File to DEVONThink" action applescript.
The "o" is not entered. QS is frozen.

Screenshot of result:
<img width="500" alt="screen shot 2015-09-10 at 11 44 03 am" src="https://cloud.githubusercontent.com/assets/1888159/9794752/8d523a72-57b2-11e5-8d47-fbb2bea466f2.png">

QS 1.3.0 (4012)
OS X 10.10.5 (Yosemite)
Plugins:
<img width="696" alt="screen shot 2015-09-10 at 11 49 57 am" src="https://cloud.githubusercontent.com/assets/1888159/9794676/1b5478fe-57b2-11e5-8ed7-1831aef3c035.png">

**Comment by pjrobertson** [comment]
Is this a custom script you have? Perhaps the custom script isn't playing
well with QS.
Try removing it from the scripts folder in ~/Library/Application
Support/Quicksilver/ then restarting Quicksilver to see if it improves
things. If you still need the script then post its contents here so we can
see what might be going wrong.

**Comment by CKHarwood** [comment]
Ouch, that was my guess as well. I will try removing the script. (What does QS look for in a script before receiving a command to actually run it?)

Meanwhile, a quick cut-and-paste of the code:

```
## Move Quicksilver selections into DEVONthink
## Many elements borrowed; but I forgot to document my sources; Sorry about that.

## Capture the Quicksilver selection
on open these_items
	
	try ## Simplifying variables
		set theSelection to these_items
		tell application "DEVONthink Pro" to set theGroup to current group
		
		## Loop over selected items:
		## 1. Get the path to the item
		## 2. Imports the item into the frontmost DT group
		## 3. Delete the original file
		repeat with theItem in theSelection
			set theFile to POSIX path of (theItem as alias)
			tell application "DEVONthink Pro" to import theFile to theGroup
			tell application "Finder" to delete theItem
		end repeat
		
		## Announcement: "I done good!"
		## The OS X "delete" sound also provides an audio cue
		tell application "Quicksilver" to show notification "DEVONthink Import Complete"
		
	on error ## Catch the error to prevent the script from crashing.
		tell application "Quicksilver" to show notification "DEVONthink Import Error"
	end try
	
end open
```

**Comment by pjrobertson** [comment]
well, some scripts have a routine to tell QS what types of files they take, and whether or not there's an indirect argument (3rd pane object). That script doesn't do either of these things so that's not the problem.

So, in that case I'm not sure what the problem might be. Did removing the script work?

**Comment by CKHarwood** [comment]
Having removed the script, the script is no longer the first action item
for "m" on a Finder object. QS does not freeze on "Move to. . ." Will see
what happens when retraining QS to bring the script up first.

- - - - - - - - - - - - - - - -
The University of Wisconsin-Madison is migrating to a new email service,
and with this service comes a new email address. My new email address is
christopher.harwood@wisc.edu. Please update your contacts.

**Comment by pjrobertson** [comment]
Looks like this was an issue with your original script @CKHarwood  - if you're still having issues with this and the latest version of Quicksilver, then please open a new issue. 

Thanks!
