### ISSUE TITLE
Networking Plugin in OS X 10.12: might not be allowed to disable Wi-Fi

### ISSUE THREAD

**Issue by AlexanderWillner** [quicksilver/Quicksilver#2102]
Version: upcoming OS X 10.12 (in 2016)

Steps that will reproduce the problem?
1. Enabled networking plugin
2. Power off Wi-Fi using QS with this plugin

What is the expected result?
No warning.

What happens instead?
`airportd[64]: WARNING: Quicksilver (424) is not entitled for com.apple.wifi.set_power, temporarily allowing request with background priority —— all entitlement requirements will be strictly enforced in a future release`
## Possible workaround:

Any additional information:
Fine for a least a year.

**Comment by skurfer** [comment]
Thanks for the heads-up.

**Comment by pjrobertson** [comment]
This appears to still be running fine on later versions of macOS. Either Apple changed their mind, or signing the app solved this issue.

I'll close this for now.
