### ISSUE TITLE
Custom script icons don't work right

### ISSUE THREAD

**Issue by devburke** [quicksilver/Quicksilver#2106]
I have some AppleScripts that I use as actions for QuickSilver, and I added custom icons to them through Finder, rather than just using the generic AppleScript icon. This used to work fine in QS, but I've noticed since updating (if not before) that QS will very briefly load the custom icon, before reverting to just showing the generic one. It'd be great if it kept with the icon displayed in Finder, as it used to.

**Comment by skurfer** [comment]
This was broken briefly (as reported in #2010), but should have been fixed quite a while ago.

I see custom icons on AppleScripts and just assigned a new one to be sure. I cleared caches and restarted to be sure and it still shows up.

What versions of Quicksilver and OS X are you using?

**Comment by devburke** [comment]
Quicksilver 1.3.0, on OS X 10.10.5.

I should also point out that this is on a new computer. I downloaded QS from the website, and pulled my preferences and Application Support files from my Time Machine backups. Caches should be fresh.

It’s not quite the same as the #2010, in a couple ways. First, it does initially show the custom icon, but it quickly changes. Second, the icon it changes to isn’t the generic gear icon, but the default icon for AppleScript files.

**Comment by skurfer** [comment]
That sounds like it’s loading the initial icon, then replacing it after the Quick Look preview is loaded. That reminded me that I’ve disabled Quick Look previews for most files (including AppleScript) in Quicksilver.

Turning it back to the default behavior, I see the custom icon first, but then it gets replaced by a faulty Quick Look preview. (I think this is TextMate’s fault.) So in your case, the Quick Look preview is probably a generic script icon. You can confirm that by Quick Looking the file in Finder (or selecting it in the column view).

If that’s it, you’ve found one of the rare cases where the Quick Look preview looks worse than the actual icon. (System Preferences are another.) That’s why I only enable Quick Look on specific types I care about. Details on that can be found at http://qsapp.com/wiki/Hidden_Defaults

**Comment by devburke** [comment]
Weird. It definitely used to behave differently. I was away from my computer all summer, and returned to find it stolen, hence the new one. That also, of course, included the update to 1.3.0, so I can’t say whether it’s the update or the change in computers somehow.

Looks like you’re right about Quick Look though. When I switch to an interface that uses bigger icons, I can definitely see it’s not just generic AppleScript, but a specific Quick Look preview.

Is there a way to blacklist file types from showing previews, rather than a whitelist? Also, how does one go about returning the list to its default setting of, I assume, showing previews for everything?

Thanks!

**Comment by skurfer** [comment]
> Is there a way to blacklist file types from showing previews, rather than a whitelist?

No, but UTIs have a hierarchy, so you can be generic. For example, you can say you want previews for images instead of listing all the image formats individually. This is what I use:

    defaults write com.blacktree.Quicksilver QSFilePreviewTypes -array public.image public.movie public.audio com.adobe.pdf public.x509-certificate net.daringfireball.markdown com.apple.ical.ics

> Also, how does one go about returning the list to its default setting of, I assume, showing previews for everything?

    defaults delete com.blacktree.Quicksilver QSFilePreviewTypes

You can also find out what’s generating the preview for a specific type (like AppleScript) by running `qlmanage -m`. If it’s some third party thing generating the icon you don’t like, maybe you can remove it.

**Comment by devburke** [comment]
Interesting. Thanks for answering all these questions!

**Comment by skurfer** [comment]
No problem. One other useful command… To find the UTI(s) of a particular file:

    mdls -name kMDItemContentTypeTree SomeFile.ext
