### ISSUE TITLE
Quicksilver Screen Capture not capturing

### ISSUE THREAD

**Issue by codeHatcher** [quicksilver/Quicksilver#2109]
The plugin Screen Capture is no longer working. Normally I could invoke region capture and after the capture it would open the file up again in quicksilver which would allow me to drag it into an app or perform another action on the file. This is no longer the case.

**Comment by codeHatcher** [comment]
I have 1.3.0 (4012) OSX 10.10.5

**Comment by pjrobertson** [comment]
On OS X 10.10.5, I can successfully run the 'capture region' command object from Quicksilver's 1st pane and get the image returned to Quicksilver.
Can you please try running this command and letting us know what (if anything) related to Quicksilver is printed to Console.app

Also, are all the screen capture actions the same? And what exactly is the issue? Is it that the file is not showing up again in Quicksilver? Is the screenshot still being made?

**Comment by tiennou** [comment]
Seems to work. QS 1.3.4/ OS X 10.11.3. Please reopen if it still happens.
