### ISSUE TITLE
quicksilver el capitan

### ISSUE THREAD

**Issue by adrian-gluu** [quicksilver/Quicksilver#2110]
latest quicksilver 1.3 is not working or running in osx 10.11 el capitan

**Comment by iandol** [comment]
1.3 (build 4012) runs on 10.11 for me fine (with a couple of bugs due to API changes)...

**Comment by skurfer** [comment]
Not running? So it won’t even launch? Are there any crash reports in `~/Library/Logs/DiagnosticReports/`?

**Comment by adrian-gluu** [comment]
sorry was in the first boot after upgrade, reboot fixed the issue
