### ISSUE TITLE
Invalid context 0x0

### ISSUE THREAD

**Issue by oscar231** [quicksilver/Quicksilver#2112]
I opened my Console.app to check something else, and there's constant messages like this:

10/2/15 09:07:21.155 Quicksilver[800]: CGContextSetFillColorWithColor: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

I am using an iMac14,2 (late 2013), OS 10.10.5

**Comment by skurfer** [comment]
Which interface are you using in Quicksilver? (You can find this in Preferences → Appearance)

**Comment by oscar231** [comment]
Ah, that may be it. I am using an interface called "Yosemite". I got it from https://github.com/mikker/YosemiteInterface-qsplugin <https://github.com/mikker/YosemiteInterface-qsplugin>

I just checked their issues and I see that this has been reported (last year!), but they don't have a solution yet. Maybe I should just change the interface.

Thanks for the prompt response.
