### ISSUE TITLE
Can't upgrade from 4012 -> 4013

### ISSUE THREAD

**Issue by Proggie** [quicksilver/Quicksilver#2113]
I'm unable to upgrade to 4013. Get the following "Download Failed" error:
An error occured while updating: You do not have permission to access the requested resource.
This is on El Capitan, if it makes a difference.

<img width="430" alt="screen shot 2015-10-02 at 9 43 37 am" src="https://cloud.githubusercontent.com/assets/2626514/10252234/09d97396-68eb-11e5-9b94-b119e58e0198.png">

**Comment by Proggie** [comment]
Works now. It's possible that this was caused by a corporate firewall issue.

**Comment by skurfer** [comment]
Didn’t have El Cap until after I had upgraded to 1.3.1, but I went through the Quicksilver update in a VM and it worked as expected. I agree that it sounds like a temporary network issue.
