### ISSUE TITLE
Paste to M$ Word from Quicksilver crashes Word

### ISSUE THREAD

**Issue by StuartRob** [quicksilver/Quicksilver#2116]
The issue is in the title. I have OS X 10.11, Quicksilver 1.3.1 and Word 2011 (14.5.5).

Pasting from the Quicksilver clipboard causes Word to crash and send a crash report to Microsoft but I can't find a saved crash report on my machine. I don't know where to look for more info. 

I've had problems pasting into Apple mail as well but it doesn't crash the app.

**Comment by pjrobertson** [comment]
My assumption is that this is a Microsoft problem. They have announced that they are working on fixes for MS Office for El Capitan. See http://www.macrumors.com/2015/10/05/microsoft-office-2016-el-capitan-bugs/ <http://www.macrumors.com/2015/10/05/microsoft-office-2016-el-capitan-bugs/>

I’m not seeing any crashes with QS 1.3.1, Word 2016 and OS X 10.1

**Comment by skurfer** [comment]
For what it’s worth, FireFox used to crash on pasting but seems to have stopped.
