### ISSUE TITLE
Quicksilver service really needs to be renamed…

### ISSUE THREAD

**Issue by devburke** [quicksilver/Quicksilver#2119]
For years now, Quicksilver has had a service in the OS X services. It's the same entry that allows you to send a selection to QS by pressing cmd-esc. However, it's got an awful, awful name: "Get Current Selection (Do Not Change Shortcut)".

There is so much wrong with that. It's completely un-descriptive of what it does. It doesn't even give any indication that it involves Quicksilver. In addition, putting "(Do Not Change Shortcut)" in the title is really grossly ugly.

Take a look in the services menu:

![screen shot 2015-10-09 at 1 21 46 am](https://cloud.githubusercontent.com/assets/1630645/10387136/637a6228-6e24-11e5-8ee6-544321a58ff0.png)

Why not change it to something like, "Send to Quicksilver"?

Quicksilver has made some wonderful strides in recent years, and this strikes me as one of the most inelegant things left in it.

Just wanted to point it out. Hopefully it'll be remedied in a future update :)

**Comment by skurfer** [comment]
> It's completely un-descriptive of what it does.

Well, not *completely*. :smiley:

> It doesn't even give any indication that it involves Quicksilver.

Good point. That’s a problem.

> In addition, putting "(Do Not Change Shortcut)" in the title is really grossly ugly.

Changing the shortcut breaks the Current Selection proxy object completely, and I think prevents the service from working. But the number of people that will try that is probably pretty low.

**Comment by devburke** [comment]
Touché. Well, I’d say un-descriptive in the context in which you encounter it. From within Quicksilver, it would make sense. But you only encounter it outside of Quicksilver.

That is an interesting problem about changing the shortcut. It’s unfortunate that that breaks the proxy objects. I’d ask why that is, but I think the explanation would go over my head anyway :P

**Comment by Sesquipedalian** [comment]
Agreed. There used to be two functionally identical services, "Send to Quicksilver" and "Get Current Selection (Do Not Change Shortcut)". I used to disable the ugly-named one and just use the pretty one. Now that we only have one service (which makes sense), I would love it if the name were changed to "Send to Quicksilver".

**Comment by TrevorSayre** [comment]
https://github.com/quicksilver/Quicksilver/blob/fe603d1f9811eff21ddc517996f8d9d2e909010b/Quicksilver/PropertyLists/Quicksilver-Info.plist#L230

**Comment by squm** [comment]
how to remove “Send to Quicksilver” ?
