### ISSUE TITLE
Quicksilver does not connect to the web

### ISSUE THREAD

**Issue by Fedster** [quicksilver/Quicksilver#2120]
Hi, I just checked if there are any updates by going to the preference panel and checking manually.  I got:

Internet Connection Error
Unable to check for updates, the server could not be reached. Please check your internet connection

So I uninstalled and reinstalled the very latest, and the same happens.  I am on El-Cap.

**Comment by skurfer** [comment]
El Capitan is blocking the connection. See https://developer.apple.com/library/mac/technotes/App-Transport-Security-Technote/index.html#//apple_ref/doc/uid/TP40016240

We’re working on fixing it, but unfortunately, you’ll never know unless you check for updates on qsapp.com or check back here.

Keep an eye on #2114 for updates.
