### ISSUE TITLE
Feature request: Sync QS settings, etc.

### ISSUE THREAD

**Issue by devburke** [quicksilver/Quicksilver#2121]
It would be great, maybe as a plugin to offer syncing of Quicksilver settings and support files, maybe via Dropbox, etc. I'm no dev myself, but it'd really be useful. Of course, certain things like the Catalog would probably need to be excluded from syncing, but I'll leave that stuff to you guys, if anyone should decide to pick up this idea.

Thanks for considering!

**Comment by pjrobertson** [comment]
This isn't a new idea, see #1158

Unfortunately there's no timeline for when this might be done
