### ISSUE TITLE
Command line tool should remove /usr/bin/qs (if possible)

### ISSUE THREAD

**Issue by pjrobertson** [quicksilver/Quicksilver#2125]
The new command line tool, when installing `qs` into `/usr/local/bin/qs` should also check to see if `/usr/bin/qs` exists, and if so, remove it.

**Comment by skurfer** [comment]
Won’t it get removed when you install El Cap? Are you worried that for people on 10.10 or older, `/usr/bin` might come first in their `$PATH`? By the time there are meaningful changes to the command, I doubt there will be many people in that situation. :smiley: But if we make big changes, this can be one of them.

**Comment by pjrobertson** [comment]
Closing as "Won't Fix"

**Comment by pjrobertson** [comment]
> Are you worried that for people on 10.10 or older, /usr/bin might come
first in their $PATH?

Yeah that was my thought, but you're probably right. In practice...what's
the likelihood!
Right now I have /usr/bin/qs and /usr/local/bin/qs and they both do exactly
the same. When will it change...!?
