### ISSUE TITLE
Web Search icons and ATS

### ISSUE THREAD

**Issue by skurfer** [quicksilver/Quicksilver#2126]
You may have noticed custom web search icons are no longer loaded because we use HTTP.

I checked, and grabicon.com does support HTTPS, but only if you have a premium account. Do we want to:

  1. Set up a premium account?
  2. Add that domain as an exception in `Info.plist`? (I’d hate for that to be the only thing we list.)
  3. Try another approach, like getting icons from the actual site?
  4. Give up on the custom icon thing?

**Comment by pjrobertson** [comment]
I've previously been in contact with the owner of grabicon. I'll get in
touch now and see if we can get a freemium anything.

**Comment by pjrobertson** [comment]
FYI there are lots of alternatives to grabicon, if I don't get a positive answer back from grabicon:

https://api.byi.pw/favicon?url=qsapp.com
https://www.google.com/s2/favicons?domain=qsapp.com

(I'd go for api.byi.pw if we had to, as Google et al is banned in China and others...)

**Comment by skurfer** [comment]
This will become irrelevant when we disable ATS
