### ISSUE TITLE
Text doesn't wrap in text entry mode

### ISSUE THREAD

**Issue by Sesquipedalian** [quicksilver/Quicksilver#2127]
Using QS 1.3.1 and OS X 10.11, if I get some text into the first (or third) pane (e.g. by right-arrowing into a text file) and then press the period key to enter text mode, the text does not wrap to the width of the pane's bounding box. Instead, the text remains one one visual line and I have to scroll horizontally to see the rest of the text. On previous versions of QS and OS X, text did wrap.

This affects all the interfaces I have tested, including Bezel, Primer, Nostromo, and Yosemite (https://github.com/mikker/YosemiteInterface-qsplugin)

**Comment by Sesquipedalian** [comment]
Just updated QS to 1.3.2. No difference.

**Comment by skurfer** [comment]
Hmmm. I can’t reproduce this in any interface.

<img width="396" alt="screen shot 2015-10-16 at 11 52 38 pm" src="https://cloud.githubusercontent.com/assets/154676/10556887/19af55a2-7461-11e5-86cb-6401ce040a75.png">

What settings could we possibly have different that would explain this?

**Comment by Sesquipedalian** [comment]
Sorry, my initial description was a little off. I've updated it now. The problem appears when I have a text string as an object in the first pane and then switch to text mode in order to edit it.

**Comment by Sesquipedalian** [comment]
Sequence to reproduce:
1. With first pane is blank, press "." to enter text mode. Enter some text. Word wrap works:
![initial entry - word wrap works](https://cloud.githubusercontent.com/assets/191731/10557154/8473e35c-745d-11e5-8edb-3d9da0400826.png)
2. Tab over to second pane, then back to first pane.
3. Press "." to enter text mode again. Word wrap no longer works:
![editing - word wrap no longer works](https://cloud.githubusercontent.com/assets/191731/10557162/be91579a-745d-11e5-9a9e-8fbe2ba16177.png)

**Comment by skurfer** [comment]
Thanks for the additional details. I can reproduce it now.

Wouldn’t surprise me if this is related to so many interfaces crashing when you follow the same steps.

**Comment by Guid0mcman** [comment]
Could have sworn there were at least a couple of reports about this on the google group but I can only find the one now... 

https://groups.google.com/forum/#!searchin/blacktree-quicksilver/text$20not$20wrapping/blacktree-quicksilver/X_DIE-e9aX0/ZCU9UidMu0kJ
