### ISSUE TITLE
invalid signature ...

### ISSUE THREAD

**Issue by rprimus** [quicksilver/Quicksilver#2130]
Sat Oct 17 20:08:04 BST 2015

sw_vers:
```
ProductName:	Mac OS X
ProductVersion:	10.11.1
BuildVersion:	15B38b
```
QS_ver:  1.3.1

From system.log:

```
Oct 17 15:31:41 rp-mbp amfid[110]: /Applications/Quicksilver.app/Contents/MacOS/Quicksilver signature not valid: 0xfffefa2a
Oct 17 15:31:41 rp-mbp kernel[0]: proc 558: load code signature error 4 for file "Quicksilver"
Oct 17 15:34:07 rp-mbp com.apple.SecurityServer[86]: suppressing keychain prompt for invalidly signed client /Applications/Quicksilver.app(558)
Oct 17 15:34:35 rp-mbp com.apple.SecurityServer[86]: suppressing keychain prompt for invalidly signed client /Applications/Quicksilver.app(558)
Oct 17 15:35:00 rp-mbp tccd[434]: Unable to verify code signing identity of com.blacktree.Quicksilver:  code identity has been invalidated
```

1.  Is this anything to worry about?
2.  Will this affect functionality in any way?

**Comment by rprimus** [comment]
Sat Oct 17 22:34:03 BST 2015

Have upgraded to 1.3.2 and no longer see these errors.
Research has shown they were due to modifying Info.plist (to allow updates).
(Also, no longer get the Contacts (keychain) permission request upon startup.

Closing.

**Comment by skurfer** [comment]
Yeah, don’t make changes inside the app. :smiley:

I thought that would prevent it from launching at all, and not just log a message. Might depend on your OS X Security preferences.
