### ISSUE TITLE
QS Shortcut unresponsive, then opens up about 15 seconds later

### ISSUE THREAD

**Issue by ethanbeyer** [quicksilver/Quicksilver#2132]
The past few days, I've been having an issue with Quicksilver where I push the keyboard shortcut, `cmd + space`, and nothing happens.

Given about 5-15 seconds, it will eventually open up, and the behavior is very sporadic.

QS v1.3.2 (4014)
Mac OS 10.10.5

**Comment by ethanbeyer** [comment]
This has still be happening, and as I was writing those words, the QS window popped up. I had pushed `cmd+space` about 90 seconds ago.

So...[here's a spindump!!](https://dl.dropboxusercontent.com/u/3194168/qs-unresponsove-spindump.txt)

**Comment by skurfer** [comment]
This looks like the same problem described in #1977, for which there is a fix in the works.

Until then, check your catalog for links or aliases to files on network drives that aren’t available.
