### ISSUE TITLE
Squashed letters in Nostromo interface

### ISSUE THREAD

**Issue by lgarron** [quicksilver/Quicksilver#2133]
I'm getting the following behaviour on my 13-inch Macbook Pro (but not my 15-inch Macbook Pro at work):

<img width="844" alt="screenshot 2015-10-21 14 17 52" src="https://cloud.githubusercontent.com/assets/248078/10650535/dccd86e4-77fe-11e5-891f-87c4bbcc35e9.png">

It doesn't appear to happen with other interfaces.
I don't know what might have caused it, but it may have happened roughly when I upgraded to El Capitan.

**Comment by skurfer** [comment]
I think this might be worse with some fonts. Is that Tahoma in the screen shot?

**Comment by lgarron** [comment]
Quicksilver Preferences tell me I'm using `LucidaGrande 48.0`.
I don't believe I've ever changed the font intentionally.

**Comment by skurfer** [comment]
Ah, thanks. I’m able to get characters to overlap with that font. I think I’m just going to add a preference to turn off “tightening” rather than globally disable it.

Until then, you can try another font. None of the other ones I tried overlap like that.

**Comment by skurfer** [comment]
If you set the update type to Developer Previews and get the latest update, there should be a new preference to take care of this.

**Comment by lgarron** [comment]
The setting works!
<img width="844" alt="screenshot 2016-01-27 23 08 22" src="https://cloud.githubusercontent.com/assets/248078/12637527/e1f58808-c54a-11e5-943b-f2316641f383.png">

**Comment by pjrobertson** [comment]
> If you set the update type to Developer Previews and get the latest update, there should be a new preference to take care of this.

Is this a setting in the Nostromo interface prefs? Or is it a hidden defaults?

**Comment by lgarron** [comment]
> Is this a setting in the Nostromo interface prefs? Or is it a hidden defaults?

General interface prefs:

<img width="825" alt="screenshot 2016-01-27 23 26 44" src="https://cloud.githubusercontent.com/assets/248078/12637882/8a6c209e-c54d-11e5-899c-634dc6f5b9e5.png">

**Comment by skurfer** [comment]
> Is this a setting in the Nostromo interface prefs? Or is it a hidden defaults?

It’s in #2162 @pjrobertson, which was part of dev preview 4017.
