### ISSUE TITLE
E-mail (Send) unhides Mail

### ISSUE THREAD

**Issue by devburke** [quicksilver/Quicksilver#2137]
Using the Send actions to go through Mail always unhides the Mail app, if it's hidden. Running OS X 10.11.1 and Quicksilver 1.3.2. It'd be better if it could do this without bringing the app up.

**Comment by skurfer** [comment]
If you use the “Direct” actions, your mail client won’t be involved and won’t be brought to the foreground.

The “Send” actions use your client, and as far as I know, there’s know way to talk to an application using AppleScript without making it active.

**Comment by devburke** [comment]
The problem with the “Direct” action is that it doesn’t work under the newer, more modern security standards of Google accounts, which don’t store passwords on OS X, but store an authentication token instead.

I’ve used “Send” in the past, and seem to remember it working without unhiding Mail.
