### ISSUE TITLE
Spotlight plugin > date queries 

### ISSUE THREAD

**Issue by bfulop** [quicksilver/Quicksilver#2140]
Time variables don't seem to work in the Spotlight plugin query.

This doesn't work: `kMDItemLastUsedDate >= $time.this_week`
This does: `kMDItemKind == 'Folder'`

**Comment by tiennou** [comment]
IIRC that's a "limitation" of `NSMetadataQuery`/`NSPredicate`. Making a predicate with some "variable" path raises the following error :
`NSComparisonPredicate with right expression which is not NSConstantValueExpressionType or NSAggregateExpressionType given to NSMetadataQuery (kMDItemLastUsedDate >= $time.this_week)`.
(Note this is not from QS but from a test I wrote when I looked at that). So those queries must be manually mangled to become some acceptable predicates, which I didn't feel the will to do.

But then, there is `[NSMetadataQuery predicateFromMetadataQueryString:]`, available 10.9+, thanks Apple ;-).
