### ISSUE TITLE
Can't search within folder after right-arrowing.

### ISSUE THREAD

**Issue by lgarron** [quicksilver/Quicksilver#2143]
Hi, I'm having a problem with QS ever since a recent update:

1. Trigger QS
2. Search for a folder
3. Right-arrow (or press slash)
4. Type to search within the folder

Instead of searching within the folder, Quicksilver starts searching from scratch in the global index.
This started happening for me around Quicksilver version 1.3. I don't recall tweaking any relevant settings, and I can't seem to fix it by playing with any settings.

(Note: the same also happens if I right-arrow into any other result that has children.)

**Comment by pjrobertson** [comment]
Try manually setting the 'search scope' after you have right arrowed into a
folder (the little cog from the results menu)

This seems to be an intermittent bug that nobody's quite figured out yet

**Comment by lgarron** [comment]
> Try manually setting the 'search scope' after you have right arrowed into a
> folder (the little cog from the results menu)

Thanks that worked!

(For future reference: mine was labeled as "Search Mode" rather than "Search Scope". Confused me for a second, but turns out to be the thing I want.)

**Comment by pjrobertson** [comment]
Glad it's sorted

> For future reference: mine was labeled as "Search Mode" rather than
"Search Scope". Confused me for a second, but turns out to be the thing I
want

Apologies on that.

**Comment by anatomatic** [comment]
I think I know what's happening. Previously I never changed modes — always kept it at "Filter Results," therefore I barely knew the setting was there (I knew the setting existed, but forgot where). In latest update QS reverts back to "Filter Catalog" with each invocation. I can't be sure, but that seems like new behavior, and feels like a bug to anyone used to QS preserving it's search mode.

**Comment by skurfer** [comment]
> In latest update QS reverts back to "Filter Catalog" with each invocation.

That used to be the default (when browsing), but it was changed to “Filter Results” in 1.1.0. But even before that, Quicksilver would remember your preference between invocations.

The file that controls that behavior [hasn’t been touched in quite a while][1], and even the changes that *are* there wouldn’t explain this. I haven’t had any problems with the browse mode being forgotten or resetting.

[1]: https://github.com/quicksilver/Quicksilver/commits/master/Quicksilver/Code-QuickStepInterface/QSSearchObjectView.m

**Comment by anatomatic** [comment]
Thanks for clarification, and happy to learn a new QS trick. If I get any more funny business I'll report back here.

**Comment by lgarron** [comment]
This has recently been happening to me on a new macOS install, and left me frustrated and confused. But it made me realize that this is something that might have come up due to migrating my QS settings with my docfiles.

In any case, fixed on my new computer again, since this issue was quick to find. :-)

**Comment by lgarron** [comment]
This just happened to me again, and I think I realized why!

"Search Mode ⌘←/⌘→"

I must be pressing `⌘→`. This is pretty plausible, since it would happen if I don't let go of the `⌘` key quickly enough after pressing `⌘␣`.

<img width="859" alt="Screen Shot 2019-04-08 at 14 28 25" src="https://user-images.githubusercontent.com/248078/55758143-bdae4b80-5a0a-11e9-8965-932052b2c0ef.png">

I'd be happy if that behaviour did not exist (i.e. you have to click or use accessibility nav to change the setting, similar to changing "Sort by Score"/"Sort by Name") or if there was an option to turn it off completely. I never use it, and the only thing it can do for me is accidentally trigger this issue.

**Comment by lgarron** [comment]
Workaround: add triggers for `⌘←`/`⌘→` that perform a bogus action:

<img width="754" alt="Screen Shot 2019-04-08 at 14 36 24" src="https://user-images.githubusercontent.com/248078/55758460-c18e9d80-5a0b-11e9-9d05-705b1130414e.png">

**Comment by lgarron** [comment]
Wait, no. Now QS *doesn't* remember the setting between invocations, and always falls back to "Filter Catalog". 😠
