### ISSUE TITLE
Filtering result lists starts new search

### ISSUE THREAD

**Issue by anatomatic** [quicksilver/Quicksilver#2145]
Invoke QS, choose "Browse Artists" for example, arrow into results, enter "Ra" to filter list, QS starts new query overriding "Browse Artists."

Mac OS X 10.10.5
QS 1.3.2 (4014)

**Comment by skurfer** [comment]
Sounds like you’re in the wrong search mode. See #2143.

Odd that two fairly experienced users would hit this in such a short time, though. Makes me think something might be wrong.
