### ISSUE TITLE
Internet connection error when trying to update.

### ISSUE THREAD

**Issue by nquixote** [quicksilver/Quicksilver#2149]
The notification says "Unable to check for updates, the server could not be reached. Please check your Internet connection". Been going on awhile, maybe since upgrade to El Capitan. I'm on 1.3.1 (4013)

**Comment by skurfer** [comment]
See #2114

I’m afraid you’ll need to download the latest release manually. http://qsapp.com/download.php

**Comment by nquixote** [comment]
Sorry, I actually thought I was on the latest. Thanks. Looks like updates are happening again.

**Comment by skurfer** [comment]
> Sorry, I actually thought I was on the latest.

Well, with no way to check for updates, you couldn’t have known about the new version.
