### ISSUE TITLE
QS crashed when invoquing the calculator plugin under El Capitan

### ISSUE THREAD

**Issue by VBoudry** [quicksilver/Quicksilver#2151]
Since the upgrade to El Capitan, QS is crashing  each time I invoque the calculator plugin by pressing "=".

Here attached a log from such a crash (change the extension .png to .txt/.log/.crash for reading; a hacked needed to attache the file) using the lastest version (1.3.2 [4014] on OSX 10.11.1).

Best regards,
Vincent.

![quicksilver_2015-10-16-154153_vincent-mbp-10](https://cloud.githubusercontent.com/assets/4489813/11038391/0c7637d4-8703-11e5-8839-5cba38216ba2.png)

**Comment by skurfer** [comment]
Please see #2111
