### ISSUE TITLE
Quicksilver crashes when calculator function is started (=)

### ISSUE THREAD

**Issue by jshank** [quicksilver/Quicksilver#2154]
Quicksilver 1.3.2 (4014)
Calculator Plugin 2.2.2

Launching quicksilver and then entering the "=" sign to start a calculation causes quicksilver to crash immediately.

**Comment by HenningJ** [comment]
Please see #2111

**Comment by skurfer** [comment]
Who knew so many people were getting into text-entry mode just to use the calculator? This is the 5th identical report. :smiley:

**Comment by jshank** [comment]
There's very few things faster than ⌘-Space =145*516 enter to get the quick
maths done. Fixed by switching to bezel, thanks!
