### ISSUE TITLE
Switch the Web Search Plugin to use HTTPS URLs where possible

### ISSUE THREAD

**Issue by pjrobertson** [quicksilver/Quicksilver#2156]
Changes I want to make:
- [ ] Add the web search html/php pages containing the search list of search websites from the QS server to the Web Search plugin module git repo
- [ ] add a hook so that when the html/php pages are changed in git it's automatically pushed to the site
- [ ] switch all URLs where possible to HTTPS

@skurfer - have you thought about how to do automatic deploys of the QSApp.com repo to the site?
Also, are all authorized keys still on the server? I can't seem to get in right now (albeit on my work box, maybe only my own MBP public key is on the server)

**Comment by skurfer** [comment]
> have you thought about how to do automatic deploys of the QSApp.com repo to the site?

Well, it’s down to `git pull --rebase`, which is a pretty big improvement. You think we should have a hook to just do that with each commit?

> Also, are all authorized keys still on the server? I can't seem to get in right now (albeit on my work box, maybe only my own MBP public key is on the server)

Crap. I ran the script I have to push out updated dot files, and it includes `authorized_keys`, so I blew away what was there. I don’t think I have a copy from the old server. Do you? If not, send me any keys you want on there.

cc: @HenningJ @tiennou

**Comment by pjrobertson** [comment]
> Well, it’s down to git pull --rebase, which is a pretty big improvement. You think we should have a hook to just do that with each commit?

I think an automatic push hook would be cool, but perhaps it's a bit overkill for something so small?

@skurfer are you happy with my suggestions for this pull?

**Comment by pjrobertson** [comment]
@n8henrie - I'm going to ping you here, as you're our resident GH Action expert 🗡️ 

Do you think you'd be able to:

1. Add the QS server login info as a secret to GitHub (assuming @skurfer approves)
2. Set up a GH action to auto-push qsapp.com repo to the qs server

For the web search plugin:
1. Take the existing `web-search-list-full.html` and  `web-search-list.php` files (in `www/qs0/plugin-data`) and save them in the web search plugin
2. Change URLs to use HTTPS
3. Create a GH action to automatically push these files to the server when the web search plugin is updates?

That'll be a big improvement to keeping everything stored perpetually on the server :)

**Comment by n8henrie** [comment]
Testing at 

https://github.com/quicksilver/QSApp.com/tree/autodeploy

Not working yet: https://github.com/quicksilver/QSApp.com/runs/6890899229?check_suite_focus=true#step:4:9

**Comment by n8henrie** [comment]
Think I have it working.

https://github.com/quicksilver/QSApp.com/actions/runs/2499008371

Could @pjrobertson and @skurfer take a look -- if this looks like an OK approach, I'll remove the `--dry-run`.

I have it currently configured for all pushes (not just tags). Thoughts?

**Comment by pjrobertson** [comment]
This looks good to me. Pulling changes on all pushes I think is fine. But maybe we should have a better review process in place for making sure we don't push code-breaking changes. Could we do something like run the code through a PHP checker first (kind of like a unit test)?

The changes you've made set up autodeploy for the QSApp.com code, but what it doesn't do is the first 3 actions of this issue - that is, pull the web search module code. Although I guess that's the next step ;-)

**Comment by n8henrie** [comment]
> Could we do something like run the code through a PHP checker first (kind of like a unit test)?

I'm sure we could! But I don't know the first thing about PHP, so I'll need someone else to take the lead here -- do you know of any linters or build tools that would serve this purpose?

> the first 3 actions of this issue

That's up next. The web search plugins are one of the very popular parts of Quicksilver that I don't use at all, so I'll have to dig a little to wrap my head around it first.

**Comment by pjrobertson** [comment]
> I'm sure we could! But I don't know the first thing about PHP, so I'll need someone else to take the lead here -- do you know of any linters or build tools that would serve this purpose?

I don't know what's best, but I suggest just using a GH action off the shelf. Here's a couple that popped up in a web search:
https://github.com/marketplace/actions/check-php-syntax-errors
https://github.com/marketplace/actions/php-syntax-checker-lint

1st one has more stars, but looks like it only works on php 8 (there's a branch for php 7), not what our server is running. 2nd one maybe looks simpler
