### ISSUE TITLE
Add Trigger Sorting Method by Key Without Modifier

### ISSUE THREAD

**Issue by hmelman** [quicksilver/Quicksilver#2159]
I have a lot of keyboard triggers defined in QS and I use modifiers to do variations on actions. E.g., control-command-J does Safari Toggle Application. If I add shift and option to that it does Current Web Page (Safari) Open With... Chrome.app. I'm considering shifting from Safari to Chrome as my default browser and was curious as to what similar triggers were available.

It would be really nice if when sorting the Triggers pref pane by Trigger if there was an additional sort order in the cycle that was the main key first and then the modifiers, so that all the "J" triggers were grouped together.

**Comment by skurfer** [comment]
It would probably make sense to change the current behavior and consider the key first, then modifiers, when sorting. I wouldn’t miss the current sort order, personally.

**Comment by hmelman** [comment]
It might be just because I'm used to it, but I get some value out of the current ordering. I have a bunch of Web Search Search For... triggers on control-command and for many of them I have additional Current Selection Find With... Web Search on shifted versions of the same key. It is kind of nice to have them separated at times. 

Other trigger types have to be considered too (mouse corners, etc). Probably makes sense to group by trigger type too. I suspect now it's all sorted based on string representation.
