### ISSUE TITLE
Can't run a trigger on `Quicksilver Selection` with proxy objects.

### ISSUE THREAD

**Issue by lgarron** [quicksilver/Quicksilver#2161]
1. Create a trigger:
  - `Quicksilver Selection`
  - `Open with...`
  - `TextEdit.app`
2. Open Quicksilver, select a text file in the first panel, and trigger the trigger.
  - This works.
3. Open Quicksilver, select the `Latest Download` proxy object in the first panel, and trigger the trigger.
  - This doesn't result in any action (the Quicksilver interface stays open, and nothing is logged in the OS console).

Note: derefencing the proxy object with a right arrow in the first panel works.

**Comment by skurfer** [comment]
Good catch. I *think* this should be pretty easy to fix.

**Comment by skurfer** [comment]
This should be fixed in the Developer Preview for 1.4.0 also. Let me know.

**Comment by lgarron** [comment]
Works perfectly! :-)

**Comment by skurfer** [comment]
Cool. Thanks for letting me know.
