### ISSUE TITLE
Wiki link in intro after install broken

### ISSUE THREAD

**Issue by chrber** [quicksilver/Quicksilver#2165]
https://qsapp.com:80/wiki/Main_Page

this one obviously works:

https://qsapp.com/wiki/Main_Page

**Comment by pjrobertson** [comment]
It's a problem with our server configuration, thanks for reporting it. We'll hopefully get it fixed soon

**Comment by pjrobertson** [comment]
FYI the actual link [in the code](https://github.com/quicksilver/Quicksilver/blob/master/Quicksilver/Code-QuickStepCore/QSPaths.h#L26) is https://qsapp.com/wiki/, which is what's currently returning  https://qsapp.com:80/wiki/Main_Page

**Comment by pjrobertson** [comment]
This has now been fixed (@skurfer)

The server now serves all traffic using SSL (with an invalid certificate). Cloudflare then 'fronts' the website and [uses a valid certificate](https://www.cloudflare.com/ssl/) (see the 'full' option). The only domain not doing this is qs0.qsapp.com, for which we have our own certificate

**Comment by skurfer** [comment]
Great. Thanks, @pjrobertson.
