### ISSUE TITLE
Remember The Milk plugin does not authenticate

### ISSUE THREAD

**Issue by smathy** [quicksilver/Quicksilver#2168]
This is basically the same as #2115, except I'll provide more details hoping that this one doesn't get closed.

Steps to reproduce:

 1. Install plugin, go to prefs
 2. Click Start
 3. RTM website opens (this is where @pjrobertson got to in trying to reproduce the error)
 4. Login and click "Ok, I'll allow it"
 5. Receive error of: _"No callback URL specified for this API key. Your frob value is ...hex key..."_

And your plugin is not authenticated, so from then on when you try to use the "Create task" you will get an error notification of _"You must authenticate this plugin in preferences"_

If you try to click "Finish" in preferences you get _"There was an error ((null)). Make sure you have given this plugin permission to access Remember The Milk."_

I contacted RTM and they said that their API hadn't changed and said it must be something here. This is confirmed in their docs, their API doesn't seem to have changed in a while.

This problem only started recently, maybe with the 1.3.1 release. I've tried building a previous version myself to confirm but I can never seem to get XCode to do what it's meant to.

Please help us restore what really was the most awesome way to create todos ever! Thanks :)

Btw, I'm happy to do more legwork on this if someone can help me get Xcode compiling this all properly (although I suspect that might be more work than checking yourself).

/cc @skurfer @StuartRob

**Comment by StuartRob** [comment]
I tried this today and it worked immediately. I don't know what changed but authentication to RTM and then creation of tasks with Quicksilver worked for me with QS 4016 and RTM plugin 103.

**Comment by smathy** [comment]
Yes, same actually. Definitely it was something at RTM's end that they've now fixed.

Sorry, I forgot I opened this issue.

**Comment by skurfer** [comment]
It’s working for me now, too. Thanks for the update.
