### ISSUE TITLE
Plugin Dev Ref giving 404

### ISSUE THREAD

**Issue by pjrobertson** [quicksilver/Quicksilver#2170]
The plugin development ref, as linked to on the wiki/blog is giving a 404

URL is http://projects.skurfer.com/QuicksilverPlug-inReference.mdown

Linked to on the following pages:

https://qsapp.com/wiki/Developer_Information
http://blog.qsapp.com/post/47769690224/developing-plugins-for-quicksilver

@skurfer

**Comment by skurfer** [comment]
I know. Had to move to a new VM and I took the chance to switch to Nginx. Haven’t gotten the thing working yet, but I will over the break. Thanks!

**Comment by skurfer** [comment]
Back in business. Had to give up on Nginx (for now). :cry:
