### ISSUE TITLE
Type text trigger inserts additional "QSID:QSPresetObjectHistory:" after QS relaunch

### ISSUE THREAD

**Issue by one70** [quicksilver/Quicksilver#2171]
I've created a trigger to type arbitrary text, using instructions on this page:
http://lifehacker.com/261103/use-triggers-for-repetitive-text

The problem: after relaunching Quicksilver, **QSID:QSPresetObjectHistory:** is prepended to my text string. So **sampleText** becomes **QSID:QSPresetObjectHistory:sampleText**.

In short, the trigger looks like this:
Item: type "." , then **sampleText**
Action: **Type text**
Control-Return to combine the trigger, like so:
Item: **Type \"sampleText\"** (becomes **Type \"QSID:QSPresetObjectHistory:sampleText\"** after relaunch)
Action: **Run after delay…**
Target: **0.1s**

The reason for using **Run after delay…** is that the text will combine with the trigger's command key to activate keyboard shortcuts, instead of being typed.
The reason I'm using **Type text** instead of **Paste** is to avoir overwriting the clipboard.

I can reproduce this issue with a clean install of Quicksilver in my Guest account. Can somebody else reproduce it?

Edit:
Running QS 1.3.4 (4016) on Mac OS 10.11.2. I have the following plug-ins installed: Bezel Interface, Contacts, Keyboard Triggers, Networking, Primer Interface, Safari, Window Interface.

**Comment by pjrobertson** [comment]
Which version of Quicksilver are you using, and which operating system are you on?

See this page for the latest versions of Quicksilver: https://qsapp.com/download.php <https://qsapp.com/download.php>

 Also, make sure all your plugins are updated by updating them from within Quicksilver



I prefer to use encrypted email. You can find my public key here <http://patjack.uk/pk.asc>.
Learn how to encrypt your email with the Email Self Defense Guide <https://emailselfdefense.fsf.org/en/>

**Comment by one70** [comment]
Sorry about that. Running QS 1.3.4 (4016) on Mac OS 10.11.2. I have the following plug-ins installed: Bezel Interface, Contacts, Keyboard Triggers, Networking, Primer Interface, Safari, Window Interface.

**Comment by skurfer** [comment]
I think this only happens if you paste directly into the first pane when creating the trigger. If you switch to text-entry mode first, then paste, the text should get stored instead of the object from the clipboard history.

**Comment by one70** [comment]
skurfer, this happens even when typing.

Here's what I tried:
* Restart QS to clear the first pane
* Enter text mode by typing ".", then **sampleText**
* Restart QS
* The unwanted **QSID…** appears

**Comment by one70** [comment]
skurfer, this happens even when typing.

Here's what I tried:

Restart QS to clear the first pane
Enter text mode by typing ".", then sampleText
Restart QS
The unwanted QSID… appears

**Comment by tiennou** [comment]
Reproduced here while trying to make a pure QS trigger that runs `date` and paste the result. That's inconvenient...

**Comment by theschwartz42** [comment]
I am having this exact same issue, seems like it has been around for a while.  Any fix or workaround for this?

**Comment by skurfer** [comment]
This should have been fixed in the recently released 1.5.3. Let us know if you can still reproduce it.
