### ISSUE TITLE
1.3.4 in OS X 10.11.2 can't access preferences.

### ISSUE THREAD

**Issue by markwbennett** [quicksilver/Quicksilver#2173]
I apologize for the length of this issue: I don't have the vocabulary to make it shorter.

OS X 10.11.2
QS 1.3.4
If I try to open Quicksilver preferences, the QS preferences window pops up but then the window for the last open app gets the focus. 

So for example, if I am using Firefox after the Finder and I try to open QS preferences, the QS preference window appears, but the Finder window is in the foreground. 

Then if I click on the QS preferences window that is showing behind the Finder window, the Firefox window jumps to the foreground. If I try to click back on the QS preferences, it goes back to Finder. It's as if clicking on the preferences window acts as a control-tab.

It actually gets stranger. If I try to open Dropbox preferences while QS is running, the Dropbox preference window appears in the foreground, but clicking on it (the Dropbox preference window) switches between Finder and Firefox. I cannot make changes to Dropbox preferences because, even though that window is in the foreground, the focus is on Firefox or Finder.

Other preferences windows (for exampopened from the menu bar exhibit the same behavior when QS is running.

I can drag the windows around, but cannot focus on them to make changes.

I can close the preference window (Dropbox or Quicksilver or whatever) by clicking the close button in the top left corner of the window.

If QS is not running, other preferences windows (including Dropbox) work fine. 

When I quit QS everything seems to work fine. 

When I quit everything but QS the problem persists.

**Comment by skurfer** [comment]
My guess is that you’ve somehow enabled the “Hide other applications when switching applications (shift prevents)” preference.

If you open Quicksilver’s preferences and go to Extras, you should see it. It sounds like you want it disabled. If you’re having trouble getting the window to stay in front, holding Shift when you click it should help (as the name of the setting implies).

**Comment by markwbennett** [comment]
Your guess is correct. Brilliant, thanks.
