### ISSUE TITLE
Result of Scripts depends to kind of shortcut

### ISSUE THREAD

**Issue by meisterleise** [quicksilver/Quicksilver#2174]
That's really strange! I want to set the date by using a script and quicksilver trigger shortcut.
The normal output without quicksilver is:

03.01.2016

According to the kind of shortcut I set to the script, Quicksilver makes different outputs:
ctrl + alt + d
03…01…2016

ctrl + shift + t
03012016

ctr + alt + shift + h
03÷01÷2016

**Comment by skurfer** [comment]
What kind of script? My guess is that the modifiers are still being pressed as the script runs.

Try editing the trigger and change it to activate “On Release” instead of “On Press”.

**Comment by meisterleise** [comment]
Sorry, suggestion didn't work.

This is one of the Scripts:

set h to do shell script "date \"+%d.%m.%Y\""

tell application "System Events"
	set k to name of every application process whose frontmost is true
end tell
set k to k as text

tell application k
	activate
	tell application "System Events"
		keystroke h
	end tell
end tell

**Comment by tiennou** [comment]
Actually, it's not a Quicksilver issue per se, as Rob told above, the modifiers that caused the script to run are still pressed, so you'll get various garbage out of `.`, depending on which shortcut you use.

You might have better luck by storing your script's result in the clipboard and `keystroke "v" using command down` instead.
