### ISSUE TITLE
Calendar plugin crashing in El Capitan?

### ISSUE THREAD

**Issue by claytonrcarter** [quicksilver/Quicksilver#2175]
If I enter text in the first pane and tab to the second, the QS window disappears as soon as I highlight a "Calendar" item.  (Either "Create Calendar Event" or "Create Calendar To-Do".)  Then a dialog is shown that displays the message: "iCal Error: You need to upgrade your calendars to a format compatible with Mac OS X Leopard by opening iCal first".  This happens regardless of what I've entered in pane 1, and it happens without selecting the item in pane 2 (ie hitting `Enter`).  I opened the Calendar app

I'm using OS X 10.11.2 and QS 1.3.4 (4016) and the Calendar plugin is v1.1.2.  I couldn't find any messages in the console about this.

**Comment by skurfer** [comment]
I looked at the source for the Calendar plug-in and that message appears when it can’t get a list of calendars. The method it’s using to get the list appears to be depreciated by Apple, but still works on my system as far as I can tell.

In any case, it looks like that plug-in will need to be updated for whatever the new Calendar API is soon.

**Comment by skurfer** [comment]
I just pushed the changes. Sorry about that. I was bound to miss _one_.

**Comment by pjrobertson** [comment]
Fixed in the latest push to master
