### ISSUE TITLE
Retina graphics for command icons

### ISSUE THREAD

**Issue by danielcompton** [quicksilver/Quicksilver#2180]
There are some graphics which aren't retina ready:

<img width="177" alt="screenshot of google chrome 28-01-16 11-32-26 am" src="https://cloud.githubusercontent.com/assets/811954/12630753/d0ea2042-c5b2-11e5-83c4-66168bda41e3.png">
<img width="177" alt="screenshot of google chrome 28-01-16 11-32-37 am" src="https://cloud.githubusercontent.com/assets/811954/12630758/d6d8a8f2-c5b2-11e5-9c35-b575dfeb1891.png">
<img width="176" alt="screenshot of google chrome 28-01-16 11-32-50 am" src="https://cloud.githubusercontent.com/assets/811954/12630766/dfb316b0-c5b2-11e5-884c-17c0154976c8.png">

Along with many of the assets in https://github.com/quicksilver/Quicksilver/tree/master/Quicksilver/Resources/Images. Some of them have been converted to @2x, but it looks like some of them have been upscaled, rather than redrawn for the higher resolution.

Relates to #1044

**Comment by skurfer** [comment]
Know any designers? :smiley:
