### ISSUE TITLE
QS 1.3.4 fails to find newest Excel app file

### ISSUE THREAD

**Issue by tgafford** [quicksilver/Quicksilver#2185]
typing E gets me /Applications/Microsoft Office 2011/Microsoft Excel.app, but does not find /Applications/Microsoft Excel.app (which is a later version)

**Comment by tiennou** [comment]
Do you mean /Applications/Microsoft Excel.app doesn't even appear in the search results ?

**Comment by tgafford** [comment]
Correct. Not a selectable option.


_____________________________

**Comment by tiennou** [comment]
Hmm, that's weird... Can you check that 1) rescanning the /Applications source in QS preferences does not fix it and 2) that it also doesn't appear under that same source's contents ?

**Comment by tgafford** [comment]
In the attached you can see the choices QS offers, which do not include the app at the top level of /Applications.  And you can see in the /Applications folder both the top level version of this file and the one inside Microsoft Office 2011.  In QS preferences Applications is rescanned every day, and I tried command-R, no help.

**Comment by pjrobertson** [comment]
@tgafford  - are you still having this issue with Excel, or can we mark this as closed?

**Comment by pjrobertson** [comment]
I'll mark this as closed unless we hear back from you. Thanks!
