### ISSUE TITLE
⌃U doesn't clear search string in v1.4.0

### ISSUE THREAD

**Issue by pjrobertson** [quicksilver/Quicksilver#2189]
I'm assuming some of @skurfer's changes have meant that ⌃U no longer clears the search string. Not sure if it was intentional or not, but it's a change in behaviour... and annoying :angry:

**Comment by skurfer** [comment]
Surely due to 3785676b46322cfdbbd6b0263e64589fb5f36bbb

But if the object is cleared, what is the search string being applied to? I can’t get anything weird or annoying to happen.

**Comment by skurfer** [comment]
Yeah, all `delete:` does is `[self setObjectValue:nil]`, while `clearObjectValue` does the exact same thing, plus other stuff specific to the current search object view.

**Comment by pjrobertson** [comment]
This is my scenario:

* type `sag` and realise it's a typo for `safari`
* Press ⌃U to clear the search
* type `safari` as I wanted.

But now ⌃U only clears the object and not the search string, so what I end up getting is a search string for `sagsafari`

**Comment by skurfer** [comment]
OK. I can reproduce that if I type fast enough. Are you sure that wasn’t possible in 1.3.x, though? The same code is called.

I don’t see anything in `setObjectValue:` that would explicitly reset the search, so I guess what you’re seeing makes sense, but again, that’s all it was doing before.

**Comment by pjrobertson** [comment]
Just tried 1.3.4 and it works perfectly, so this is a bug here.

Most likely the search timer isn't getting stopped or something. Would there be any disadvantage to changing it back to `delete:`?

**Comment by skurfer** [comment]
> Would there be any disadvantage to changing it back to `delete:`?

Yes. Try changing it back, or just launch 1.3.4, then:

1. Select a couple of things with `,`
2. Hit `⌃U`

Only the main part of the pane is cleared. `delete:` only seemed to work by voodoo anyway. We should fix it explicitly.
