### ISSUE TITLE
Proxy Objects for Safari Technology Preview

### ISSUE THREAD

**Issue by Guid0mcman** [quicksilver/Quicksilver#2194]
I've been using the new [Safari Technology Preview](https://developer.apple.com/safari/technology-preview/) that  released a couple of weeks ago. It seems very stable and a damn sight more efficient than the regular Safari. In fact, as all my extensions work with it OK, the only thing I'm missing are the Quicksilver Proxy Objects for Safari. I must use my triggers to copy the url to my clipboard and paste it into the current application dozens of times a day!

**Comment by skurfer** [comment]
I think it should be supported eventually, but it would mean either making a mess of the current plug-in, or maintaining two nearly identical ones. Neither sounds that appealing.

**Comment by pjrobertson** [comment]
Unfortunately maintaining two plugins will be difficult for us. As such we'll stick to continuing to support just the official Safari version, not the Technology Preview versions. 

Thanks!

**Comment by skurfer** [comment]
You could probably build a version of the plug-in that worked by just replacing every occurrence of `com.apple.Safari` with `com.apple.SafariTechnologyPreview`.
