### ISSUE TITLE
disable prompt to move Quicksilver app?

### ISSUE THREAD

**Issue by hakamadare** [quicksilver/Quicksilver#2195]
At launch, Quicksilver apparently determines its location in the filesystem, and if it's not located in /Applications, prompts to move it (looks like that check is implemented [here](https://github.com/quicksilver/Quicksilver/blob/19c8ca9825d61df8a9a03bba554322f9a03a854b/Quicksilver/Code-App/QSController.m#L644)?)

This makes Quicksilver somewhat unsuitable for installing via [Homebrew Cask](http://caskroom.io), since Cask installs applications into versioned directories and then symlinks them to ~/Applications. Please consider implementing an application preference setting (hidden preference is fine) to disable the checks in that QSApplicationLaunch case statement.

**Comment by skurfer** [comment]
It should only do that if you’re launching it from a different path for the first time. If you always run it from the same path, no matter what the path is, it shouldn’t bother you. (Unless you’re trying to run it from inside a DMG. It will *always* complain about that.)

So with the way Homebrew Cask works, you should only see this message once after each update. With the bazillion buttons you click during an upgrade, what’s one more? (Kidding. That’s something we’re also working on. #2104)

**Comment by hakamadare** [comment]
got it.  complaining when run from within DMG makes sense (booooooooo), and i also like the idea of turning modal dialogs into notifications.  it would still be nice to be able to quash the check entirely (since i know it will always trigger, and i know i will never want to move the app), but i can live with the current state of affairs.

**Comment by hakamadare** [comment]
And now Homebrew Cask has changed its behavior to move application bundles into /Applications, and so this issue is no longer relevant :)
