### ISSUE TITLE
my input will be changed  since I used QS

### ISSUE THREAD

**Issue by apprentice1988** [quicksilver/Quicksilver#2198]
For example, I input "mac" will return "Command ⌘
Shift ⇧
Option ⌥
Control ⌃
Caps Lock ⇪
Fn".
There are other words will be changed, including 'slim', 'vi', 'rake'. Can you help me?

**Comment by skurfer** [comment]
If you go to Preferences → Command, is the “When activated, switch keyboard to” setting enabled?

**Comment by apprentice1988** [comment]
I found it's dash that causes my confusion. It's not related to QS. It's my wrong.
