### ISSUE TITLE
Null Alert when QS is launched after reboot

### ISSUE THREAD

**Issue by sarahsda** [quicksilver/Quicksilver#2206]
Anyone seeing an issue where following reboot (MacOS 10.11.4) I get a notification from Quicksilver E-mail Support. Clicking on it reveals nothing. Only happens with first use of QS after reboot. Subsequent uses do not generate this notification. See attached screenshot. Don't know what this is trying to tell me. Any ideas would be appreciated. 
![screen shot 2016-05-08 at 09 16 56](https://cloud.githubusercontent.com/assets/19252184/15098427/a7b8234c-150b-11e6-8ef8-e5c6d8e06b01.png)

**Comment by skurfer** [comment]
The rest of that message probably says “not found”. Make sure you have the MailMate plug-in installed if that’s what you’re using, or go to Preferences → Handlers and change your E-mail handler to a plug-in you have installed.

**Comment by pjrobertson** [comment]
Rob's suggestion should have fixed the issue. If you are facing further problems, then please open a new issue.
