### ISSUE TITLE
Focus on next item in finder window after move operation

### ISSUE THREAD

**Issue by gavinhughes** [quicksilver/Quicksilver#2207]
I frequently rename and move many individual files in a folder. The process is:
1. ⌘-esc to select file in Finder.
2. Move it.
3. Esc to dismiss QS.
4. Mouse click the next file in Finder.

I'd like to remove step 4 and just have QS focus on the next file.  Edge case on multiple moved files would be to select the next file after the lowest last moved.

**Comment by skurfer** [comment]
It can’t select the next file after a Move operation, because very often that will be done with no Finder windows open. So it would have to select the next item upon ⌘⎋. I’m not sure how I feel about that. It might be confusing, or very useful.

**Comment by gavinhughes** [comment]
Yes, if the operation is not started with a Finder window in focus, then this behavior would not work. But when working in a Finder window, the absence of this behavior leaves the window in focus with nothing selected. Defaulting to "Another operation is desired, and likely on the next file in the window" is more helpful than no focus at all.

I grant that I'm biased on the usefulness of this feature because my workflow requires manually renaming files in bulk.

**Comment by skurfer** [comment]
We can assume a Finder or Path Finder window is available when using the respective selection proxy, which is why that’s where the behavior would have to be added.

What about just selecting the files in Quicksilver instead of Finder? You can get back to the selection after the move pretty easily with `⌘[`.

**Comment by gavinhughes** [comment]
> What about just selecting the files in Quicksilver instead of Finder? You can get back to the selection after the move pretty easily with ⌘[.

That doesn't quite work. It brings you back to the last handled object. So, if I've moved three files, to move the fourth, I would ```⌘[``` back through three paths then arrive at the parent directory, then ```/``` down and find the next file I need.

**Comment by pjrobertson** [comment]
This is a great suggestion, but I think that the behaviour to select the next file may be somewhat confusing to most users.

If you want to do this, I suggest you set up an [AppleScript Action](https://qsapp.com/wiki/AppleScript_Actions) to do this for you.

1. Create an applescript with the contents similar to:
```applescript
using terms from application "Quicksilver"
  on open files direct_objects with indirect_objects
 set direct_path to POSIX path of (item 1 of direct_objects)
 set indirect_path to POSIX path of (item 1 of indirect_objects)
    tell application "Finder"
         move POSIX file direct_path to POSIX file indirect_path with replacing
        activate
    end tell
  tell application "System Events" to key code 125 -- down arrow
  end open files
 
  on get argument count
    return 2
  end get argument count
 
  on get direct types
    return {"NSFilenamesPboardType"}
  end get direct types
 
  on get indirect types
    return {"NSFilenamesPboardType",  "NSStringPboardType"}
  end get indirect types
 
end using terms from
```
