### ISSUE TITLE
I don't see the toggleApplication action

### ISSUE THREAD

**Issue by wmertens** [quicksilver/Quicksilver#2214]
According to https://github.com/quicksilver/Quicksilver/blob/4203d087d2076ff3adfdb24cb3d036efeecc5b00/Quicksilver/PlugIns-Main/QSCorePlugIn/QSCorePlugIn-Info.plist#L345-L366 there should be an action that shows/hides an application, but I don't see any way to trigger it, it doesn't show up anywhere afaict.

**Comment by skurfer** [comment]
Note the `enabled: false` on lines 356 and 357. That means it’s not enabled by default, but you can turn it on by going to Preferences → Actions.

**Comment by wmertens** [comment]
Oh wow, that was well hidden :)

Could I request then that this action is enabled by default? It seems to work really well for me…

**Comment by hmelman** [comment]
Someone want to update the manual to say as of 1.4.2 the Toggle Application is no long disabled by default :)

**Comment by skurfer** [comment]
> Someone want to update the manual to say as of 1.4.2 the Toggle Application action is no long disabled by default

Done
