### ISSUE TITLE
command line client qs fails to install

### ISSUE THREAD

**Issue by bhyde** [quicksilver/Quicksilver#2216]
I suspect it's trying to write the command line client into /usr/bin/gs.  But the Mac's security prevents that.  I believe /usr/local/bin/qs would work.

**Comment by bhyde** [comment]
Ah, I had an olde version 1.2??.  I'd asked if there were updates but it didn't say anything.

Downloading the newest version, deleting the command line client plug-in, restarting quicksilver, toggling the command line client on again ... etc. etc.   and it now works.

**Comment by skurfer** [comment]
It looks like you figured it out. The latest version is 1.1.0, but in any case, it was updated ahead of El Capitan to work well with SIP.

I’m wondering why you didn’t see the update. What version of Quicksilver and OS X were you using?

**Comment by bhyde** [comment]
Sadly the version I was using is lost, unless you know of some place I might find it.  I've been using QS since forever.  So thank you all!

**Comment by skurfer** [comment]
> Sadly the version I was using is lost, unless you know of some place I might find it.

I’m not worried about the plug-in’s version. Just Quicksilver and OS X.

**Comment by bhyde** [comment]
I was running Quicksilver 1.2.2 and I’m now running 1.4.1.  My Mac 
is/was running the lastest
consumer version of MacOS.  So it was 1.2.2 which, when I hit Check Now 
in the QS Preference panel,
nothing appeared to happen.

**Comment by skurfer** [comment]
OK. The latest Command Line Tool plug-in wouldn’t have shown up for Quicksilver 1.2.2, so that makes sense.
