### ISSUE TITLE
AppleScript Action with direct types handler for Contacts fails

### ISSUE THREAD

**Issue by anatomatic** [quicksilver/Quicksilver#2217]
I'm working on an AppleScript action to copy (some of) the contents of an Address Book Contact. It seems that when I run the action, Quicksilver treats the contact as something other than a file, and therefore the action fails. When I run my script I get the following notification, whether the `direct types` handler is commented out or not:

> **Error loading AppleScript Action**  
> The open files handler takes only files as an input

I'm using the `on open files` handler and 

```applescript
on get direct types
        return {"ABPeopleUIDsPboardType"}  
    end get direct types
```

Any hints to help me get this working would be much appreciated!

Quicksilver 1.4.2 (401A) on OS X 10.11.5
Address Book Plugin installed (along with many others)

**Comment by skurfer** [comment]
While each contact has a corresponding file, the Address Book API doesn’t make the location available. I’m sure there’s still a way to find the files using the UUID or something, but we haven’t had a chance to look into it. (The main benefit in my eyes would be they ability to Quick Look contacts in QS.)

The point is… The contact objects in QS don’t have a file associated with them (yet), so `on open files` won’t be able to do anything.

**Comment by anatomatic** [comment]
Bummer — but thanks for the quick reply and explanation.
