### ISSUE TITLE
Please add web actions for Safari technology preview.

### ISSUE THREAD

**Issue by D-elias** [quicksilver/Quicksilver#2218]
I use web kit (Safari technology preview) for my browser and Quicksilver currently does not have web actions for this browser like "copy current web page to clipboard" and "show contents of current web page".

**Comment by Guid0mcman** [comment]
To quote Rob: "I think it should be supported eventually, but it would mean either making a mess of the current plug-in, or maintaining two nearly identical ones. Neither sounds that appealing."

**Comment by skurfer** [comment]
See #2194
