### ISSUE TITLE
First time triggering safari technology preview

### ISSUE THREAD

**Issue by michaelsalmon** [quicksilver/Quicksilver#2222]
I have a keyboard trigger for Safari Technology Preview which does not work the first time after QS starts, instead I get a "Type to search" popup.

**Comment by skurfer** [comment]
What does the trigger do? Open? Toggle?

Triggers only work on things in the catalog. Is it possible you’re hitting it before QS has had a chance to reload things into the catalog?

**Comment by michaelsalmon** [comment]
I want to open it.

I restarted QS, waited 5 minutes and got the same result.

On the second try I got the same popup but with STP and open as the defaults after I had searched for Te.

**Comment by skurfer** [comment]
> I want to open it.

I know but I’m asking what the trigger is currently set up to do. That is, if you go to Preferences → Triggers and double-click the one in question, what does it say in the middle pane (under “Action”)?

> On the second try I got the same popup but with STP and open as the defaults after I had searched for Te.

It sounds like maybe it’s set up to show the command in the interface instead of run it, but that would be pretty difficult to arrive at accidentally, so I have my doubts.

**Comment by michaelsalmon** [comment]
The action is Open, the command is "Open Safari Technology Preview.app".
[STP.txt](https://github.com/quicksilver/Quicksilver/files/344866/STP.txt)

**Comment by skurfer** [comment]
The XML was helpful, but I still can’t reproduce the problem. I recreated the trigger on my system, even using the same ⌃⌥⌘Q shortcut, and relaunched QS several times.

I didn’t try rebooting or logging out. Does this seem to happen only then, or is it any time QS is relaunched? (You can quickly relaunch it by calling it up and hitting ⌃⌘Q.)

What version of Quicksilver are you running?

**Comment by michaelsalmon** [comment]
I just relaunched qs and got the problem. I am running 1.4.2 (401a).

Once I have done a search then qs remembers but I still get the popup and I have to type return. I usually search for tech as searching for "safari " doesn't work.

This isn't a big deal for me, I just believe in reporting problems.

**Comment by michaelsalmon** [comment]
I changed the trigger and the problem went away.

When I had it as ⌃⌥⌘Q and had started STP I could not create a new trigger, changing the trigger fixed that as well.

**Comment by skurfer** [comment]
OK. Thanks for the update.
