### ISSUE TITLE
Fix deprecation warnings in QS

### ISSUE THREAD

**Issue by pjrobertson** [quicksilver/Quicksilver#2223]
There are several areas of QS (like the QSProcess code) where there have been deprecation warnings for some time.

During the upcoming QS sprint it would be good to go through all warnings and fix any that may be likely to break QS in a new OS release.

**Comment by tiennou** [comment]
I can work on the process part (I rewrote it already once).

There are some things that might be harder to fix : some POSIX->HFS path conversion for AppleScript — deprecated with no replacement, used to get/set Finder comments. There's a public way to get the comment, but no public way to set them (and the setter is "buggy").

**Comment by tiennou** [comment]
Reassign, I got that one somewhere, just need to PR.

**Comment by pjrobertson** [comment]
It's my worry that deprecation warnings will never go away... this issue is a non starter :)
