### ISSUE TITLE
Feature Request: Get Results List of all Browser tabs Titles and URLs

### ISSUE THREAD

**Issue by hmelman** [quicksilver/Quicksilver#2225]
Short: I'd like a way to get a results list of all open Safari tabs titles and urls. Probably useful for other browsers too.

Long: I use a trigger for "Current Web Page (Safari), Paste" all the time. Sometimes I forget i have a second browser window open and try to paste the url of the other browser window into it. It's reasonable that this fails (it pastes the url of the window I'm pasting into). Rather than solve this with some heuristic of find another window to use if pasting into a browser I think it would be useful to get all the titles and urls of tabs open in the browser. I'm not sure how to enable this, perhaps a proxy ojbect used with Show Contents action or maybe right-arrow into Safari and list it like History or Bookmarks. It would be ideal if I could make a trigger to get to this results list immediately.

Ideally this would work for multiple browsers.

**Comment by skurfer** [comment]
The Safari and Chrome plug-ins both add an “Open Web Pages” object to the catalog. It does nothing, but right-arrowing into it should show everything from every tab and window. (Not sure about private browsing.)

I don’t have to tell you, but for others that might read this… You can create a trigger for “Open Web Pages ⇥ Show Contents”.

Firefox is probably a lost cause, since it’s not a proper Cocoa app. OmniWeb could probably do it, but no one is really asking.

**Comment by hmelman** [comment]
Well, thank you for the speedy work. Trigger made. ;)

**Comment by skurfer** [comment]
> Well, thank you for the speedy work.

Very speedy. I did it in -4.5 years. 😉 

https://github.com/quicksilver/com.apple.Safari-qsplugin/commit/d71efa370ea29764bbc681157e10968c44a4150d

**Comment by binjo** [comment]
“Open Web Pages” object is really nice, I've been searching for it so long time to switch opened tabs of browser using QS. Creating triggers as @skurfer mentioned, and "⇥" find the url(tab) I want to switch, then "Reveal tab" in panel 2, just works, but still a bit troublesome, would it be more ideal that being a proxy object? e.x: users can put a "Open Web Pages" in panel 1, "Reveal tab with ...", and type strings match in the web pages list in panel 3, hitting return will result switch to specific tab?

**Comment by skurfer** [comment]
Assuming “Open URL” is your default action for these things, you should be able to just use that. Opening an already open URL has the effect of just selecting the open tab, rather than creating a new one. At least Safari does that.

**Comment by binjo** [comment]
For Google Chrome, "Open URL" just open a new tab, "Reveal tab" will switch to the opened tab, which is not the default action :( So current keystroke for me is like: "⌘/" (my trigger shortcut for "Open Web Pages(Chrome)" "Show Contents") and "/" get the opened tab list, type to select the one I want to switch, tab to 2nd panel, and type "r" to get the "Reveal tab" action and done. I don't know how to make the "Reveal tab" as default action, or save keystrokes of the "tab" and "r", that'd be perfect for my "workflow". :)

**Comment by skurfer** [comment]
> For Google Chrome, "Open URL" just open a new tab

Well, there isn’t much Quicksilver can do about that.

> I don't know how to make the "Reveal tab" as default action

Preferences ⇥ Actions. The highest one that applies to a particular type will be the default. From what I can tell, “Reveal tab” only applies to tabs from Chrome, so dragging it really high up the list shouldn’t interfere with anything else. Haven’t tried it, though.

**Comment by binjo** [comment]
Thanks @skurfer , adjusting "Reveal tab" higher than "Open URL" just works perfect to me.
