### ISSUE TITLE
Request: toggleApplication is equivalent to clicking dock icon

### ISSUE THREAD

**Issue by wmertens** [quicksilver/Quicksilver#2226]
`toggleApplication` is a great command for assigning global shortcuts to apps with triggers, but all it does is hide/bring forward.

Sometimes I close windows that I no longer want to see, while the application keeps running. If I then toggle the app, it will simply not show anything. However, if I switch by clicking the dock icon, it shows the main window again

So it would be nice to have `toggleApplication` behave in the same way…

**Comment by skurfer** [comment]
The Open action behaves like clicking the Dock icon. Seems like Toggle Application should do the same, but I can confirm that it doesn’t.

**Comment by hmelman** [comment]
I'm good with this change (though I fear there's something subtle I'm missing)

Slack is an example app where after closing the window (with the red button) the QS action Open and Toggle Application behave differently.

Numbers (a document style app), if you close all the windows, clicking the Dock icon shows the Open document dialog.
