### ISSUE TITLE
Add support for workflows

### ISSUE THREAD

**Issue by skurfer** [quicksilver/Quicksilver#2227]
…or multi-step triggers.

In other words, the ability to chain commands together, running additional commands on the result.

Examples:
- Finder Selection → Get Path → Paste
- Capture Screen → Scale Image… 50% → Email To… (Compose)

Some of this can be accomplished using Event Triggers, but those _always_ run in response to something.

The code should be fairly simple. Don’t even know where to start with the UI.

**Comment by pjrobertson** [comment]
Is this the same as #538?

**Comment by hmelman** [comment]
Just thinking out loud, the current UI replaces one command window with the next. Perhaps the keystroke to add a new chained command could append a new command window (with the needed panes lined up) below the old one (in the case of Bezel and most others) or to the right (in the case of Primer and other vertical interfaces).

**Comment by skurfer** [comment]
> Is this the same as #538?

No, I think that’s more like #225 on steroids. That is, redisplay the interface with the second pane selected for _all_ actions.

**Comment by skurfer** [comment]
@hmelman I was thinking this UI would be in the preferences somewhere, like the “command builder” for defining commands in triggers. But anyone who wants to volunteer to handle that part can implement it however the want. 😃

**Comment by hmelman** [comment]
Yeah I was thinking of "the command builder" too. I think it definitely should display the entire command (or all the commands?) at the same time.

**Comment by pjrobertson** [comment]
I'm going to reopen this because I think it's the kind of feature we should add for v3.0.0

Basically, I want to do this right now (save as a trigger):

`Current Document → Get Path → Paste`  or `Current Document → Get Path → Copy to clipboard`
