### ISSUE TITLE
add a “Search Term” proxy object

### ISSUE THREAD

**Issue by skurfer** [quicksilver/Quicksilver#2230]
Might need a better name, but anyway, there should be a way to access the text stored in the global “Find” pasteboard.

This is the text you’d see when running `pbpaste -pboard find`. It also appears in the third pane for web searches currently.

**Comment by pjrobertson** [comment]
QS already kind of does this right - if you add something to the find pasteboard with ⌘E then it’s the main thing that’s selected if you do an action like “Google -> Search For… -> [find pasteboard selection]” but I agree a proxy object would be cool. I guess looking at the Web Search Plugin is a good place to start for inspiration

**Comment by skurfer** [comment]
Yeah, I just wanted a way to access it from the first pane. The implementation is dead simple. I just put this here to remind me.
