### ISSUE TITLE
Entering text mode in 3rd pane for 'indirect optional' actions causes sporadic behaviour

### ISSUE THREAD

**Issue by pjrobertson** [quicksilver/Quicksilver#2233]
To reproduce, use either the 'Create File [...]' action or the example Applescript in #2071 

* Type text in the 1st pane
* Tab to the 2nd pane and find the action (e.g. 'Create File')
* Tab to the 3rd pane - you should have an empty 3rd pane ready for text (but it's not already in text mode, which is perhaps the initial problem)
* Press `.` to enter text mode and note how the 3rd pane closes and stay closed until you start typing

@skurfer or anyone else - can you confirm this?

**Comment by skurfer** [comment]
I can reproduce that.

Probably unrelated but shouldn’t “Create File” require a folder in the third pane anyway?

**Comment by skurfer** [comment]
Also, I can look at this together with #2201 unless you’ve already got a fix in the works.

**Comment by skurfer** [comment]
Isn’t this also fixed by #2235?

**Comment by pjrobertson** [comment]
Yes, I tagged the issue but it didn't seem to get assigned automatically.

Fixed by #2235
