### ISSUE TITLE
found some files are lose 

### ISSUE THREAD

**Issue by zhipengbird** [quicksilver/Quicksilver#2245]
when i start build the source ,product some errors:  some files are lost(NSView+DisableSubviews.h,VDKQueue.h), where i can find this files ,please help me!

**Comment by skurfer** [comment]
Please see the instructions at https://qsapp.com/wiki/Building_Quicksilver

Make sure to run the Git commands as shown in steps 1 and 3.

**Comment by zhipengbird** [comment]
i do this guid ,but also has some error, such as   some class duplicate, redifine,there has a picture in my xcode [errorpic](http://7xw3wp.com1.z0.glb.clouddn.com/errorpic)
next what should i do??

**Comment by zhipengbird** [comment]
i did it ,thanks

**Comment by skurfer** [comment]
> i did it ,thanks

You mean you got it to build successfully?

**Comment by zhipengbird** [comment]
yes,thanks
