### ISSUE TITLE
New Shelf action: Edit Shelf Item...

### ISSUE THREAD

**Issue by hmelman** [quicksilver/Quicksilver#2262]
I keep text like the following on the shelf and I need to update it from time to time.

```
QS 1.5.0 (401B) 10.11.6, 3.4 GHz i7 iMac, 24GB RAM, 1TB Fusion
```

Today I use a trigger for Shelf Show Contents, select the item, switch to text mode, make the edits and use the Put on Shelf action. I then have to bring up the Shelf pane, move the new item from to the top to the position I want and delete the old item.

I'd like a new action to edit a text shelf item. It should be enabled when browsing shelf items and It should open a third pane in text mode with the text of the existing item in it. Running it will change the existing item in place. I'm not sure that's possible but I'd find it useful.

**Comment by skurfer** [comment]
Good idea, but for this specific use case, some kind of “System Information” proxy object would also be nice to have.

**Comment by studgeek** [comment]
Even just a Delete Shelf Item would make this common need much easier. Then we could do Put, go back in history, then Delete.
And while we are at it, an "Open Shelf Pane" would be nice (since I never remember the hot key).
