### ISSUE TITLE
Adjustments for path randomization

### ISSUE THREAD

**Issue by skurfer** [quicksilver/Quicksilver#2278]
I haven’t seen any problems myself, since I already had QS installed, but I’m sure we’ll need to revisit the code that tries to prevent launching from a DMG, and the code that warns when running from a new location.

http://weblog.rogueamoeba.com/2016/06/29/sierra-and-gatekeeper-path-randomization/

**Comment by pjrobertson** [comment]
Going to close this, it's been a while :-)

DMG opening still appears to be working
