### ISSUE TITLE
OS 10.12

### ISSUE THREAD

**Issue by Chet2861** [quicksilver/Quicksilver#2280]
Quicksilver is not working with the new OS release do you know when you expect an update?

**Comment by hmelman** [comment]
QS 1.5.0 (401B) is working fine for me on 10.12. Maybe you could provide more details as to your issues and the version you're using.

**Comment by Chet2861** [comment]
Hi Harold-

Here is the error I am receiving-

thanks

D

David Tschetter- CEO

**Comment by Chet2861** [comment]
Hi Harold-

Got it running but now it’s not accessing some of the plug ins such as address book, thoughts?

d

David Tschetter- CEO
David@qwizzle.us <mailto:David@qwizzle.us>
Direct: 720-675-7422

**Comment by skurfer** [comment]
What version of Quicksilver are you running? You probably want 1.4.2, which is available from qsapp.com.
