### ISSUE TITLE
Quicksilver shows in wrong display/space

### ISSUE THREAD

**Issue by diiiv9** [quicksilver/Quicksilver#2288]
I have a Macbook pro connected to a external display , each display is a separate Space ( not mirrored ) . When I activate quicksilver in a fullscreen application on the external display it doesn't show , instead it shows on the Macbook . 

This happens only for fullscreen apps on the external display . 

It does show up on the desktop of the external display .

**Comment by skurfer** [comment]
I can reproduce this. I think you were getting at this, but to be clear for anyone reading, it doesn’t happen with full-screen apps on the primary display.

**Comment by diiiv9** [comment]
Oh , didn't know I could set the external to be the primary display  ( Preferences > Display > Arrangement  , then drag the menu bar to the external display ) . That said and done , it makes sense for QS to show on the Primary display , just like the app switcher does ( the app switcher also follows the dock btw. ) . 

Thanks .
