### ISSUE TITLE
Document XML sharing setting for iTunes >= 12.2

### ISSUE THREAD

**Issue by lgarron** [quicksilver/Quicksilver#2291]
https://support.apple.com/en-us/HT201610

> The iTunes Library.xml file contains some, but not all, of the same information that's stored in the iTunes Library.itl file. The purpose of the iTunes Library.xml file is to make your music and playlists available to other applications on your computer, such as iPhoto, Garageband, iMovie, and third-party software, in OS X Mountain Lion and earlier. These applications use this file to make it easier for you to add music from your iTunes library to your projects.
>
> By default, **iTunes 12.2 and later doesn't create an iTunes Library.xml.** If you're using OS X Mountain Lion or earlier or a third-party app that uses the XML file, you need to enable Legacy library XML support:
>
> 1. Open iTunes.
> 2. From the menu bar at the top of your computer screen, choose iTunes > Preferences.
> 3. Click the Advanced tab.
> 4. Select "Share iTunes Library XML with other applications."

The iTunes plugin documentation should probably mention this. The plugin could possibly also do something smart to notify the user when the file is unexpectedly missing.

**Comment by skurfer** [comment]
> The iTunes plugin documentation should probably mention this.

I thought it did mention that somewhere, but maybe not.

> The plugin could possibly also do something smart to notify the user when the file is unexpectedly missing.

Yeah, if the path to the file isn’t even set, that’s probably a good condition to alert on. But what if you only use the plug-in to control the EQ or select AirPlay devices or something? Then you don’t need the library, but you’d still get the alert.

**Comment by skurfer** [comment]
I added a notification to the plug-in back in March.
