### ISSUE TITLE
applescript apps asking for permission

### ISSUE THREAD

**Issue by jimlongo56** [quicksilver/Quicksilver#2298]
I have 2 triggers that are set to Open applescript apps.

The first one toggles some prefs in Safari.
The second toggles the sound output prefs.

Both will run when launched from the finder.

However when the second one is launched from a QSTrigger with a key command it displays an Applescript dialog "Press Run to run this script, Quit to quit".

Both the script.apps and Quicksilver are checked in System Preferences > Security & Privacy > Accessibility

Mac OS Sierra 10.12.2 
Quicksilver 1.4.2

in case it may be something in the app conflicting with QS here is the script before exporting to an app

    tell application "System Preferences"
	activate
	reveal anchor "output" of pane id "com.apple.preference.sound"
	
	delay 1
	
	tell application "System Events"
		
		if (selected of row 1 of table 1 of scroll area 1 of tab group 1 of window "Sound" of application process "System Preferences" of application "System Events") then
			set selected of row 2 of table 1 of scroll area 1 of tab group 1 of window "Sound" of application process "System Preferences" of application "System Events" to true
			set deviceselected to "Scarlett 6i6 USB"
		else
			set selected of row 1 of table 1 of scroll area 1 of tab group 1 of window "Sound" of application process "System Preferences" of application "System Events" to true
			set deviceselected to "Headphones"
		end if
		
	end tell
	quit
end tell

**Comment by skurfer** [comment]
Have you tried opening the settings for those triggers and selecting “On Release” instead of “On Press”? The behavior of AppleScripts is often affected by modifiers for triggers still being held.

**Comment by jimlongo56** [comment]
Thanks, I just tried that and it had no effect on the behavior.  This is happening on 3 out of 4 applescript apps that I am triggering.

**Comment by skurfer** [comment]
I tried to reproduce this with a small script and noticed that when saving, there was an option for “Show startup screen”. Enabling that caused the confirmation to appear. Disabling it made the applet run immediately. (It didn’t seem to matter how I launched it.)

**Comment by jimlongo56** [comment]
I'm 100% positive I didn't **Export** the scripts that way, but exported them once more - nothing checked, just the dropdown changed to Application.

Surprise!  They launched without the Run dialog (after having to add them to Accessibility again).

They still seem to throw up the dialog once in a while when launched from a QS trigger, maybe 10% in my limited patience for testing them (but I've never seen the dialog when launching the app directly by double clicking it in the finder).

**Comment by skurfer** [comment]
OK. That was probably it, then. Quicksilver basically just asks the OS to open files.
