### ISSUE TITLE
'Type Text' action not working in 1.5.1

### ISSUE THREAD

**Issue by brodkewitz** [quicksilver/Quicksilver#2302]
The 'Type Text' action appears not to be working anymore in version 1.5.1 (build 401C). OS X 10.11.6 on 2012 rMBP.

Rather than typing the text, the system error bell chimes and Quicksilver dismisses as normal. The 'Paste' and 'Paste as Plain Text' actions work as expected. Quicksilver still has permission under assistive applications. (I assume Type Text works by accessing the virtual keyboard?)

Nothing is reported in the console that seems obviously relevant. However, both invoking and dismissing Quicksilver throws multiple WindowServer errors e.g.:
```
1/1/17 2:01:54.439 PM WindowServer[197]: _CGXRemoveWindowFromWindowMovementGroup: window 0x9e is not attached to window 0x2e7
```
Hex code at the end varies. I'm using the Bezel Interface.

Let me know if I can adjust anything to help you test!

**Comment by pjrobertson** [comment]
This is most likely related to #2300

@tiennou - sounds like in #2300 you were suggesting the action be changed to ‘fix’ this as opposed to reverting your commit. If there are multiple actions exhibiting this problem then shouldn’t we revert the commit or find a solution that fixes both what you were trying to fix but doesn’t break this?

**Comment by tiennou** [comment]
Depends on what you want to break ? I'm fine with reverting whatever causes the bug, but this will also revert the clear on close behavior we wanted in #2268.
