### ISSUE TITLE
1Password Plugin Integration is Too Difficult

### ISSUE THREAD

**Issue by ooglek** [quicksilver/Quicksilver#2309]
So I uninstalled and reinstalled the 1Password plugin, 3.1.0, hoping for some sort of amazing success, but to no avail. I found a contents.js in my 1Password .agilekeychain folder, but I couldn't select it.

The 1Password app, though it allows me to "enable 3rd party integrations" doesn't actually tell me where in the world it left that file. It definitely isn't where the default path is, ~/Library/Application Support/1Password 4/...

Finally in GitHub issue #2011 I found the answer -- it is found in ~/Library/Containers/2BURANDOM4JR.com.agilebits.onepassword-osx-helper/Data/Library/3rd Party Integration

So finally I was able to find it. Manually. And with some loss of hair. Using `locate` on the CLI didn't work. When I tried `find ~/Library/ -type f -name "bookmarks-default.json" -ipath "*agilebits.onepassword*" -print` seemed to find the file just fine though.

It shouldn't require 20 years of unix experience and `find` mastery to get a super excellent and useful plugin to work.

I suggest adding such initial scanning of the installer's ~/Library folder so that people installing the plugin need to know absolutely nothing and it "just works." Offer another button that, when the first scan fails to return results, offers "Here's how to enable 3rd party integration" and a "Rescan" button to make it much more simple and works the first time.

If making a system call makes one uneasy (you control all the inputs, so likely not an attack vector, unless a well-written JSON file could break 1Password's security), at least better document the potential locations on the `QS Config -> General -> 1Password` configuration tab, or even find it and offer a "use this file" button once found.

**Comment by skurfer** [comment]
> The 1Password app, though it allows me to "enable 3rd party integrations" doesn't actually tell me where in the world it left that file.

This is the real problem, isn’t it? And there’s not much we can do there.

Scanning potential locations would be a good thing to look at for whoever does the next big update.

**Comment by kvaradhan3** [comment]
1Password6, v6.8.9, QS plugin v3.1.0, you can find that dang bookmarks-default.json in  ~/Library/Application Support/1Password 4/3rd Party Integration/bookmarks-default.json

**Comment by skurfer** [comment]
1Password 7 makes this much easier by switching to a Spotlight-based system. The next release of the 1Password plug-in won’t even have a pref pane because you no longer need to tell it where the items are.
