### ISSUE TITLE
Quicksilver keeps crashing

### ISSUE THREAD

**Issue by Dinky1905** [quicksilver/Quicksilver#2313]
I am still running Yosemite and see no reason to upgrade yet. If it ain't broke, don't fix it....
Quicksilver, however, is constantly crashing since a couple of weeks and no updates appear. Is it dead ? Should I change to something else ? 

The crash is always caused by this:
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000148fb26fbec0

I am running version 1.5.2

**Comment by skurfer** [comment]
> Quicksilver, however, is constantly crashing since a couple of weeks and no updates appear. Is it dead ? Should I change to something else ?

Is this a serious question? There have been *two* updates very recently.

I’ve seen problems myself around the code that caused this crash, but I’m not sure yet what the solution is.

**Comment by skurfer** [comment]
See #2311
