### ISSUE TITLE
Quicksilver crashes when attempting to open a directory in iTerm2

### ISSUE THREAD

**Issue by mumblingsages** [quicksilver/Quicksilver#2314]
I'm on a late 2016 MBP with Sierra (10.12.3) with the latest versions of Quicksilver and iTerm 2. The command prompt, terminal and iTerm plugins are install. iTerm is set as the Terminal handler. 

If I highlight a directory in Finder, hotkey to Quicksilver, press ⌘G to select the dir for Finder, then tab and select Open Directory in iTerm, visually nothing happens. If I subsequently try to hotkey to Quicksilver, it becomes apparent that Quicksilver has crashed and needs to be restarted. How can I go about debugging this flow?

**Comment by skurfer** [comment]
iTerm changed their AppleScript interface in version 3.0.0. We’re still looking for a volunteer to update the plug-in. See #2086
