### ISSUE TITLE
Selected command after trigger change

### ISSUE THREAD

**Issue by michaelsalmon** [quicksilver/Quicksilver#2318]
In the trigger window with the list sorted by trigger there is a problem if the trigger is updated. The row number remains selected rather than the command. This is particularly noticeable when adding a command as the new command is the first row, on many occasions I have forgotten QS's behaviour and believed that I typed the wrong trigger.

Not really a bug but it is irritating.

**Comment by skurfer** [comment]
Probably related to #1997
