### ISSUE TITLE
Safari Plugin 2.3.0 breaks Bookmark catalog on El Capitan

### ISSUE THREAD

**Issue by fschulze** [quicksilver/Quicksilver#2321]
After installing Safari Plugin 2.3.0 the Bookmark catalog was empty and refreshing didn't fill it up again. I'm using Safari 10.0.3 (11602.4.8.0.1) on El Capitan 10.11.6. I reverted to Safari Plugin 2.1.6 from my Time Machine Backup for now. I don't use the other catalogs, so can't say if they break as well.

**Comment by skurfer** [comment]
Version 2.3.1 was released yesterday and should fix the issue.

**Comment by fschulze** [comment]
It does, thanks!
Weirdly I was presented with the 2.3.0 update today and only a forced deinstall/install got me 2.3.1 now.
