### ISSUE TITLE
After update, high CPU usage and unresponsive

### ISSUE THREAD

**Issue by ekrasno** [quicksilver/Quicksilver#2323]
Hi.

Since the most recent update quicksilver has been behaving differently on my macbook pro (OS 10.10.5). Fairly often (3 times today) it stops responding to my hotkey shortcut. I also can't access the logo in the top bar. 

When I open activity monitor to force quit the program, it is taking up 80-99% of the CPU and is "Unresponsive" in Activity monitor. 

Can I easily go back to the previous version?

**Comment by claudiodsf** [comment]
I have exactly the same problem

**Comment by skurfer** [comment]
Recent update to Quicksilver, or recent update to the Safari plug-in?

Previously, the Safari History preset was broken. It’s fixed now, so people are suddenly seeing thousands of additional entries in their catalog. Go to Preferences → Catalog → Plugins and look at the Safari History entry. If it has a huge number, you might want to disable it.

Previous versions of the app itself can be found at https://qsapp.com/archives/

If it’s not related to Safari history, please try this test build, which addresses another possibly related issue. https://cl.ly/0N3W180S2G45

**Comment by ekrasno** [comment]
Hi Rob!

You were 100% right about the history preset. It showed 60,000 entries. I
disabled it. I'll reply again in a few days if it keeps freezing.

Thanks,
Elliot

**Comment by mikeybycrikey** [comment]
I've just had a couple of problems tonight with Quicksilver using large amount of memory and being unresponsive. I thought that I would get around the issue by clearing the history in Safari after reading this issue. It seems to have helped but I've still got 5678 items in the QS Safari history catalog. Seems a bit odd so maybe there is something else going on here as well.

**Comment by claudiodsf** [comment]
I confirm that deactivating the Safari plugin and removing the (huge) Safari history, Quicksilver is now responsive again.

**Comment by piersb** [comment]
63833 entries.

That could be it. I've unchecked the Safari History in Catalog/Plugins/Safari, but left it turned on in Plugins/Safari. Will return here if that doesn't work to report next steps.

NB to anyone else with this problem: going to Catalog/Plugins and unchecking the Safari button looks as if you've stopped the history entries, as the number disappears. But if you then click the disclosure arrow, Safari History is still turned on; you probably need to turn it off there.

**Comment by skurfer** [comment]
I think there was a general problem with large numbers of items in the catalog. The Safari History just happened to be a common source for a lot of people. I’m working on a fix. After the next release of QS, you should be able to re-enable Safari History (if you even want it).
