### ISSUE TITLE
Stop using private SharedFileList API

### ISSUE THREAD

**Issue by alex-carter** [quicksilver/Quicksilver#2326]
Stop using private SharedFileList API.

https://github.com/quicksilver/Quicksilver/blob/master/Quicksilver/Code-QuickStepCore/QSObject_FileHandling.m
https://github.com/quicksilver/Quicksilver/blob/master/Quicksilver/Code-QuickStepFoundation/SFLListItem.h

Quicksilver is using private SharedFileList API by loading the recent app documents .sfl files. If the structure of these files changes in the future Quicksilver may crash. At minimum the NSKeyedUnarchiver that decodes these files should be wrapped in a @try @catch.

**Comment by pjrobertson** [comment]
Makes sense, do you know of any public APIs available for this, or any other ways of getting recent documents into Quicksilver's catalog?

It would be great if you could make a pull request with either some improvements or the try/catch option you suggest. Thanks!

**Comment by skurfer** [comment]
I’m sorry, but this made me laugh a little bit. Using a private API is a step up from “normal”. Most of the information Quicksilver makes available has *no API at all*. A lot of time is spent just figuring out how things are stored on disk and reverse engineering. Things break periodically as a result (recent documents, Safari history) but that’s the cost of having a useful app.

Having said that, reducing the chance of a crash with a try/except is a great idea.
