### ISSUE TITLE
“Show other results” preference missing from UI

### ISSUE THREAD

**Issue by martinlabuschin** [quicksilver/Quicksilver#2328]
I would like the result list only to show if I press e.g. ↓instead of instantly. Is that possible?

**Comment by pjrobertson** [comment]
Go to preferences > Command and then change the dropdown for “Show other results” to ‘manually’

**Comment by martinlabuschin** [comment]
I don't see that dropdown in 1.5.2 (401D)

<img width="558" alt="screen shot 2017-03-08 at 14 27 45" src="https://cloud.githubusercontent.com/assets/4237881/23705729/7bc60f52-040b-11e7-8c79-10f9853f9658.png">

**Comment by skurfer** [comment]
It’s at the bottom, so maybe it’s cut off, but it looks like there should be room to show it. Anyway, try making the window taller.

**Comment by martinlabuschin** [comment]
Thanks, but that doesn't solve it either :(

<img width="1042" alt="screen shot 2017-03-08 at 14 33 10" src="https://cloud.githubusercontent.com/assets/4237881/23705898/2f292214-040c-11e7-871d-90939e57a0dd.png">

**Comment by skurfer** [comment]
Hmm. I thin someone else ran into that a couple of years ago. Not sure what’s going on, but we’ll look into it.

For now, you can run this in Terminal to set the preference:

~~~
defaults write com.blacktree.Quicksilver "Result Window Behavior" -1
~~~

I’d do that when Quicksilver isn’t running (though I’m not sure if it matters).

**Comment by skurfer** [comment]
Can you tell us which version of macOS you’re on?

**Comment by martinlabuschin** [comment]
Terminal command works like a charme! Thanks!

My Mac runs on macOS Sierra Version 10.12.3

**Comment by skurfer** [comment]
I couldn’t find an existing report of this, so I’m renaming and re-opening. Thanks for the info.

**Comment by martinlabuschin** [comment]
FYI:
After setting the option via Terminal, it appeared in GUI. Even setting it via GUI to "immediately" or "delayed", it stayed in the GUI. Even after restarting QS. 

I hope this helps to solve this for others.

**Comment by skurfer** [comment]
That’s probably a huge clue. Thanks!
