### ISSUE TITLE
Quicksilver 1.5.3 doesn't always open in the foreground.

### ISSUE THREAD

**Issue by lgarron** [quicksilver/Quicksilver#2333]
When invoked, Quicksilver 1.5.3 opens *behind* certain windows often. I'm not sure exactly which windows, but it happens consistently when iTunes is in front. I think I've had this problem on multiple computers.

Downgrading to Quicksilver 1.5.2 seems to fix the problem.

Unfortunately, I don't have more information. :-(

**Comment by skurfer** [comment]
That’s a weird one. The only possibly relevant change is that the NIBs were updated to track the deployment target for the project (so they should target 10.10 now).

Which interface do you use?

**Comment by Howmuch** [comment]
Same interview, I use the built-in Bezel interface.

**Comment by lgarron** [comment]
> Which interface do you use?

Nostromo!

**Comment by skurfer** [comment]
I’ll run with iTunes in a normal window for a while to see ifI can reproduce this, but if you find anything else that narrows down the conditions, let me know.

**Comment by lgarron** [comment]
This isn't an issue for me right now, so presumably this is resolved.
