### ISSUE TITLE
Reduce number of individual windows produced during updating

### ISSUE THREAD

**Issue by brumm** [quicksilver/Quicksilver#2334]
Updating Quicksilver produces four individual popup windows, excluding Quicksilver's own TaskViewer, which could count as another window. 
Overall it's a disjointed experience and could benefit from being a more streamlined process.

<img width="532" alt="screen shot 2017-03-24 at 11 54 03" src="https://cloud.githubusercontent.com/assets/170500/24299463/92092dc6-10a9-11e7-936e-cc7ad0819fca.png">
<img width="544" alt="screen shot 2017-03-24 at 11 54 40" src="https://cloud.githubusercontent.com/assets/170500/24299464/920a6132-10a9-11e7-989c-c437106b32a7.png">
<img width="532" alt="screen shot 2017-03-24 at 11 54 53" src="https://cloud.githubusercontent.com/assets/170500/24299465/920ad5e0-10a9-11e7-927e-5619c681e1a2.png">
<img width="504" alt="screen shot 2017-03-24 at 11 54 58" src="https://cloud.githubusercontent.com/assets/170500/24299466/921953a4-10a9-11e7-86cf-b6435fb3d9d0.png">

To contrast this with an example of a different approach, 1Password handles those four individual steps in one window, and displays the changelog inline during the entire process:

<img width="674" alt="screen shot 2017-03-24 at 16 14 18" src="https://cloud.githubusercontent.com/assets/170500/24300649/6a058c26-10ad-11e7-916d-91c464306b3a.png">
<img width="674" alt="screen shot 2017-03-24 at 16 14 24" src="https://cloud.githubusercontent.com/assets/170500/24300646/6a015f70-10ad-11e7-9d4a-06e623309ee1.png">
<img width="674" alt="screen shot 2017-03-24 at 16 14 34" src="https://cloud.githubusercontent.com/assets/170500/24300647/6a024458-10ad-11e7-8a29-97ff9533ac06.png">
<img width="674" alt="screen shot 2017-03-24 at 16 14 41" src="https://cloud.githubusercontent.com/assets/170500/24300648/6a02bd16-10ad-11e7-97df-d0bb20e806f0.png">

**Comment by skurfer** [comment]
See #1859 and #1669

**Comment by brumm** [comment]
Fair enough, sorry for not searching prior issues <3

**Comment by skurfer** [comment]
No problem. I even got it working all using Notification Center about a year ago. The problem is, it only works if the user sets up Quicksilver to use the “Alerts” style, which is out of our control. It’s also application-wide and might not be appropriate for some notifications. I’m sure we’ll revisit it one day, though.
