### ISSUE TITLE
URGENT

### ISSUE THREAD

**Issue by mattbaker** [quicksilver/Quicksilver#2335]
More like I wanted to _urgently_ thank everyone that contributes to Quicksilver. I bet a lot of folks take for granted that this wonderful piece of software is still quietly getting updated. I am one person that does not!

Please feel free to close, but this just seemed so important! ;)

**Comment by skurfer** [comment]
Thanks for the message. There have been a lot of complaints lately. Probably legitimate, but it can still get frustrating, so this was nice to hear.

**Comment by pjrobertson** [comment]
Thanks Matt, all kudos go to Rob (@skurfer). As of late he's been the only guy holding the fort. Thanks Rob!
