### ISSUE TITLE
Repeated crashes

### ISSUE THREAD

**Issue by StuartRob** [quicksilver/Quicksilver#2336]
I'm experiencing repeated crashes; both versions 1.5.3 and 1.5.2 have crashed for me. I've attached multiple crash reports here (zipped). I don't know what to look for in the reports to help identify what the problem might be.
[quicksilver crashes.zip](https://github.com/quicksilver/Quicksilver/files/883281/quicksilver.crashes.zip)

**Comment by skurfer** [comment]
Some are from what’s reported in #2319. Others are from ion loading. I see those myself, but it’s not going to be easy to fix 100%. Here’s a test build that hopefully fixes it. https://cl.ly/3z1a2q1u1n3y

Please let us know if you encounter any problems with it.

**Comment by StuartRob** [comment]
No worries. I've used Quicksilver since Tiger and I'm not proposing to stop. I'll try the build you've offered and let you know what happens.

**Comment by pjrobertson** [comment]
Hi @StuartRob ,

It's been a while since we've heard from you, and hopefully skurfer's build fixed the issue for you! If you're still facing an issue with the latest version of Quicksilver, please create a new issue.

Thanks!
