### ISSUE TITLE
MacOS 10.12.4: cannot use shortcuts any longer 

### ISSUE THREAD

**Issue by radiospiel** [quicksilver/Quicksilver#2337]
I have a file inside my ~/Dropbox folder, which I assigned a shortcut to. Yesterday I updated OSX to 10.12.4 (and indicentally also XCode) and now my assigned shortcut stopped working.

Note that the shortcut is still listed correctly in  ~/Library/Application Support/Quicksilver/Mnemonics.plist

**Comment by skurfer** [comment]
Two possibilities come to mind…

  1. Did the path to the file change in any way?
  2. Is the file in your catalog? That is, can you locate it as soon as Quicksilver is launched without hitting `→` or `/`?

**Comment by radiospiel** [comment]
@skurfer thanks for checking back. 

No, the file didn't change its location, and no, Quicksilver does not locate it any longer. (it used to before my OSX update.)

**Comment by skurfer** [comment]
If you’re using the preset bundled with the Dropbox plug-in, it only scans the top level contents, so unless this file was right at the top, it makes sense that you don’t see it. I can’t explain why you were able to see it before.

There are a few ways to get it back into the catalog.

The mindless brute force method would be to create a custom catalog entry that scans the Dropbox folder to a high depth, but that will also fill your catalog with a lot of things you probably don’t need instant access to.

Another option is to list the file’s full path, along with any others you want added to the catalog, on lines in a text file. Then create a custom File & Folder Scanner entry, point it at that file, and for “Include Contents”, choose “Text Lines”. It will recognize each line as the path to a file and treat it accordingly. (This works for any string QS can auto-detect, like URLs and e-mail addresses, as well.)

What I do (and would recommend) for any one-off files you want to make sure are indexed is to

  1. Install the File Attributes plug-in.
  2. Using either Quicksilver or Finder, tag the files you want added with something like “Quicksilver Catalog”.
  3. Create a custom catalog entry and choose “Tagged Files”.
  4. Configure it to look for whatever tag you came up with in step 2.

**Comment by radiospiel** [comment]
If in the future I see a problem with that I will certainly go the "Tagged Files" way, this seems pretty much doable.

A couple of days the file did now appear again. I didn't do anything special for that. This makes me wonder that maybe the OSX update - which was a "please set your icloud password" kind of update, i.e. felt like a full installation - triggered a rebuild of Spotlight indices, and that certainly  wasn't completed when I tried to open my file via Quicksilver, but now, a couple of days later, the rebuild is completed and all is back to normal..

I hope you don't feel like I wasted your time @skurfer. Thanks once more for your helpful and quite extensive response.
