### ISSUE TITLE
Cube interface crashing again

### ISSUE THREAD

**Issue by ManifoldSky** [quicksilver/Quicksilver#2340]
Trying to tab from first item to second item action causes Quicksilver to crash when using the Cube interface plugin.

**Comment by skurfer** [comment]
It sure does. What version of macOS are you on? I think this might be new in Sierra.

**Comment by skurfer** [comment]
Never mind. I could reproduce it in 10.10.

**Comment by ManifoldSky** [comment]
FTR, 10.12. But yes, I also reproed on 10.10.
Not to say that there aren’t other serious issues that are crashing QS that are most likely specific to 10.12. Can’t really provide repro steps, but after the upgrade, I quite frequently hit the trigger for QS only to find that it has crashed out from under me at some indeterminate period in the past!

**Comment by pjrobertson** [comment]
Considering the Cube interface 'unsupported' at this time. Please switch to an alternative interface.
