### ISSUE TITLE
"Current Selection" becomes "Unknown Clipboard Object" in Firefox 53.

### ISSUE THREAD

**Issue by 1-p** [quicksilver/Quicksilver#2349]
(Only in Firefox 53, still works in other Apps.)

Let's say I do this (as you can see, with "Before you submit an issue, please review the guidelines for this repository." selected in the background)

<img width="819" alt="image" src="https://cloud.githubusercontent.com/assets/17230311/25309378/b898ca58-2780-11e7-9f92-289ec773e4f1.png">

I will get

<img width="1398" alt="image" src="https://cloud.githubusercontent.com/assets/17230311/25309382/cfc41c32-2780-11e7-9aa5-8bdb1541fe69.png">

This only happens after upgrading to Firefox 53.

**Comment by skurfer** [comment]
I was able to reproduce this. It probably has something to do with Firefox not being an actual Cocoa application. (I’m surprised it ever worked.)

There’s a related issue where trying to get the current selection (from Terminal for example) returns nothing at all. Hopefully fixing that will fix this as well.

**Comment by pjrobertson** [comment]
I have just tested this with Firefox 98.0.2 and it appears to be working correctly. This was likely an issue with Firefox.

However, the issue with Terminal is still present.
