### ISSUE TITLE
com.apple.mail not found

### ISSUE THREAD

**Issue by Dinky1905** [quicksilver/Quicksilver#2351]
Recently Quicksilver reported a problem in Email support: mail mediator com.apple.mail not found
What could be the reason for this ?

**Comment by skurfer** [comment]
Either the Apple Mail plug-in isn’t installed, or it wasn’t loaded for some reason. If it failed to load, there might be a reason under “Status” in its info drawer.

**Comment by chiro79** [comment]
Same problem here. "Status" info says "Loaded".
For your info, I have Quicksilver installed in macOS 10.13 public beta.

**Comment by pjrobertson** [comment]
The Mail support has been updated and a new version will be released shortly for 10.14+
