### ISSUE TITLE
Running applications shows thousands of Google Chrome Helper

### ISSUE THREAD

**Issue by yostinso** [quicksilver/Quicksilver#2352]
Quicksilver has been really slow for me recently, and I think I've tracked it down to the Running Applications & Processes catalog entry, which is populated with > 9000 entries for Google Chrome Helper, while Activity Monitor shows merely 18 entries. Triggering "rescan and reindex" doesn't clean up the redundant entries.

Running version 1.5.3 / 401E.

**Comment by skurfer** [comment]
I couldn’t reproduce that, but I just ran Chrome for a couple of minutes with three tabs open. I saw 7 helpers in both Activity Monitor and Quicksilver.

Does it steadily get worse as Chrome is running? Do they all go away when Chrome isn’t running?

**Comment by yostinso** [comment]
Things I just tried:
- Closing Chrome: the count in the catalog decreases by one (I'm assuming for the main Chrome app), and increases by one when I reopen Chrome.
- Opening lots of YouTube tabs: no change
- Closing and re-opening Quicksilver: clears the list to a much more sane 9 entries... but I've done this to fix it before in the past and the issue invariably reoccurs.
- Disabling and re-enabling my extensions one by one: no change.

Interestingly, even though I currently have the usual 20ish Google Chrome Helper processes in Activity Monitor, they aren't showing up in Running Applications & Processes in Quicksilver right now. (I've clicked the Rescan button.)

**Comment by skurfer** [comment]
OK. I guess I’ll just open some tabs in Chrome and leave it running for a while to see if I can reproduce the problem.

**Comment by skurfer** [comment]
I left Chrome running for a couple of days and didn’t see anything, but of course I wasn’t really interacting with it. However, I did start to see what I think are processes representing tabs in Safari (40 when there should be 9), so probably the same issue.

**Comment by radiospiel** [comment]
I have just wondered why QS felt a bit sluggish recently, and discovered that I have a huge number of entries for com.apple.WebKit.WebContent.xpc (See screenshot.)

Note that the only Safari tab active is the one I am writing this ticket in, and `ps aux | grep Safar`returns just 7 hits, none of which include "WebKit".

I'll leave the catalog disabled for now, I don't need it that much anyways.

<img width="1242" alt="screen shot 2017-07-28 at 14 56 27" src="https://user-images.githubusercontent.com/29153/28718286-8da443e2-73a5-11e7-80a5-e51dea8a27cb.png">
