### ISSUE TITLE
QuickSilver hangs all the time with Sierra

### ISSUE THREAD

**Issue by littleyellowcook** [quicksilver/Quicksilver#2357]
Hi,

Ever since I upgraded to Sierra, QuickSilver takes a long time to load (pressing cmd+space) 
If I hover over the QuickSilver icon on menu bar during this time, the spinning disc is observed.
I checked that I am using the latest version of QuickSilver already.

Is this a common issue? have you any suggestion? should I de-install + reinstall?

This is my machine spec
MacOS Sierra 10.12.4

MacBoo Pro Ret 15in
2.3Ghz i7
8GB DDR3
Intel Iris Pro 1536mb

**Comment by skurfer** [comment]
It’s been a common complaint since the Safari plug-in was fixed. You might want to disable the Safari History preset for now.

It can be found under Preferences → Catalog → Plugins → Safari

See #2331

**Comment by littleyellowcook** [comment]
Perfect!  Problem solved.
Thank you so much for such prompt response, I was lost without Quicksilver.

And thank you for such wonderful product!
Have a good day.

Philomena.

**Comment by dfallman** [comment]
Thank you! I have had the same issue and this solved it for me as well.
