### ISSUE TITLE
Can't enter/edit Spotlight query in 1.5.3

### ISSUE THREAD

**Issue by arezeeman** [quicksilver/Quicksilver#2358]
I recently upgraded to Quicksilver 1.5.3 (right after setting up a new MacBook pro, so I had just transitioned from El Capitan to Sierra as well). I have a custom catalog of applications based on a Spotlight search, which was not working quite right, but when I open the info drawer for it, the Query text box is empty. And if I create a new Spotlight catalog source, I can't enter a query. It's like the text box is disabled. I have version 2.1.2 of the Spotlight plugin.

The query for my old catalog entry is still in the Catalog.plist file, and that query is still used to populate the catalog entry. Editing in that file is therefore a workaround for this problem.

As an aside, what I want is a Catalog entry that includes all the applications in two different folders (I find it useful to separate user from system apps). I don't understand why this is so difficult! Here are the things I've done:

- Make a special folder with soft links to the two applications folders and catalog that parent folder. That used to work (years ago) but quicksilver no longer follows links or aliases. Is there any reason for that? Following soft links is totally SOP in unix.

- Do a spotlight search for applications but exclude system applications (meaning, exclude when kMDItemSupportFileType is MDSystemFile). That was fine for a year or two, but now various random apps (for instance, Google Chrome) are marked as system files.

- I also tried a catalog Group to combine the two folders. That almost works, except that it gives me a catalog of catalog entries, which can't be used to launch the apps.

Any hints would be welcome. Having said that, I don't mean to complain--qs is amazing and indispensable to me. Many thanks for all the hard work.

**Comment by skurfer** [comment]
I have a Spotlight-based catalog source for applications as well. I haven’t touched it for years, but if I go to the settings, I see what you describe. Thanks for the report.

**Comment by pjrobertson** [comment]
This appears to be working for me no problem. Again, not sure if you checked before applying the `noactivity` tag @skurfer ?

![Screen Region 2022-04-30 at 21 00 20](https://user-images.githubusercontent.com/150431/166106644-b8e4bdc5-fcb1-4f45-a090-0e2bb3dffba8.png)
