### ISSUE TITLE
Slow to respond on return from sleep

### ISSUE THREAD

**Issue by ffr2822** [quicksilver/Quicksilver#2360]
It appears like quicksilver has crashed if the hotkey combo is hit right after returning from sleep mode. 
You can see the spinning beachball of death in the status bar, and it seems like the only way to get things working again is to kill off the quicksilver process (from the terminal, there is no other way I found). The reality is that it is EXTREMELY slow to respond to that first hotkey signal - defined as anything from 10 to 120 seconds. Yes, 2 minutes (or more). I discovered this when I decided to just start the app from the finder - the popup appeared long after I had already started using the program I started.  After that first very long delay, normal response is restored. 

OS: 10.12.4
QuickSilver version - 1.5.3(401E)
Mid 2015 MacBook Pro Retina with SSD
Of note: I'm an emacs user. The default hotkey for quicksilver collides with the "set mark" command in emacs (ctrl-space). As a result I have it mapped to option-space. It has been working for years without this delay - so it's something newish.

Additional information: I generally do not restart my laptop - I just put it to sleep (Been a unix user for over 30 years - not used to having to reboot machines). I just checked, and the memory allocated to QS exceeded 4.3GB - this explains the very slow start -it was restoring from disk then compressed memory. A clean restart shows 98M of memory at start up. Every time QS is invoked via hotkey it leaks between 2 and 10MB.

Note:Sorry - this appears to be a duplicate of 2343 "Memory Leak" - I thought it was just slow response until this morning.

**Comment by ffr2822** [comment]
Additional information: I generally do not restart my laptop - I just put it to sleep (Been a unix user for over 30 years - not used to having to reboot machines). I just checked, and the memory allocated to QS exceeded 4.3GB - this explains the very slow start -it was restoring from disk then compressed memory. A clean restart shows 98M of memory at start up. Every time QS is invoked via hotkey it leaks between 2 and 10MB.

**Comment by ffr2822** [comment]
Sorry - this appears to be a duplicate of 2343 "Memory Leak" - I thought it was just slow response until this morning.

**Comment by skurfer** [comment]
The “Something newish” is probably the fact that the Safari plug-in was fixed and your catalog suddenly has thousands of things in it that weren’t there before. The work-around for now is to disable Safari History (under Preferences → Catalog → PlugIns → Safari).

**Comment by skurfer** [comment]
Sounds like #2331
