### ISSUE TITLE
Random Freezing

### ISSUE THREAD

**Issue by LanceDaoust** [quicksilver/Quicksilver#2363]
Dont know why, but the menubar icon becomes a beachball and all hotkeys die. After some period of time every hotkey pressed while it was frozen magically are launched at the same time.

Sierra 10.12.5
Quicksilver 1.5.3 (401E)

**Comment by skurfer** [comment]
Sounds like #2331

I’d recommend disabling the Safari History preset until the next release. (It’s under Preferences → Catalog → Plugins → Safari.)
