### ISSUE TITLE
Contents (text lines) of files added to catalog not showing up

### ISSUE THREAD

**Issue by izaakm** [quicksilver/Quicksilver#2364]
I want to have the text lines of a couple of files in my catalog. These text lines used to show up whenever I entered text in the first pane, but now I have to deliberately go "into" that file (select file > "show contents") to see its contents.

I started noticing this problem recently, within the past month (but I think I missed a couple of updates, so I'm not sure when exactly the problem started). 

![screenshot 2017-06-07 18 24 48](https://user-images.githubusercontent.com/1505395/26904274-2e0a88ba-4baf-11e7-81f9-1bfc533f1e63.png)

**Comment by koro-xx** [comment]
I noticed the same issue when I moved to a new mac today. My old mac runs Mavericks so I'm stuck at an earlier version of Quicksilver, but when I installed the latest version in MacOS Sierra and configured my catalog, my "snippet" text file which I use very frequently doesn't show text lines stored in it.

Interestingly, a couple of the text lines are URL's and those DO show up in the catalog (with the "open URL" default action).

**Comment by skurfer** [comment]
I was able to reproduce this the other day, but now I can’t. If one of you has an example text file you don’t mind sharing, could you please post it here and I’ll see if that exhibits the problem? Thanks.

**Comment by koro-xx** [comment]
It happens with an arbitrary text file. For instance I just made a file with 3 lines as follows:

This is a line of text 
Another line of text 
Final line of text

Added it to the catalog as a custom file & folder scanner item, with the option "source options-> include contents -> text lines". 

If you go to the "contents" tab for this item, you can see the three lines of text appear as "scanned objects", so they should be in the catalog. But I can't make them show up in the first pane at all.

**Comment by skurfer** [comment]
Fixing #2306 is probably what caused this. Working on a way to fix both.

**Comment by koro-xx** [comment]
Any news on this? Is there maybe a temporary fix that I could use? For me this bug screws with the functionality much more than #2306, since I use the text scanner a lot for text snippets. Haven't been able to use that for months now...

**Comment by skurfer** [comment]
I attempted a fix in #2369 but it created worse problems. Someone else want to take a crack at it?

**Comment by skurfer** [comment]
I’ve reopened the original fix. It no longer causes the problems I was seeing. (I think because of other changes I made to the way multiple objects are handled.) I’ll test if for a while and possibly have this in the next release.

**Comment by izaakm** [comment]
It's working for me again (v1.5.8). Thank you!
