### ISSUE TITLE
OS Sierra 10.12.4 Quicksilver 1.5.4 Can't set custom triggers

### ISSUE THREAD

**Issue by diegodesouza** [quicksilver/Quicksilver#2365]
I installed Quicksilver and am trying to set `Custom Triggers - (hot keys)` in order to open some apps quicker. I am able to search for apps and add them to the list but I am no able to edit the `Trigger` option, by default it's set to `None`. The input box flickers and nothing changes. I'm not sure what's going on there.

**Comment by skurfer** [comment]
This has been fixed. The fix will appear in the next release.

See #2361
