### ISSUE TITLE
Cant't edit any shortcut

### ISSUE THREAD

**Issue by MortyMacfly** [quicksilver/Quicksilver#2367]
Quicksilver 1.5.4, Sierra 10.12.5, plugins disabled

I'm unable to edit any shortcut. Not in general preferences nor in triggers menu. I want to change or disable activation shortcut, is there any config key that I can edit?

![shortcut_bug](https://user-images.githubusercontent.com/11868819/27001978-314aed76-4ddf-11e7-93be-b4a4ee8f9204.gif)

**Comment by HenningJ** [comment]
This has been fixed. The fix will appear in the next release.

See #2361
