### ISSUE TITLE
Quicksilver not starting after latest update

### ISSUE THREAD

**Issue by Dinky1905** [quicksilver/Quicksilver#2368]
Since updating Quicksilver to 1.5.4 the app is starting, but then immediately aborting. I have sent the resulting report to Quicksilver. Tried to restore an older version but that does not help

**Comment by skurfer** [comment]
Try clearing the caches by running `rm -r ~/Library/Caches/Quicksilver` in Terminal, then see if it will start.

**Comment by Guid0mcman** [comment]
I have this issue too. Deleting caches doesn't fix it, but deleting everything except the app itself and the Application Support folder does - until it doesn't anymore and QS crashes again! Crash report / spin dump can be downloaded here: [http://d.pr/f/wZ84iX](url)

**Comment by Dinky1905** [comment]
I downloaded the app and reinstalled it. Problem gone. Maybe a flaw in the update process ?

**Comment by skurfer** [comment]
I’ve seen some similar issues. It seems to be hit or miss (without changing anything) which is probably why you’re not able to nail down the problem.

**Comment by Proggie** [comment]
I was having similar issues with 1.5.4 (maybe related to updating to latest 10.12.6 beta?). I downloaded the newer 1.5.5 and now it works

**Comment by Guid0mcman** [comment]
Interesting - auto-update hadn't offered me 1.5.5 even though it's set for to check on launch and to notify me about developer updates!

**Comment by skurfer** [comment]
I can’t think of any recent changes that would explain this, except that we’re now building QS with the latest Xcode instead of the previous version. There might be a problem with the Contacts plug-in. (Looking into it.) If anyone runs into this problem again, you could try temporarily disabling it to see if that’s it.

**Comment by FlyingCodeMonkey** [comment]
This may or may not be related, but I also have the latest version, and although it starts up OK and is usable for a while, a little while later I'll notice that the keyboard launch commands aren't working because QS has crashed.  Up until this latest version, I would swear that QS was rock solid.

**Comment by skurfer** [comment]
Did you submit any of the crash reports @FlyingCodeMonkey? If so, I’ll need to know the name of your machine to find them. (Feel free to send that privately if you want.)

**Comment by skurfer** [comment]
I can’t find any reports under that name. Feel free to upload one somewhere (like gist.github.com) and share the link here.
