### ISSUE TITLE
Create Sequential Actions for Triggers that return a new object

### ISSUE THREAD

**Issue by chinchin96** [quicksilver/Quicksilver#2371]
I'd like to be able to do more than one action using a trigger. For example, I have a keyboard shortcut bound to the trigger which says:

1. Get current (finder) selection
2. Get Absolute path. 

But I want to take it a step further. Given a new object (absolute path) is now in the left-most pane I'd like to have another action of copying it to my clipboard as part of the same trigger. The same thing can be said for a trigger that moves files to destination. It would be great if you could do a follow-up action on those files that is already defined as part of the trigger.

See screenshot for more context. 

![sequential actions](https://user-images.githubusercontent.com/2515460/27264708-83a2338a-5452-11e7-9c90-2619030f94fc.png)

**Comment by skurfer** [comment]
I agree. See #2227
