### ISSUE TITLE
Create triggers through QS panes

### ISSUE THREAD

**Issue by chinchin96** [quicksilver/Quicksilver#2373]
Given that actions on objects are created all the time with Quicksilver, it would be novel if while constructing your flow in the main panel, you could have a way to make that a trigger. It would take you to the trigger panel automatically and just ask for your shortcut binding. In some cases, Quicksilver would need to track how some objects were invoked. For example, if I typed "Cmd" + "Esc" (which invokes current selection and puts it into QS), it would insert "Current QS Selection" into the first pane.  

The big issue is that settings are not very keyboard-shortcut friendly and there's a lot of clicking necessary. Why not use the powerful interface of QS's panes to configure and create those settings? 

If you use SulbimeText at all, there's a great model for this with the [Edit Preferences](https://packagecontrol.io/packages/Preferences%20Editor) package.

**Comment by tiennou** [comment]
> build command in UI
> ⌃↩  (encapsulate command)
> "encapsulated command" > create trigger

That should create a trigger with what command you built at step 1, and open the Triggers pref panel for the rest of the info.

**Comment by skurfer** [comment]
As described above, this is already possible (minus the bit about automatically realizing the trigger should be based on “Current Selection”).

**Comment by chinchin96** [comment]
Oh neat. I didn't realize that was there. Thanks!

--------------------------------
Chinedu Ezeamuzie
(404) 514-7910
