### ISSUE TITLE
Quicksilver Window showing up behind windows in Bezel Mode.

### ISSUE THREAD

**Issue by chinchin96** [quicksilver/Quicksilver#2376]
There are many times when I invoke quicksilver (Bezel default) and it is not shown on top of other windows. None of my other windows are set to float over anything else. It seems to just get in a funky state and continues to show up behind windows. Here is a screenshot. 

![image](https://user-images.githubusercontent.com/2515460/27315013-3124c46c-5545-11e7-8df0-141ba1fc7281.png)

I realize this is not an issue with some other QS interfaces (e.g. Menu) but the Bezel is far my favorite way to use it.

**Comment by skurfer** [comment]
Are you still able to reproduce this using Quicksilver 1.5.7?

**Comment by chinchin96** [comment]
Not recently, no. Thanks for checking back in.

Chinedu Ezeamuzie
404-514-7910
________________________________
