### ISSUE TITLE
Third pane not visible when using calendar plugin

### ISSUE THREAD

**Issue by kobrix** [quicksilver/Quicksilver#2377]
When creating a calendar item, tabbing to the third pane activates the pane and shows the list, but the pane itself doesn't open visually apart from a few pixels of the edge. The third pane seems to be working normally with other plugins.

OS X 10.12.5
QS 1.5.5 (4020)
Calendar plugin 1.1.2

**Comment by pjrobertson** [comment]
I can confirm this is happening. Tabbing to the 3rd pane doesn’t open it either (i.e. it’s not a ‘3rd pane optional’ problem)

**Comment by pjrobertson** [comment]
Fixed in the latest build
