### ISSUE TITLE
Eating lots of CPU after sitting "idle"  for while

### ISSUE THREAD

**Issue by ktgeek** [quicksilver/Quicksilver#2380]
I've attached a sample from Activity Monitor, but the current release (1.5.5 (4020)) seems to start chewing lots of CPU after sitting idle for a random amount of time. Killing it and restarting it sometimes helps, but it seems to start much slower than it previous versions.

[Sample of Quicksilver.txt](https://github.com/quicksilver/Quicksilver/files/1143619/Sample.of.Quicksilver.txt)

**Comment by skurfer** [comment]
Ah, yeah. That’s what I was talking about in #2356. Thanks for the report.

I’ve created a test build with a temporary hack. See if this is any better.

https://cl.ly/0o3w1g0f0R3V

The version will be the same as the current release, but there is a small internal difference.

**Comment by ktgeek** [comment]
I'll give it a try, thanks!

**Comment by ktgeek** [comment]
Here's a new sample.  It looks like it took less CPU, but wasn't coming up when I did the activation shortcut.

[Sample of Quicksilver.txt](https://github.com/quicksilver/Quicksilver/files/1145919/Sample.of.Quicksilver.txt)
