### ISSUE TITLE
Finder integration issue

### ISSUE THREAD

**Issue by codefish** [quicksilver/Quicksilver#2386]
Quicksilver 1.5.5 / MacOS 10.13.6

QS not responding to requests involving Finder: "get info" "reveal" and so on.

This is new after updating MacOS.

Any thoughts? 

Thanks.

**Comment by skurfer** [comment]
> MacOS 10.13.6

I don’t think that exists yet. Did you mean 10.12.6 or 10.13.0?

In any case, go to Preferences → General → Handlers and make sure the File System Browser is set to “Finder Selection”.

**Comment by codefish** [comment]
🥇 Ah, excellent, thank you!! That did solve the issue. I'm grateful for your help. 👍 

(10.12.6. Not writing from the future.)
