### ISSUE TITLE
Settings calls backspace key delete key

### ISSUE THREAD

**Issue by herrieii** [quicksilver/Quicksilver#2388]
The setting _Pressing the Delete key clears the whole search string_ found in _Preferences_ > _General_ > _Extras_ should say **Backspace** instead of **Delete**.

The setting correctly sets the behaviour of the backspace key.

**Comment by skurfer** [comment]
The terminology doesn’t match what Windows uses, but is correct for a Mac.

  Key                               | Windows   | Mac
  --------------------------------- | --------- | --------------
  The one in the upper right corner | Backspace | Delete
  The one on the numeric keypad     | Delete    | Forward Delete

Show me an Apple keyboard with a backspace key, and I’ll reconsider. 😃

**Comment by herrieii** [comment]
This is bizarre, but out of Quicksilver's scope I understand. Tnx for clarifying.
