### ISSUE TITLE
Keychain plugin supposedly works on Sierra?

### ISSUE THREAD

**Issue by elmart** [quicksilver/Quicksilver#2389]
Hi,

Keychain plugin gets installed, and my login and System keychains are loaded in the catalog.
But when I try to navigate to a login item (a particular account), it does not locate it.
I can search for the account normally with the KeychainAccess app.
So, am I doing something wrong, or is this plugin abandoned? Last update was years ago...

Thx for your hard work. Quicksilver has always been my favourite OSX tool.

**Comment by skurfer** [comment]
I *think* the plug-in only adds the keychains (like “login” and “System”) to the catalog, but not every individual item. If you select a keychain and hit `→` or `/`, you should see the login items.

You can either search for the keychains by name, or select the “Keychain Access” app and right-arrow into it.

**Comment by elmart** [comment]
I can see login and System keychains. It's when I press `/` to navigate into my login keychain, that many items are showed, but not all of them which really exist. I've refreshed catalog many times but it seems to not find some items.

**Comment by bryanpi** [comment]
I was having this same problem, but digging into it more today... I noticed that almost all of my new "Web Form Passwords" are being saved to the iCloud keychain, not the login keychain.  And I don't see the iCloud keychain as an option in the keychains plugin.
I realize this is three years old, not sure if this got identified or understood elsewhere... or if there's any investigation to if/how to get the plugin to scan the iCloud keychain?

**Comment by skurfer** [comment]
The `SecKeychainCopySearchList()` function must not include iCloud.

https://github.com/quicksilver/Keychain-qsplugin/blob/master/QSKeychainSource.m#L208

**Comment by pjrobertson** [comment]
Rob's message is correct. iCloud keychains do not behave in the same way as 'standard' keychains on the disk, and therefore cannot be accessed. Unfortunately this is not something that we can change.

For more information, see: https://developer.apple.com/forums/thread/676891
