### ISSUE TITLE
Search Priority

### ISSUE THREAD

**Issue by george-norris-salesforce** [quicksilver/Quicksilver#2391]
Is there a way to make Quicksilver prioritize certain folders?
For instance when searching `System Preferences` Quicksilver returns `system.framework` first, which is not useful.

**Comment by skurfer** [comment]
No, but any default priorities would be so quickly overridden by QS learning your habits that it wouldn’t make much difference.

Just type something that makes sense _to you_ for finding System Preferences (like “pref” or “sp”). At first, you will probably need to scroll through the results to find it, then hit Return to open it. Every time you do that, System Preferences will appear higher up in the results. In fact, it will probably become the default match after just once or twice.

If you want to speed up the learning process, you can just find System Preferences using any method you want, then run the “Assign Abbreviation…” action on it and enter the shortcut you expect to use most often.

Also note that things you open often are ranked higher, even if you don’t use the exact same abbreviation every time.

Let me know if you have any questions about that.
