### ISSUE TITLE
In Sierra my Quicksilver entry window comes up behind other windows

### ISSUE THREAD

**Issue by joshgold22** [quicksilver/Quicksilver#2392]
It's very challenging to use Quicksilver since upgrading my mac to Sierra (10.12.6).  Quicksilver's window consistently comes up behind other windows, though it does have keyboard focus and can make actions happen if I trust that it's reading my mind propoerly.

QS 1.5.5 (4020)

**Comment by joshgold22** [comment]
I searched for under, underneath and hidden, but didn't see this similar bug with "behind": #2376 
I use the Primer interface, not bezel, so I suspect the problem is independent of the interface.

**Comment by joshgold22** [comment]
I tried quitting and restarting Quicksilver, and that has it behaving properly again, at least for now.

**Comment by skurfer** [comment]
If you can figure out something that happens before things go wrong again, let us know.

**Comment by joshgold22** [comment]
Ok, I’ll keep my eye out.  So far the restart has held up (a day later it’s still popping up on top.)

Thanks!
  -Josh
