### ISSUE TITLE
silent crashes on High Sierra

### ISSUE THREAD

**Issue by fivetonsflax** [quicksilver/Quicksilver#2394]
Here's all I have in system.log:

Sep 17 00:02:35 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 00:12:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 00:22:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 00:32:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 00:42:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 00:52:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 01:02:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 01:12:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 01:22:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 01:32:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 01:42:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 01:52:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 02:02:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 02:12:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 02:22:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 02:32:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 02:42:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 02:52:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 03:02:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 03:12:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 03:22:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 03:32:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 03:42:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 03:52:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 04:02:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 04:12:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 04:22:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 04:32:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 04:42:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 04:52:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 05:02:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 05:12:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 05:22:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 05:32:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 05:42:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 05:52:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 06:02:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 06:12:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 06:22:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 06:32:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 06:42:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 06:52:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 07:02:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 07:12:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 07:22:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 07:32:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 07:42:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 07:52:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 08:02:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 08:12:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 08:22:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 08:32:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 08:42:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 08:52:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 09:02:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 09:12:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 09:22:34 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 09:32:35 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 09:42:35 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 09:51:09 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 09:52:35 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 10:02:35 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 10:12:35 pannonica Quicksilver[5998]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 10:46:52 pannonica com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100008.Aqua): failed lookup: name = com.blacktree.Quicksilver.ServiceProvider, handle = 0, instance = (n/a), flags = 0x1, requestor = Quicksilver.927, error = 3
Sep 17 10:46:55 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 10:47:06 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 10:47:14 pannonica com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100008.Aqua): failed lookup: name = com.apple.AddressBook.AddressBookApplicationFrameworkIPC, handle = 0, instance = (n/a), flags = 0x1, requestor = Quicksilver.927, error = 3
Sep 17 10:56:54 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 11:06:53 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 11:16:58 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 11:26:53 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 11:36:55 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 11:46:54 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 11:56:57 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 12:06:53 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 12:16:51 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 12:26:51 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 12:36:51 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 12:46:56 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 12:56:54 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 13:06:52 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 13:16:51 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 13:26:51 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 13:36:51 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 13:46:51 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 13:56:59 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 14:06:51 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 14:16:51 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 14:26:51 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 14:37:04 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 14:46:56 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 14:56:51 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 15:06:51 pannonica Quicksilver[927]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 15:24:02 pannonica com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100008.Aqua): failed lookup: name = com.blacktree.Quicksilver.ServiceProvider, handle = 0, instance = (n/a), flags = 0x1, requestor = Quicksilver.2116, error = 3
Sep 17 15:24:02 pannonica Quicksilver[2116]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 15:24:17 pannonica Quicksilver[2116]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
Sep 17 15:24:25 pannonica com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100008.Aqua): failed lookup: name = com.apple.AddressBook.AddressBookApplicationFrameworkIPC, handle = 0, instance = (n/a), flags = 0x1, requestor = Quicksilver.2116, error = 3

**Comment by skurfer** [comment]
Thanks. I’ll see if I can reproduce it once I’ve upgraded.

I’m trying to think of what could be sending AppleEvents. Try disabling “iTunes Equalizer Presets” or “AirPlay Devices” under Preferences → Catalog → PlugIns → iTunes.

**Comment by fivetonsflax** [comment]
Thank you. iTunes Equalizer Presets was already disabled, but I've disabled AirPlay Devices now.

**Comment by fivetonsflax** [comment]
Still repro'ing fairly frequently. Have you had any luck reproducing it yourself? Is there some configuration I could dump to help you with that?

**Comment by skurfer** [comment]
I see the noise in the log, but no crashes. (I am using a version that was built with the new Xcode, though.) Do you have any reports in `~/Library/Logs/DiagnosticReports`? If so, pasting the contents of one as a [Gist](https://gist.github.com/) might help.

**Comment by fivetonsflax** [comment]
https://gist.github.com/fivetonsflax/d4b4ed7de3d467e8b2a5a2f85d20554f

Thanks.

**Comment by skurfer** [comment]
Thanks for the report. Now I can see that you’re running into #2379, which isn’t specifically related to the new OS.

This happens when QS checks for updates in the background and tries to alert you that it found one. Updgrading to the latest version will fix it (until we release another update). 😞 

I think you can do it manually in Quicksilver’s preferences. If not, just get it from qsapp.com.

**Comment by fivetonsflax** [comment]
Splendid, thank you!
