### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by grdh20** [quicksilver/Quicksilver#2397]
Can you make the ability to browse to a folder, drag and drop a folder or something other than the "search" way to add a keyboard shortcut? I have external drives that I want to place a shortcut for a specific sub folder and it is next to impossible using the current search for system. Only a few folders ever show up in the search results and it is quite tedious. Just provide some other direct way to add a hotkey/shortcut to the list please?  thanks!

**Comment by skurfer** [comment]
Are you talking about adding a Keyboard Trigger that opens a folder? If so, two things will help you:

1. When creating a trigger, you _can_ drop a file or folder from Finder on the first pane to select that item.
2. When a folder is selected, hitting `→` or `/` will show its contents. Holding `/` for a second or so will select your hard drive. So, even if something isn’t in your catalog, you can still get to it no matter where it is.

**Comment by grdh20** [comment]
Thanks. Tried that but none of that is working anymore in High Sierra.  Can’t imagine why, but HS has quite a few weird bugs so it shouldn’t surprise me.. If you end up looking at HS let us know what you find along those lines. Maybe it’s just me..

**Comment by skurfer** [comment]
> Tried that but none of that is working anymore in High Sierra.

None of what? I was able to both drag, and use `/` to navigate into the folder (on High Sierra). Here’s a short video of it.

https://cl.ly/1U1d0O1v0s2x

Are you running the latest version (1.5.6)?

**Comment by grdh20** [comment]
Exactly what you did, hmm…maybe it will work after a restart. I’ll try again tonight and see.

**Comment by grdh20** [comment]
Seems to work now as you described. Tested on 10.13.1 Thanks for your help.
