### ISSUE TITLE
Quicksilver needs a new “relaunch” shortcut

### ISSUE THREAD

**Issue by skurfer** [quicksilver/Quicksilver#2399]
As of 10.13, macOS uses ⌃⌘Q for “Lock Screen”, and it doesn’t appear to be configurable.

So Quicksilver, TextMate, and all the other apps using this unofficial standard for relaunching will need to pick something else.

**Comment by skurfer** [comment]
1Password has settled on ⌃⌥⌘Q

We’re not using that, so I say it’s a suitable choice. My plan is to

  1. Remove support for ⌃⌘Q
  2. Add a “Relaunch” trigger to the preferences with ⌃⌥⌘Q as its default

That should allow users to customize it if they want to use something else.

**Comment by tiennou** [comment]
Just FMI, does that shiny new system-wide shortcut appear in the Keyboard preferences ? IOW, can it be overridden ?

**Comment by skurfer** [comment]
No. That was the first thing I checked.

**Comment by pjrobertson** [comment]
> We’re not using that, so I say it’s a suitable choice. My plan is to
> 
> Remove support for ⌃⌘Q
> Add a “Relaunch” trigger to the preferences with ⌃⌥⌘Q as its default
> That should allow users to customize it if they want to use something else.
> 

Sounds good to me, we don’t want to hard-code it in ourselves either. Problem is ⌃⌥⌘Q is a little tricky to finger. I’d prefer ⌘⌃⇧Q, but I’m easy if that’s already taken/others think  ⌃⌥⌘Q  is better.
