### ISSUE TITLE
High CPU Usage While Idle High Sierra

### ISSUE THREAD

**Issue by brichards72** [quicksilver/Quicksilver#2400]
Running 1.5.6, eating a ton of CPU just sitting there idle on High Sierra.  Hopefully the attached file will uncover something.
[Sample of Quicksilver.txt](https://github.com/quicksilver/Quicksilver/files/1366430/Sample.of.Quicksilver.txt)

**Comment by skurfer** [comment]
That sample was helpful. Thanks.

I see a couple of things going on (mostly already known issues).

1. The Safari plug-in tells Quicksilver to watch Bookmarks and History and immediately rescan on any change. That might be a bit aggressive, especially for history. The Google Chrome plug-in does the same thing.
2. Something changed in macOS 10.12 that caused looking up types for some things to be much, much slower. This seems to impact URLs especially. See #2356

**Comment by brichards72** [comment]
Thanks for taking a look.  Disabling Safari and Chrome plug-ins resolved it for me.
