### ISSUE TITLE
How do I get rid of file path in the description?

### ISSUE THREAD

**Issue by SeabassWells** [quicksilver/Quicksilver#2401]
Hi, I switched computers and downloaded a new version of quicksilver.

I use the Bezel appearance and when I hit the down arrow to see a list of files, it shows me the path for each of them. I've looked through the settings and I'm not seeing a place to toggle them off.

How do I get rid of the file path from showing up in the list of files? Thanks!

**Comment by skurfer** [comment]
You can’t turn off the details explicitly, but they will be hidden automatically if the results aren’t tall enough. That’s probably what you had before.

Try different settings for Preferences → General → Command → Results Row Height
