### ISSUE TITLE
Issue typing some characters in alternative layouts

### ISSUE THREAD

**Issue by danielcompton** [quicksilver/Quicksilver#2405]
I'm using Norman layout which has the 'h' key in the place of the ';'. In the Australian layout ';' is ignored. When I switch to Norman, the 'h' key is ignored. If I quit and relaunch QS in Norman mode then I can use 'h'. Switching back to Australian, I can now type ';' in the search, but can't type 'p' which is where the semicolon is in Norman.

In summary it looks like QS is handling keybindings by position, not label.

Looks similar to #1482?

**Comment by skurfer** [comment]
Almost certainly fixed by #1147, but @tiennou hasn’t had time to put the finishing touches on it.
