### ISSUE TITLE
Power went out & Quicksilver needed to be reinstalled

### ISSUE THREAD

**Issue by stradify** [quicksilver/Quicksilver#2416]
Just a note of an unusual occurance last night when the power went out for a few hours.
My iMac shut off without going through a normal shutdown and when the power came back on, and I rebooted the computer, Quicksilver was unresponsive and wouldn't launch. No message. Nada.
I reinstalled the app and now everything works fine again. Thought you might find it worth noting.

**Comment by skurfer** [comment]
There could be several explanations for this. If it happens again, the first thing I’d try is removing `~/Library/Caches/Quicksilver`. Thanks for the report.
