### ISSUE TITLE
Delete key not displayed in trigger key shortcuts

### ISSUE THREAD

**Issue by pbx** [quicksilver/Quicksilver#2418]
Quicksilver 1.5.6 (4021) under macOS 10.13.2 (17C88).

Steps to reproduce:
1. Go to Triggers > Custom Triggers
2. Create a new trigger
3. Set the Shortcut for the trigger to _Cmd-option-delete_
4. Observe that the displayed shortcut is simply "⌥⌘"

The shortcut _does_ work as set, it simply isn't displayed correctly.

Other "invisible" keys (e.g. space, return) have visible representations.

**Comment by skurfer** [comment]
Probably related to #1918 and possibly fixed by the immortal #1147
