### ISSUE TITLE
Some `.txt` files not recognized as text files

### ISSUE THREAD

**Issue by louabill** [quicksilver/Quicksilver#2419]
QS is showing some `.txt` files as an unknown type. [Called 'bad' files below.]

Some `.txt` files are recognized as text files. [Called 'good' files below.]

A screenshot of how this appears is attached below.

I cannot figure out the pattern for when a file is good or bad. I have many `.txt` files in the same directory. All the files have the same permissions (644). All the `.txt` files are recognized by Quick Look as text files. Some are good files, some are bad. Some have extended attributes and some do not, but this does not match up with being good or bad. 

When I tried to use a trigger which appended to this file in the very recent past, I sometimes got complete nothingness (no error, no appended text), twice got an error that text could not be added to a (null) file, and once got an error that text could not be added to a text file. [These are approximations to the error messages, as the actual error messages come up only sporadically.] 

After a nothingness event, the Console had the message
`default	13:59:39.204629 -0600	Quicksilver	unexpected object for file path: (null), object: QSObject <0x6040004d3400>, /Users/<somePathHere>/TextScraps/Ideas.txt`

I'm using macOS 10.13.2 and just upgraded to QS 1.5.7 when looking for help on this topic. The problem existed in QS 1.5.6. I do not know if it existed in earlier versions, but I know it did not exist back in 2013, because of how I used to use triggers. I have FileVault turned on and my filesystem in now APFS. 

Any tips would be much appreciated.

![qs_txt_oops](https://user-images.githubusercontent.com/546277/34692636-6405a8f2-f486-11e7-9bd1-f08e41e138f6.png)

**Comment by skurfer** [comment]
It seems to be acting like those files aren’t there at all. I assume they still are.

Could there be any strange characters lurking in the path that might be confusing it?

When you say Quick Look works, I assume that’s from Finder and not from Quicksilver?

Maybe when you see a file go bad, try selecting the parent folder and right-arrowing into it to see if it rediscovers the file. That’s not a solution, but might offer a clue about the problem.

**Comment by tiennou** [comment]
A few more things to test :

- What happen to those files when triggering a manual rescan from the Catalog preferences ?
- Are some of those not UTF-8 text files ? (see `man file`)

I'd be interested to see what's the underlying object state. Since I don't think release builds can get The Debug Menu (which has Log Object Dictionary), you'll have to jump through some hoops :
- Select `good` file.
- Choose `does not matter` action.
- Encapsulate (that's ⌃↩)
- "Save command to file" (by default, in your user directory). This outputs the serialized representation of "the minimum required" to restore the object, as a plist file (use a text editor).
- Repeat from step 1 with `bad` file.
- Compare plists (yay).

HTH ! Hopefully something comes out of all this 😉.

**Comment by louabill** [comment]
The files are indeed still there.

All the characters are ASCII, so dull, but not strange.

Quick Look from the Finder, because I wanted to see if the OS thought they were text files.

Right arrowing is also OK.

Upon further fuddling, I realized the following:

QS does not recognize the file if and only if it has an active (checked) trigger associated with it. So... _all_ files which have triggers show up as ? and _all_ files with no triggers show up as txt.

I tried deleting some triggers point to some of the unrecognized text files and restarting QS, and magically QS recognized the files as text files.

Now... the other thing could be that the triggers are out-of-date, and hence confusing, because they say `Append line to`... instead of `Append to`.

**Comment by louabill** [comment]
@mylastpost
The -if and only if- is not correct. _If_ there was a trigger attached the file _could_ be bad. _If_ there is no trigger attached, _then_ the file is good. Some `Append to` triggers get confused, and when they are confused, the QS as a whole is confused (or perhaps QS is confused first, I cannot tell).

Perhaps the problem is in the Text Manipulation plugin (v1.2.0 from Mar 18, 2015).

@tiennou 

Manual rescan does nothing.... those which have triggers (which have been triggered) are unknown.
All the files are UTF-8.

The plists are identical except for the names of the files. FWIW, I did need to make the command `Copy to Clipboard` to be sure the plists were comparable, because some of the other commands put double-quotes around the file names and some do not.

**Comment by skurfer** [comment]
> *If* there was a trigger attached the file *could* be bad.

This is helpful. I’ll bet it has something to do with the way the triggers are stored. If you haven’t already recreated all of the bad ones, could you compare a trigger involving a broken file with one that’s not in `~/Library/Application Support/Quicksilver/Triggers.plist`?

Are the broken files used in triggers also in Quicksilver’s catalog?

**Comment by louabill** [comment]
@skurfer

I finally had some time to play around with this. After playing around, I got two triggers both of which are for appending to a text to the same file.

The one that works is new.

The one the does not work is an older trigger.

The plists are different, and I've put them below, in case it sheds any light.

Let me know if there is some other experiment I should be running.


---- begin plist which works ----
````
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ID</key>
	<string>0049F0F4-D704-434D-A4D0-72F1B3677834</string>
	<key>command</key>
	<dict>
		<key>actionID</key>
		<string>QSTextAppendReverseAction</string>
		<key>directID</key>
		<string>/Users/brising/Universal/Everywhere/TextScraps/aquaemacs-bugs.txt</string>
		<key>indirectArchive</key>
		<dict>
			<key>class</key>
			<string>QSObject</string>
			<key>data</key>
			<dict>
				<key>QSTextProxyType</key>
				<string></string>
			</dict>
			<key>properties</key>
			<dict>
				<key>QSObjectName</key>
				<string></string>
				<key>QSObjectType</key>
				<string>QSTextProxyType</string>
			</dict>
		</dict>
	</dict>
	<key>enabled</key>
	<true/>
	<key>keyCode</key>
	<integer>27</integer>
	<key>modifiers</key>
	<integer>1835305</integer>
	<key>onPress</key>
	<true/>
	<key>type</key>
	<string>QSHotKeyTrigger</string>
</dict>
</plist>
````
---- end plist which works ----

---- begin plist which fails ----
````
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ID</key>
	<string>A9B21243-69AC-4C8C-845F-C167801248AB</string>
	<key>characters</key>
	<string>b</string>
	<key>command</key>
	<dict>
		<key>actionID</key>
		<string>QSTextAppendReverseAction</string>
		<key>directArchive</key>
		<dict>
			<key>data</key>
			<dict>
				<key>NSFilenamesPboardType</key>
				<string>/Users/brising/Universal/Everywhere/TextScraps/aquaemacs-bugs.txt</string>
			</dict>
			<key>properties</key>
			<dict>
				<key>QSObjectDetails</key>
				<string>~/Universal/Everywhere/TextScraps/aquaemacs-bugs.txt</string>
				<key>QSObjectName</key>
				<string>aquaemacs-bugs.txt</string>
				<key>QSObjectObjectID</key>
				<string>/Users/brising/Universal/Everywhere/TextScraps/aquaemacs-bugs.txt</string>
				<key>QSObjectType</key>
				<string>NSFilenamesPboardType</string>
			</dict>
		</dict>
		<key>directID</key>
		<string>/Users/brising/Universal/Everywhere/TextScraps/aquaemacs-bugs.txt</string>
		<key>indirectArchive</key>
		<dict>
			<key>class</key>
			<string>QSObject</string>
			<key>data</key>
			<dict>
				<key>QSTextProxyType</key>
				<string></string>
			</dict>
			<key>properties</key>
			<dict>
				<key>QSObjectName</key>
				<string></string>
				<key>QSObjectType</key>
				<string>QSTextProxyType</string>
			</dict>
		</dict>
	</dict>
	<key>enabled</key>
	<true/>
	<key>keyCode</key>
	<integer>11</integer>
	<key>modifiers</key>
	<integer>1835305</integer>
	<key>type</key>
	<string>QSHotKeyTrigger</string>
</dict>
</plist>
````
---- end plist which fails ----

**Comment by pjrobertson** [comment]
So it seems that with your *bad* plist, there's `directArchive` and a
`directID` for the object. Only one of these should really exist.
I don't know whether this would fix the problem, but my solution would be
to alter `setDirectObject:(QSObject *)newObject` in QSCommand.m so that if
you're saving the object `rep` to `directID` you remove any existing object
for `directArchive`, and vice-versa if setting a `directArchive`. I'll make
a pull request, see what you think.

**Comment by pjrobertson** [comment]
So it seems that with your *bad* plist, there's `directArchive` and a `directID` for the object. Only one of these should really exist.

I don't know whether this would fix the problem, but my solution would be to alter `setDirectObject:(QSObject *)newObject` in QSCommand.m so that if you're saving the object `rep` to `directID` you remove any existing object for `directArchive`, and vice-versa if setting a `directArchive`.

I'll make a pull request, see what you think.
