### ISSUE TITLE
I have found a minor typo

### ISSUE THREAD

**Issue by KatkayApps** [quicksilver/Quicksilver#2425]
When you install Quicksilver for the first time, you see this option screen.

The word "shortcut" is typed "shortcu" there...

**Comment by skurfer** [comment]
I can’t find that anywhere in the app. Could the window be cutting off the text? Can you provide more context, like the sentence the word appears in?

**Comment by Ding-Fan** [comment]
@skurfer 
![image](https://user-images.githubusercontent.com/26438549/36977048-c6006406-20ba-11e8-9c15-5923fb90c814.png)

**Comment by skurfer** [comment]
OK, thanks. The ’t’ is there, but the box isn’t big enough to show it.
