### ISSUE TITLE
Initial Install Plugin Output is incorrect, bad substitution

### ISSUE THREAD

**Issue by ooglek** [quicksilver/Quicksilver#2427]
Initial install of QS 1.5.7 (4022). Installing Plugins and the output on the progress bar is not what one might expect. Looks like a bad substitution. 

Text is "Installing %|d Plugins" (or maybe that's an l (lowercase L))

<img width="529" alt="screen shot 2018-03-02 at 12 13 12 pm" src="https://user-images.githubusercontent.com/100755/36912002-5caa2ae0-1e13-11e8-8168-7bdd40e105e1.png">

**Comment by skurfer** [comment]
This is fixed. It just hasn’t made it into a release yet. Thanks!

See #2409
