### ISSUE TITLE
Assigned abbreviations being ignored & Quit action has disappeared.

### ISSUE THREAD

**Issue by g1oria** [quicksilver/Quicksilver#2428]
I enter an assigned abbreviation (for example: gs for google search) & it no longer brings up the item it's supposed to. All of my web searches are gone, even though the plugin is installed, plus the Quit action has disappeared entirely. I can no longer quit an application via Quicksilver. Argh!

**Comment by skurfer** [comment]
It could be corruption in the catalog. The first thing I’d try is

1. Shut down Quicksilver
2. Delete `~/Library/Caches/Quicksilver`
3. Start Quicksilver again

Let me know whether or not that works.

**Comment by g1oria** [comment]
That did help w/the abbreviations issue, but, unfortunately, it didn't
bring back the quit action.

**Comment by g1oria** [comment]
Ok, I tried reinstalling & that fixed it. Thanks for your help! 🙂

**Comment by g1oria** [comment]
Ok, I'm realizing what the issue is now. The quit action only shows up i
app in question is actually running. Which is fine if all I'm wanting to do
is quit an app, but not so good when I'm trying to create a trigger. Right
now if I wan to create a trigger to close an app, I have to have that app
open to do it. Urgh. Suggestions?

**Comment by skurfer** [comment]
It’s pretty common to need an action that isn’t available when creating a trigger. What people normally do is get the action to appear somehow in the main interface, tab to the action pane, and copy the action with ⌘C or by right-clicking. Then, when you create the trigger, you can paste it into the action pane there.

Note that if the action has an alternate, holding ⌘ will show it. So you won’t be able to copy with ⌘C in that case, but you can still right-click the action.

**Comment by g1oria** [comment]
Ah, ok. Thank you! 🙂
