### ISSUE TITLE
Quicksilver crashing at startup

### ISSUE THREAD

**Issue by Dinky1905** [quicksilver/Quicksilver#2433]
Returned after a few weeks from holidays and restarted the computer. Quicksilver now immediately aborts on startup. Have sent error report

**Comment by skurfer** [comment]
Some recent versions would crash when checking for updates in the background (if an update was available). There were a couple of new releases last week. You should make sure you’re running the current version (1.5.9).

Checking for updates in the foreground (by manually doing it in the preferences) should work, or you can download a copy from https://qsapp.com/

**Comment by Dinky1905** [comment]
Thanks. I did just that, but 1.5.9. crashes as well



Hans Douma

**Comment by Dinky1905** [comment]
I withdraw that. Works fine now


Hans Douma




> Begin forwarded message:
> 
> From: Hans Douma <hadouma@gmail.com>
> Subject: Re: [quicksilver/Quicksilver] Quicksilver crashing at startup (#2433)
> Date: 16 March 2018 at 17:32:10 GMT+1
> To: quicksilver/Quicksilver <reply@reply.github.com>
> 
> Thanks. I did just that, but 1.5.9. crashes as well
> 
> 
> 
> Hans Douma
> 
> 
> 
>

**Comment by skurfer** [comment]
OK, glad to hear it.
