### ISSUE TITLE
Scroll Clipboard History to the top on Paste

### ISSUE THREAD

**Issue by joesolly** [quicksilver/Quicksilver#2434]
It would be nice to have an option to always display the first row of the Clipboard history when the clipboard opens instead of the last selected row index.

**Comment by skurfer** [comment]
The first row _is_ the last pasted item, so I don’t quite understand what you’re after.

**Comment by joesolly** [comment]
Sorry about that @skurfer . I got the functionality a little mixed up. I tend to have a 100 items in my clipboard history and after I paste item 57, the next time I open the clipboard history, I am still on row 57 (which no longer contains my last pasted item), when I'd really like to be back to row 1 (or index 0). I will update the initial comment to try to be a bit more clear.

**Comment by skurfer** [comment]
Oh, I see. So have it scroll to the top when you paste? Makes sense. I’m usually also a little annoyed when I go back to the history and it’s scrolled to the middle somewhere.

**Comment by pjrobertson** [comment]
FWIW I’ve been getting annoyed about this lately. It feels like a regression, but haven’t got round to debugging it. 

It make be a problem with the clipboard setting ‘hide on paste’. Basically when the clipboard displays whatever scenario we should probably scroll to the 1st row.

**Comment by skurfer** [comment]
> Basically when the clipboard displays whatever scenario we should probably scroll to the 1st row.

Agreed. I’m just wondering if we can do that without changing the base docking window behavior. Or maybe we don’t care if it’s a universal change?
