### ISSUE TITLE
Clipboard search

### ISSUE THREAD

**Issue by joesolly** [quicksilver/Quicksilver#2435]
Add the ability to type characters and have it filter out non-matching clipboard items.

**Comment by skurfer** [comment]
It’s not a feature of the clipboard history window, but people do this all the time in Quicksilver’s main interface by running Clipboard History ⇥ Show Contents. That gives you a searchable history. You could create a trigger for that, of course.

Also note that if the Paste action happens to be the default when you type ‘P’ in the second pane, then you can quickly paste an item without jumping to the second pane by hitting ⇧⌘P.

**Comment by joesolly** [comment]
Thanks for the quick response @skurfer . I'm having trouble reproducing the steps you gave in your first paragraph. I tried Clipboard History -> Show Contents and Quicksilver crashes. When I do Clipboard History -> Search Contents, Quicksilver just brings up the main interface again completely blank.

Assuming I eventually get this to work, I agree that this is a viable alternative to searching directly in the clipboard, although a bit more inconvenient. I tend to only need to search after I bring up the clipboard history and don't see the clip I'm looking for immediately.

**Comment by skurfer** [comment]
> I tried Clipboard History -> Show Contents and Quicksilver crashes.

What version of Quicksilver?
Which interface?

> When I do Clipboard History -> Search Contents, Quicksilver just brings up the main interface again completely blank.

That should also work. That is, if you were to start typing there, it should search the Clipboard History, while hitting ↓ should show the full list. The only difference between Show Contents and Search Contents is whether or not the results are initially shown or hidden.

> Assuming I eventually get this to work, I agree that this is a viable alternative to searching directly in the clipboard, although a bit more inconvenient. I tend to only need to search after I bring up the clipboard history and don't see the clip I'm looking for immediately.

I can’t speak for everyone that’s ever worked on the project, but my guess is that the current approach is close enough for most people that they can’t justify the additional work.
