### ISSUE TITLE
Interface Changed: Interface could not be loaded. Switching to Bezel

### ISSUE THREAD

**Issue by miguelmorin** [quicksilver/Quicksilver#2436]
Hello,

I am new to Quicksilver and installed it following  followed [these steps](https://qsapp.com/wiki/Building_Quicksilver). Quicksilver launches and I can see Preferences and plugins. But when I hit Control-Space, it shows a notification on the top-right of the screen with title "Interface Changed" and description "Interface could not be loaded. Switching to Bezel". Quicksilver is still running but I cannot access the interface.

The same thing happens when running Quicksilver from XCode or from the Release binary. I ran a ‘Product -> Clean’ (or ⇧⌘K), deleted the `/tmp/QS` directory, emptied the Trash, removed the following files and folders:
- ~/Library/Application Support/Quicksilver/Plugins
- ~/Library/Preferences/com.blacktree.Quicksilver.plist
- ~/Library/Caches/com.blacktree.Quicksilver/
- ~/Library/Caches/Quicksilver/

and restarted the computer, but it was still showing the same notification. I had no plugins installed. I added the "Bezel Classic Interface" plugin, restarted Quicksilver, and got the same problem. I read a thread from 2012 blaming it on an old version of the Automator plugin, which I didn't have so I installed it, and I still go the same problem. I added all plugins that finished with "interface" and got the same problem.

The download of Quicksilver directly from https://qsapp.com/download.php works with no problems.

Quicksilver version: .5.9 (4024)
Mac OS X Version: MacOS High Sierra 10.13.3
List of any Quicksilver plugins: the problem happens with no plugins, with just "Bezel Classic Interface", with the previous + Automator 1.2.1, with the previous + all plugins finishing with the word "interface".

**Comment by skurfer** [comment]
Make sure you’ve selected “Quicksilver Distribution” as the scheme and not just “Quicksilver” (step 5). With the latter scheme, you get the app, but not the built-in plug-ins, which is where most of the functionality comes from. That sounds like what’s happening.

**Comment by skurfer** [comment]
Also, if you’re looking for something in particular, [the map](/quicksilver/Quicksilver/blob/master/The_Map.md) will hopefully help.

If what you want isn’t there, or if you have any other questions, please let me know.

**Comment by miguelmorin** [comment]
Yes, that did it. Thank you @skurfer ! For information, XCode was showing "Quicksilver > My Mac" at the right of the "play" button, and I clicked on "Quicksilver" to change that to "Quicksilver Distribution > My Mac".
