### ISSUE TITLE
Action to show documentation

### ISSUE THREAD

**Issue by hmelman** [quicksilver/Quicksilver#2438]
The new plugin documentation is nice, but I find it frustrating I have to go to QS's preferences and click a small button to see it. Since I (can) have the plugins in my catalog, I think there should be an action to display the plugin doc directly from the QS interface. It could pop up a new window just like it currently works.

**Comment by skurfer** [comment]
> Since I (can) have the plugins in my catalog

By just scanning `~/Library/Application Support/Quicksilver/PlugIns` or do you know something I don’t?

**Comment by hmelman** [comment]
Yes I scan that, but also the Quicksilver Catalogs Entries source listed under Quicksilver.

**Comment by skurfer** [comment]
Oh, OK. Well the bundles themselves would be treated like any other file unless we add special behavior for that path.

For the catalog entries, there isn’t necessarily a one-to-one with plug-ins. To use Mail as an example again, there are no catalog entries for the mail clients or the E-mail Support plug-in.

I’d prefer to just create another source under the Quicksilver section of the catalog called “Plugins” that adds them as a new type of thing. It would probably make sense to also have actions for install/remove, enable/disable, etc.

**Comment by hmelman** [comment]
Ah I guess I misunderstood my own post. The Quicksilver Catalogs Entries source listed under Quicksilver has an item called "Plugins (Catalog)" and if I right-arrow into that it seems to be most if not all of my catalog (I guess every item from a source from a plugin). That's not what I expected. 

I agree, there are not catalog entries for plugins unless you scan the PluginIns folder. I agree with your proposal and including the new actions.
