### ISSUE TITLE
Plugin Documentation Linking

### ISSUE THREAD

**Issue by hmelman** [quicksilver/Quicksilver#2439]
I looked at the new plugin documentation for the Apple Mail plugin and it referred to the E-Mail Support plugin. It would have been nice if it were a link I could click on to bring up the E-Mail Support plugin documentation. This is kind of a wiki'ish feature which may be bloat, but I think a special case just between plugin docs would make the experience nicer.

**Comment by skurfer** [comment]
We might be able to extend the URL scheme to allow linking to plug-in documentation. My only real concern is that the plug-in documentation could (and [hopefully soon will][1]) appear in other contexts.

[1]: https://github.com/quicksilver/manual/issues/1

**Comment by hmelman** [comment]
I don't see why that's a concern. Everything Quicksilver provides quick access too appears in other contexts.

**Comment by pjrobertson** [comment]
Now that the plugin documentation is collated at qsapp.com/manual, I think this can be 'fixed' by just providing a direct link to the manual. E.g.:

In the Apple Mail 'Documentation' you'd add a link directly to: https://qsapp.com/manual/plugins/emailsupport/

I have added a note in the Plugin Dev Ref and will mark this as 'fixed':  https://github.com/quicksilver/PluginDevelopmentReference/commit/358906c42b4d0afa581b43bbd704bc9c13e2b87c
