### ISSUE TITLE
Clipboard Plugin shows Unmet Dep

### ISSUE THREAD

**Issue by dsc** [quicksilver/Quicksilver#2441]
Not sure when this started.

![qs_clipboard](https://user-images.githubusercontent.com/47595/38213244-650515fe-3675-11e8-9572-5777ef3edd70.png)

Obviously this means it no longer functions, its objects do not appear, etc.

**Comment by dsc** [comment]
I guess it also means this entire page is wrong/useless: https://qsapp.com/manual/Clipboard%20and%20Shelf/

**Comment by skurfer** [comment]
The clipboard plug-in requires the Shelf plug-in. I suspect you have that disabled. Quicksilver will download and install plug-ins to meet such dependencies, but it will not forcibly re-enable something you’ve disabled.

The manual could be wrong. I’m working my way through updating the entire thing, but haven’t gotten that far. Feel free to update that page and submit a pull request.

**Comment by pjrobertson** [comment]
As stated by Skurfer, the Clipboard plugin requires the 'Shelf' plugin be enabled. However I agree, the error message could be more helpful. I have made this more visible in the Quicksilver interface now:
![Screenshot 2022-04-04 at 13 17 26](https://user-images.githubusercontent.com/150431/161478534-ab0e3e4c-826a-4d4a-bd6c-c144ce961dec.png)
