### ISSUE TITLE
Remember the milk fails to authenticate, same as #2168

### ISSUE THREAD

**Issue by ciltis** [quicksilver/Quicksilver#2442]
I've just updated QS, and Remember the milk is once again failing to authenticate. Same issue is #2115 and #2168 . Is anyone else having this problem again?

I get:

"No callback URL specified for this API key. Your frob value is ea53dd31bb53c68312df402616d9abb063e73a8e"

**Comment by pjrobertson** [comment]
I cannot reproduce. I have successfully authenticated using Quicksilver 2.0 and RememberTheMilk plugin 1.6.0
