### ISSUE TITLE
App completely hangs if searching for Box.com

### ISSUE THREAD

**Issue by msichicago5700** [quicksilver/Quicksilver#2443]
This started a few months back. I'm using the most current version of Quicksilver and have cleared out all caches.

Searching for "Box" to access box.com sync folder will immediately hang the app. 100% reproducible every single time. The only way to recover is to forcibly kill the app and restart.

**Comment by skurfer** [comment]
Next time it hangs, [take a sample][1], upload it somewhere (Box maybe?) and post a link here.

[1]: https://support.omnigroup.com/sample-osx/
