### ISSUE TITLE
Trigger request for connection/disconnection to remote desktop client.

### ISSUE THREAD

**Issue by D-elias** [quicksilver/Quicksilver#2444]
Hi,
My feature request is for a Quicksilver trigger for disconnecting/connecting from remote desktop clients/screen sharing such as Logmein. I would like to automatically run an Applescript as soon as the connection to Logmein is disconnected/connected.

https://secure.logmein.com/central/Central.aspx

**Comment by skurfer** [comment]
It sounds like you want an [Event Trigger](https://qsapp.com/manual/Preferences/#event-triggers), but that requires two things:

1. A native macOS application (not Java, etc.)
2. The application has to post event notifications for others to pick up on

It seems pretty unlikely that both of those will be true. (I don’t know anything about the service.)

Have you asked them to add connect/disconnect scripts as an option? It seems like a natural fit.

**Comment by D-elias** [comment]
It doesn't look like it is a native OSX application. The notification that it gives when a connection is established is not a OSX banner but rather an application exclusive one. I asked them already if they could enable AppleScripts to be run on disconnect and they said that it was not possible. The only way now could be for me to find a way to run the script when secure.logmein.com is disconnected from.

**Comment by skurfer** [comment]
I don’t know if there’s any way to detect when that notification appears, then. The best I can suggest is an event trigger for when the application is launched/quit, but I’m guessing that will run at the wrong time. Maybe the script could start by pausing for a while to wait for a connection?

**Comment by D-elias** [comment]
Not sure how to do that because it runs in the background in the menu bar listening for connections. Perhaps an "ip" event trigger could be added. If a connection was established to a specific ip, then an AppleScript could be run.
