### ISSUE TITLE
Qs quick look bug.

### ISSUE THREAD

**Issue by D-elias** [quicksilver/Quicksilver#2445]
I use Quicksilver for so many tasks. One that I use the most is to bring up an item in the QS window and "quicklook" the item with the space bar to enlarge it for information. Then the information is typed into a text field of some kind. The would save so much time, the only problem is that this process takes a-lot of time. Whether I hit the space bar again or exit the command window with the activation shortcut, it takes 20 or more seconds for me to be able to start typing in the text field. It just does not show the text cursor even though I'm clicking in the text field until a significant amount of time has passed.

**Comment by skurfer** [comment]
I’m not sure if I’m doing the same steps as you. All I see is that the Quick Look panel steals focus from the app, but clicking on it allows interaction immediately. (I created a “Previous Application ⇥ Open” trigger for when QS steals focus without changing the app.)

**Comment by D-elias** [comment]
I figured out what is going on. Since I'm visually impaired, I use the zoom feature frequently. When you activate Quicksilver and quick look an image and deactivate Quicksilver the same way. You can start typing in a text field immediately like expected. Now if you use Apple's zoom accessibility feature to zoom in to the image and move the cursor to the text field after Qs is out of the way, the systems resources get taxed significantly. I have not noticed  this graphics resource draw anywhere else except with Quicksilver.
![window 2018-06-12 at 15 22 37](https://user-images.githubusercontent.com/3038757/41313240-703c945a-6e57-11e8-9d13-fe0272b31347.png)
![window 2018-06-12 at 15 22 43](https://user-images.githubusercontent.com/3038757/41313241-704c0b6a-6e57-11e8-9822-34f78148190d.png)

**Comment by skurfer** [comment]
OK, that’s helpful. I don’t know if it’s practical to do this while zooming, but can you keep Activity Monitor open and see which process seems to be tying up the CPU during the delay?

If I get a chance, I’ll try to reproduce it locally, but things are pretty busy this week.

**Comment by D-elias** [comment]
Thanks for that, consistently at the top of the list when Quicksilver is jammed up is window server and dictation is second.

**Comment by skurfer** [comment]
Hmmm. Which interface do you use?

**Comment by D-elias** [comment]
I have never herd of this before. What information do you need?

**Comment by skurfer** [comment]
It’s specific to Quicksilver. Other apps might call it a “skin”.

If you go to Preferences → General → Appearance, your chosen interface should be near the top of the window.

**Comment by D-elias** [comment]
It looks like Bezel built in, I tried all of the other options and the same results were manifested.
![window 2018-06-15 at 12 09 22](https://user-images.githubusercontent.com/3038757/41478654-8a29b168-7096-11e8-9efb-2c5f3e5efdf0.png)

**Comment by pjrobertson** [comment]
Hi D-elias. Are you still getting these hangs with the latest version of Quicksilver (v2.0.0). I have just tried to reproduce using the 'zoom' feature (very useful tool) and cannot reproduce.

Thanks
