### ISSUE TITLE
Instead of restarting right away after a crash, the crash reporter asks me to send a message and only restarts after

### ISSUE THREAD

**Issue by lucian303** [quicksilver/Quicksilver#2447]
Crashes do happen. The correct UX here is to restart QS and then, if you must insist, ask for a crash message but have a checkbox to never see it again also. As it stands, QS crashes and I have no idea that it did other than it stops working. Really, if it restarted automatically upon crash, I wouldn't even care that it crashes every once in awhile and probably no one else would care much either.

**Comment by skurfer** [comment]
> The correct UX here is to restart QS and then, if you must insist, ask for a crash message but have a checkbox to never see it again also.

I don’t entirely understand this. It _can’t_ show the crash reporter until after it restarts.

If you don’t want to see it any more, there’s a [hidden preference][1] for that: `QSRestartAutomaticallyWithoutCrashReporter`

> Really, if it restarted automatically upon crash, I wouldn't even care that it crashes every once in awhile and probably no one else would care much either.

There are tricks out there on the mailing list or maybe other places that people have used to keep it running. I imagine you could use a `launchd` Launch Agent for that. Doing this automatically on everyone’s system seems a bit heavy-handed and presumptuous, but if you find a reliable technique, maybe we could add it to the manual.

Also, please make sure you’re using the latest version. There was a long period where checking for updates would cause a crash, so it would only happen about once a week (and you would never get the update that fixed it).

[1]: https://qsapp.com/wiki/Hidden_Defaults

**Comment by lucian303** [comment]
I didn't know there was a newer version. I just upgraded. Maybe that was the problem as the crashes were very rare. If the box comes up after restarting (which of course makes sense, I don't know what I was thinking), is it possible to continue loading QS while waiting for the box? The problem is while the box is active, QS is not loaded and doesn't work. It only starts working after the box is dismissed. It sounds like QSRestartAutomaticallyWithoutCrashReporter will fix this by skipping the box altogether and moving on to. I will try that in combination with the new version and hopefully it should resolve the issue Thank you.

**Comment by skurfer** [comment]
> The problem is while the box is active, QS is not loaded and doesn't work.

Well, that’s true. It checks for crashes pretty early on and waits for an answer before doing anything else. I generally agree that it would be nice to let the app keep loading, but what if that’s where the crash is happening?
