### ISSUE TITLE
Conflict with Mac and Office 365 - Typically MS Excel

### ISSUE THREAD

**Issue by spiketrain** [quicksilver/Quicksilver#2448]
Took me a while to work this out - but Quicksilver and Excel no longer live in harmony on my Mac.

Copy / Paste of cells using keyboard shortcuts... and general slowness result.

When I shut down Quicksilver and rebooted - the Excel problem went away.

Did a fair bit of testing on this... so I guess it's a thing. I told the Microsoft Support Network people about this too in case you need to know!

I have MS Office 2011 for Mac also on my computer - and it runs fine - always did! - This issue is with 365 on a MacBook Pro late 2015.

**Comment by spiketrain** [comment]
It certainly does! - I just tested it! - Well done - and thanks for helping me.

**Comment by skurfer** [comment]
Well, that’s not a fix, but it gives us an idea where the problem is. Something about the Excel data must be confusing the clipboard code.

A less extreme solution might be to list Excel under “Ignore Applications” in the Clipboard plug-in’s preferences.

**Comment by spiketrain** [comment]
Gotcha - thanks for the advice. I shall make the necessary alterations.

**Comment by pjrobertson** [comment]
@spiketrain  - what version of Excel are you using, and is this still an issue?

I am unable to reproduce here using Excel version 16.46
