### ISSUE TITLE
Cube Interface Crashes on Secondary Actions (tab key)

### ISSUE THREAD

**Issue by toonmaster** [quicksilver/Quicksilver#2449]
Hi. I keep experiencing crashes with the Cube interface whenever trying to perform secondary actions. For example, if I type 'ddg' for DuckDuckGo and then 'tab' to move the action to the search field to enter my query, Quicksilver crashes. The same thing happens if I use the 'Current Selection' trigger, which I often use to perform actions on files, like 'Open With...' or 'Move to...' or 'Copy to...'. Other interfaces I generally use do not exhibit this issue.

**Comment by skurfer** [comment]
Yeah, it hasn’t worked well (or at all at times) on recent versions of macOS. That’s the risk you run with undocumented private APIs. I’ve updated the plug-in system so it won’t offer that interface to anyone on macOS 10.10.0 or later. You should probably remove it if you’re on a more recent OS. 😕

**Comment by toonmaster** [comment]
That is understandable. I customized it to look a lot like the old Fumo interface that I loved. So, I hate to see it won't be fixed. But there are some other good ones that I like as well and they are working flawlessly. Thanks.

**Comment by skurfer** [comment]
Well, I hope _someone_ will fix it, or rewrite it using Core Animation or something.
