### ISSUE TITLE
Incomplete translations

### ISSUE THREAD

**Issue by phineasfrogg** [quicksilver/Quicksilver#2456]
All the localised forms of Quicksilver show large amounts of stray English because much of the UI text is stored in .nib files in the main Resources folder that don't have corresponding .strings or .nib files for each of the available languages. This was plainly obvious when I was running Quicksilver in French. I confirmed this when working on updating the British English translation to actually use British spellings consistently--I opened up the Resources folder and noticed that a lot of the text that still had US spellings wasn't editable from that folder, but it was if I checked the nibs in the Resources folder. Is it possible for someone to create the actual string files for ALL the UI elements in Xcode?

**Comment by skurfer** [comment]
> Is it possible for someone to create the actual string files for ALL the UI elements in Xcode?

It’s not something I know how to do personally, but it’s an open source project so anyone can contribute. I’d love for someone to take that on.

**Comment by pjrobertson** [comment]
Hi @phineasfrogg - could you please provide screenshots or even better - a list of strings that aren't yet translated. That will help us put them up for translation on https://www.transifex.com/quicksilver/ 

If you have the time, you could also help translate existing text at https://www.transifex.com/quicksilver/

French is marked as just 78.1% translated, which is likely why you're seeing untranslated strings.

Thanks
