### ISSUE TITLE
Safari plugin doesn't work for Safari 12 on Mojave

### ISSUE THREAD

**Issue by devburke** [quicksilver/Quicksilver#2461]
I just updated to macOS Mojave, including Safari 12, to find that Quicksilver is no longer able to load any data from Safari into the Catalog (bookmarks, history, open pages). I'm running the Safari plugin v. 2.4.2.

**Comment by skurfer** [comment]
Hopefully this is just due to restructuring the way that stuff is stored, and not because they’ve completely locked it down.

**Comment by skurfer** [comment]
I found the fix, which I’ll add to the FAQ: Open your [privacy preferences](
x-apple.systempreferences:com.apple.preference.security?Privacy) and add Quicksilver to the “Full Disk Access” list.

**Comment by devburke** [comment]
That did the trick! Is there a way to make it so macOS gives a prompt about QS asking permission for full disk access, so this doesn’t catch other users?

**Comment by skurfer** [comment]
I don’t think so, but I’m just reading up on it now.
