### ISSUE TITLE
Shortcut not Triggering a Script

### ISSUE THREAD

**Issue by raythw** [quicksilver/Quicksilver#2462]
Until I went over to Mojave I was able to use a shortcut to trigger an AppleScript file that typed the current date into the frontmost application. I can still run that script from the Script menu in any application and it works fine, but it just won't trigger from Quicksilver, whatever shortcut key I use.

I can run other scripts via Quicksilver and they work fine as well. It's just this script that's meant to type into the front application that doesn’t appear to run. I can't work out if this to do with the extra security of Mojave that stops me using a script that actuates a keystroke in Systems Events or something even more obscure than that...

Many thanks!

**Comment by skurfer** [comment]
Can you share the script? I’ll try it locally.

One thing you can try is add a delay to the trigger so no keys will be held when it starts running.

**Comment by raythw** [comment]
Certainly! Here it is:



Many thanks!

**Comment by skurfer** [comment]
Hmm. I don’t know if you can send an attachment to GitHub like that. Maybe copy and paste it into a comment?

**Comment by raythw** [comment]
This is the content:


set {year:theYear, month:theMonth, day:theDay} to (current date)

set theYear to strings 3 thru 4 of (theYear as string)

set theMonth to (theMonth as integer) as string
if length of theMonth = 1 then set theMonth to "0" & theMonth

set theDay to (theDay as string)
if length of theDay = 1 then set theDay to "0" & theDay

set outputString to theYear & "_" & theMonth & "_" & theDay & " " -- line added, see below

tell application "System Events"
	--keystroke (theYear & "_" & theMonth & "_" & theDay & " ")
	--The following is a fix for erroneous keystroke operation of above line
	set len to length of outputString
	repeat with i from 1 to len
		set x to character i of outputString
		keystroke x
		key up {shift}
	end repeat
end tell

**Comment by raythw** [comment]
[Type Date.scpt.zip](https://github.com/quicksilver/Quicksilver/files/2418848/Type.Date.scpt.zip)

**Comment by skurfer** [comment]
The first time I ran the script via Quicksilver (not with a trigger), I saw this.

<img width="532" alt="screen shot 2018-09-26 at 1 34 37 pm" src="https://user-images.githubusercontent.com/154676/46098271-03ec3d80-c192-11e8-885b-92c634bff9c8.png">

I allowed it, then created a trigger using <kbd>⌃</kbd><kbd>Y</kbd>. I set the trigger to run “On Release” instead of “On Press”.

I found that if I released <kbd>Y</kbd> first, the script would fail to insert anything. I assume because holding <kbd>⌃</kbd> messes up the script’s ability to type. But if I was careful to release <kbd>Y</kbd> last, it seemed to work.

**Comment by raythw** [comment]
Thanks. I’ll give that a go later!

**Comment by raythw** [comment]
I don't seem to remember getting the above 'access' message, so I went into the Security & Privacy pane in System Preferences and discovered that under the Automation tab Quicksilver hadn't been given access to System Events! Ticking that fixed the problem. Thanks for your efforts, skurfer. Helpful responses are always appreciated!

**Comment by skurfer** [comment]
I’ve noticed that the request for access can sometimes appear behind Quicksilver’s interface. And if you don’t answer in the allowed time, it was designed to assume you meant “no” and never ask again.

Anyway, I’m glad you figured it out.
