### ISSUE TITLE
Clipboard History, can't paste file paths

### ISSUE THREAD

**Issue by abstractrealism** [quicksilver/Quicksilver#2464]
In my office we share file paths to files on our server a lot via a chat app. 
I've noticed that if you copy a file path (text), Quicksilver's clipboard history automatically resolves it to the file in question. Which is great if that's what you need, but if you want to paste the path as text, not the file, there doesn't seem to be a way to get that back. Perhaps there's some kind of way to do a workaround with a trigger? Any suggestions appreciated!

**Comment by skurfer** [comment]
Try the “Get Path” action. You might need to enable it in Preferences → General → Actions.

**Comment by n8henrie** [comment]
I've run across this; my approach to this works pretty well for me:

1. Choose a letter that you want to serve as a "keyboard shortcut" for resolving the file into a path (and decide whether you want relative or absolute path)
2. Grab an example file or folder in the first pane (such as `Desktop`)
3. Tab to the second pane
4. Hit the letter you've decided on (<kbd>p</kbd> in my case)
5. Use the down arrow to get the drop-down menu for choosing other actions
6. Find the action you're interested in (`Get Absolute (POXIS) Path` in my case)
7. Right-click the action and set it as default for <kbd>p</kbd>

From now on, you can have a file or folder in the first pane and hit <kbd>⇧</kbd><kbd>⌘</kbd><kbd>p</kbd> to resolve it into an absolute file path.

There are a few variations you can make using this general approach.

For reference the trick about jumping to a default action is mentioned at <https://qsapp.com/wiki/Keyboard_shortcuts>

It looks like there used to be a blog post about it at <http://lovequicksilver.com/post/7413266835/putting-in-a-shift> which no longer exists and I can't find in Wayback -- if anyone finds a copy, please let us know!

Closing -- hopefully this workaround solves your issue.
