### ISSUE TITLE
Quicksilver 1.6.0 not working on El Capitan

### ISSUE THREAD

**Issue by arvidtp** [quicksilver/Quicksilver#2465]
After updating from QS 1.5.8 to 1.6.0 on a macbook pro running macOS 10.11.6, the Quicksilver UI won't trigger with a keystroke (or at all) and opening Preferences, Catalog or Triggers results in a blank window with only the General button in the toolbar visible. The plugins menubar menu is also empty. Reverting to Quicksilver 1.5.8 resolves all issues.

**Comment by skurfer** [comment]
There’s a bug in 1.6.0 for users on 10.10 and 10.11, but the update system shouldn’t offer 1.6.0 to those users (any more). It’ll be fixed in 1.6.1. You should be able to run 1.5.9 until then.
