### ISSUE TITLE
Clipboard Issues

### ISSUE THREAD

**Issue by mattsaler** [quicksilver/Quicksilver#2468]
macOS 10.14
QS 1.6.0 (4025)
Clipboard Plugin 1.6.0

Ever since upgrading to Mojave, the Clipboard plugin functionality has been degraded. I can no longer paste directly from my Clipboard History—if I select an item in the list, it goes to the top of the list but requires a second attempt to paste. Steps to recreate: 

With Clipboard History enabled, bring up the list. Key down the list to the item to paste, hit Enter.  Previously, it would paste at the cursor. But now a separate Cmd+V is required. 

My "Paste Clipboard Content a Plain Text" trigger no longer works directly, either—I run the trigger, then have to Cmd+V.

**Comment by skurfer** [comment]
I can’t reproduce this. I normally have the history docked to a screen edge, but even if I detach it and manually call it up with ⌘L, hitting ↩ or double clicking works as expected. Anything else you’ve noticed that might help?

**Comment by mattsaler** [comment]
Welp, looks like Quicksilver wasn't enabled under Privacy > Accessibility. Toggled that and the clipboard plugin stuff is working as expected.

**Comment by skurfer** [comment]
Ah, OK. I think it needs that to “press” ⌘V. I’m glad you figured it out.
