### ISSUE TITLE
Safari Bookmarks not Indexing in OS 10.14 Mojave

### ISSUE THREAD

**Issue by ssperoni88** [quicksilver/Quicksilver#2469]
Quicksilver is failing to index bookmarks in Mac OS 10.14 Mojave.  Worked fine before the update, now shows no bookmarks.  Running Quicksilver 10.6.0.

**Comment by skurfer** [comment]
Quite a few people have run into this. See https://qsapp.com/manual/FAQ/#catalog-entries-are-missing-on-mojave-or-later
