### ISSUE TITLE
Be able to individually set the indexing intervals for indiviudal custom catalog entries

### ISSUE THREAD

**Issue by calc** [quicksilver/Quicksilver#247]
Tiennou told me that in the advanced mode I have to enable 'listen to filesystem notifications to update the catalog'. Where is this setting? I do have the advanced mode enabled, fyi.  Running β59 on 10.6.7 on a 32 bit machine.

**Comment by tiennou** [comment]
Closing because old. The setting is called watch, and it's not user-accessible yet. Ideally every source filesystem-related would have it enabled, but it's not the case right now (except for some of the default ones).
