### ISSUE TITLE
Mojave Interface

### ISSUE THREAD

**Issue by jspiro** [quicksilver/Quicksilver#2471]
Interesting that no one has mentioned dark mode anywhere... Issue: QS is BRIGHT compared to the darkness I've now become accustomed to.

If no one is planning on implementing dark mode, could someone point me to where the Yosemite interface plugin is hosted, so that I could fork it and adapt it to for a Mojave Dark Mode?

**Comment by skurfer** [comment]
> If no one is planning on implementing dark mode, could someone point me to where the Yosemite interface plugin is hosted, so that I could fork it and adapt it to for a Mojave Dark Mode?

It’s at https://github.com/mikker/YosemiteInterface-qsplugin

But let me save you some time.

https://github.com/mikker/YosemiteDarkInterface-qsplugin

If you’re looking for a dark mode project, feel free to adapt the QS preferences interface. 😉

**Comment by jspiro** [comment]
Amazing! Thanks. It should be added to the plugin registry, no?

**Comment by skurfer** [comment]
> It should be added to the plugin registry, no?

We’ve [talked about it][1], but there hasn’t been any further development.

[1]: https://github.com/mikker/YosemiteInterface-qsplugin/issues/9
