### ISSUE TITLE
Arrowing into items does not filter

### ISSUE THREAD

**Issue by clarkewd** [quicksilver/Quicksilver#2472]
Before upgrading, I could:

1. Activate Quicksilver
1. Type in a few characters to find a folder
1. Use the right arrow key to select the folder ( and dive into the contents)
1. Type a few more characters to filter / narrow down the results of that folder

After upgrading to `1.6.0` (`4025`) when I try to type a few characters to filter / narrow down the resulting items Quicksilver seems to actually be performing a new search.

I tried adjusting Settings -> Command -> Search, specifically changing the timeouts and even unchecking the "Reset search after" box but these don't seem to affect it.

Is this a bug, or is there a setting for this, or am I doing something wrong?

Thanks

**Comment by skurfer** [comment]
This is going into the FAQ. 😃

After you right-arrow, click the gear at the top of the results list. You can change the search mode there. You want “Filter Results”.

Note that you can also change the mode using <kbd>⌘</kbd><kbd>→</kbd> and <kbd>⌘</kbd><kbd>←</kbd>. I suspect you hit one of those on accident.
