### ISSUE TITLE
Invoke Quicksilver with a Touch Bar button

### ISSUE THREAD

**Issue by zzyyfff** [quicksilver/Quicksilver#2473]
Feature request:

Adding a custom Touch Bar button to the set of globally available buttons which invokes/activates Quicksilver, in addition to the usual "^Space" and other methods of activation.

Here's an example of how the app "BetterTouchTool" has added a custom button (the icon which looks like two fingers on a touchpad) for its app to be invoked:
![image](https://user-images.githubusercontent.com/7986137/47273535-0741d180-d564-11e8-850d-3fe3bf833725.png)

**Comment by skurfer** [comment]
If there was a supported way to do this, I would, but I don’t think there is. It looks like BetterTouchTool had to take over and replace the entire Touch Bar to make that possible.

The good news is it looks like you can also use BetterTouchTool to globally add an arbitrary button, like one that activates Quicksilver. (Simply telling it to launch the app should do it. If that doesn’t work, let me know. I have more complicated ideas.)

**Comment by skurfer** [comment]
I don’t think there’s a supported way to do this. It looks like BetterTouchTool had to take over and replace everything on your Touch Bar to pull that off.

The good news is that it also looks like you can use BetterTouchTool to add an arbitrary button, like one that invokes Quicksilver. Just telling it to launch the app should work, but if not, let me know. There are more complicated things you can try.

For the button’s icon, the image used for the menu bar might work: `/Applications/Quicksilver.app/Contents/Resources/QuicksilverMenu.tiff`

**Comment by zzyyfff** [comment]
Thanks for the quick response and for looking into this!

I tried doing this w/ BetterTouchTool, and you can create a button that sends ^Space to application Quicksilver, properly invoking QS, but this button lives within the BetterTouchTool Touch Bar replacement interface. The user touches the BTT button, which then overlays/replaces what's currently displayed on the Touch Bar, and then the Quicksilver button is revealed.

This requires touching the Touch Bar twice, in two different locations, to invoke QS, which is less than smooth for a workflow. I was hoping there would be an easy way to have an ever-present one-touch solution, the way BTT has an ever present one-touch button to invoke its Touch Bar replacement interface. There are a few other apps that have this, ex: TouchSwitcher. 

I figured it couldn't hurt to ask! After failing w/ BTT, I had first looked into whether I could implement it myself, but the code is beyond my current abilities. Perhaps that will change soon as I continue to investigate.

The 2016 and 2017 Touch Bar Macbook Pros also have some dust issues w/ the normal keyboard, which has made many of my usual keystrokes unreliable. Funny that the Touch Bar is more reliable! I Also have a separate issue where QS modifier-only activation isn't working as reliably as it used to, but I'll fill out a separate issue describing that in detail, in case anyone else has the same issue.

Thanks again for all the work you do! QS is my favorite must-have utility for MacOS!
