### ISSUE TITLE
Modified-only activation invokes when unintended

### ISSUE THREAD

**Issue by zzyyfff** [quicksilver/Quicksilver#2474]
Potential bug

15" Macbook Pro 2016 w/ Touch Bar
macOS 10.14 Mojave 
Quicksilver 1.6.0 (4025) 
This also happened when I ran 10.13 High Sierra and also w/ earlier versions of QS.

With Modifier-only activation turned one and set to single-press of Command, the way it used to work for me and what I believe the desired behavior was:
- Single tapping Command invoked QS
- Holding Command to combine with another key (like -c for copy, -v for paste, etc.) did not invoke QS

Now, the behavior is:
- Single tapping Command invokes QS
- Holding Command to combine with another key (like -c for copy, -v for paste, etc.) **sometimes** intermittently invokes QS, and sometimes does not.

**Comment by zzyyfff** [comment]
Other insights:

If this is not reproducible by others or uncommonly occurs, I wonder if my Command key has pice of dust under it causing the key to "bounce" internally, and registering as multiple quick presses. I will try experiment with test the left and right Command keys to see if it happens with both of them. If it only happens with one of them, this strongly suggests a specific mechanical issue here, and then this github issue can just be documentation of a weird issue the hopefully helps anyone else w/ the same problem it in the future!

**Comment by tiennou** [comment]
I can completely reproduce this 🙄. The MBP TouchBar has the 💩-iest keyboard I've ever had. Duplicate key registration also happens to my Shift, Tab, e, and n keys. So, yeah, sometimes holding Cmd doesn't actually result in a consistent Cmd (ie. you can "blink" the key by ever so slightly changing your finger's position while it's engaged). This can result in a bunch of `szzzz` characters, while mashing Cmd-Z.

You might be able to alleviate the issue by blowing some air near the afflicted keys, but in my experience it's hopeless. Also, KeyCodes might help seeing the "blinks" (https://manytricks.com/keycodes/).

Sorry, it's not helpful, but I couldn't help. This keyboard is driving me crazy.

**Comment by skurfer** [comment]
> I wonder if my Command key has pice of dust under it causing the key to "bounce” internally

That was my immediate thought when I read your description of the problem. I’ve already had to send my computer away for a week to get half of it replaced once. I can’t wait until the next time!

As for the QS behavior, I use modifier-only (with <kbd>control</kbd>) and it’s been very reliable throughout recent QS and macOS updates. (I use an external keyboard 90% of the time, though.)

If you have another keyboard laying around, I’ld try it out and see if you can reproduce the problem. My guess it that things will work as expected.

**Comment by zzyyfff** [comment]
SOLVED:

Just got my laptop back from Apple, repaired with a new keyboard. All behaviors are working perfectly again!

Prior to sending it off, I confirmed our guess that it was sending multiple Command keypresses by trying other unaffected keys within the laptop keyboard (the other side command key and a control key) and by testing with an external keyboard.

For anyone with this same issue, there is a **free** keyboard replacement program for affected models. See here: https://www.apple.com/support/keyboard-service-program-for-macbook-and-macbook-pro/

If you have keys that intermittently won't register, they may just blow air inside those keys to remove dust. However, if you have keys that exhibit other behaviors like repeating on a single press, then they will replace your entire keyboard with a new one.

**Comment by skurfer** [comment]
Thanks for the update.
