### ISSUE TITLE
Random trigger delays

### ISSUE THREAD

**Issue by wmertens** [quicksilver/Quicksilver#2482]
**Describe the bug**

Sometimes, when I type a keyboard trigger to toggle an application, the command is delayed until I wait about 10s or I type any other key.

**To Reproduce**
1. Set up the keyboard shortcut "shift+ctrl+option+cmd+c" to "Toggle visibility of [some application]"
2. Toggle the application so it's hidden, then don't use it for a while
3. Type "shift+ctrl+option+cmd+c"

**Expected behavior**

4. The application pops up

**Actual behavior**

4. Sometimes, the application doesn't pop up. After a few seconds, type the shift key and it pops up immediately

**What version of macOS?**

Mojave

**What version of Quicksilver?**

1.6.0.(4025)

**Comment by skurfer** [comment]
I can get this to happen following the steps above. I added some logging and I can tell you the toggle action is running and finishing _immediately_. So, there’s a delay in the OS somewhere.

The good(ish) news is that building QS with Xcode 10 seems to mysteriously remove the delay. So while it doesn’t seem to be something we can fix, it might get fixed one day.

**Comment by wmertens** [comment]
So, is building QS with XCode 10 an option? The delays seem to be getting worse :(

**Comment by skurfer** [comment]
You should be able to build the app in Xcode 10, and it will run, but some things are off and there are quite a few nasty warnings in the Console, so it’s not something I’d want to release, but you’re welcome to try it.

Here’s whatever’s currently on the `master` branch, built with 10: https://qsapp.com/archives/downloads/QS%201.6.0%20Xcode10.dmg

**Comment by wmertens** [comment]
That works indeed, many thanks!

One issue I'm seeing with it is that using the macOS dark mode messes up the text color in the sidebar of preferences. For the rest everything I use seems to work just fine.

**Comment by hmelman** [comment]
I just upgraded to Mojave (only a little late) and I'm seeing these delays with Toggle Application triggers. I'm using 1.6.0 (4025) on 10.14.5 (18F132) on an iMac using Light Mode. Is there a fix yet?

**Comment by hmelman** [comment]
I tried the Xcode 10 build above, worked fine for a couple of hours then kept crashing. I'm not using Dark Mode.
