### ISSUE TITLE
Version Beta 36 & 54 in downloads page should be marked as PowerPC compatible

### ISSUE THREAD

**Issue by blackjack75** [quicksilver/Quicksilver#2484]
It would help a lot those of us who look for  an old version. I am getting an old Cube back to life and disabling Spotlight in favour of QuickSilver (just to launch apps) is a big boost in responsiveness.

**Comment by blackjack75** [comment]
I tried several ones at the bottom of the list and only these two actually opened. (On a G4 running 10.5, not sure if there were other requirements). So I guess 54 is indeed the last one

**Comment by skurfer** [comment]
That sounds about right. Thanks.
