### ISSUE TITLE
Add QS Triggers to Catalog 

### ISSUE THREAD

**Issue by gdvine** [quicksilver/Quicksilver#2488]
Currently, Triggers function as custom command containers, but can only be launched with a keyboard combination (or other similar user event).

It would be very convenient if the QS Catalog also had optional access to the QS Triggers so that they could be searched for and launched through the main QS window. Imo this would greatly empower Quicksilver as a general purpose launcher, especially for combination commands such as opening multiple applications and files with a single command.

**Comment by pjrobertson** [comment]
You can already technically do this:

1. Set up the command you want to run in Quicksilver. E.g. 'Relaunch Chrome'
![Screenshot 2019-04-24 at 08 19 43](https://user-images.githubusercontent.com/150431/56624073-ca1ce000-6669-11e9-9da1-fca5e0a11a1a.png)

2. Hit CTRL + ↩ to turn it into a command
![Screenshot 2019-04-24 at 08 20 27](https://user-images.githubusercontent.com/150431/56624094-e587eb00-6669-11e9-9d58-eda8d9daa49f.png)

3. Choose the action 'Save Command to File' and save the file somewhere that's indexed by your QS catalog. E.g. create this folder and add it to your catalog
![Screenshot 2019-04-24 at 08 23 15](https://user-images.githubusercontent.com/150431/56624150-3ac3fc80-666a-11e9-971c-385640641d4e.png)

4. You can rename the to whatever you want to make it easier to search for. E.g. rename this file to "Restart my Browser" so you can find it by searching for 'browser'

**Comment by pjrobertson** [comment]
I've removed the tag 'feature' request and added a tag 'usability'. @gdvine perhaps you can take what I've written here and make changes to our [Quicksilver manual](https://github.com/quicksilver/manual) GitHub repository so this can be included in the manual!

Thanks :)

**Comment by pjrobertson** [comment]
I've removed the tag 'feature' request and added a tag 'usability'. @gdvine perhaps you can take what I've written here and make changes to our [Quicksilver manual](https://github.com/quicksilver/manual) GitHub repository so this can be included in the manual!

Thanks :)

**Comment by MonkeyBars3k** [comment]
You gave an example of a single command. I have Triggers that combine multiple commands. Could I access them via the QS Catalog?
