### ISSUE TITLE
Disabled Event Triggers still run

### ISSUE THREAD

**Issue by skurfer** [quicksilver/Quicksilver#2491]
**Describe the bug**
I have a trigger that sets the EQ in iTunes when a DAC is connected. I’m experimenting with some system-wide EQ apps and have disabled the EQ in iTunes, but it keeps getting reenabled when I connect the DAC.

**To Reproduce**
1. Create an event trigger that does something obvious, like show something in large type.
2. Verify that the trigger works as expected
3. Disable the trigger
4. Cause the event to happen again. The trigger will still run.

**Expected behavior**
Nothing should happen in response to the event.

**What version of macOS?**
10.14.4 (probably irrelevant)

**What version of Quicksilver?**
1.6.0 (with some extras I’m testing)

**Comment by skurfer** [comment]
Fixing this might also fix #2103

**Comment by tiennou** [comment]
Does it happen with the "modern" ndhotkey stuff ? I do remember something about mismanaged trigger state…

**Comment by skurfer** [comment]
These are event triggers, so I don’t know if that would matter here. Maybe for the other issue, though.

**Comment by tiennou** [comment]
> **To Reproduce**
> 
> 1. Create an ~event~ trigger that does something obvious, like show something in large type.
> 2. Verify that the trigger works as expected
> 3. Disable the trigger
> 4. Cause the event to happen again. The trigger will still run.

One word less, but I still remember the debugging 😅.

**Comment by skurfer** [comment]
I deleted the trigger, relaunched QS, and confirmed that it no longer exists in `Triggers.plist`. It _still_ runs. 🧟‍♂️

**Comment by pjrobertson** [comment]
Seems to work fine here for me. @skurfer  - did you try on the latest master when you removed the `noactivity` label?

I set up a tigger for: Show large type > Connected to AC

**Comment by skurfer** [comment]
I tried this again and disabling an Event Trigger. It seemed to work as expected. I relaunched to make sure it still stayed disabled, and it was apparently deleted. So that’s a problem, but should be its own issue I suppose.
