### ISSUE TITLE
"Stationery Pad" Finder setting is not followed by Quicksilver

### ISSUE THREAD

**Issue by devburke** [quicksilver/Quicksilver#2496]
Finder has a setting in the "Get Info" window of a document that can set a document as a "Stationery pad", basically a template file. With this setting, every time the document is opened, it's copied and the copy is opened. Quicksilver does not follow this behavior, and always opens the template document itself.

1. Go to a document in Finder.
2. Open "Get Info" window for the document.
3. Make sure the "Stationery pad" checkbox is checked.
4. Open the document from Finder to see expected behavior.
5. Open the document using Quicksilver to see erroneous behavior.

**Expected behavior**
A copy of the document should be created and that is what should be opened (I'm not sure whether Finder handles this normally, or instructs the opening application to make a new copy).

![Screen Shot 2019-06-24 at 5 28 36 PM](https://user-images.githubusercontent.com/1630645/60058410-819f9400-96a5-11e9-852c-d523af3b3ac2.png)

macOS 10.14.5

Quicksilver 1.6.0

**Comment by skurfer** [comment]
Interesting. I never knew about that feature. (Quicksilver has a similar “Templates” feature, if you want to try that, but that’s beside the point.)

What happens if you run `open Cover\ Letter\ Template` in Terminal? If that fails, what about `open -a Finder Cover\ Letter\ Template`?

**Comment by devburke** [comment]
Good question! Just tried it out. `open` just directly opens the document, but `open -a Finder` works correctly.

Admittedly, it's an extremely low priority thing. There's probably just about nobody who actually uses the stationery pad feature. And I tested it opening the document in Pages for iOS too, and it also just straight up opens it, rather than making a copy. Most likely the stationery pad feature is just vestigial and forgotten.

**Comment by devburke** [comment]
This feature is meant to apply for all types of documents, but for iWork apps specifically, they actually made a feature inside the app for adding a template to the template chooser.

**Comment by tiennou** [comment]
FWIW I'm pretty sure that Stationary is System 7-era stuff, even maybe 6 — memory wasn't that good at the time 👶. System 7 [confirmed](https://udcf.gla.ac.uk/~gwm1h/macinfo/section9.html), thanks for the memory trip, sorry for the noise.

**Comment by pjrobertson** [comment]
This appears to be a finder-specific function. It's not explicit that the **Open** command in Quicksilver should open things via Finder (for example, other File browsers are possible).

As such, the default behaviour of 'Open' shouldn't be changed, but you can get this to work by using the 'open with...' 'Finder' option:

![Screenshot 2022-02-14 at 11 47 47](https://user-images.githubusercontent.com/150431/153797022-3fa4a85e-2fa8-4309-9a2d-a246c5d542d6.png)


If you were to make the 'Open With...' action the default for files, then you could make this explicitly happen. Or, if you have a specific set of template files you know you want to open with Finder, then you could just manually use 'open with...' 'Finder' for those files.

It's a great tip - I didn't know it existed! But we don't want to change the default 'Open' action just for a Finder feature. I'll mark this issue as "Won't fix" for now.

Thanks!
