### ISSUE TITLE
Quicksilver hangs when huge files stored to clipboard

### ISSUE THREAD

**Issue by pjrobertson** [quicksilver/Quicksilver#2501]
I was just copying and pasting large Adobe Illustrator files (>500MB) into my clipboard for image editing work. Quicksilver was storing these files in its clipboard, and then subsequently saving them to disk using `[QSLibrarian saveShelf:]` every time the clipboard changed (`clipboardChanged` notif).

This was causing QS to hang indefinitely (writing a 1GB file to disk every time I copy/paste)

Solutions that come to mind:

1. Have an option to limit the filesize saved to the QS clipboard
2. Don't save the clipboard to disk *every* time the clipboard changes, but either:
     a) save it periodically (e.g. every 30s) if anything's changed - downside is some things might be lost if QS crashes before saving the latest clipboard
     b) Use some binary file format for saving to disk and only make incremental edits. Or maybe just something like SQLite to 'insert' new items at the top of the list and 'pop' old items off the bottom of the list.

Open for discussion, but noting this issue here now

**Comment by skurfer** [comment]
I could have sworn we put something in there to ignore data past a certain size for this exact reason. Maybe we just talked about it. 🤷‍♂

**Comment by pjrobertson** [comment]
I think we probably just talked about it!

**Comment by pjrobertson** [comment]
Oh it's in there, just hidden and unimplemented. 
![Screenshot 2019-08-15 at 12 36 33](https://user-images.githubusercontent.com/150431/63073032-5a549d00-bf59-11e9-8fe8-567da59d99c4.png)

**Comment by pjrobertson** [comment]
OK, so a bit more debugging shows there are actually 2 places that are causing QS to hang.

Let's say you have a clipboard item from Powerpoint, it has the following types available:

```
(lldb) po [pboard types]
<__NSArrayM 0x600000d61890>(
dyn.ah62d4qmxhk4d425try1g44pdsm11g55gsu1fa551qz3fa55mr34c4qmwf22c4wpssvw1e5xbru0zg4dbsbw1g,
com.microsoft.PowerPoint-12.0-Internal-Shapes,
dyn.ah62d4qmxhk4d425try1g44pdsm11g55gsu1e82xnqzv1kpneqz30g6xmsb4g86u,
com.microsoft.Object-Descriptor,
dyn.ah62d4qmxhk4d425try1g44pdsm11g55gsu1fa551qz3fa55mr34c4qmwf22c4wpssvw1e5xbru0zk4dfrzwu,
com.microsoft.PowerPoint-12.0-Internal-Theme,
dyn.ah62d4qmxhk4d425try1g44pdsm11g55gsu1fa551qz3fa55mr34c4qmwf22c4wpssvw1e5xbru0yg55qr73c4y5drbw043k,
com.microsoft.PowerPoint-12.0-Internal-Color-Scheme,
dyn.ah62d4qmxhk4d425try1g44pdsm11g55gsu1ec6xyfy0yszwrmu0yg5dmsbdg86xrqf4a,
com.microsoft.Art--GVML-ClipFormat,
com.adobe.pdf,
Apple PDF pasteboard type,
public.tiff,
NeXT TIFF v4.0 pasteboard type,
dyn.ah62d4qmxhk4d425try1g44pdsm11g55gsu1ek2pyqfh0e4xfqr4a,
com.microsoft.DataObject,
com.microsoft.appbundleid
)
```

As per `QSObject_Pasteboard.m:L91` when we want to add this item to the QS Clipboard we iterate through ALL types and create a QSObject with `data` for each type on the Pasteboard Type list. So if, for example our pasteboard item is an 8MB PDF, and we have types public.tiff, NeXT TIFF..., com.adobe.pdf, Apple PDF pasteboard type all representing some kind of PDF/image equivalent, we will be adding all these data types to QS. That means an 8MB clipboard object could well bloat to 100+MB if there are lots of different types.

QS then reads all these objects from the clipboard to save into the QSObject, reading 100MB of data from the clipboard can be slow (since the clipboard has to go ask the original app for the content in that specific type. So e.g. Powerpoint would have to then convert its internal object to a TIFF to supply to the clipboard).

That's roadblock no.1.

Roadblock no.2 is what my original post referred to - having to save all this info to the disk. It's compounded by the fact that one 8MB image might actually be 100+MB in RAM inside QS (in the form of a QS object with a huge data dictionary).

Needs more debugging/thinking through

**Comment by pjrobertson** [comment]
I just downloaded Yippy and Maccy - two pasteboard apps for macOS and they both exhibit the same issue. Was hoping we could just fork one of those for this, but it looks like not. I think I'll implement the filesize limiter first, although my guess is that might not actually work - since we won't know the size of the data until we've got it.
