### ISSUE TITLE
Broken links on tutorials page

### ISSUE THREAD

**Issue by CouldBeThis** [quicksilver/Quicksilver#2502]
Hello, I am almost certain I am posting in the wrong place but I am new to this stuff and I can't figure out where else to post it. I am sorry to be contributing to any unwanted chaos. If someone would like to tell me how I should have known where to put it, then next time I will know how to look for the information more effectively. In any case please direct this to whoever should be aware of it. 

> For questions or tech support, please start with the [users’ group][1]. If you know the problem is in Quicksilver itself, report it here.
> [1]: https://groups.google.com/forum/#!forum/blacktree-quicksilver

I'm not making a google account and this also doesn't sound particularly appropriate for that. 

**Describe the bug**

This is about the page: https://qsapp.com/wiki/Tutorials

Under the heading "Quicksilver" all but one of the links are broken: 

- Quicksilver Screencast: The Setup
   - links to https://gigaom.com/apple/quicksilver-screencast-the-setup/
   - actually goes to https://gigaom.com/archives/apple/ which has nothing about Quicksilver that I can see

-  Quicksilver Tutorial Mac OS X - Demo, Installation, Setup in 10 mins.
   - links to https://www.youtube.com/watch?v=EBvFUhTqKK4
   - "Private video Sign in if you've been granted access to this video"
-  Quicksilver Tutorial v2.0 - Very good 7.5 min on manipulating files.
   - links to https://www.youtube.com/watch?v=EydTYOeqIrk&mode=related&search=
   - "Private video Sign in if you've been granted access to this video"
-  Comma Trick
   - looks ok
-  Quicksilver Screencast: Pictures - one of the best demonstrations of Quicksilvers power
    - links to https://gigaom.com/apple/quicksilver-screencast-pictures/
   - actually goes to https://gigaom.com/archives/apple/ which has nothing about Quicksilver that I can see
-  Quicksilver In-n-Out - 5 mins, mostly about dragging and dropping to and from QS
    - links to https://gigaom.com/apple/quicksilver-screencast-in-n-out/
   - actually goes to https://gigaom.com/archives/apple/ which has nothing about Quicksilver that I can see
-  Arrowing - 3.5 mi
    - links to http://theappleblog.com/2007/02/28/quicksilver-screencast-arrowing/
   - that page exists, however the URL for the video it points to (http://media.theappleblog.com/screencasts/qsarrows.mov) does not

**To Reproduce**
1. Click the link above.

**Expected behavior**
The links should not be broken.

**Screenshots**
Don't think they are required. 

**What version of macOS?**
irrelevant

**What version of Quicksilver?**
irrelevant

**Comment by skurfer** [comment]
> I am almost certain I am posting in the wrong place but I am new to this stuff and I can't figure out where else to post it.

This is the right place. Thanks for letting us know. What we really need to do is move whatever’s useful out of the wiki to the manual or developer docs and shut it down.

> I'm not making a google account

Good for you. (That’s not sarcasm.) FYI, you can use a Google group like a mailing list. You don’t have to have an account. Just send a message to `blacktree-quicksilver+subscribe@googlegroups.com`. Change that to “unsubscribe” to leave.

Unrelated: Imagine how you’d feel if your kid’s school gave them a Google account using their real name without asking (or even _telling_) you. Happened to me. 😡

**Comment by pjrobertson** [comment]
Nice searching @thynus ! I managed to find most of the videos and download them from web.archive.org.

Here are the ones I've already downloaded:
![Screenshot 2022-02-07 at 09 10 10](https://user-images.githubusercontent.com/150431/152710223-12168c30-3f88-4fd0-a20b-7556b6896c24.png)

What I propose is that we go through each of the links on that page one-by-one, and try to find archives of the videos from web.archive.org. Then we upload them all to a new YouTube channel, which I will create.

@thynus - are you able to help out a little more with the the archival work, then storing the files somewhere online so that I can upload them all to a new "Quicksilver" YouTube channel?

**Comment by hmelman** [comment]
Why not just change the links to point to web.archive.org?

**Comment by n8henrie** [comment]
Hey, what do you know? [Apple Maps Quicksilver Action](http://n8henrie.com/2013/12/apple-maps-quicksilver-action/)

I have a couple aliases for things like this. They're kind of quick and dirty but maybe will give us a head start.

```bash
get_urls_containing() {
  local string=$1
  local url=$2
  local domain
  : "${url#*//}"
  domain=${_%%/*}
  proto=${url%%/*}
  curl --silent "${url}" |
    xmllint \
      --html \
      --xpath '//a[contains(@href, "'"${string}"'")]/@href' \
      - \
      2> /dev/null |
    awk -F'"' -v domain="${domain}" -v proto="${proto}" -v url="${url}" '{
        path = $(NF-1)
        if (path ~ /^https?:\/\//) {
          print path
        } else if (path ~ /^#/) {
          print url path
        } else {
          print proto "//" domain path
      }
    }'
}

get_status() { curl --head --write-out "%{http_code}" --output /dev/null --silent "$1"; }
```

```console
$ export -f get_status
$ get_urls_containing '' 'https://qsapp.com/wiki/Tutorials' | parallel '[ $(get_status {}) -gt 299 ] && echo {}'
...
```

- [ ] http://n8henrie.com/2013/12/apple-maps-quicksilver-action/
- [ ] http://www.moncefbelyamani.com/search-for-selected-text-on-any-website-with-quicksilver/
- [ ] http://theappleblog.com/2007/02/28/quicksilver-screencast-arrowing/
- [ ] https://gigaom.com/apple/quicksilver-screencast-the-setup/
- [x] https://gigaom.com/apple/quicksilver-screencast-in-n-out/
- [ ] https://gigaom.com/apple/quicksilver-screencast-pictures/
- [ ] https://qsapp.com/wiki/Unit_Conversion_Module
- [ ] https://qsapp.com/wiki/Shelf_Module
- [ ] https://gigaom.com/apple/quicksilver-does-menus-too/
- [ ] http://vjarmy.com/archives/2004/03/quicksilver_a_b.php
- [ ] http://vjarmy.com/archives/2005/02/quicksilver_fro.php
- [ ] https://gigaom.com/apple/the-metadata-screencast-part-three/
- [ ] http://vjarmy.com/archives/2006/01/quicksilver_gold_trigger.php
- [ ] https://gigaom.com/apple/quicksilver-does-menus-too/
- [ ] https://gigaom.com/apple/quicksilver-screencast-the-setup/
- [ ] https://gigaom.com/apple/quicksilver-screencast-pictures/
- [ ] https://gigaom.com/apple/spotlight-comments-using-quicksilver/
- [ ] https://gigaom.com/apple/quicksilver-screencast-the-clipboard/
- [ ] https://gigaom.com/apple/quicksilver-changes-everything/
- [ ] https://gigaom.com/apple/quicksilver-running-scripts/
- [ ] https://gigaom.com/apple/full-quicksilver-demo-movie-1/
- [ ] https://gigaom.com/apple/screencast-quicksilver-catalogs/
- [ ] http://theappleblog.com/2007/02/28/quicksilver-screencast-arrowing/
- [ ] https://gigaom.com/apple/quicksilver-screencast-tags-playlists/
- [ ] https://gigaom.com/apple/quicksilver-screencast-in-n-out/
- [x] https://gigaom.com/apple/quicksilver-screencast-abracadabra-gestures-triggers/
- [ ] https://gigaom.com/apple/the-metadata-screencast-part-three/
- [ ] http://www.facilware.com/screencast/quicksilver/qscap4.mov
- [ ] https://www.youtube.com/watch?gl=ES&amp;hl=es&amp;v=xtPGEgIhjdo
- [ ] https://www.youtube.com/watch?gl=ES&amp;hl=es&amp;v=ghVvYUjCW-M
- [ ] https://qsapp.com/wiki/Remember_The_Milk
- [ ] https://qsapp.com/w/index.php?title=Talk:Tutorials&amp;action=edit&amp;redlink=1
- [ ] https://qsapp.com//www.mediawiki.org/
- [ ] https://qsapp.com/wiki/Quicksilver_Wiki:Privacy_policy
- [ ] https://qsapp.com/wiki/Quicksilver_Wiki:About
- [ ] https://qsapp.com/wiki/Quicksilver_Wiki:General_disclaimer

With possible wayback urls:

```console
$ get_urls_containing '' 'https://qsapp.com/wiki/Tutorials' | parallel '[ $(get_status {}) -gt 299 ] && curl --silent --head http://archive.org/wayback/available?url={} | grep memento-location'
memento-location: http://web.archive.org/web/20150317224127/http://www.moncefbelyamani.com/search-for-selected-text-on-any-website-with-quicksilver/
memento-location: http://web.archive.org/web/20210508103853/https://n8henrie.com/2013/12/apple-maps-quicksilver-action/
memento-location: http://web.archive.org/web/20100312235807/http://theappleblog.com:80/2007/02/28/quicksilver-screencast-arrowing/
memento-location: http://web.archive.org/web/20120309144419/http://gigaom.com:80/apple/quicksilver-screencast-in-n-out/
memento-location: http://web.archive.org/web/20120126190542/http://gigaom.com:80/apple/quicksilver-screencast-pictures/
memento-location: http://web.archive.org/web/20120126114733/http://gigaom.com:80/apple/the-metadata-screencast-part-three/
memento-location: http://web.archive.org/web/20140708171917/http://qsapp.com/wiki/Unit_Conversion_Module
memento-location: http://web.archive.org/web/20210506080736/https://vjarmy.com/archives/2004/03/quicksilver_a_b.php
memento-location: http://web.archive.org/web/20121210174412/http://gigaom.com:80/apple/quicksilver-screencast-the-setup/
memento-location: http://web.archive.org/web/20220128045424/https://vjarmy.com/archives/2006/01/quicksilver_gold_trigger.php
memento-location: http://web.archive.org/web/20120505180758/http://gigaom.com:80/apple/quicksilver-does-menus-too/
memento-location: http://web.archive.org/web/20211004093203/https://vjarmy.com/archives/2005/02/quicksilver_fro.php
memento-location: http://web.archive.org/web/20140708193312/http://qsapp.com/wiki/Remember_The_Milk
memento-location: http://web.archive.org/web/20120505180758/http://gigaom.com:80/apple/quicksilver-does-menus-too/
memento-location: http://web.archive.org/web/20121210174412/http://gigaom.com:80/apple/quicksilver-screencast-the-setup/
memento-location: http://web.archive.org/web/20121106042257/http://gigaom.com:80/apple/quicksilver-changes-everything/
memento-location: http://web.archive.org/web/20120126190542/http://gigaom.com:80/apple/quicksilver-screencast-pictures/
memento-location: http://web.archive.org/web/20110517225108/http://gigaom.com:80/apple/full-quicksilver-demo-movie-1/
memento-location: http://web.archive.org/web/20120309144419/http://gigaom.com:80/apple/quicksilver-screencast-in-n-out/
memento-location: http://web.archive.org/web/20140708190857/http://qsapp.com/wiki/Shelf_Module
memento-location: http://web.archive.org/web/20110802034857/http://gigaom.com:80/apple/quicksilver-running-scripts/
memento-location: http://web.archive.org/web/20121025163024/http://gigaom.com:80/apple/quicksilver-screencast-tags-playlists/
memento-location: http://web.archive.org/web/20110911135607/http://gigaom.com:80/apple/spotlight-comments-using-quicksilver/
memento-location: http://web.archive.org/web/20120126114733/http://gigaom.com:80/apple/the-metadata-screencast-part-three/
memento-location: http://web.archive.org/web/20110821064532/http://gigaom.com:80/apple/screencast-quicksilver-catalogs/
memento-location: http://web.archive.org/web/20120415204650/http://gigaom.com:80/apple/quicksilver-screencast-abracadabra-gestures-triggers/
memento-location: http://web.archive.org/web/20100312235807/http://theappleblog.com:80/2007/02/28/quicksilver-screencast-arrowing/
memento-location: http://web.archive.org/web/20120721025316/http://gigaom.com:80/apple/quicksilver-screencast-the-clipboard/
memento-location: http://web.archive.org/web/20160203220325/http://www.facilware.com/screencast/quicksilver/qscap4.mov
```

Short on time. Hope this is helpful.

**Comment by n8henrie** [comment]
I got:

- QSemailfilefullsize.mp4
- QS-screencast-pics.mov
- Quicksilvertunes.mov
- qs-clipboard.mov
- QS-theSetup.mov
- qscap4.mov

**Comment by pjrobertson** [comment]
> Why not just change the links to point to web.archive.org?

My hope is that by consolidating all the videos in one place, it'll make it easier for new users to find them. And at the same time, give Quicksilver more coverage. I've set up a YouTube channel here: https://www.youtube.com/channel/UCncG9qMNHNkWcxi5ONKksHA

@n8henrie - would you be willing to upload those videos you got straight to YouTube? If so, please send me your (Google) email address and I'll add you to the YouTube account.

**Comment by pjrobertson** [comment]
@CouldBeThis and @thynus  - if you're also willing to help consolidate all these videos in one place, let me know and I can add you as members to the account as well.

Anybody else who'd like to help on this project - please let me know.

**Comment by n8henrie** [comment]
Sure -- I'm @n8henrie pretty much everywhere.

**Comment by pjrobertson** [comment]
I've updated the Tutorials page and have added a link to the [Youtube page](https://qsapp.com/wiki/Tutorials)

@n8henrie - I think we're just waiting on you to upload what videos you have to YouTube. Please close this issue once you've uploaded. Thanks!

**Comment by n8henrie** [comment]
I uploaded what I have a couple days ago -- but I didn't think to update the descriptions and titles, will work on that.

Unfortunately it won't let me delete the 2 files that were named e.g. `foo.mov` but were actually 404 pages in disguise; gives me an error when I delete -> confirm deletion, "try again later" -- been giving me this for a couple days now.

**Comment by pjrobertson** [comment]
> Unfortunately it won't let me delete the 2 files that were named e.g. `foo.mov` but were actually 404 pages in disguise; gives me an error when I delete -> confirm deletion, "try again later" -- been giving me this for a couple days now.

Ah, gotcha. I guess they don't display on the front-end, so not a biggie.

**Comment by n8henrie** [comment]
All set
