### ISSUE TITLE
Clipboard isn't updated when copying from iWork

### ISSUE THREAD

**Issue by sahi1l** [quicksilver/Quicksilver#2504]
**Describe the bug**
If I try to copy and paste something in iWork (Pages specifically), it will instead paste the object I copied previously.  This doesn't happen with text, only sometimes with objects or groups of objects.

**To Reproduce**
1. Open Pages.
2. Make two sets of objects: a rectangle, some text, and an equation.  (I'm not sure which of these are actually required but this seems to work.)
3. Copy the first set, and paste somewhere else.
4. Copy the second set, and press paste.
5. When you paste, the first set will show up instead of the second.
6. Quitting Quicksilver seems to stop this behavior, and turning off the Clipboard plugin also seems to help after a restart of Quicksilver.

**Expected behavior**
When I copy an object, it should be available to paste right away.

**What version of macOS?**
10.13.6 

**What version of Quicksilver?**
1.6.0

**Comment by skurfer** [comment]
I can confirm this. For now, you could try adding Pages to the list of ignored applications under Preferences → General → Clipboard. You should still be able to copy/paste in Pages with Quicksilver running. It just won’t add things to the history.

**Comment by studgeek** [comment]
I see a similar problem with Google Docs that seemed to start with the clipboard plugin upgrade. I would rather not disable clipboard for all of Chrome. Is it possible to switch back to the previous version of the plugin?

**Comment by jschwalbe** [comment]
yes, the previous plugin version worked. at one point i rolled back, but somehow it re-updated and i cannot recall how to get back to the older version. any help?

**Comment by zjlovezj** [comment]
@jschwalbe 

clipboard plugin 1.6.0 (works for me).

https://qs0.qsapp.com/plugins/download.php?id=com.blacktree.Quicksilver.QSClipboardPlugIn&version=347

**Comment by skurfer** [comment]
@pjrobertson Looks like there are issues with the changes to get the “most rich” representation of something. Do you have time to take a look?

**Comment by skurfer** [comment]
We're released an update to the Clipboard plug-in (version 1.6.2). Can you see if it fixes this?
