### ISSUE TITLE
shortcut to open Finder fails to bring Finder window to focus

### ISSUE THREAD

**Issue by lch48a** [quicksilver/Quicksilver#2505]
Hi, I associated a shortcut to trigger the opening of finder (CMD+E). In Mojave this fails to bring focus to that window as you can see in this screen cast https://d.pr/free/v/vDXOJi

Somehow thew "open" trigger is only able to change the focus of the menubar, which is useless (and odd).

I have used this shortcut for years in previous OSX versions, and it is only now in Mojave that the problem present itself.

**Comment by skurfer** [comment]
Hmmm. If you run **Finder ⇥ Open** in the regular Quicksilver interface, does it work? (That works for me.) I wonder if it has something to do with the ⌘ key being pressed at the time. If so, you could try changing the trigger settings so it runs after you let go of the keys instead of when you press them.

FYI, ⌘E is already a super useful system-wide shortcut that you might not want to clobber with a trigger. It takes the selected text and uses that as the search term in all Find dialogs across the system. So if you want to find the selected word in a document, you can just hit ⌘E, then ⌘G repeatedly. That search term also gets used by default for Quicksilver’s web search plug-in.

**Comment by lch48a** [comment]
It does not look like the problem has to do with the shortcut. I figured
out what triggers the problem: https://d.pr/free/v/IKTn0B
Also, the problem is there with the regular QS interface as well:
https://d.pr/free/v/UmfqUb

**Comment by skurfer** [comment]
I can’t reproduce that. Here are some things to try:

* Go to “Extras” in Quicksilver’s preferences and try different settings for “Reopening the current application”.
* When you have it in a broken state, see if clicking the Finder icon works. I don’t think what QS does is all that different, so it wouldn’t surprise me if other ways to focus Finder also fail.
* Try disabling whatever extension you’re using to add those tabs to Finder. Maybe it’s interfering with the normal window behavior.

**Comment by lch48a** [comment]
Tried different settings in Extras but it did fix the problem.
The extension that add those tabs is Xtrafinder, but even disabling it the
problem persisted.
I finally fixed it using Keyboard Maestro with the same shortcut CMD+E with
an added option "Bring window to focus".

On another note, I do not see the CMD+E shortcut referenced anywhere as a
way to search selected terms in Finder.
For example, not here:
https://support.apple.com/en-us/HT201236
Could you provide any link where what you mention is explained in some
detail?
Thanks!

**Comment by skurfer** [comment]
> On another note, I do not see the CMD+E shortcut referenced anywhere as a way to search selected terms in Finder.
> 
> Could you provide any link where what you mention is explained in some detail?

It’s not for searching in Finder. (In Finder, apparently that shortcut is for Eject.) It’s for the Find dialogs you get with ⌘F in most apps. In pretty much every app where you deal with text, ⌘E performs “Use Selection for Find”. You can find it on the Edit menu under “Find”.

**Comment by lch48a** [comment]
Got a new Mac and while setting it up I figured out how to reproduce this
issue:

Set QS trigger to cmd+E to open Finder
Show desktop (through Hot Corner or trackpad gesture)
Click on desktop
Go back to apps (i.e. return from Hot Corner or trackpad gesture)
Now when you cmd+E Finder is not brought up, because the Desktop "window"
of Finder is brought up, which ends up in nothing except a change in the
Menubar shows you are now in Finder.

Hope it makes sense!

**Comment by pjrobertson** [comment]
I'm unable to reproduce this (on macOS 10.14). Is this still a problem, @lch48a 

Here's what I get:

https://user-images.githubusercontent.com/150431/161474328-8cab3a6c-953f-49bf-a377-22d8df28a81c.mov

**Comment by lch48a** [comment]
It's still an issue. I had to use a different app to implement this
specific shortcut to Finder.
