### ISSUE TITLE
Add /usr/local/bin for use in "Run Command in Shell"

### ISSUE THREAD

**Issue by geo-ryffraff** [quicksilver/Quicksilver#2508]
When I do echo $PATH in a terminal window, the result is "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin" but when I do echo $PATH in QS and then select the "Run Command in Shell" Quicksilver, the path is just "/usr/bin:/bin:/usr/sbin:/sbin"

How do I get the terminal plugin to "see" /usr/local/bin so I can execute those commands in QS as well?

**Comment by skurfer** [comment]
This looks like a pretty good list of all the ways to set variables, depending on your OS version.

http://www.dowdandassociates.com/blog/categories/set-mac-os-x-environment-variables/

**Comment by tewing-riffyn** [comment]
I'm having that same issue.   I'm trying to execute the quicksilver run command but it's not finding the scripts in /usr/local/bin.
