### ISSUE TITLE
Crash after using Large Type

### ISSUE THREAD

**Issue by awdsmirk** [quicksilver/Quicksilver#2511]
Quicksilver crashes after using the Large Type feature and dismissing the window.
Crash file attached.
**To Reproduce**
1. Launch Quicksilver - I am using Bezel (built-in)
2. Type period character "." to go into text large type mode
3. Type in any text, hit Enter
4. Your text is displayed in Large Type on the screen
5. Dismiss the text by clicking anywhere outside the text
RESULT: Quicksilver crashes

**Expected behavior**
Quicksilver should not crash

**Screenshots**

**What version of macOS?**
10.15.3
**What version of Quicksilver?**
1.6.0
[Quicksilver_2020-02-12-222300_deathstar.crash.zip](https://github.com/quicksilver/Quicksilver/files/4196811/Quicksilver_2020-02-12-222300_deathstar.crash.zip)

**Comment by jedjds** [comment]
The same for me!
MacOS: Catalina (10.15.3)
Version of Quicksilver: 1.6.0

**Comment by pjrobertson** [comment]
I'm not on Catalina yet, but the QSVanishingWindow code mentioned in the crash log looks iffy. Running stuff in `dealloc` doesn't seem good. It's originally from these two commits:

First this: 33067ae
Then a 'bug fix': a64a8cc

**Comment by skurfer** [comment]
Yeah, the `_largeTypeWindows` array is obviously just there to keep the retain count up, but there must be a safer way to accomplish that. I've tried a few things, but either the window never appears, or the app crashes.

**Comment by awdsmirk** [comment]
Thanks for fixing this!

**Comment by lgarron** [comment]
I just finally realized today that this bug was causing a huge part of what felt like Quicksilver flakiness!

Not sure why I didn't auto-update yet, but a manual update fixed it for me! Thanks, @skurfer  😍
