### ISSUE TITLE
Clipboard module Capture History breaks Mojave clipboard (taking screenshots to memory))

### ISSUE THREAD

**Issue by stevechen** [quicksilver/Quicksilver#2512]
**Describe the bug**
After turning Capture History on, Mac can no longer captured screenshots to memory. The error message displays when trying to paste after a taking a screenshot:

The file “Unsaved Preview Document #.png” could not be opened.
It may be damaged or use a file format that Preview doesn’t recognize.

**To Reproduce**
1. Go to 'General' in QuickSilver
2. Click on 'Clipboard'
3. Check 'Capture History' to turn the function on.
<img width="835" alt="Pasted_Image_2020_3_12__5_53_PM" src="https://user-images.githubusercontent.com/497347/76509120-789c6000-648a-11ea-8dfe-0f09630f8747.png">

4. Perform a screenshot (command + control + shift + 4)
5. Open Preview.app.
6. Press command + n
7. Error message displays

If I turn Capture History off, clipboard works as expected.

**Expected behavior**
At step 6, Preview should create a new document with the captured screenshot as the content.
 
**Screenshots**
![image](https://user-images.githubusercontent.com/497347/76508357-345c9000-6489-11ea-84f9-a0cfdaf56f4a.png)

**What version of macOS?**
Mojave 10.14.6

**What version of Quicksilver?**
1.6.0(4025)

This seems to be the error message in the console:
default	17:48:30.881777 +0800	Quicksilver	unexpected object for file path: (null), object: QSObject <0x600003220700>, (null)
default	17:48:31.036536 +0800	useractivityd	ADVERTISING: Setting supressAdvertisementChange = YES because the client attempted to change advertisement too quickly, 0.407255 since lastAdvertisementTime (now=Thu Mar 12 17:48:31 2020 last=Thu Mar 12 17:48:30 2020)
default	17:48:31.090220 +0800	useractivityd	ADVERTISING: Setting supressAdvertisementChange = YES because the client attempted to change advertisement too quickly, 0.460852 since lastAdvertisementTime (now=Thu Mar 12 17:48:31 2020 last=Thu Mar 12 17:48:30 2020)

**Comment by skurfer** [comment]
We're released an update to the Clipboard plug-in (version 1.6.2). Can you see if it fixes this?

**Comment by stevechen** [comment]
> We've released an update to the Clipboard plug-in (version 1.6.2). Can you see if it fixes this?

It's working now, thank you!
