### ISSUE TITLE
Recent documents/recent applications catalog doesn't get rescanned

### ISSUE THREAD

**Issue by JulianKingman** [quicksilver/Quicksilver#2514]
For questions or tech support, please start with the [users’ group][1]. If you know the problem is in Quicksilver itself, report it here.

[1]: https://groups.google.com/forum/#!forum/blacktree-quicksilver

**Describe the bug**
Under User/Recent Items, Recent Applications and Recent Documents do not automatically get re-scanned.

**To Reproduce**
1. Open an app (e.g. "Shorui")
2. Quite the app
3. Rename the app (e.g. "Disk Space")

**Expected behavior**
You would expect to find the app under the new name (this works), and you would expect the old app name to disappear (this doesn't work). After looking around for where the reference to the old app name is, I narrowed it down to the Recent Items. The same occurs if you move and/or rename a recently opened folder.

**Screenshots**
Original name still present:
<img width="360" alt="Screen Shot 2020-03-17 at 6 36 58 PM" src="https://user-images.githubusercontent.com/1566400/76916660-605b8500-687e-11ea-863d-0ebf85868a95.png">
New name also present:
<img width="362" alt="Screen Shot 2020-03-17 at 6 37 07 PM" src="https://user-images.githubusercontent.com/1566400/76916686-6f423780-687e-11ea-89d9-40fa091cef6c.png">

**What version of macOS?**
10.15.3

**What version of Quicksilver?**
1.6.0 (4025)

**Workaround**
One time,  manually rescanning the top level "Recent Items" catalog entry fixed it, now it doesn't, even though it doesn't show the new app name there.

There's also a chance that it's under a different catalog, but I went through quite a few suspects and didn't find it listed there.

Similar to: https://github.com/quicksilver/Quicksilver/issues/11,

**Comment by skurfer** [comment]
Silly oversight. Should be fixed in the next release.

**Comment by skurfer** [comment]
Also note:

* There’s a “Show Source in Catalog” action that will reliably tell you what entry is adding something to the catalog. You might need enable it under Preferences → General → Actions
* These entries aren’t scanned in real time. The fix means that when the scheduled rescan occurs (every 10 minutes by default), these entries will get updated if necessary.
