### ISSUE TITLE
paste from clipboard storage not working mac mojave

### ISSUE THREAD

**Issue by eebzla** [quicksilver/Quicksilver#2517]
when trying to paste from stored clipboard contents, nothing happens, 
when trying to add QS to Full Disc Access, it asks to quit QS, but nothing else happens when trying to add,
I have QS ver. 1.6.0
Mac OS Mojave 10.14..6

I have been asked to grant permissions for other apps, like iTunes etc, and when viewing privacy in systems preferences, i can see QS is allowed for contacts and reminders, but can't seem to add it to Accessibility and Full Disc Access\
the only message is asking to quit QS, but it still won't appear in this area

could this be a app permissions error? i have it set to Read & Write

<img width="666" alt="Screenshot 2020-04-11 at 8 31 35 am" src="https://user-images.githubusercontent.com/63491273/79038139-df6a8180-7bce-11ea-8a04-e62d62e712dd.png">

**Comment by skurfer** [comment]
I'm not sure what all you've tried, but try quitting Quicksilver, then dragging it from Finder to the Full Disk Access and Accessibility lists, then start it again.

**Comment by eebzla** [comment]
Hi, thanks for looking into this, i have tried dragging the app over, and still get the same result, 
the Full Disk Access panel remains blank when i try to drag or add anything into it,

i've just tried to use the mail plugin (compose email) and it asked me to approve access, but i can't seem to re-create this permission when trying to paste from clipboard/shelf for the first time

**Comment by skurfer** [comment]
You could try resetting all the prompts with something like `tccutil reset All com.blacktree.Quicksilver`, but I think you should be able to add things manually with or without the prompts.

I don’t think it will ever prompt for Full Disk Access, though. I think all apps have to be manually added to that one. Are you able to give any other apps full disk access?

**Comment by eebzla** [comment]
I've tried adding other apps to Full Disk Access, but that doesn't seem to work either,
Same message about quitting the app first, but nothing after that,
I had tried resetting Full Disk Access before with another terminal line previously, but that hasn't helped

**Comment by pjrobertson** [comment]
These are my security settings on Mojave. Quicksilver should not require 'Full Disk Access', only 'Accessibility' access.

![accessibility requirements mojave](https://user-images.githubusercontent.com/150431/150704908-db000e0b-c7dd-40a9-96be-414aebfe60dc.png)


Can you walk through the exact steps you're taking to 'paste from the clipboard'. How are you doing this? Does copy/pasting work, or dragging from the clipboard, or double clicking?

**Comment by pjrobertson** [comment]
Hi @eebzla - if you're still having this issue, please feel free to re-open this, or create a new issue. I will mark it as 'fixed' for now, short of hearing more from you.
