### ISSUE TITLE
The proxy Current Document appears to have disappeared

### ISSUE THREAD

**Issue by Jickeymoe** [quicksilver/Quicksilver#2518]
The Proxy Current Document appears to have gone missing. And when I check Catalog/Quicksilver/Proxy Objects and info it lists 32 proxy objects but Current Document is not there.

**Comment by skurfer** [comment]
Current Document isn’t part of the core plug-in. It comes from [the User Interface plug-in][1]. Do you have it installed and enabled?

[1]: https://qsapp.com/manual/plugins/uiaccess/

**Comment by Jickeymoe** [comment]
I have now installed the User interface plug-in and the Current Document functionality is now working again. Thank you for taking the time to post this clarification.

**Comment by skurfer** [comment]
No problem.
