### ISSUE TITLE
Will there be a 1.6.1 binary download?

### ISSUE THREAD

**Issue by TravellerSam** [quicksilver/Quicksilver#2519]
It'll be very nice to be able to download the 1.6.1 version compiled at https://qsapp.com/download.php

Many thanks!

**Comment by skurfer** [comment]
I can’t get Gatekeeper to accept any recent builds, but I'm probably going to just release with or without that eventually. I’m just waiting until #2511 is fixed.

**Comment by TravellerSam** [comment]
I'm still on Mojave 10.14.6 (and no intention to upgrade yet), the above mentioned crash doesn't happen on my installation, so I can't confirm it. 
Wouldn't it be more sensible to release normally and issue 1.6.2 when that bug is corrected?

BTW, is there a changelog for the versions?

**Comment by skurfer** [comment]
https://github.com/quicksilver/Quicksilver/blob/master/Quicksilver/SharedSupport/CHANGELOG

**Comment by bhyde** [comment]
If or when there is a binary for 1.6.1 will that resolved the crash'n I'm getting on Catalina?

**Comment by skurfer** [comment]
> If or when there is a binary for 1.6.1 will that resolved the crash'n I'm getting on Catalina?

Probably. It specifically fixes a few Catalina crashes.
