### ISSUE TITLE
"Failed to Extract Plugin" downloading version 1.6.1

### ISSUE THREAD

**Issue by GianMarco-Tavazzani** [quicksilver/Quicksilver#2523]
"There was a problem extracting the QSPkg.
The file is most likely corrupt."
High Sierra, 1.6.0 works flawlessly

**Comment by skurfer** [comment]
Sorry about that. The update system seems to have treated it like a plug-in instead of an application update. You could have renamed the `.qspkg` to `.dmg`, but there’s no way to know that. Anyway, it should be fixed on the site now.
