### ISSUE TITLE
Quicksilver 1.6.1 doesn't launch selected application

### ISSUE THREAD

**Issue by JRichelle** [quicksilver/Quicksilver#2524]
Hi,
I'm a longtime Quicksilver user.  Till today I was happily using version 1.5.9.  I agreed to upgrade to 1.6.1. This new version allows me to select any application, but at hitting the return key or clicking an application in the list, nothing happens.
I have a MacBook Pro running under MacOS 10.11.6.
I reinstalled v. 1.5.9 and it works (back) as expected and correctly.
Best regards,
Jean

**Comment by skurfer** [comment]
I thought we had fixed the one incompatibility with 10.11 (see #2460), but maybe there’s something else.

I’ve changed the rules in the update system. If you go back to 1.5.9, it should stop telling you there’s an update. (Maybe this isn’t ideal, but we generally only try to support the two most recent versions of macOS.)
