### ISSUE TITLE
Strange character in Info.plist file causes problems with packaging automation

### ISSUE THREAD

**Issue by grahampugh** [quicksilver/Quicksilver#2527]
**Describe the bug**
There is a strange character in the `Info.plist` file of Quicksilver.app, on line 220. the string appears empty in some editors, but when pasted into GitHub, the non-printable character appears:

```xml
			<key>NSKeyEquivalent</key>
			<dict>
				<key>default</key>
				<string>�</string>
			</dict>
```

Unfortunately, this character causes parsing of the plist file using python's `plistlib` module to fail.

This causes the AutoPkg recipe which packages up Quicksilver for import into Mac software enterprise management tools such as Jamf Pro and Munki to fail. See https://github.com/autopkg/homebysix-recipes/issues/297 for more details. 

For information, [AutoPkg](https://github.com/autopkg/autopkg) is the most-used solution for automating Mac software management in the enterprise. 

I assume this `�` character is an unseen artefact not required for the software to run, and could be safely removed? 

**To Reproduce**
1. Install python 3 on a Mac.
2. Download and mount the Quicksilver 1.6.1 installer DMG
3. Run `python3`.
4. Run the following commands to induce the error:

```
>>> import os.path
>>> import plistlib
>>> app = '/Volumes/Quicksilver/Quicksilver.app'
>>> plistpath = os.path.join(app, "Contents", "Info.plist")
>>> with open(plistpath, "rb") as f:
...     info = plistlib.load(f)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/plistlib.py", line 950, in load
    return p.parse(fp)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/plistlib.py", line 260, in parse
    self.parser.ParseFile(fileobj)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 220, column 12
```

**Expected behavior**
`plistlib` should be able to read values from `Quicksilver.app/Contents/Info.plist`.

**What version of macOS?**
macOS 10.15.5

**What version of Quicksilver?**
1.6.1

**Comment by skurfer** [comment]
I’d expect that sort of junk from Python 2, but… anyway.

> I assume this � character is an unseen artefact not required for the software to run, and could be safely removed?

It’s the character that represents ⎋ (Escape) where it defines the ⌘⎋ shortcut for the “Get Current Selection” service. So it can’t be removed, but there might be another way to represent it. I’ll take a look. Thanks.

**Comment by grahampugh** [comment]
For info, AutoPkg uses python 3.7 these days.

**Comment by skurfer** [comment]
I think I was able to fix this. Give [this test build][1] a try. It should be identical to the current release, except for that one value in the property list.

It sounds like you might have access to a large number of Macs, so could you do me a favor? Run the test build on a totally clean system and make sure selecting text or a file and hitting ⌘⎋ pulls the selection into Quicksilver? It seems to work on my system, but I want to make sure I’m not benefitting from a cached value somewhere.

[1]: https://qsapp.com/archives/downloads/Quicksilver%201.6.1-esc.dmg

**Comment by grahampugh** [comment]
Hi Rob

Thanks for working on this. Typing Cmd-Esc definitely worked for a selected file (once all the macOS security prompts have been negotiated). 

On selected text in an email, the Cmd-Esc key combination also invoked Quicksilver, but the text was not there. The audible beep that denotes that the operation could not be done was heard before Quicksilver popped up. I’m not normally a Quicksilver user (though it does look cool, I max start!), so I don’t have much experience to know if that is normal.

Cheers
Graham

**Comment by skurfer** [comment]
There are some apps where it doesn’t work, but it sounds like the keystroke was recognized which is the main thing I was worried about. Thanks for checking.

**Comment by grahampugh** [comment]
Are there any plans to release this fix? It would be good to prevent AutoPkg from complaining to me every day :)

**Comment by skurfer** [comment]
Actually, we might need to revert the change I made. I noticed ⌘⎋ wasn’t working reliably lately, and I think I see why.

<img width="536" alt="Screen Shot 2020-09-18 at 9 33 16 AM" src="https://user-images.githubusercontent.com/154676/93603509-17ea6480-f992-11ea-92f3-d4a753936773.png">

So maybe it _was_ cached on my system before.

**Comment by grahampugh** [comment]
This seems to be a specific problem with the `plistlib` module of python. Apple's APIs don't have the problem.

So long as the version printed on the website https://qsapp.com/download.php is always updated and matches the actual application version, I can live with scraping the website to obtain the version.

**Comment by skurfer** [comment]
OK. Sorry I couldn’t be more help. I’m curious about that `Foundation` module. Can you send me a link?
