### ISSUE TITLE
Consistent crashing behavior when typing "tr"

### ISSUE THREAD

**Issue by heumann** [quicksilver/Quicksilver#2529]
**Describe the bug**
When typing in "tr" (without quotes) in order to get to the trash, the application immediately quits.  This behavior is consistent; it has happened every time.  I haven't found other letter combinations that trigger this behavior.  I have rebooted, which solved other issues, but this one persists.

**To Reproduce**
1. Invoke Quicksilver
2. Type the t character, and then the r character.
3. Quicksilver crashes

**Expected behavior**
Quicksilver not to crash, and also show the option to open the trash.

**What version of macOS?**
10.15.5, 2015 Macbook Air

**What version of Quicksilver?**
1.6.1 (4026)

**Comment by heumann** [comment]
Update: my work laptop has all the same settings, except it is macOS version 10.15.4 and is a Macbook Pro, whereas my personal laptop is a Macbook Air.  I'll update when I upgrade the work laptop to 10.15.5 with whether this bug starts there as well.

**Comment by skurfer** [comment]
Hmmm. I have Trash in the catalog and it’s the default result for “tr”, but can you actually do anything with it?

For me the default action is “Get Spotlight Results”, which is usually a clue that QS couldn’t find any useful actions for a thing and is just showing actions that claim to work on anything.

**Comment by heumann** [comment]
Previously I was able to open the Trash folder.  It's not explicitly listed in the catalog, and since ~/.Trash is a hidden folder, it's not an option when adding a new folder to search.

I can't see the default actions as it crashes before it shows any actions.

**Comment by skurfer** [comment]
Do you have a crash report for one of these crashes?

**Comment by heumann** [comment]
I have submitted crash reports as I've encountered this bug.

However, I am no longer experiencing this problem, and I believe the issue to be that the trash contained items from the Relocated Items folder that was left over after an os upgrade.  Attempting to empty the trash would result in several "this item cannot be deleted" messages, and following [these instructions](https://www.gearbest.com/blog/how-to/how-to-remove-the-relocated-items-folder-after-finishing-the-macos-catalina-update-8675) resolved both the problem emptying the trash, and also this crash.

I think this means we can probably close this issue (I'm happy to leave that up to you).  Since I can't get these files back, it'll be tough to recreate the problem, but that does provide a little more information on the nature of the crash.

**Comment by skurfer** [comment]
Those files are named after the computer that submits them. Can you tell me your computer’s name in System Preferences → Sharing? (Feel free to send it to me directly if you don’t want to share it here.)

**Comment by heumann** [comment]
I don't mind.  The computer I'm referencing is named `rowlf`.

**Comment by skurfer** [comment]
The crash is actually coming from one of the proxy objects in the iTunes plug-in. My guess is that typing “tr”, or maybe just “t” was causing QS to resolve either the Currently Playing Track or Random Track proxy objects. I’m not 100% why it’s crashing though. Can you tell me about the state of iTunes at the time? Was it running or not? Do you have an empty library because you never use it? Anything else you can think of? Thanks.

**Comment by heumann** [comment]
iTunes was almost certainly not running.  While I do use it (and therefore my library isn't empty), I tend to keep it closed most of the time.

**Comment by heumann** [comment]
Interestingly, this bug just popped up again.  I've since upgraded to 10.15.6 (19G2021), so iTunes is gone (although I'm sure elements remain).

Once again, invoking Quicksilver and typing "tr" causes a crash.  I no longer have locked items in the Trash, so there goes that theory, but based on the August 8th comment, I tried other letter combinations and found that "tk" also causes a crash as well.

I'm attaching the crash log report, in case that's useful.
[crash_report.txt](https://github.com/quicksilver/Quicksilver/files/5269174/crash_report.txt)

**Comment by skurfer** [comment]
“tk” probably pulls up the same proxy object, causing the same crash. I’ll see if we can guard against it a little better somehow. For now though, you can disable the iTunes plug-in since it won’t do much for you on 10.15.

**Comment by heumann** [comment]
Excellent, that totally avoids the crash.  Thanks, @skurfer!  It's lovely to get such swift responses.

**Comment by pjrobertson** [comment]
Looks like this issue was resolved. Thanks @skurfer !
