### ISSUE TITLE
New Macbook Air blocks install of Quicksilver (Catalina 10.15.6)

### ISSUE THREAD

**Issue by lifelongpatsy** [quicksilver/Quicksilver#2530]
For questions or tech support, please start with the [users’ group][1]. If you know the problem is in Quicksilver itself, report it here.

[1]: https://groups.google.com/forum/#!forum/blacktree-quicksilver

**Describe the bug**
My brand new (7/24/2020 purchase), fully-updated Macbook Air, blocks me from opening the QS app, after repeated attempts w/ fresh downloaded 1.6.1 version (see error below). 

**To Reproduce**
1. Go to 'https://qsapp.com/download.php' 
2. Click on 'downloaded 1.6.1 version, install on mac, click to open Quicksilver, '
3. See error, "“Quicksilver” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information."

**Expected behavior**
I expected he quicksilver app to easily install as it always has in past years. 

**Screenshots**
<img width="418" alt="Screen Shot 2020-07-25 at 12 54 43 PM" src="https://user-images.githubusercontent.com/68787588/88463119-05621c00-ce76-11ea-869b-d218b12f5a48.png">

**What version of macOS?** Catalina 10.15.6

**What version of Quicksilver?** 1.61

**Comment by skurfer** [comment]
That’s probably because code signing stopped working. After messing with it for months, I finally decided to just release so I could get some important updates out. You’ll have to right-click it in Finder and choose “Open” once. After that, it should launch without complaint.

**Comment by lifelongpatsy** [comment]
Thanks! That worked. Good to have my favorite app back.
