### ISSUE TITLE
Firefox plugin > Erro: Unable to locate session store file for firefox

### ISSUE THREAD

**Issue by damionx7** [quicksilver/Quicksilver#2531]
the firefox plugin for quicksilver doesnt import history or bookmarks and i have this error in my notification center.

<img width="316" alt="Screenshot 2020-07-31 at 11 07 52 AM" src="https://user-images.githubusercontent.com/6530843/89003694-fbb23b80-d2ef-11ea-8b4f-3345cf92f24a.png">

**Comment by damionx7** [comment]
this is the error i am getting in console 
`Jul 31 07:45:38 mac Quicksilver[2757]: Error while reading Firefox's places.sqlite DB. Error 11: malformed database schema (moz_meta) - near "WITHOUT": syntax error`

**Comment by skurfer** [comment]
They must have changed the layout in the database. Someone will need to update the plug-in. Until then, you could disable the Catalog preset from the plug-in and try [scanning the bookmarks from a file][1] instead.

[1]: https://github.com/quicksilver/Quicksilver/issues/2407#issuecomment-649492374

**Comment by pjrobertson** [comment]
The Firefox plugin has been updated to fix this issue. Please keep an eye out for an updated Firefox plugin from within Quicksilver.

Thank you for reporting the issue, @damionx7 !
