### ISSUE TITLE
OS Catalina vs Quicksilver

### ISSUE THREAD

**Issue by Writer75** [quicksilver/Quicksilver#2532]
Hi there, downloaded Quicksilver today and get this message:

“Quicksilver” can’t be opened because Apple cannot check it for malicious software.

Any tips / ideas?

Thank you! 😀

**Comment by skurfer** [comment]
It’s because we couldn’t get the code signing to work in recent versions of Xcode. This delayed releases for over a year, so I finally gave up and released it as-is. If you right-click it in Finder and choose “Open”, you’ll be able to run it. (You only need to do that once.)

**Comment by Writer75** [comment]
Thanks for coming back to me on this Rob - much appreciated. Have
downloaded. 😀👌🏾

Arani.
