### ISSUE TITLE
Open does not show all finder windows when extra setting is set 1.6.1

### ISSUE THREAD

**Issue by whoisdecoy** [quicksilver/Quicksilver#2539]
**Describe the bug**
Recently upgraded to Quicksilver 1.6.1. After upgrading I am no longer able to show all Finder windows with a trigger. Reverted to 1.6.0 and am able to show all windows again.

**To Reproduce**
In 1.6.1, UNable to show all windows with action "open", "activate", or "toggle".
In 1.6.0, ABLE to show all windows with "activate" or "toggle".

Extra setting: "reopening the current application" set to "show all windows"

**Expected behavior**
Show all finder windows.

**What version of macOS?**
10.15.5
**What version of Quicksilver?**
1.6.1

**Comment by skurfer** [comment]
I can reproduce this, but I can’t explain it. There were some changes to the code that handles that behavior between 1.6.0 and 1.6.1, _but_ that code is never used in either version. Still looking into it.

**Comment by skurfer** [comment]
I managed to hack something together just to force QS to run the code from the new API that includes `NSApplicationActivateAllWindows`, and it unfortunately does _not_ bring all windows forward. That seems like an OS bug.

FYI, it looks like the code in question that reads that “Reopening the current application” setting was created as a separate “Switch to Application” action that was never added to the UI. It never had any effect on the “Open” action.

**Comment by whoisdecoy** [comment]
What OS version are you on? What is being called if 1.6.0, that differs and allows it to work? 

Yes, it doesn't seem to affect "open" action in 1.6.0. Am I referencing the correct setting from this:

"The actions above, Open, Hide, Activate, and Toggle Application work on the whole application, including all of its windows. There’s no way with Quicksilver to show or hide specific (i.e., document) windows of an application. **The closest is that the Application reopen behavior option in the Extras Preferences allows Open to show the front window or show all windows instead of doing Activate**."

**Comment by skurfer** [comment]
> What OS version are you on?

10.15, but I’ve mostly been experimenting in a VM running 10.13.

> What is being called if 1.6.0, that differs and allows it to work?

1.6.0 was using an older deprecated API (see #2500), which I assume works, but there’s nowhere in QS that calls either the old code or the new code, so I don’t know why it would matter.

> Yes, it doesn't seem to affect "open" action in 1.6.0.

So what action are you using that _does_ work? Toggle?

**Comment by whoisdecoy** [comment]
Toggle and activate both work to bring up all open finder windows in 1.6.0

**Comment by skurfer** [comment]
I’ve done some experimentation and I can get it to bing all windows forward _once_, but then it stops. I’m inclined to incorporate these changes into the app and hope for the best. The fact that it works once makes me think the code must be right. The inconsistency could be a bug in the OS, or the intended behavior.

**Comment by skurfer** [comment]
I was going to reach out to the developer of [Front and Center](https://apps.apple.com/us/app/front-and-center/id1493996622), knowing that he must be familiar with the new API, but I think I already see his answer. Look at the response to the comment “works until it doesn’t”. Sounds like it’s just buggy. 😕 And of course the old API they’re killing off works perfectly every time.
