### ISSUE TITLE
Prompt window missing after some time in Catalina 10.15.7

### ISSUE THREAD

**Issue by ganar** [quicksilver/Quicksilver#2540]
[1]: https://groups.google.com/forum/#!forum/blacktree-quicksilver

**Describe the bug**
Upon working for some time the Quicksilver prompt key won't work when pressed. The program still works – it can be brought forward in the dock– but the prompt window will not appear until the program is quit and launched again.

**To Reproduce**
1. My Quicksilver instance is programed to work when the "home" key is pressed
2. upon clicking the activation key, the prompt window does not appear
3. Quitting and opening quicksilver makes it work again

**Expected behavior**

**Screenshots**

**What version of macOS?** 
Catalina 10.15.7

**What version of Quicksilver?** 
1.6.1

**Comment by skurfer** [comment]
Which interface do you use? (Look in Preferences → General → Appearance)

I’ve seen a few menu bar apps that won’t show anything when clicked until you “launch” them again. (You don’t have to restart, just use Quicksilver or Finder to activate it.) I wonder if something similar is happening here.

Are you able to use it even though you can’t see it? You could try using Quicksilver to relaunch itself if so.

I doubt it’s related, but you could try Turing off Quicksilver’s dock icon. I think it’s a generally nicer experience, even if it doesn’t fix this issue.

**Comment by ganar** [comment]
>Which interface do you use? (Look in Preferences → General → Appearance)

![Screen Shot 2020-11-26 at 13 21 40](https://user-images.githubusercontent.com/431185/100374078-80853b80-2fea-11eb-91b9-3edff45bb055.png)
I use the default interface

>Are you able to use it even though you can’t see it? You could try using Quicksilver to relaunch itself if so.

I was able to launch a program without seeing the pop-up window, but that does not work well.

>I doubt it’s related, but you could try Turing off Quicksilver’s dock icon. I think it’s a generally nicer experience, even if it doesn’t fix this issue.

If I do that, it will be harder for me to quit the app when this problems happens again

**Comment by skurfer** [comment]
>> I doubt it’s related, but you could try Turing off Quicksilver’s dock icon. I think it’s a generally nicer experience, even if it doesn’t fix this issue.
> 
> If I do that, it will be harder for me to quit the app when this problems happens again

Oh, you’ll want to enable the icon in the menu bar, if it’s not already on.

**Comment by ganar** [comment]
I found a way to solve the issue: switching the interface to `Bezel` allowed me to be able to trigger Quicksilver with the keyboard again.

**Comment by KrisShannon** [comment]
I've been having the exact same issue.

I use the Nostromo interface and I am also still on macOS Catalina (10.15.7)

I've found that if I open the preferences (⌘-,) and then also use the keyboard shortcut trigger I have to show the clipboard, after both of these windows are showing the shortcut works again to show/hide the interface.

I can then close both the clipboard and preferences windows and the shortcut continues to work;  at least until whatever causes this issue happens again.

I can also confirm that it's just a visibility issue.  I can type blindly and open up applications etc.

**Comment by skurfer** [comment]
@KrisShannon Do you have the Dock icon enabled? I’m wondering what combination of settings causes this.

**Comment by KrisShannon** [comment]
Yes I do

**Comment by KrisShannon** [comment]
Other possible factors I can think of that might have an effect:
- Using multiple virtual desktops
- Normally have laptop connected to an external monitor
- Using window arrangement app called [Moom](https://manytricks.com/moom/)

**Comment by pjrobertson** [comment]
Hi everyone,

We have just release version 2.0 of Quicksilver, which has a lot of fixes for later versions of macOS. Please download that, and if you're still experiencing the problem then you can re-open this issue.

I will mark this as closed for now
