### ISSUE TITLE
Big Sur Icon

### ISSUE THREAD

**Issue by lgarron** [quicksilver/Quicksilver#2542]
Copied from [a mailing list email](https://groups.google.com/g/blacktree-quicksilver/c/QQ8t1RtM4nU).

Now that Big Sur is out, iOS-style rounded squares are the new icon style:
https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/
https://developer.apple.com/design/resources/#macos-apps

I haven't seen an updated icon for Quicksilver, so I thought I'd take a stab at it:

<img width="256" alt="icon_512x512@2x" src="https://user-images.githubusercontent.com/248078/100526492-3339d300-317e-11eb-86e6-5f8f497f4a63.png">

In context with the Big Sur dock (with the old icon on the right for comparison):

<img width="392" alt="Screen Shot 2020-11-28 at 1 55 50 AM" src="https://user-images.githubusercontent.com/248078/100526493-3634c380-317e-11eb-8cf1-aaa3970f2529.png">

I tried to match the outer guides of macOS icon template while keeping as much of the original icon shape as possible:

<img width="256" alt="Screen Shot 2020-11-28 at 01 43 04" src="https://user-images.githubusercontent.com/248078/100526490-2d43f200-317e-11eb-8ac3-fcaca06b4133.png">

If I can get a signal in this issue from a core developer that this is a good direction, I'd be happy to pixel-tweak the full range of resolutions and send a PR to replace https://github.com/quicksilver/Quicksilver/blob/master/Quicksilver/Resources/Images/Quicksilver.icns !

**Comment by skurfer** [comment]
> If I can get a signal in this issue from a core developer that this is a good direction, I'd be happy to pixel-tweak the full range of resolutions

Yeah, go for it. I’d love to have an updated icon. From the outside, it might look silly to have an updated icon when there are so many more important UI issues, but I’ll still do it. 🤪

**Comment by lgarron** [comment]
Sent!

> From the outside, it might look silly to have an updated icon when there are so many more important UI issues, but I’ll still do it. 🤪

It *is* the most conspicuous visual part of the app, though. :-P
Perhaps it'll look so shiny and new that it papers over the rest a bit. ;-)
