### ISSUE TITLE
On Big Sur, my triggers (keyboard shortcuts) stopped working

### ISSUE THREAD

**Issue by captainmacnl** [quicksilver/Quicksilver#2545]
I have tried adding Quicksilver to the Security&Privacy SystemPreferences-pane, adding it under Input Monitoring (it was already added to Full Disk Access, Files and Folders, Accessibility [although not to Automation?] ).
I have tried restarting Quicksilver, rebooting, but absolutely no reaction.

An example of a trigger that i use often is to trigger a search from text that i have selected. The trigger uses the selected text and does a search on a database that i have to check like 20 times a day, so this would help a lot in my workflow.

I have been using QS from the start and am refusing to go with any other utility because i love it.
But this really needs to be fixed!
Thanks.

**Comment by skurfer** [comment]
I’ve never used (or even noticed) Input Monitoring and triggers are working fine for me.

I suppose the first thing I would check is that you have the current version (1.6.1). If you’ve been using it from the start, I know there were at least two versions where the auto-updates broke, so a lot of people are running old copies.

**Comment by juanfal** [comment]
They have been working for me since first beta of Big Sur, and now on an Air M1.  What is failing, is Clipboard History

**Comment by skurfer** [comment]
Not to hijack this issue, but what about Clipboard history? I have the panel docked to a screen edge and it sometimes gets confused, but other than that, it functions.

**Comment by captainmacnl** [comment]
OK, I have no idea why I hadn't tried reinstalling the app yet.. *facepalm*
Everything works now! YAY I'm so glad i can still be using this amazing tool!!

**Comment by captainmacnl** [comment]
OK. So i realised that all my triggers work, EXCEPT the one i use most: the 'find with' trigger, which i use to search a website.
I have even fully uninstalled quicksilver and all its preferences, reinstalled everything, but same result.

I've got the trigger setup in the following way:

Select an item:
 Current Selection
Action:
 Find With...
Target:
 The website address with a search query where i have it end in *** to be replaced with the current selected text.

Somehow, this trigger won't do anything.
All the other triggers do work.
It's independent of what key combo i assign it to.
If i set the trigger to 'Show Window' when triggered, it does show that quicksilver tries to do something, but nothing actually happens..
I have also tried setting up a new trigger with as basic a setting as any (ie: using the standard https://www.google.com/search?q=*** )
but still no dice

Anyone can help out?

**Comment by skurfer** [comment]
If you just call up “Current Selection” in Quicksilver, does it grab the expected thing? If not, I would re-check the access it has under Accessibility and Automation.

**Comment by captainmacnl** [comment]
no, it does not. But it has access under the syspref-pane..

**Comment by captainmacnl** [comment]
OK, so i figured out it does work in the Finder. In System preferences under Automation, that is the only application thats listed as being accessible to Quicksilver. There is no way to manually add other Apps.
seems that is the problem i guess??
![Screenshot 2020-12-11 at 09 55 10](https://user-images.githubusercontent.com/75302802/101883037-fa92f400-3b96-11eb-93a2-61c355c7325f.png)

**Comment by skurfer** [comment]
> There is no way to manually add other Apps.

I think this is the same as it has been since 10.14: It will ask you if you want to allow Apple Events from Quicksilver to another application. The alert might appear **behind** Quicksilver. If you don’t answer in 30 seconds, the system assumes “No” and never asks you again.

See https://qsapp.com/manual/FAQ/#actions-fail-on-mojave-or-later

I haven’t revisited the topic in a while, so you should check around for tips. I think it might be possible to do more fine-grained things with `tccutil`, so check that as well before resetting everything with brute force.

**Comment by pjrobertson** [comment]
So this appears to be an issue with either:
a) the 'get current selection' trigger not working; or
b) Quicksilver requesting permission, but not being authorized in time.

Are these things that we can change, or are we at the mercy of the OS?

We have #2646 related to the current selection action. Can we close this?

**Comment by skurfer** [comment]
We’re at the mercy of the OS for most of it. I know getting the selection was working when this issue was created. Not so sure now, but I need to do more testing.

**Comment by pjrobertson** [comment]
I've been getting intermittent problems because of 'Security' settings recently. The way that I solve this is by 'removing' the 'Quicksilver' entry from the Accessibility pane, and then dragging `Quicksilver.app` (from my /Applications folder) back into this pane. That seems to reset permissions for me.

![Screenshot 2022-02-23 at 11 17 56](https://user-images.githubusercontent.com/150431/155256444-13ef5076-f7f5-44ff-8279-836bfc6e5191.png)


@captainmacnl - could you try that and see if it solves your problem?

**Comment by debugDS** [comment]
By the way, I had to add Quicksilver also to **Input Monitoring** for Triggers to work.

**Comment by pjrobertson** [comment]
@debugDS - can you take a screenshot of where you changed these settings? I'm not aware of this, but it could be a newer macOS thing.

We may need to explicitly allow this permission in Quicksilver to make triggers work by default.

Thanks

**Comment by debugDS** [comment]
My system is in french but i'm sure you can find your way.

<img width="893" alt="InputMonitoring" src="https://user-images.githubusercontent.com/1036368/159999517-2a82f2ed-d3c2-442a-b116-a25eb2b0bd31.png">

**Comment by pjrobertson** [comment]
Ça marche, merci! :)

I've created a new issue here: #2684 specifically regarding this 'Input Monitoring' issue. I'll close this issue and keep that one open.

Quicksilver 2.0 will released within the next 24 which should fix the majority of issues as outlined in this post. A fix for not having to manually enable 'Input Monitoring' will be in Quicksilver 2.1.
