### ISSUE TITLE
blog.qsapp.com appears to have been taken over by someone who is not even making a token effort to forward the principle of wu wei through Mac software

### ISSUE THREAD

**Issue by everdred** [quicksilver/Quicksilver#2546]
[https://blog.qsapp.com/](https://blog.qsapp.com/)

**Comment by skurfer** [comment]
I don’t think anything nefarious is going on. I assume the account got shut down and Tumblr’s DNS is just showing another page.

I’ve removed the links from the qsapp.com site.

**Comment by everdred** [comment]
Figured it was something like that; it seemed disused. Cheers!
