### ISSUE TITLE
Can't group triggers into folders

### ISSUE THREAD

**Issue by usizu** [quicksilver/Quicksilver#2547]
**Describe the bug**
On the Triggers window, after creating a Group, it is not possible to drag triggers into the Group folder. Nothing happens if you do that and the dragged trigger doesn't move into the folder.

**To Reproduce**
1. Go to Triggers
2. Click on + in the bottom left and create a new Group
3. Drag a Trigger onto the icon of the new Group folder
4. See that the Trigger hasn't been added to the folder which remains empty.

**Expected behavior**
It is expected that the Trigger be listed inside the Group folder after dragging it there

**Screenshots**
n/a

**What version of macOS?**
10.14.6
**What version of Quicksilver?**
1.6.1 (4026)

**Comment by skurfer** [comment]
This is a known issue. See #135
