### ISSUE TITLE
Crash in NSViewSendViewWillDrawToSubviews

### ISSUE THREAD

**Issue by jacob-carlborg** [quicksilver/Quicksilver#2548]
**Describe the bug**

Quicksilver crashes very often. It always crashes in the background, never when Quicksilver is the active application. When I press the global hotkey nothing happens because Quicksilver has crashed.

The crash report, which is produced, reports that the last two calls in the carshing threads are to `NSViewSendViewWillDrawToSubviews` and then `objc_msgSend`.

The frequency of the crashes has increased significantly since I upgraded to macOS Big Sur. It's at a point where the application is barely usable.

**To Reproduce**

I don't know how to reproduce it.

**Expected behavior**

Quicksilver should not crash.

**What version of macOS?**

macOS Version 11.1 (20C69)

**What version of Quicksilver?**

1.5.4 (401F)

I've attached a crashlog: [Quicksilver_NSViewSendViewWillDrawToSubviews.txt](https://github.com/quicksilver/Quicksilver/files/5871649/Quicksilver_NSViewSendViewWillDrawToSubviews.txt).

**Comment by skurfer** [comment]
The current version (1.6.1) fixes a few crashes we were seeing on 10.15+. Please try it out.

https://qsapp.com/download.php

**Comment by jacob-carlborg** [comment]
Thanks, I'll give that a try. I thought I was already running the latest version. I will check more carefully next time.

**Comment by skurfer** [comment]
Not your fault. The update system has broken a couple of times, so a lot of people have missed the releases that came after.

**Comment by pjrobertson** [comment]
@jacob-carlborg  - did 1.6.1 fix this for you?

**Comment by jacob-carlborg** [comment]
I can't recall the last time quicksilver crashed. I use it every day, so I assume it's fixed.

**Comment by pjrobertson** [comment]
Good to hear! Thanks for the update Jacob :)
