### ISSUE TITLE
Crash due to NSRunInformationalAlertPanel in non-main thread

### ISSUE THREAD

**Issue by jacob-carlborg** [quicksilver/Quicksilver#2549]
**Describe the bug**

Quicksilver crashes due to `NSRunInformationalAlertPanel` being called on a thread which is not the main thread. See attached crashlog.

https://github.com/quicksilver/Quicksilver/issues/2548 might be related.

**To Reproduce**

I don't know how to reproduce it.

**Expected behavior**

Quicksilver should not crash.

**What version of macOS?**

macOS Version 11.1 (20C69)

**What version of Quicksilver?**

1.5.4 (401F)

I've attached a crashlog: [Quicksilver_NSGenericException.txt](https://github.com/quicksilver/Quicksilver/files/5871667/Quicksilver_NSGenericException.txt)

**Comment by skurfer** [comment]
The current version (1.6.1) fixes a few crashes we were seeing on 10.15+. Please try it out.

https://qsapp.com/download.php

**Comment by pjrobertson** [comment]
The attached crash-log content is identical to #2548 - closing this one in favour of that.
