### ISSUE TITLE
Plugins not Appearing

### ISSUE THREAD

**Issue by lwb52** [quicksilver/Quicksilver#2552]
v.1.6.1 on Mojave 10.14.6:
very few older plugins (like ”Calculator") appear when selected (”Shelf” does work), and also not appearing are the new ”Networking” & ”Zoom" Plugins

**Comment by skurfer** [comment]
What do you mean when you say they aren’t “appearing”? They aren’t loading, or they aren’t even listed in the preferences?

If they aren’t loading, there should be an explanation under **Status** on the plug-in’s info panel.

**Comment by lwb52** [comment]
I have quite a few enabled:
![Screen- 2021-02-18 at 10 36 16 AM](https://user-images.githubusercontent.com/22728371/108405478-f9ed8e00-71d5-11eb-8038-f54a4ed497db.jpg)
the status of all but 1 is all ”loaded”—only the Mail plugin shows an error:
![Screen- 2021-02-18 at 10 39 35 AM](https://user-images.githubusercontent.com/22728371/108405705-43d67400-71d6-11eb-9837-acbf57723518.jpg)
but only 2 show up under the Plugin menu item:
![Screen- 2021-02-18 at 10 37 04 AM](https://user-images.githubusercontent.com/22728371/108405727-4df87280-71d6-11eb-81c6-da2b12c0445e.jpg)

**Comment by skurfer** [comment]
The Mail plug-in depends on the E-mail Support plug-in. Make sure that’s installed and enabled.

The Plugins menu only shows items that provide additional keyboard shortcuts. The two you’re showing are the only two that have ever appeared on that menu.

**Comment by lwb52** [comment]
thank you, good sir!
