### ISSUE TITLE
Bezel interface with "Bezels are glass" does not show up properly in 11.2

### ISSUE THREAD

**Issue by Proggie** [quicksilver/Quicksilver#2553]
Bezel interface with the transparent "bezels are glass" option does not show properly in MacOS 11.2
<img width="410" alt="QSbezel" src="https://user-images.githubusercontent.com/2626514/108614139-0f68e080-73ad-11eb-87d8-e49868c5809d.png">

**Comment by pjrobertson** [comment]
This is similar to issues we're seeing in #2537. I think our solution will be to remove the 'Bezels are glass' option entirely.

Please continue the discussion over at #2537 if you have more details.
