### ISSUE TITLE
@lovequicksilver Twitter account suspended

### ISSUE THREAD

**Issue by Diggory** [quicksilver/Quicksilver#2554]
@lovequicksilver is suspended on Twitter (https://twitter.com/lovequicksilver)

I'm not sure what you did to get banned, but maybe make a new handle or remove the link on the website (https://qsapp.com)

Thanks.

**Comment by skurfer** [comment]
That was run by @philostein, so maybe he can take a look. I had the password at one point, but wasn’t able to access it last time I tried. I think it may have been taken over by bad guys, which would explain the suspension.

Unless Phil chimes in soon, I think we should just remove the references from the site.

**Comment by n8henrie** [comment]
Just opened an issue with Twitter support, I'll let you know what they say. I'm guess that if anything they'll issue a password reset to @philostein.

**Comment by n8henrie** [comment]
> Twitter
> Hello, 
> 
> Sorry that you’re having this issue. The next best step is to take the following action(s) to secure and/or access your account: 
> 
> If you’re able to log in, follow these steps. 
> 
> If you can’t log in, please try resetting your password. If you’re not able to reset, and you filed this ticket using the email associated with your account, please reply to this message with the following information: 
> 
>     Your username
>     Any email addresses that may be associated with your account 
>     The last date you had access to your account
>     The phone number associated with the account (if you verified your phone number) 
> 
> Once we receive these details, we’ll be able to assist further. 
> 
> Thanks, 
> 
> Twitter

**Comment by skurfer** [comment]
I’ve disabled the link on the Support page for now. Hopefully Phil will poke his head up eventually.

**Comment by pjrobertson** [comment]
I tried re-activating the Twitter account, but don't know the email address. I think only @philostein has that. Hopefully he'll turn up and can provide either:

a) the email address used to sign up
b) log in and get things working again.

In the meantime, we have @quicksilverapp on Twitter which is still alive and could be used as an alternative. Although I'd prefer to keep @lovequicksilver as it has a greater following

**Comment by n8henrie** [comment]
Given recent changes to the platform, I vote we let this one go.
