### ISSUE TITLE
Big Sur "Apple cannot check it for malicious software"

### ISSUE THREAD

**Issue by lcuff** [quicksilver/Quicksilver#2555]
With Big Sur installed, (version 11.2.1) I downloaded the newest version of Quicksilver (1.6.1).  Trying to launch results in the dialog "can't be opened because Apple cannot check it for malicious software".  Followed by "This software needs to be updated."
<img width="241" alt="Quciksilver dialog" src="https://user-images.githubusercontent.com/4588269/109911730-6f8a3d00-7c5f-11eb-9dbe-68ba44879d6e.png">

**Comment by skurfer** [comment]
Code signing broke a couple of years ago. It should be safe to open.

(Right-click it and choose “Open” to allow it to run anyway. You only need to do this once.)

**Comment by kconner** [comment]
At least as of macOS 11.2.3, version 1.6.1 as downloaded from qsapp.com won't open even with right-click and Open. The error is no different. What does work is to strip the quarantine metadata entry so Gatekeeper no longer flags it as downloaded code.

```
xattr -d com.apple.quarantine Quicksilver.app
```

**Comment by kajala** [comment]
> xattr -d com.apple.quarantine Quicksilver.app

Got error "App not found" (Launchpad shows Quicksilver.app though)

**Comment by finisi** [comment]
Just disable the Gatekeeper to run any unsigned software.
To disable to allow apps from anywhere to be installed use the following command in terminal ::

    sudo spctl --master-disable

To re-enable use the following command

    sudo spctl --master-enable

**Comment by skurfer** [comment]
> Got error "App not found" (Launchpad shows Quicksilver.app though)

@kajala I haven’t tried this, but I Assume you need to `cd /Applications` first, or specify the whole path in the command: `/Applications/Quicksilver.app`

**Comment by kajala** [comment]
Thanks the `xattr -d com.apple.quarantine /Applications/Quicksilver.app` worked!

**Comment by radiospiel** [comment]
BTW: Besides CLI shanannigans one can also do the following:

1. download
2. doubleclick to start, macOS will complain
3. Open System Preferences, go to Security & Privacy > General, this should now show a checkbox allowing to run Quicksilver. ("Open Anyway")

**Comment by DaveEveritt** [comment]
> This might be a useful addition to the installation guide

 I'm on Monterey, obvs same issue.

To head off new issues about signing I updated the actual [Quicksilver download page](https://github.com/quicksilver/QSApp.com/pulls) to mention the "ctrl-click -> security dialog; open button" method and sent a pull request. I'll do similar for the installation guide repo and add a mention of install with Homebrew.

**Comment by DaveEveritt** [comment]
Clarification:

> (Right-click it and choose “Open” to allow it to run anyway. You only need to do this once.)

You need to ctrl- or right-click (if you've set that up) the app, choose "open" from the contextual menu, **then choose the extra "open" button** that now appears in the warning dialog box—only needs doing once. (BTW I'm on Monterey)

**Comment by gliptak** [comment]
Dialog/option might not be available in (corporate) more restricted environments.

**Comment by pjrobertson** [comment]
I'm going to close this issue, and open a new issue at #2654 so we can better keep track of exactly what needs doing.

For those following this issue, you may continue to follow #2654. Our goal is to have this issue fixed for the next version of Quicksilver.

Thanks for all the reports everyone!
