### ISSUE TITLE
Domains added to Custom "Web Search List" Don't show up in "Find With..." Pane

### ISSUE THREAD

**Issue by entreprenewer** [quicksilver/Quicksilver#2558]
For questions or tech support, please start with the [users’ group][1]. If you know the problem is in Quicksilver itself, report it here.

[1]: https://groups.google.com/forum/#!forum/blacktree-quicksilver

**Describe the bug**
I've added a few domains I want to be able to search with to a Web Search List in "Custom" as instructed by the plugin docs. They do not appear in the "Find With" 3rd pane, even after refreshing/indexing, quitting quicksilver, etc. 

**To Reproduce**
1. Add a Web Search List by clicking + on the Catalog options for Web Search
2. Add some domains
3. Click the Refresh to index those new domains
4. Type a custom string of text using . window
5. Tab over and choose "Find With"
6. Search for the name of the new domain you've added

**Expected behavior**
The new domains should be there as an options for finding with.

Interestingly, the new domains show if you search for them in the FIRST pane, but not the third. 

**Screenshots**
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/1540530/115138977-12442280-a038-11eb-83c9-568f538fe76d.png">

<img width="747" alt="image" src="https://user-images.githubusercontent.com/1540530/115138986-1d974e00-a038-11eb-8161-d6082ab3568f.png">

**What version of macOS?**
Big Sur 11.1 (20C69)

**What version of Quicksilver?**
1.6.1 (40260

**Comment by skurfer** [comment]
That’s odd. Every web search in my catalog is a custom one and they all appear as expected in the 3rd pane. It’s hard to tell from the screenshot, but do all of your custom search URLs contain `***` where the search term should appear?

**Comment by entreprenewer** [comment]
Nice one, I missed that somehow in the documentation, and as soon as I added it, my custom search domain began working!

Thanks so much for the reply!
JL

--

Jonathan Levi
Founder | SuperHuman Enterprises, LLC.
https://superhumanacademy.com/ <https://superhumanacademy.com/>
P.S. I generally handle emails on Mondays and Thursdays only. Thanks for your patience.
 <http://fb.com/jonathanleviofficial>	 <http://jle.vi/youtube>	 <http://instagram.com/jonathanalevi>	 <http://twitter.com/jonathanalevi>#noauto#
