### ISSUE TITLE
Twitter Plugin only accepts 140 characters (The limit is now 280)

### ISSUE THREAD

**Issue by jonathanalevi** [quicksilver/Quicksilver#2562]
**Describe the bug**
Twitter plugin is limited to 140 characters

**To Reproduce**
1. Attempt to send a tweet that is 141+ characters
2. View error message

**Expected behavior**
Tweet should send, as Twitter allows 280 characters

**Screenshots**
<img width="415" alt="image" src="https://user-images.githubusercontent.com/1540530/120156693-e43b2c00-c1fa-11eb-8d29-e7b93731069e.png">

I've tried to edit the code for the plugin but I can't find where the limit is.

**Comment by skurfer** [comment]
I don’t have the code for that plug-in. Maybe it’s one that @pjrobertson has in a private repo.

**Comment by pjrobertson** [comment]
It’s been a while, but I believe the code is available here: https://github.com/pjrobertson/QSTwit <https://github.com/pjrobertson/QSTwit>

**Comment by entreprenewer** [comment]
Awesome. What do we need to do to update / build it?

**Comment by didaquis** [comment]
I created this PR on the @pjrobertson repo: https://github.com/pjrobertson/QSTwit/pull/2

**Comment by pjrobertson** [comment]
I noted the code is already available under the QS organisation: https://github.com/quicksilver/QSTwit

I've merged your PR @didaquis - thanks for the contribution!

@skurfer - I've pulled the latest changes into the QS repository and renamed to 'Twitter Plugin': https://github.com/quicksilver/Twitter-Plugin Are you able to build and release?

Thanks!

**Comment by entreprenewer** [comment]
wooohhooo! So happy that this is getting done :)

**Comment by skurfer** [comment]
Yeah, I should be able to.

**Comment by didaquis** [comment]
Has the plugin been updated yet?

**Comment by entreprenewer** [comment]
Nope. Can someone push out an update?

**Comment by skurfer** [comment]
The plug-in is pretty out of date. After several changes, there’s still plenty to work through.

<img width="662" alt="Screen Shot 2021-07-07 at 8 50 39 PM" src="https://user-images.githubusercontent.com/154676/124845587-08f69200-df65-11eb-8425-6ac49b94ad81.png">

One thing that will definitely be a road-block though is the missing `ConsumerKey.h`. Can you send that to me privately @pjrobertson ? Thanks.

**Comment by didaquis** [comment]
Is the new version of plugin been released yet?

**Comment by skurfer** [comment]
I still don’t have the key, so there’s not much I can do for now.

**Comment by didaquis** [comment]
Hi, Is there anything we can do to unblock this issue?  🙂

**Comment by skurfer** [comment]
I’ve reached out to Paddy via e-mail. We’ll see.

**Comment by pjrobertson** [comment]
Sorry for the delay guys. I've sent through the ConsumerKey.h file to Rob.
Hopefully you can get this built and the issue fixed!

**Comment by pjrobertson** [comment]
I've fixed up the code, and got the plugin re-building and have pushed the changes to the QSTwitter repository.

@skurfer  - if this builds no problem for you, can you please create a Release build and then publish it on the QS site?

(You may have to do a full clean ⌘⇧K - then re-build the QS project as well to get this working. Without that I was getting errors on YAJL.h not found)

**Comment by pjrobertson** [comment]
This has now been fixed and pushed. Please update to version 1.1.0 of the plugin. Thanks!
