### ISSUE TITLE
QSApp Still Being Developed?

### ISSUE THREAD

**Issue by albert-csms** [quicksilver/Quicksilver#2564]
Is QSApp still being developed? There haven't been any commits or meaningful releases for some time. I'd like to support the app, but only if it's being worked on.

**Comment by skurfer** [comment]
I have no plans to stop working on it (but I have very little time to do so). I can only speak for myself, though. Anyone could contribute in theory.

**Comment by reagle** [comment]
BTW: I've tried to Donate but PayPal says "This organization is currently ineligible to receive donations."

**Comment by Michel91dev** [comment]
Sad to see no more activity on this wonderful app. @skurfer : thank you for keeping an eye on it

**Comment by pjrobertson** [comment]
> BTW: I've tried to Donate but PayPal says "This organization is currently ineligible to receive donations."

Thanks for the heads up on this @reagle - this has now been fixed and donations are once again possible. I unfortunately do not have time to work on development any longer, however Quicksilver is in good hands with @skurfer , and more devs have been getting involved recently.

Donations to the Quicksilver project still help cover costs like Apple Developer license and development software/hardware. Thanks for your support and for looking out for Quicksilver!
