### ISSUE TITLE
“Quicksilver” can’t be opened on macOS Big Sur ver 11.5.1 (see attached image)

### ISSUE THREAD

**Issue by sealilev** [quicksilver/Quicksilver#2565]
“Quicksilver” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.

<img width="257" alt="Screen Shot 2021-08-07 at 6 30 33" src="https://user-images.githubusercontent.com/88569497/128586866-4ce1fd7b-d61b-44f4-be7a-3acd65905d7d.png">

**Comment by n8henrie** [comment]
Duplicate: https://github.com/quicksilver/Quicksilver/issues/2555
