### ISSUE TITLE
Using the emoji palette in text mode steals focus from the current app

### ISSUE THREAD

**Issue by lgarron** [quicksilver/Quicksilver#2566]
**Describe the bug**

Using the emoji palette in text mode steals focus from the current app.

**To Reproduce**
1. Open a text input in any app.
1. Invoke Quicksilver
2. Type `.` to start text input.
3. Enter `⌘^Space` to invoke the `Emoji & Symbols` palette.
  - This dismisses the Quicksilver interface and pops up the emoji palette where the cursor *was*. I'm well aware of that by this point, but I still invoke the emoji palette out of instinct sometimes.
4. Press `Esc` to dismiss the emoji palette.
5. Try to type into the foreground app from step 1.

At this point, QS and the palette have gone, and focus has returned to the foreground app by all regular indications (e.g. the app name remains in the OS menu, the window has foreground styling, the text field cursor remains in place), but the app doesn't receive keyboard input.

The only workaround I know is to click on the app (which sort of defeats the point of QS), or switch completely to another app and back.

**Expected behavior**

The foreground app (which appears to remain in the foreground by all indications) receives keyboard input.

**What version of macOS?**
macOS 11.5

**What version of Quicksilver?**
QS 1.6.1

**Comment by lgarron** [comment]
Also, if the QS interface is open but the text input is *not* invoked (i.e. skip step 3), then focus returns to the app as expected, but the emoji palette remains on screen, unattached.

**Comment by lgarron** [comment]
One workaround I just thought of is to set `⌘^Space` as a trigger for a bogus command, and scope it to Quicksilver. This should prevent the palette from triggering while QS is open. (That means I can't enter emoji into the text mode of the interface, but due to the nature of this bug that was already impossible.)

I'm going to try that out.

**Comment by skurfer** [comment]
There are a few things you can do in QS that get the foreground application into that state, like bringing up the Quick Look panel or running certain actions that touch the UI in some way. (I think in this case, QS still has focus even though there’s nothing left of it on screen.)

I ended up creating a trigger using ⌥⌘⇥ that runs **Previous Application ⇥ Open**, which returns focus to the app you’re looking at.

**Comment by pjrobertson** [comment]
> 4. Enter ⌘^Space to invoke the Emoji & Symbols palette.
> * This dismisses the Quicksilver interface and pops up the emoji palette where the cursor was. I'm well aware of that by this point, but I still invoke the emoji palette out of instinct sometimes.


I don't get this. Quicksilver stays focused and I can type into Quicksilver. 




Can we close this issue, @lgarron ?

https://user-images.githubusercontent.com/150431/161473663-d87f59e2-f8f3-438a-bf9d-a5a52182cc23.mov

**Comment by lgarron** [comment]
> > 7\. Enter ⌘^Space to invoke the Emoji & Symbols palette.
> > 
> > 
> > * This dismisses the Quicksilver interface and pops up the emoji palette where the cursor was. I'm well aware of that by this point, but I still invoke the emoji palette out of instinct sometimes.
> 
> I don't get this. Quicksilver stays focused and I can type into Quicksilver.
> 
> Can we close this issue, @lgarron ?

ooooh, I just tried removing my workaround and things look good! 😻
