### ISSUE TITLE
Publish to Mac App Store

### ISSUE THREAD

**Issue by mcandre** [quicksilver/Quicksilver#2567]
Could we get an entry on the Mac App Store, so that this excellent application is even easier to install?

**Comment by skurfer** [comment]
I’m afraid that isn’t realistic or desirable. There are many rules an application has to follow to get into the App Store and Quicksilver probably breaks just about all of them.

Most notably, applications in the App Store are not allowed to access data from other applications on the system. What would Quicksilver even do without that access?
