### ISSUE TITLE
ENHANCEMENT: Add support text or UI Action to Receiver page to save bind (UUU/DDD Gesture)

### ISSUE THREAD

**Issue by ProjectMockingbird** [quicksilver/Quicksilver#2568]
Currently, the user has to know the UUU/DDD gesture to save bind once they are bound.  This is leading to confusion as there is no indication on the page to have to do that OR button or other UI Action to save bind.

1. Go to Receiver Tab
2. Bind from radio, notice the Save says "no"
3. There is no indication or UI Action to change no to yes

Enhancement:

1. Add text next to the page to say "Use Up, Up, Up, Down, Down, Down on your radio to save"
2. OR add a Save button or other UI Action on the page that changes from disabled to active when the user is bound but hasn't saved.

**Comment by skurfer** [comment]
This is a place to report issues about the macOS software Quicksilver.

I think you might be looking for https://qsradio.com/about-us.html
