### ISSUE TITLE
I want to contribute via GitCoin, let's revive the best launcher ever :)

### ISSUE THREAD

**Issue by logiota** [quicksilver/Quicksilver#2569]
Hi, I have been a huge fan of Quicksilver and it feels like a part of my digital existence at this point, in the very best way.
Nothing compares to Quicksilver and I want to make up for all the years I never contributed by donating a sizeable sum to hopefully get it going again :)
https://gitcoin.co/blog/gitcoin-now-easily-integrates-w-github-chrome-extension-enters-beta/
Thank you so much for these wonderful 15 years either way!

**Comment by logiota** [comment]
Somebody interested?

**Comment by pjrobertson** [comment]
Hi @logiota  - this is a great idea, and a great way to support the Quicksilver community and promote certain issues at the same time.

We currently have a donation page where we receive donations here: https://qsapp.com/donate.php

However, if you would like to use this approach and offer bounties on issues or provide tips to active developers, then please go ahead and do so.

Thanks for your support to the Quicksilver community!
