### ISSUE TITLE
Update internal Python packages and scripts

### ISSUE THREAD

**Issue by skurfer** [quicksilver/Quicksilver#2571]
* Update Markdown, etc. to the latest versions
* Use Python 3 to avoid the warning from Monterey

**Comment by n8henrie** [comment]
I know next to nothing about Obj C*, but I am pretty familiar with bash and
python. I see you've self-assigned here -- is this something I could help
with? Don't want to start a PR and deal with merge conflicts if you've got
something already in progress.

* though I hope to contribute to converting some code to Swift, which I
also imagine will help encourage contributors going forward

>

**Comment by n8henrie** [comment]
#2577

Needs additional work, I'll make a few more pushes.

> The way I got those Python packages into QS was by installing them to a virtualenv with pip, then just copying the resulting folder out of site-packages.

`pip download --no-binary=:all: markdown` gets a `tar.gz` (without the `--no-binary` gives a wheel). I'll see if that works, if not fallback to the site-packages workaround.

**Comment by n8henrie** [comment]
@skurfer How does one run `bltrversion` (and what is it for)?

I'm trying from `Tools/` but there are several unset envvars.

```
PYTHONPATH=./python-support INFOPLIST_FILE=org.quicksilver.plist ./bltrversion 
```

**Comment by n8henrie** [comment]
In the future, it looks like this works for vendoring dependencies:

```console
$ pip download beautifulsoup4
$ find . -maxdepth 1 -name '*.whl' -exec unzip {} \;
$ rm -r ./*.dist-info *.whl
$ python3 -c 'import bs4'
```

NB that this will be a platform-specific compiled wheel if any dependencies are not pure python code.

**Comment by skurfer** [comment]
There’s a pretty good explanation of `bltrversion` in [the plug-in dev reference][1]. It gets run by Xcode against the current project when you build a plug-in.

The packages we’re using should be pure Python and one of them (Markdown) only runs on developer machines.

[1]: https://github.com/quicksilver/PluginDevelopmentReference/blob/master/QuicksilverPlug-inReference.mdown#documentation-and-bltrversion
