### ISSUE TITLE
Can't be opened on mac

### ISSUE THREAD

**Issue by moshfeu** [quicksilver/Quicksilver#2572]
**Describe the bug**

Mac doesn't allow running this app (See the screenshot below)

**To Reproduce**
1. Download the latest version
2. Click on the app icon the run it

**Expected behavior**

**Screenshots**

<img width="265" alt="Screen Shot 2021-11-07 at 9 12 42" src="https://user-images.githubusercontent.com/3723951/140636081-a54ab3a0-eca7-424b-83a0-be474af9d666.png">

**What version of macOS?**

11.3.1

**What version of Quicksilver?**
1.6.1 - Latest

**Comment by n8henrie** [comment]
Duplicate: https://github.com/quicksilver/Quicksilver/issues/2555
