### ISSUE TITLE
FMDB.framework not found during copy phase on Xcode 13.1 on M1 Mac and Monterey

### ISSUE THREAD

**Issue by DivineDominion** [quicksilver/Quicksilver#2578]
When cloning the git repo and opening the project in Xcode 13.1, building the project fails because

> .../Quicksilver/Quicksilver.xcodeproj This Copy Files build phase contains a reference to a missing file 'FMDB.framework'.

It's easily fixed by removing the framework reference and dragging the FMDB.framework build product from the sub-project into the `QuickStep Foundation` framework target again. I just wonder if anyone else is experiencing this, because I see neither open issues nor PRs for this.

(I noticed something like this in another project a while ago where some custom framework path lookups were all of a sudden not necessary anymore. Could be a bug or a feature of Xcode 13?)

**Comment by skurfer** [comment]
Did you get all of the submodules with `git submodule init; git submodule update`?

**Comment by DivineDominion** [comment]
Yeah the code and project references are all there. The expected build product path, though, didn't match Xcode's expectations.

**Comment by skurfer** [comment]
Nothing about this project matches Xcode’s expectations. ☹️

**Comment by DivineDominion** [comment]
@skurfer I shared my changes in PR #2580 so you can see what happens on your device -- if it breaks everything for you, for example. That'd be odd.

**Comment by n8henrie** [comment]
FWIW, I can build from master with no errors using the most recent Xcode, on Monterey, on an M1 Mac.

**Comment by DivineDominion** [comment]
I tried a fresh checkout:

```
❯ git clone https://github.com/quicksilver/Quicksilver.git --recurse-submodules
❯ cd Quicksilver/Quicksilver
❯ xcodebuild clean build \-destination "platform=macOS" -scheme "Quicksilver" -project "Quicksilver.xcodeproj"
```

Succeeds right away. Opened in Xcode, works as well. I'm mystified -- and I'm sorry for wasting all of your time!

**Comment by skurfer** [comment]
No problem. Glad you sorted it out.
