### ISSUE TITLE
UI API called on background thread

### ISSUE THREAD

**Issue by DivineDominion** [quicksilver/Quicksilver#2579]
Building and running current `master` (40f0f59c39797c251dfbd44563586663b6812ccc) in Xcode produces runtime errors right away:

    Main Thread Checker: UI API called on a background thread: -[NSWindow setLevel:]

Fixing that by dispatching back to the main queue produces more of these errors when `QSTaskViewer` tries to add view controllers, thus loading nibs on the BG queue, for background tasks that have been triggered.

    Main Thread Checker: UI API called on a background thread: -[NSViewController initWithNibName:bundle:]
    PID: 19985, TID: 1749351, Thread name: (none), Queue name: com.apple.root.utility-qos, QoS: 17
    Backtrace:
    4   Quicksilver                         0x0000000100f965f4 -[QSTaskViewController initWithTask:] + 280
    ...

    Main Thread Checker: UI API called on a background thread: -[NSViewController initWithNibName:bundle:]
    PID: 19985, TID: 1749351, Thread name: (none), Queue name: com.apple.root.utility-qos, QoS: 17
    Backtrace:
    4   Quicksilver                         0x0000000100f965f4 -[QSTaskViewController initWithTask:] + 280
    ...

    Main Thread Checker: UI API called on a background thread: -[NSViewController setRepresentedObject:]
    PID: 19985, TID: 1749351, Thread name: (none), Queue name: com.apple.root.utility-qos, QoS: 17
    Backtrace:
    4   Quicksilver                         0x0000000100f9665c -[QSTaskViewController initWithTask:] + 384
    ...

Looking for ways to add   `QSGCDMainAsync` calls is not a problem, here, too, I wonder if I'm overlooking something -- because this must've been an issue in the past. How come y'all can compile and run this just fine without these changes? :)

**Comment by skurfer** [comment]
I’ve seen things like that in the past when OS updates are released, but it seems to get less picky as the SDK gets updated. When I get time, I’ll clone to a fresh directory and see if I run into the same problems.

**Comment by DivineDominion** [comment]
I can provide fixes for this, too; I just need to know the general direction. Probably easiest to decipher in context of PRs. The location to dispatch back to main (as always) requires some consideration.

**Comment by skurfer** [comment]
Building and running in a new directory didn’t give me much trouble (except for all the missing plug-ins that made it kinda useless).

What are you doing in the UI to hit the errors? I thought I had gotten them all in #2503, but I know some more cropped up later. I just don’t see them for some reason.

**Comment by DivineDominion** [comment]
These are all firing during the app launch procedure.

I wonder if it's the M1 Monterey Mac causing trouble. The combo is pretty new to me and I don't yet trust if fully :)

**Comment by n8henrie** [comment]
I saw similar errors in the console when running from source, but the app launched and behaved normally.

**Comment by skurfer** [comment]
I’m on an M1 Max running Monterey.
