### ISSUE TITLE
Quicksilver trigger triggers wrong application

### ISSUE THREAD

**Issue by rwvo** [quicksilver/Quicksilver#2589]
I've set a number of triggers to open applications, or to bring them in focus if they are already open. Among these are:

Control-Command-T: iTerm
Control-Command-/: Todoist

If both iTerm and Todoist are open, then pressing Control-Command-T cycles between bringing iTerm into focus and bringing Todoist into focus. The expected behavior is that only iTerm is brought into focus. If Todoist is not open, then Control-Command-T works as expected: only iTerm is brought into focus. In particular, the trigger will not open Todoist; it will only incorrectly focus is if it is already open.

I've seen similar behavior on an other MacBook, where I bound Control-Command-E to Aquamacs. If Evernote happened to be open, this trigger would alternate between focusing Aquamacs and Evernote (wich had a different trigger).

Since Control-Command-T incorrectly focuses Todoist, and Control-Command-E incorrectly focuses Evernote, it looks like some matching based on the first character of the application name is (incorrectly) going on.

To make sure the special character in the trigger for Todoist wasn't the issue, I set the trigger for Todoist to Control-Command-G. The same behavior was still observed: Control-Command-T alternated between focusing iTerm and Todoist. Quitting and restarting Quicksilver made no difference.

2019 MacBook Pro MacOs 11.6.2, Quicksilver 1.6.1

**Comment by skurfer** [comment]
Assuming it doesn’t contain any sensitive information, can you attach a copy of `~/Library/Application Support/Quicksilver/Triggers.plist`?

**Comment by rwvo** [comment]
[Triggers.plist.zip](https://github.com/quicksilver/Quicksilver/files/7942497/Triggers.plist.zip)

**Comment by n8henrie** [comment]
@rwvo -- I can't replicate this problem; just set two triggers, one each for `Due.app` and `Terminal.app`, tried with both `Activate` as well as `Open`, both reliably foreground the expected application regardless of the number or order of activation. Are you still seeing this behavior?

Is it possible that there is a conflict between some other system setting (i.e. something in `System Preferences` -> `Keyboard` -> `Shortcuts` -> `Services`), or perhaps `iTerm` or `Todoist` is registering itself as handling one of those shortcuts globally?

> To make sure the special character in the trigger for Todoist wasn't the issue, I set the trigger for Todoist to Control-Command-G. The same behavior was still observed: Control-Command-T alternated between focusing iTerm and Todoist. Quitting and restarting Quicksilver made no difference.

This makes me think that Todoist might be trying to grab Ctrl-T. 

Looks like this is the case: <https://todoist.com/help/articles/keyboard-shortcuts>

Action | Shortcut
-- | --
Show/hide Todoist | CMD (⌘) + CTRL + T

I'm going to go ahead and close this issue -- if you can replicate the problem with Todoist using something other than <kbd>⌘ Ctrl T</kbd> please let me know and I'll re-open.

**Comment by skurfer** [comment]
This is why I have so few keyboard triggers. It’s nearly impossible to find something that isn’t already used by _any_ app.

**Comment by rwvo** [comment]
@n8henrie Thanks for correctly identifying the issue. Once I disabled the Todoist shortcut, behavior was as expected. Same for Aquamacs and Evernote: my Quicksilver trigger for Aquamacs was also a built-in shortcut in Evernote, giving the same undesirable cycling between the two applications. Disabling the shortcut in Evernote made the trigger work as expected too.
