### ISSUE TITLE
Extras Preferences localizations aren’t being applied

### ISSUE THREAD

**Issue by skurfer** [quicksilver/Quicksilver#2645]
Probably a result of the (much needed) Transifex updates.

<img width="969" alt="Screen Shot 2022-02-17 at 8 54 07 AM" src="https://user-images.githubusercontent.com/154676/154496651-f12699aa-f310-4d47-86a8-7e1ccbcf3ff7.png">

**Comment by pjrobertson** [comment]
Hmm... it looks alright for me here. You're running from `master` I presume, and you cleaned the build? Is it *just* the extras prefpane, or are other prefs panes not showing?

![Screenshot 2022-02-21 at 21 15 10](https://user-images.githubusercontent.com/150431/154962517-14f52ee8-bcbf-46d9-acf5-7cf08313fe28.png)

Those strings seem to be pulled from `DefaultsMap.plist`, which was last updated 3 years ago:

```
commit bb5387d41680759eeb2f7261cc497ed9c78b627c
Author: Rob McBroom <github@skurfer.com>
Date:   Thu Apr 18 19:00:44 2019 -0400

    add max history items to the “Extras” prefs
```

**Comment by pjrobertson** [comment]
Sorry about that. I went a bit too overboard using `stringstool`. This should now be fixed.
