### ISSUE TITLE
Triggers that use a keycode with ⎋ appear as '5' instead.

### ISSUE THREAD

**Issue by pjrobertson** [quicksilver/Quicksilver#2657]
If I set a trigger to ⌥⎋ it appears as ⌥5 in the interface, and I can only invoke it with ⌥5.

Seems like ESC and 5 are getting mixed up somehow.

This apparently also affects the 'Command Window with Selection' trigger, which was overhauled in v1.0.0.

More info at the end of: #2651

**Comment by pjrobertson** [comment]
Same is also true for 'tab' appears as '0'.

Fixed in the latest QS fork of NDHotkeyEvent

**Comment by skurfer** [comment]
Looks good!

**Comment by pjrobertson** [comment]
Thanks for the confirmation!
