### ISSUE TITLE
ExtraScripts-qsplugin: some functionality has been lost with the recent update

### ISSUE THREAD

**Issue by didaquis** [quicksilver/Quicksilver#2659]
**Describe the bug**
Recently the "ExtraScripts-qsplugin" was updated and some of its functions are no longer available. 
In the previous version of the plugin these actions worked without problem on the same operating system and the same version of QuickSilver.

I attach a screenshot of the options that have disappeared in the new version of the plugin.

**Expected behavior**
I would like to be able to reuse the options: "Shutdown", "Sleep" and "Restart"

**Screenshots**
<img width="799" alt="Captura de pantalla 2022-02-25 a las 1 10 56" src="https://user-images.githubusercontent.com/6883041/155629009-633526e6-b02e-4ef7-aeea-111ce5c37e26.png">

**What version of macOS?**
macOS Monterey 12.2.1

**What version of Quicksilver?**
1.6.1 (4024)

**Comment by n8henrie** [comment]
Sorry about that, I'll take a look!

**Comment by n8henrie** [comment]
Hmmm, I have these actions present and working.

A few have slightly different names, as the absence of the extension made is somewhat difficult to determine how they were compiled.

I have:

- `Sleep.scpt` (-> `~/Library/Application Support/Quicksilver/PlugIns/com.blacktree.Quicksilver.QSExtraScriptsPlugIn.97.qsplugin/Contents/Resources/ExtraScripts/System/Sleep.scpt`)
- `Restart.scpt` (-> `~/Library/Application Support/Quicksilver/PlugIns/com.blacktree.Quicksilver.QSExtraScriptsPlugIn.97.qsplugin/Contents/Resources/ExtraScripts/System/Restart.scpt`)
- `Shut Down.scpt` (-> `~/Library/Application Support/Quicksilver/PlugIns/com.blacktree.Quicksilver.QSExtraScriptsPlugIn.97.qsplugin/Contents/Resources/ExtraScripts/System/Shut Down.scpt`)

The default action is `Run`, and they seem to work.

Can you refresh your catalog and see if these appear?

**Comment by n8henrie** [comment]
Hmmm, it looks like I updated the plugin, and I've run `qs-push-plugin` to push it to the plugin server, but I'm still only showing `1.0.0` from 2/04 available. Just tried bumping the version number and pushing again with no luck.

Not sure what I did wrong, will take a closer look tomorrow.

**Comment by n8henrie** [comment]
Fixed the version number problem.

Can you make sure you're running 1.1.2?

**Comment by didaquis** [comment]
HI! I Updated the plugin and now is working again! The version 1.1.2 has been downloaded to my mac correctly. 

Thank you. I have been using Quicksilver for more than 10 years, it is a great software. Thank you very much!! ❤️

**Comment by SmilinBrian** [comment]
Yay! I had been missing the Sleep and Shutdown scripts for a couple weeks but hadn't got round to reporting a bug - glad to see this fixed!
