### ISSUE TITLE
Activation key with space appears as '1'

### ISSUE THREAD

**Issue by debugDS** [quicksilver/Quicksilver#2662]
First, let me thank you all for the beautiful work you're doing on Quicksilver. 👏

<br>
My activation shortcut is `opt-space`, and recently the space symbol was replaced by the character `1` in the command pane.

Like @pjrobertson did recently, the solution  is to replace `kVK_Space` in the file [`NDKeyboardLayout.m`](https://github.com/quicksilver/ndhotkeyevent/blob/1846371cf13fb9d9c9e6824828e8da402ffc98f6/Classes/NDKeyboardLayout.m#L54) with

```objc
// SPACE: should be kVK_Space, but 0x31 clashes with the '1' char - they both have the same unichar value
  {0x97, 0x31, {0x23B5, '\0', '\0', '\0'}}, // 0x02FD
```

**Comment by pjrobertson** [comment]
You are likely running a pre-release version of Quicksilver. This has been fixed in the latest `master` and will be part of 2.0, which will be released shortly.

Thanks!
