### ISSUE TITLE
Proxy objet 'Current Document' not working

### ISSUE THREAD

**Issue by debugDS** [quicksilver/Quicksilver#2663]
The proxy object `Current Document`, in the `Catalog`'s `Proxy Objects`, is present but not working. All the others (`Current Application`... ) are OK.

I get the notification : *Unable to select current document*,  when I activate `Current Document` in the first pane.

With my Intel Quicksilver version, it's working fine.
*Maybe I'm not building QS correctly ? :-(*

By the way, the objects in the `Contents` pane of `Proxy Objects` cannot be unchecked.
If you click on them, they are added to the `omittedItems` section in `~/Library/Application\ Support/Quicksilver/Catalog`

<br>
Thanks a lot!

**Comment by pjrobertson** [comment]
If you are building from source, then the likely cause is that macOS is getting confused about security permissions. I have encountered these problems. Here's what you should to do fix:

1. Open up security & privacy
2. Remove the 'Quicksilver' app from the 'Accessibility' section
![Screenshot 2022-03-02 at 09 58 37](https://user-images.githubusercontent.com/150431/156280110-93828fb1-00db-4867-b305-b0608898cff4.png)
3. Drag the Quicksilver.app you have just built (likely in `/tmp/QS/build/Debug` or `/tmp/QS/build/Release` into the 'Accessibility' pane.
4. Profit

It seems macOS cannot security very well when you have two copies of the same app on your system.


I'll close this for now. But if that doesn't solve your problem, let me know.
