### ISSUE TITLE
Preference Pane Sidebars Truncating Text

### ISSUE THREAD

**Issue by pjrobertson** [quicksilver/Quicksilver#2673]
**Describe the bug**

**To Reproduce**
1. Run latest master, built by GH Actions.
2. Open up the preferences

**Screenshots**
See left sidebar:
![Screenshot 2022-03-14 at 09 40 04](https://user-images.githubusercontent.com/150431/158090555-20841a7e-965c-46d5-a62f-89b1b993af6a.png)

**What version of macOS?**
10.14.6

**What version of Quicksilver?**
Lastest Master

@skurfer @n8henrie - are you able to reproduce this on your version of macOS? If you build from master, do you also get this issue? If I build myself, I don't get the issue.

If this is just an issue for me (on 10.14) then I suggest I look into this for 2.1.0, don't have it affect our 2.0 release.

**Comment by skurfer** [comment]
I don’t see this with the version I built locally.
