### ISSUE TITLE
How Do i use quick silver to search a website

### ISSUE THREAD

**Issue by profe6** [quicksilver/Quicksilver#2678]
I'd like to search a specific website with a quick type of quick silver.  So it automatically appends what i type into the url and searches it.  

For example if I wanted to search VUDU for movies i would have this URL
https://www.vudu.com/content/movies/search?minVisible=0&returnUrl=%252F&searchString=tacos

Is there a way to have quicksilver automacially pull up that search in a new tab when i type in tacos?

**Comment by pjrobertson** [comment]
Sure, this is possible using the 'Web Search' Plugin :)

See the guide at https://qsapp.com/manual/plugins/websearch/ and especially the section titled '
