### ISSUE TITLE
Funky Colors after Upgrading to macOS Monterey 12.3

### ISSUE THREAD

**Issue by wdr1** [quicksilver/Quicksilver#2680]
For questions or tech support, please start with the [users’ group][1]. If you know the problem is in Quicksilver itself, report it here.

[1]: https://groups.google.com/forum/#!forum/blacktree-quicksilver

**Describe the bug**

After upgrading to macOS Monterey 12.3, the various UI panels have an odd rainbow color.

The problem persists after several restarts/reboots.

**Screenshots**
<img width="469" alt="Screen Shot 2022-03-18 at 10 43 03 PM" src="https://user-images.githubusercontent.com/1408642/159109001-5578025b-8a19-40db-a634-0fb34a0497d7.png">

<img width="543" alt="Screen Shot 2022-03-18 at 10 43 09 PM" src="https://user-images.githubusercontent.com/1408642/159109004-6831a778-7c00-4a15-b6e0-c048c467fe0c.png">

**What version of macOS?**
macOS Monterey 12.3

**What version of Quicksilver?**
1.6.1 (4026)

**Comment by pjrobertson** [comment]
This has been fixed in the latest version of Quicksilver, which will be released publicly soon. You can download a pre-release version here:

https://github.com/quicksilver/Quicksilver/suites/5689842843/artifacts/187145157
