### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by thewellington** [quicksilver/Quicksilver#2683]
For questions or tech support, please start with the [users’ group][1]. If you know the problem is in Quicksilver itself, report it here.

[1]: https://groups.google.com/forum/#!forum/blacktree-quicksilver

**Describe the bug**
- Primer interface displays a black-green gradient across the top half.
- Preferences -> General displays a black-green gradient across the top half of the window.
- Other (Plugins, Catalog, Triggers) display similar gradients in certain controls, making it hard to discern what that control is for.   The controls affected are the info, refresh, +, and - at the bottom of the window.
- Left navigation bar is black text on black background.  Hard to read. 

**To Reproduce**
- Use QuickSilver primer interface
- Use Quicksilver Preferences

**Expected behavior**
I expect the interface to have a consistent color scheme

**Screenshots**
(https://www.dropbox.com/sh/x384z6e2r0qbrxg/AAADq3hVFt2pR_bsbTeclbZja?dl=0)

**What version of macOS?**
12.3
**What version of Quicksilver?**
1.6.1 (4026)

**Other Information**
This is from a M1 MacBook Pro, but I see similar, though not as intrusive UI issues on my 2019 i9 MacBook Pro - same versions

**Comment by pjrobertson** [comment]
Thanks for the bug, report @thewellington . This is a known issue with macOS 11 and above. We will be releasing Quicksilver 2.0 which will solve this issue. Please make sure to check for updates from within Quicksilver, or keep an eye on https://qsapp.com/download.php

Thanks!
