### ISSUE TITLE
Fix Quicksilver icon for more sizes

### ISSUE THREAD

**Issue by pjrobertson** [quicksilver/Quicksilver#2685]
Some icon sizes are missing in the newest QS icon, created by vadimrob.

-----

From @lgarron:

Would it make sense to add more resolutions to the `.icns` files?

In https://github.com/quicksilver/Quicksilver/pull/2544 I put a lot of care into the dimensions to match Apple's guidelines/icons, and also to make sure that the horizontal short line at the bottom remains visible in Finder at 1x monitor resolution (right side of screenshot).

![Screen Shot 2022-03-16 at 17 41 39](https://user-images.githubusercontent.com/248078/158714144-92421703-29a1-4692-a7a2-573264a40f92.png)

_Originally posted by @lgarron in https://github.com/quicksilver/Quicksilver/issues/2595#issuecomment-1069784894_

Original `.afdesign` files are available in that post as well for editing

@lgarron, would you be able to update the icons?

**Comment by lgarron** [comment]
Okay, here's a go that tries to match @vadimrob's design and dimensions. I'll make a PR for it.

![icon_16x16](https://user-images.githubusercontent.com/248078/160120524-0eb7dbd7-afc6-4733-bf95-95bca18ee7eb.png)
![icon_32x32](https://user-images.githubusercontent.com/248078/160120525-53cd2068-d06d-4c9a-931a-af678602286d.png)
![icon_32x32@2x](https://user-images.githubusercontent.com/248078/160120526-ad456dc6-de3d-45e1-b550-44827417a016.png)
![icon_128x128](https://user-images.githubusercontent.com/248078/160120529-db51ed66-8775-4f80-b573-fe634def19c8.png)
![icon_256x256](https://user-images.githubusercontent.com/248078/160120530-83b8d6e6-d575-43ee-a226-ffcb1e9e528f.png)
![icon_256x256@2x](https://user-images.githubusercontent.com/248078/160120531-e55fe4da-dd4b-4a36-b8db-bcc4d1a75a8f.png)
![icon_512x512@2x](https://user-images.githubusercontent.com/248078/160120534-caa3c181-9662-4b79-b407-db1397267538.png)

If we want a bigger purple surface, I'd be more partial the preserving the traditional Quicksilver style of using a purple inset, also matching current icons for apps like Safari:
![icon_512x512@2x](https://user-images.githubusercontent.com/248078/160121853-58fccfe1-4e87-4582-8124-5e16d1b5fddc.png)
<img width="326" alt="Screen Shot 2022-03-25 at 05 38 46" src="https://user-images.githubusercontent.com/248078/160122276-e996cb92-dff0-48b7-872f-97dc83469c92.png">
But it seems that ship has sailed for now.

**Comment by lgarron** [comment]
(Splitting out into a separate comment for linking.)

If we want a bigger purple surface, I'd be more partial to preserving the traditional Quicksilver style of using a purple inset, also matching current icons for apps like Safari:
![icon_512x512@2x](https://user-images.githubusercontent.com/248078/160121853-58fccfe1-4e87-4582-8124-5e16d1b5fddc.png)
<img width="326" alt="Screen Shot 2022-03-25 at 05 38 46" src="https://user-images.githubusercontent.com/248078/160122276-e996cb92-dff0-48b7-872f-97dc83469c92.png">
But it seems that ship has sailed for now.

**Comment by pjrobertson** [comment]
Fixed by #2686
