### ISSUE TITLE
Can't use cmd-space with quicksilver 2.0.0

### ISSUE THREAD

**Issue by natcl** [quicksilver/Quicksilver#2687]
**Describe the bug**
I just installed Quicksilver 2.0.0 and I can't set cmd-space as my activation shortcut, when I set cmd-space it shows cmd-1 in the UI.

**What version of macOS?**

12.2.1

**What version of Quicksilver?**

2.00

**Comment by natcl** [comment]
This might be a duplicate of #2682

**Comment by pjrobertson** [comment]
Likely a duplicate, and should be fixed in the official 2.0 release (which will be released shortly). You're likely running a pre-release of 2.0. See the version number in your Quicksilver preferences.

**Comment by pjrobertson** [comment]
If it's still an issue with 2.0 official, then please comment here and we'll re-open the issue.

**Comment by natcl** [comment]
I have this version  :
<img width="1483" alt="image" src="https://user-images.githubusercontent.com/77556/160257226-889d615d-f1e1-4b00-a91f-a0ac7fe8bdb5.png">

Is that the official  2  ?

**Comment by natcl** [comment]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/77556/160257266-06f21f1a-7289-4a68-8dc1-1d75f1c85f75.png">
