### ISSUE TITLE
Nostromo top text is not vertically centered anymore

### ISSUE THREAD

**Issue by lgarron** [quicksilver/Quicksilver#2688]
The top text for Nostromo is no longer visually centered (vertically) in its top space. I would guess it's no longer taking into account the space from the margin/padding of the top input.

Quicksilver 1.6.1 😌

<img width="856" alt="Screen Shot 2022-03-25 at 18 13 50" src="https://user-images.githubusercontent.com/248078/160218872-62586f6c-d930-41a6-95bb-2586b6255a04.png">

Quicksilver `2.0.0:(HEAD detached at pull/2686/merge)` 😭

<img width="856" alt="Screen Shot 2022-03-25 at 18 14 19" src="https://user-images.githubusercontent.com/248078/160218900-42255c92-f451-45f5-9214-775ce5ee6c28.png">

I know this is kind of a minor nit, but the previous alignment felt really natural, and this is one of the most prominent details see hundreds of times a day as a regular user.

**Comment by pjrobertson** [comment]
This should have been fixed by Nostromo v1.4.1 - please update the plugin from within Quicksilver.

Thanks
