### ISSUE TITLE
All Quicksilver windows have a green gradient overlay.

### ISSUE THREAD

**Issue by nquinlan** [quicksilver/Quicksilver#2691]
**Describe the bug**
Every window rendered by Quicksilver has a green overlay on it. The issue persists even after restarting the application and the computer.

**To Reproduce**
1. Open any Quicksilver window.

**Expected behavior**
Quicksilver windows rendered without the green overlay.

**Screenshots**
<img width="512" alt="Quicksilver launcher with a green gradient overlaying the top" src="https://user-images.githubusercontent.com/829864/160413714-582c67e5-a7dd-418f-bf84-9eaab95f5325.png">
<img width="662" alt="Quicksilver preferences with a green gradient overlaying the top" src="https://user-images.githubusercontent.com/829864/160413729-004aaa71-5933-44e6-be2c-f82d69731843.png">

**What version of macOS?**
12.3 (21E230) running on Apple M1 Pro

**What version of Quicksilver?**
1.6.1 (4026)

**Comment by nquinlan** [comment]
Solved by updating to [v2.0.0](https://github.com/quicksilver/Quicksilver/releases/tag/v2.0.0) from GitHub. Quicksilver would not update in app.

I'll leave the issue open in case you want to fix with a minor version, before 2.0.0.

_As an aside, thank you so much for your active development of Quicksilver and bringing it all the way to 2.0.0_

**Comment by n8henrie** [comment]
Thanks for the updates!

> Solved by updating to [v2.0.0](https://github.com/quicksilver/Quicksilver/releases/tag/v2.0.0) from GitHub. Quicksilver would not update in app.

The in-app update issue should be resolved soon, I think we just need to push to qsapp.com.
