### ISSUE TITLE
required macOS version for Quicksilver 2.0

### ISSUE THREAD

**Issue by thisisgk** [quicksilver/Quicksilver#2693]
Please correct the required macOS version for Quicksilver 2.0 on the download page https://qsapp.com/download.php. It says 10.12+ but actually requires 10.14+.

I am using macOS 10.12 and was notified of the Quicksilver 2.0 update, followed it and of course it won't launch.

**Comment by pjrobertson** [comment]
Hi thisisgk,

You're correct, Quicksilver 2.0 requires 10.14+.

We've fixed the download page to state this. Thanks for the report, and for your support in making Quicksilver better!

**Comment by skurfer** [comment]
Did you change it in the database so it won’t be offered to users on 10.13 and 10.12?

**Comment by pjrobertson** [comment]
Yes, I changed the min OS requirement to 101400
