### ISSUE TITLE
Problem with trigger keycodes

### ISSUE THREAD

**Issue by tiennou** [quicksilver/Quicksilver#2696]
**Describe the bug**

I had a trigger set to ⌥⇧ù, and it got turned into ⌥⇧Q when I updated to 2.0.0. Trying to set it again doesn't work, it always ends up as the wrong keycode. Physical keyboard layout is French, in French input mode, and it maps to the first key above the right shift key, going left to right.

Doing a full sweep of all keys, the missing keys are the following: 
![Capture d’écran 2022-03-31 à 13 19 42](https://user-images.githubusercontent.com/81099/161043685-68a7ccfc-58cf-44aa-9d31-1c07415a041d.png)

**Expected behavior**
Well, it should work 😁 .

**What version of macOS?**

ProductName:	macOS
ProductVersion:	12.1
BuildVersion:	21C52

**What version of Quicksilver?**
 2.0.0

---

Good job on the 2.0.0 update, it's nice seeing some activity again. And yeah, I find it ironic to be filing a bug against one of the features I've spent the most time, trying to tackle those keymapping issues 😊 .

**Comment by pjrobertson** [comment]
Good to hear from you Etienne! We updated NDKeyBoardLayout for 2.0 based on your code / PR from a while back. I'm trying to hack with it right now but it's difficult.

**Comment by pjrobertson** [comment]
I'm assuming you don't have anything set here?
![Screenshot 2022-03-31 at 19 25 09](https://user-images.githubusercontent.com/150431/161044525-b779745a-5e0f-4063-bcb3-250254931a90.png)

**Comment by RModiz** [comment]
Hello. Same basic problem Keyboard is Swiss. QWERTZ
I had to go back to previous version of Quicksilver because the new one won't accept ctrl-spacebar as my trigger. It always puts ctrl-1 (ie, the upside-down-v1).

Thanks.

**Comment by tiennou** [comment]
![Capture d’écran 2022-03-31 à 16 31 07](https://user-images.githubusercontent.com/81099/161079909-40eabd16-7801-4fa9-81e8-e3944f35a1c4.png)

That's the layout my keyboard has, and here's the relevant part of Triggers.plist:
```
			<key>keyCode</key>
			<integer>42</integer>
			<key>modifiers</key>
			<integer>655684</integer>
```

It's been a while, but IIRC that happens when the code fails to find a mapping, making the default `Q`.

**Comment by skurfer** [comment]
Bonsoir, Etienne!

So, should we hold off on 2.0.1 until this is also fixed?

**Comment by pjrobertson** [comment]
OK, I can reproduce when switching to a French keyboard layout. Will work on it and aim to get a fix out tonight (in 12hrs).

**Comment by GregOriol** [comment]
I have the same issue here with a french keyboard and with a `ctrl+enter` shortcut that gets renamed to `ctrl+$` and therefore doesn't work as before. Will the fix work for this too?

**Comment by pjrobertson** [comment]
This has been fixed :) I was 1 hr behind my target, dammit.

As always, an incredibly simple fix that needed ~4 hrs of debugging :'(

Issue was due to `isprint()` returning '0' (false) for non-ascii characters like ùè

https://github.com/quicksilver/ndhotkeyevent/commit/5989a24260df457ad3ea2c494d1f53f48b0bcfd0#diff-2183d1ef4cfe86bd63ec854b86402c910c3203597ffca573d3443d91a25dabbeL313

**Comment by pjrobertson** [comment]
@GregOriol - I've just checked on my local build and it looks like it works:
![Screenshot 2022-04-01 at 22 38 19](https://user-images.githubusercontent.com/150431/161285969-2d3e104d-8930-4fd9-ab85-87640857c359.png)

**Comment by GregOriol** [comment]
@pjrobertson Awesome! Merci :-)

**Comment by RModiz** [comment]
Howdy. It didn^'t solve my problem. Instead of the spacebar, it requires the 1 key. I tried editing, but no luck.  The keyboard is Swiss (French). This is different from the French keyboard.  Thanks.

**Comment by pjrobertson** [comment]
Hi RModiz, can you please open a new issue and provide some screenshots showing the issue you're facing. That will help us fix this problem.

Thanks!
