### ISSUE TITLE
Can't activate Quicksilver with "command + space" anymore

### ISSUE THREAD

**Issue by wirezen** [quicksilver/Quicksilver#2700]
Just updated Quicksilver to the version 2.0.0 (4027) and the activation shortcut has changed to "command + 1".
I've tried to change it back to "command + space" but it's not possible.
Looks like it doesn't accept the space bar in conjunction with command.

Please note that i've always used a diferrent shortcut for Spotlight, so it's not about a conflict between those two.

macOS version 12.3

Quicksilver 2.0.0 (4027)

**Comment by pjrobertson** [comment]
Thanks for the report, wirezen. This is a known issue with Quicksilver 2.0.0. We have a fix for it and we will release an updated version of Quicksilver soon.

See #2692 for more information 

Thanks!
