### ISSUE TITLE
Sorry.

### ISSUE THREAD

**Issue by RModiz** [quicksilver/Quicksilver#2702]
fyi

**Describe the bug**
If I open either version using the shortcut, I get what is shown in the screenshots below.

If I use the Launchpad, sometimes it works.

I've tried several times to "uninstall" (using the pref panel) and to reinstall, but without luck. I've also switched versions, using the ^1 combo on version 2.0. I can't figure out how to uninstall more completely than by using the panel.

Thanks in advance. I know you're working on the keyboard problem but thought my problem might be interesting and useful to know about ahead of time.

**Screenshots**
![Screenshot 2022-04-03 at 16 23 40](https://user-images.githubusercontent.com/102740834/161433748-f4cf7d28-602f-49b8-8b92-6d323936994f.png)
![Screenshot 2022-04-03 at 16 22 06](https://user-images.githubusercontent.com/102740834/161433759-88d4bfac-c8f4-49f6-a226-0e94829d821e.png)
![Screenshot 2022-04-03 at 16 20](https://user-images.githubusercontent.com/102740834/161433769-498040ff-ecd2-43d4-bbe9-9ca3c32597db.jpg)

**What version of macOS? 12.3.1

**What version of Quicksilver? 1.6.1 and 2.0

**Comment by pjrobertson** [comment]
Hi RmModiz,

Please try downloading v2.0.1 of Quicksilver, the issue should have been fixed there.

Thanks!

**Comment by RModiz** [comment]
YAY!

**Comment by n8henrie** [comment]
Sorry, I don't understand the problem you're worried about. Would you mind
elaborating?

Is it the green color in the first screenshot? If so, what are you trying
to show us in the other two?

**Comment by RModiz** [comment]
The problem was solved 6 months ago. I don’t even remember what it was any more. But thanks.
