### ISSUE TITLE
App crashed when setting up custom folder in Catalog

### ISSUE THREAD

**Issue by kzykx** [quicksilver/Quicksilver#2704]
For questions or tech support, please start with the [users’ group][1]. If you know the problem is in Quicksilver itself, report it here.

[1]: https://groups.google.com/forum/#!forum/blacktree-quicksilver

**Describe the bug**
App crashed when setting up custom folder in Catalog
**To Reproduce**
Crashed every time when setting up custom folder. 
1. Go to 'Preferences'--'Catalog'--'Custom'
2. Click on 'Add button'
3. Click on 'File and Folder Scanner', and choose Folder
4. app crashed

**Screenshots**
<img width="1050" alt="Screen Shot 2022-04-04 at 8 42 54 AM" src="https://user-images.githubusercontent.com/102411489/161458660-ba46660b-851a-4e39-b9c9-224ce88227c0.png">

**What version of macOS?**
macOS 12.3.1
**What version of Quicksilver?**
2.0.1(4028)

**Comment by pjrobertson** [comment]
Thanks for the report @kzykx 

This has been fixed and an updated v2.0.1 has been released. Please re-download from qsapp.com or check for updates from within Quicksilver.

Thanks

**Comment by kzykx** [comment]
Thanks a million for your amazing quick fix@pjrobertson
