### ISSUE TITLE
QS 2.0.1 has a strange version number in CFBundleShortVersionString

### ISSUE THREAD

**Issue by MiqViq** [quicksilver/Quicksilver#2709]
For questions or tech support, please start with the [users’ group][1]. If you know the problem is in Quicksilver itself, report it here.

[1]: https://groups.google.com/forum/#!forum/blacktree-quicksilver

**Describe the bug**
QS 2.0.1 has a strange version number in CFBundleShortVersionString
	<key>CFBundleShortVersionString</key>
	<string>2.0.1:(HEAD detached at v2.0.1)</string>

This caused my munkicatalogs to fail as it cannot handle such exotic version numbering.
Had to remove it from my munki repo.
Please fix this.

**What version of Quicksilver?**
2.0.1

**Comment by MiqViq** [comment]
<key>CFBundleShortVersionString</key>
		<string>v2.0.2</string>
This version formatting is better now but still the best version number in CFBundleShortVersionString does not have anything but digits and dots...so I suggest that you use plain "2.0.2" style with public releases.

**Comment by n8henrie** [comment]
Let's keep the discussion consolidated at https://github.com/quicksilver/Quicksilver/issues/2705
