### ISSUE TITLE
Hangs at login

### ISSUE THREAD

**Issue by nemesyssoft** [quicksilver/Quicksilver#2711]
Since upgrading to 2.0.0 (4027), Quicksilver hangs when I login since I have set it to open at login. Not sure what to provide here but, as a developer, I can provide anything you want to help.

**Comment by pjrobertson** [comment]
Please provide a spindump sample when Quicksilver hangs. To do this, follow the instructions here:

https://support.zoom.us/hc/en-us/articles/206435255-Creating-a-Spindump-file-on-macOS

Except replace 'zoom.us' with 'Quicksilver in step 5.

Thanks

**Comment by nemesyssoft** [comment]
Not sure if it's related but after trying to update from 2.0 to 2.0.1, it hung again. Here is the spindump:

[QS Spindump while updating.txt](https://github.com/quicksilver/Quicksilver/files/8428358/QS.Spindump.while.updating.txt)

**Comment by pjrobertson** [comment]
Thanks for the spindump. This appears to be the same issue as #2708, and should be fixed in an upcoming release (v2.0.3) which will be released in the next 24 hours.

Thanks for your patience!
