### ISSUE TITLE
^space as Activation shortcut does not work anymore in 2.0

### ISSUE THREAD

**Issue by ruflin** [quicksilver/Quicksilver#2712]
Today I upgraded to Quicksilver 2.0. The Activation Shortcut I used so far was `^Space`. Now with 2.0, the Activation Shortcut is `^1` instead. I tried to change it by clicking Edit and Press `^Space` but the result it shows me is `^1`. Below is a small screenshot of the output when I press `^Space`.

![Screenshot 2022-04-06 at 16 56 53](https://user-images.githubusercontent.com/244900/162005256-b097793f-e986-4935-a977-5c7414eb20a8.png)

I'm partially wondering if any other tool on my machine gets in the way and replaces `^Space` with `^1` or if others can reproduce this. What bugs me is that it was working in the previous releases on the same OS X version.

* OS X Version: 12.3.1
* Intel machine

Thanks for the amazing tool 🙇

**Comment by pjrobertson** [comment]
Thanks for the report ruflin! 

This is a known issue with version 2.0 of Quicksilver. Please try updating to 2.0.1. You can download it from: https://qsapp.com/download.php

**Comment by ruflin** [comment]
Thanks @pjrobertson for the feedback. Should have done better search on the closed issues (instead of open) in advance: https://github.com/quicksilver/Quicksilver/issues/2692 Sorry about the noise.
