### ISSUE TITLE
qsapp.com/archives (github.qsapp.com) should auto-update on new release

### ISSUE THREAD

**Issue by timvisher** [quicksilver/Quicksilver#2713]
v2.0.1 and v2.0.2 are not available at qsapp.com/archives/ which makes updating the Homebrew Cask more complicated than it should be. Not sure whether that's intentional on your end or not but I'm assuming it isn't. :)

See https://github.com/Homebrew/homebrew-cask/pull/121662

**To Reproduce**
1. Go to https://qsapp.com/archives/
2. See latest release of 2.0.0

**Expected behavior**
v2.0.1 and v2.0.2 should be present

**Screenshots**

![image](https://user-images.githubusercontent.com/34676/162214725-5c02c6d9-669f-4781-9258-ab287479feff.png)

**What version of macOS?**

N/A

**What version of Quicksilver?**

N/A

**Comment by n8henrie** [comment]
GitHub releases should be a pretty reliable way to get QS releases going forward, I would recommend you convert the cask over to tracking it instead of qsapp.com.

Unfortunately GitHub Releases still don't automatically provide a hash, which is useful for creating a cask IIRC. Perhaps I can add an md5 to the artifacts or something.

In the meantime we'll work on updating qsapp.com -- it just requires a few extra steps, whereas GA automatically cuts a release with pushing a new tag.

**Comment by pjrobertson** [comment]
Right, GitHub releases is the way to go for homebrew.

This bug report does, however highlight another issue. I'm not quite sure what's going wrong here.

I already pushed the [gh-pages branch](https://github.com/quicksilver/Quicksilver/tree/gh-pages) (which contains the archives file) to GitHub, so the index.html file is there and has been updated. `gh-pages` is set to resolve to [https://github.qsapp.com/](https://github.qsapp.com/) which as you can see has been updated correctly, but the server also seems to contain an `/archives/` folder in the `www` root, with a copy of these files.

The reason I'm confused is that I never updated those files for 2.0.0, but the https://qsapp.com/archives/ shows 2.0.0.

I suggest we either:

1. Update `gh-pages` to point to `archives.qsapp.com` and then redirect qsapp.com/archives to archives.qsapp.com`
OR:
2. Do away with `gh-pages` all together, and replace the qsapp.com/archives page a link to the GH releases page
OR:
3. Do away with `gh-pages` all together and make the `archives` page part of the main site repo that just populates automatically on build.

**Comment by pjrobertson** [comment]
For the time being, I've had qsapp.com/archives point directly to github.qsapp.com

**Comment by timvisher** [comment]
Sorry for the noise if I'm just missing something but it doesn't look like github.qsapp.com has been updated to me.

![image](https://user-images.githubusercontent.com/34676/162446548-0455471f-7ea4-4be1-928d-418407d34cde.png)

**Comment by n8henrie** [comment]
> Do away with gh-pages all together, and replace the qsapp.com/archives page a link to the GH releases page

I'm in favor of this option.

I think the sprawl is one of the hardest aspects of the project -- between the qsapp / the wiki, issues here, reference info and documentation in various non-README markdown files, and gh-pages... it's a lot to keep track of! Of course I don't *like* the idea of vendor lock-in having issues, releases, disussion, gh-pages, everything dependent on MS / GitHub either.

But I think that trying to reduce the number of moving parts that need maintenance would be a good move for the project in the long term; the GitHub Releases page seems to fulfill the minimum requirements for the project, why not use it?

**Comment by skurfer** [comment]
> The reason I'm confused is that I never updated those files for 2.0.0, but the https://qsapp.com/archives/ shows 2.0.0.

That was me. I’ve been manually adding each version to that folder with each release. I didn’t even know we were keeping it in Git somewhere. 😬

**Comment by pjrobertson** [comment]
> Releases page seems to fulfill the minimum requirements for the project, why not use it?

OK, sounds good to me. Let's move to using that. I'll open a new issue to list out the tasks

> That was me. I’ve been manually adding each version to that folder with each release. I didn’t even know we were keeping it in Git somewhere. 😬

I'd forgotten as well. Was scratching my head going through the `Release Process` for a while.
