### ISSUE TITLE
latest QS version for each macOS version?

### ISSUE THREAD

**Issue by TallTed** [quicksilver/Quicksilver#2716]
I'm trying to locate the latest QS that will run on my High Sierra 10.13.6, which after some poking around appears to be 1.6.1.

MacUpdate claims to be offering 1.6.1, but really delivers 2.0.2, which the developer site says in one place requires macOS Mojave 10.14 or later (this is not clear in changelog, among other places). 

Compatibility statements are enormously helpful to people trying to be users!

**Comment by pjrobertson** [comment]
Thanks for the feedback TallTed. Going forwards, we'll make sure to add version compatibility to the changelog.

I have updated the current changelog with this information: https://qsapp.com/changelog.php

You can also view the information at: https://qsapp.com/archives
