### ISSUE TITLE
QuickSilver 2.0.0 hangs when attempting to update

### ISSUE THREAD

**Issue by hofman** [quicksilver/Quicksilver#2720]
For questions or tech support, please start with the [users’ group][1]. If you know the problem is in Quicksilver itself, report it here.

[1]: https://groups.google.com/forum/#!forum/blacktree-quicksilver

**Describe the bug**
When QS 2.0.0 attempted to update today to a new version (2.0.2 I think), it ended up in a hang, showing the beach ball. 

**To Reproduce**
1. On startup, QS shows an alert for a new update
2. Click on the button to update
3. The task window shows
4. Quick silver hangs, the beach ball shows on the task window.

**Expected behavior**
QS updates and restarts. Certainly does not hang.

**Screenshots**

**What version of macOS?**
11.6

**What version of Quicksilver?**
2.0.0

**Comment by aspacca** [comment]
same from 2.0.1 to 2.0.2

**Comment by pjrobertson** [comment]
Thanks for the reports. These were known issues with 2.0.0 through 2.0.2. Read more on the changelog page: https://qsapp.com/changelog.php

You will need to upgrade manually by downloading via https://qsapp.com/download.php to fix this problem.
