### ISSUE TITLE
Autoupdate crashes, unresponsive.

### ISSUE THREAD

**Issue by ST33LDI9ITAL** [quicksilver/Quicksilver#2723]
Installed through brew. On running notifies to update from 4027 -> 4031. Pinwheel of infinity.

**Comment by n8henrie** [comment]
The in-app update problem is a known issue and we think is resolved, but requires a manual update to 2.0.3.

- <https://qsapp.com/changelog.php>
- <https://github.com/quicksilver/Quicksilver/issues/2720#issuecomment-1092738830>

If these don't resolve your problem, please let us know, and I'll be happy to re-open the issue.
