### ISSUE TITLE
(download) older links not functioning

### ISSUE THREAD

**Issue by mrkapqa** [quicksilver/Quicksilver#2724]
hello,

please reinstate the links for quicksilver legacy version before 2+

thanks.

**Comment by pjrobertson** [comment]
Hi mrkapqa, you can find links to all previous downloads here: https://github.qsapp.com/

Thanks!

**Comment by mrkapqa** [comment]
hello,
for some reason the downloads are not avaible to me.

**Comment by mrkapqa** [comment]
alright, it seems older versions still are,
thanks.
