### ISSUE TITLE
Installed the newest version (?), and it hung forever, had to be killed

### ISSUE THREAD

**Issue by DougHockin** [quicksilver/Quicksilver#2725]
For questions or tech support, please start with the [users’ group][1]. If you know the problem is in Quicksilver itself, report it here.

[1]: https://groups.google.com/forum/#!forum/blacktree-quicksilver

**Describe the bug**
I just installed the newest version (shows I'm running 2.0.1, don't know new version) and the install hung forever after the download completed. MacOS Activity Monitor showed Quicksilver unresponsive. So I killed it.

**To Reproduce**
Install newest version.
**Expected behavior**
Install should complete in a reasonable amount of them and exit, or tell me it's done.
**Screenshots**

**What version of macOS?**
11.6.5

**What version of Quicksilver?**
Currently running 2.0.1. Don't know what new version was.

**Comment by pjrobertson** [comment]
The in-app update problem is a known issue and we think is resolved, but requires a manual update to 2.0.3.

- <https://qsapp.com/changelog.php>
- <https://github.com/quicksilver/Quicksilver/issues/2720#issuecomment-1092738830>

If these don't resolve your problem, please let us know, and I'll be happy to re-open the issue.

**Comment by DougHockin** [comment]
Manual install worked fine. Thanks.
