### ISSUE TITLE
[Bug]: Activation hot key doesn't allow ctrl-space any more

### ISSUE THREAD

**Issue by thirkej** [quicksilver/Quicksilver#2731]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

I used to use ctrl-spacebar as my hotkey to call up Quicksilver.  After downloading the latest version this doesn't work any more.
Run setup, type ctrl-spacebar and what appears in the window is ^1
Close
Type  ctrl-space, no Quicksilver any more.  Type ctrl-1 nothing happens either... (not that that is what I want).

Help - it's my muscle memory to use that combination...  (NB Still works on my laptop - haven't downloaded the latest version there). 

### Steps to reproduce

1. Try to set hot keys for activation to Ctrl-space
2. Exit setup / preferences
3. Type Ctrl-space
4. Nothing happens

### Expected behavior

Press ctrl-space and Quicksilver opens...

### MacOS Version

macOS 10.15

### Quicksilver Version

2.0.0 (4027)

### Relevant Plugins

n/a 

### Crash Logs or Spindump

n/a

### Screenshots

can't remember how to take screenshots without quicksilver - used just to launch it and type screenshot ;-( 

But anyhow, not much to show

**Comment by n8henrie** [comment]
Sorry for the inconvenience! 

This is a known issue -- please update to the latest version (<https://github.com/quicksilver/Quicksilver/releases>); if you're still having trouble let us know, and I'll be happy to reopen.

See also:

- <https://github.com/quicksilver/Quicksilver/issues/2662>
- <https://github.com/quicksilver/Quicksilver/issues/2682>
- <https://github.com/quicksilver/Quicksilver/issues/2687>
- <https://github.com/quicksilver/Quicksilver/issues/2692>
- <https://github.com/quicksilver/Quicksilver/issues/2699>
- <https://github.com/quicksilver/Quicksilver/issues/2700>
- <https://github.com/quicksilver/Quicksilver/issues/2712>

**Comment by thirkej** [comment]
Apologies, I had forgotten that when I tried to update from 2.0 it hung.

Deleted quicksilver, installed from your web page and now all works perfectly.  Thank you for your quick response.
