### ISSUE TITLE
Upgrading from 2.0.1 Head to 2.0.1 4029 crashes

### ISSUE THREAD

**Issue by ahu45242** [quicksilver/Quicksilver#2732]
Attempted the upgrade 3 times. Each time it hung QS, requiring a Restart to get back to running it.
24 inch iMac M1 with 16 GB, running 12.3.1

**Comment by n8henrie** [comment]
The in-app update problem is a known issue, and we think is resolved, but requires a manual update to 2.0.3.

- <https://qsapp.com/changelog.php>
- <https://github.com/quicksilver/Quicksilver/issues/2720#issuecomment-1092738830>

If these don't resolve your problem, please let us know, and I'll be happy to re-open the issue.
