### ISSUE TITLE
[Bug]: app crashes after downloading a plugin

### ISSUE THREAD

**Issue by pilarArr** [quicksilver/Quicksilver#2736]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

When I try to install a plugin the app crashes just as the installation is finishing.

When I open the app again the app the plugin I clicked appears as if has been installed.
The app otherwise looks like it works but I haven't tested a lot since I just installed it.

I tried deleting all the plugins and trying again and also deleting the data cache, preferences and app support files.

### Steps to reproduce

1. Open Quicksilver preferences
2. go to plugins tab
3. click on any plugin to install

App crashes right when the download is finished.

### Expected behavior

The app finished the download and installation of the new plugin without crashing

### MacOS Version

macOS 11.6.5

### Quicksilver Version

2.0.3

### Relevant Plugins

any pluging causes this. I tried to install only the new plugins like clipboard, and the classic bezel theme. Nothing too old.

### Crash Logs or Spindump

[crash_report.txt](https://github.com/quicksilver/Quicksilver/files/8495708/crash_report.txt)

### Screenshots

https://user-images.githubusercontent.com/26302137/163566583-d7e05a57-a699-4698-be5b-f8ec596f687f.mov

**Comment by pjrobertson** [comment]
This issue has been fixed with version 2.1.0 of Quicksilver. You can download an update from: https://qsapp.com/download.php

Thanks!
