### ISSUE TITLE
[Bug]: Doesn't start at login, as configured

### ISSUE THREAD

**Issue by DougHockin** [quicksilver/Quicksilver#2738]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Quicksilver is configured to start at login, but does not. 

### Steps to reproduce

1. Logged in 
2. Quicksilver should have been running, but was not
3. Had to start it manually

### Expected behavior

Quicksilver is automatically running

### MacOS Version

macOS 11

### Quicksilver Version

2.0.3 (4031)

### Crash Logs or Spindump

system.log
Apr 15 07:11:33 Dougs-MacBook-Pro com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.blacktree.Quicksilver.8626705612.8626705911(501)> [679]
Apr 15 07:11:35 Dougs-MacBook-Pro Quicksilver[1648]: objc[1648]: Class FMDatabase is implemented in both /Applications/Quicksilver.app/Contents/Frameworks/QSFoundation.framework/Versions/A/Frameworks/FMDB.framework/Versions/A/FMDB (0x10205bb58) and /Users/Doug 1/Library/Application Support/Quicksilver/PlugIns/com.blacktree.Quicksilver.QSFirefoxPlugIn.BA.qsplugin/Contents/MacOS/Firefox Plugin (0x105883cf0). One of the two will be used. Which one is undefined.
Apr 15 07:11:35 Dougs-MacBook-Pro Quicksilver[1648]: objc[1648]: Class FMStatement is implemented in both /Applications/Quicksilver.app/Contents/Frameworks/QSFoundation.framework/Versions/A/Frameworks/FMDB.framework/Versions/A/FMDB (0x10205bb80) and /Users/Doug 1/Library/Application Support/Quicksilver/PlugIns/com.blacktree.Quicksilver.QSFirefoxPlugIn.BA.qsplugin/Contents/MacOS/Firefox Plugin (0x105883d40). One of the two will be used. Which one is undefined.
Apr 15 07:11:35 Dougs-MacBook-Pro Quicksilver[1648]: objc[1648]: Class FMResultSet is implemented in both /Applications/Quicksilver.app/Contents/Frameworks/QSFoundation.framework/Versions/A/Frameworks/FMDB.framework/Versions/A/FMDB (0x10205bbf8) and /Users/Doug 1/Library/Application Support/Quicksilver/PlugIns/com.blacktree.Quicksilver.QSFirefoxPlugIn.BA.qsplugin/Contents/MacOS/Firefox Plugin (0x105883d90). One of the two will be used. Which one is undefined.

**Comment by DougHockin** [comment]
In case it makes a difference, my MacBook Pro (Late 2013) is too old to run MacOS 12. I'm running 11.6.5.

**Comment by pjrobertson** [comment]
Hi @DougHockin 

Thank you for submitting the report. Can you please confirm that the option is enabled in the preferences to run Quicksilver: 
![Screenshot 2022-04-16 at 08 42 14](https://user-images.githubusercontent.com/150431/163655151-3bb26f57-cb2e-4cf8-a7cd-c62153577d54.png)

Your logs seem to indicate that Quicksilver is, in fact running. Perhaps it's not activating or it's crashing? You can double check that Quicksilver is running by enabling the "Show icon in dock" option from the image above - then you'll see an icon in the dock to know it's running.

Finally, if it isn't running, then please check for crash reports in Console.app (from the sidebar under 'User Reports'

**Comment by DougHockin** [comment]
The first two of those options were enabled, and I've now enabled the third one. I have just now also disabled all plugins (I don't use them, I think the installation of new ones must automatically enable them). I restarted my system and this time Quicksilver _did_ startup automatically as the system came up. I will close this and make a new problem report if it happens again. Thanks.

**Comment by pjrobertson** [comment]
Thanks for the update. I think this may be related to #2736 which we are currently in the process of fixing.

Thanks!
