### ISSUE TITLE
[Bug]: Numberblock on keyboard does not trigger

### ISSUE THREAD

**Issue by pawi-cmrg** [quicksilver/Quicksilver#2742]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

After 2.x update, my triggers, assigned to cmd+1/2/3/etc stopped working. 

The triggers work well with the assigned keys with the normal numbers above the keyboard, but not with the separate number block (on the same keyboard). I'm using the Apple Magic Keyboard with Numeric Keypad, Swiss Layout. I've tried different languages on the input source without success. 

### Steps to reproduce

1. Assign a trigger to a number (e.g. cmd+1)
2. Test cmd+1 on the number block

### Expected behavior

The trigger should also work on the number block, as before the 2.x update

### MacOS Version

macOS 12

### Quicksilver Version

2.0.3

**Comment by pjrobertson** [comment]
Thanks for reporting the bug. I can confirm that keyboard shortcuts are mixed between the keypad number block and the general numbers.

Can you please confirm that your expected behaviour/previous behavour is:

A trigger for ⌘1 works on both the keypad and normal number

Or:

You can have two separate ⌘1 triggers, one for the keypad and one for the normal numbers

Thanks

**Comment by pjrobertson** [comment]
Thanks for the update. We've created a fix which should be released soon.

To reiterate, the behaviour now is:

If I create a trigger for ⌘1, you can fire the trigger using the standard '1' above they keyboard, **and** by using the '1' on the keypad.

Thanks!

**Comment by pawi-cmrg** [comment]
Hey, very cool! Looking forward to the update. Thanks a lot for the fix. 

I'm so used to using your app without being aware it is there - always silently in the background making work a bit more efficient ;-) 

Will leave a donation. Cheers!

**Comment by pawi-cmrg** [comment]
works perfectly after update 2.1.0 (4032).
