### ISSUE TITLE
[Bug]: QS crashes when updating either the app itself or clipboard plugin

### ISSUE THREAD

**Issue by jonathanalevi** [quicksilver/Quicksilver#2744]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

I couldn't get any updates to work, so I overwrote the app itself w/ the app from the website, but I still can't update the clipboard plugin. App crashes every time I hit install. 

### Steps to reproduce

1. Go to preferences
2. Go to check now
<img width="560" alt="image" src="https://user-images.githubusercontent.com/1540530/164334708-8df52fab-e0f4-4ba7-86c8-6ec6b9c5dd41.png">

4. Hit "install" on the dialog

![Uploading image.png…]()

### Expected behavior

Plugin should update and all should work. 

### MacOS Version

macOS 12

### Quicksilver Version

2.03

### Relevant Plugins

Clipboard

### Screenshots

![Uploading image.png…]()

**Comment by n8henrie** [comment]
@jonathanalevi it sounds like clicking `install selected plugins` for the Clipboard plugin is crashing QS reproducibly, and that you're now running 2.0.3 but you also had a crash when updating. Does that sound right?

What version of the clipboard plugin is installed now?

**Comment by JoeInOhio** [comment]
I'm not the OP but having this problem as well. MacOS 12.0.1, Clipboard 1.7.1. Quicksilver Update 4027 -> 4031 just hangs (whether I select Clipboard in upgrade loop or not).

**Comment by pjrobertson** [comment]
> UPDATE: Downloaded QS 2.0.3 (4031 -- though it's seems to be referenced in the changelog as 2.0.2./4030) and this time when I ran the clipboard update QS crashed -- but seems to have installed the update anyway. ¯\_(ツ)_/¯

This is a known issue and should be fixed in a future update to be released soon.

**Comment by pjrobertson** [comment]
Please update to 2.1.0 of Quicksilver, just released. It should have fixed this issue.

**Comment by jonathanalevi** [comment]
I'm on 2.1.0 now, it allows updates, but I find it randomly crashes many times throughout the day. I don't discover that it's crashed till I try to invoke.
