### ISSUE TITLE
MacOS 12.2.1 QS constantly crashing.

### ISSUE THREAD

**Issue by codefish** [quicksilver/Quicksilver#2746]
Intermittently crashes repeatedly. Restart and it works for a while, then crashes again. Not specific as far as I can tell to any particular action.

**Comment by n8henrie** [comment]
I'm sorry you're running into trouble! Would you mind going back and using the issue template to help us get a little more information with which to work?

**Comment by pjrobertson** [comment]
We have just released v2.1.0 of Quicksilver which should fix these crashes on launch. You can download the latest version from: https://qsapp.com/download.php
