### ISSUE TITLE
"Latest Screenshot" proxy object

### ISSUE THREAD

**Issue by lgarron** [quicksilver/Quicksilver#2749]
I find myself *constantly* pulling up the latest screenshot. The sharing tool in the lower right-hand corner is limited, and after a few years I turned it off in favor of working with the image file directly. I'd love something like "Latest Download", but "Latest Screenshot" instead. The implementation details are actually fairly similar (and should maybe share code?), and I have a branch with partial work.

https://github.com/lgarron/Quicksilver/compare/a1c47c23a1c65344f69ead2a0053ca92fc5012e5...latest-screenshot

Mostly filing this issue as context for a follow-up bug.

**Comment by lgarron** [comment]
> The implementation details are actually fairly similar (and should maybe share code?), and I have a branch with partial work.

Looks like there's at least one bug in the existing code that prevents a Safari downloads folder with spaces from working:
https://github.com/quicksilver/Quicksilver/blob/master/Quicksilver/Code-QuickStepCore/QSDownloads.m#L48

**Comment by pjrobertson** [comment]
Fixed by #2752
