### ISSUE TITLE
Show Other Results: Delayed doesn't work if "Reset search after:" is disabled

### ISSUE THREAD

**Issue by pjrobertson** [quicksilver/Quicksilver#2753]
1. Set up prefs as below:
![Screenshot 2022-04-27 at 15 57 59](https://user-images.githubusercontent.com/150431/165470098-f6981ac4-141e-472c-8336-54367b3103d8.png)
2. Search, and see how the results are displayed immediately.

Expected behaviour: results are delayed when displaying.

Relevant code is: `QSSearchObjectView.m:L854` - the time to display the results list uses the `reseat search after` value. It should have it's own preferences, or just be hard-coded e.g. as 0.5s for simplicity

**Comment by skurfer** [comment]
After a lot of experimenting, I settled on 1.1s for myself. I can’t imagine there’s a value that would make everyone happy, but maybe that’s a better default?

**Comment by pjrobertson** [comment]
Yeah, 1.1s sounds more reasonable to me. I don't want to give people who've been using the default 2s a scare if we make it _too_ short, so I'll change it to 1.5s in `main` now
