### ISSUE TITLE
Function key not functioning since QS 1.2.0

### ISSUE THREAD

**Issue by Bif2** [quicksilver/Quicksilver#2863]
Since the recent upgrade to 2.1.0 (4032), I'm been unable to assign a trigger in QS to function key 14. The trigger reads as "Fn-" without a number following Fn. I can use keyboard preferences in System Preferences to assign other actions to F14, and they work just fine, so I know the key/keyboard (Apple external keyboard) is not the issue. All the other function keys are working normally in QS.

**Comment by pjrobertson** [comment]
Thanks for reporting this. There indeed was an issue with just the F14 key. This will be fixed in the next version we release.
