### ISSUE TITLE
[Bug]: Mac Notes.app crashes on QS launch

### ISSUE THREAD

**Issue by PeterJ1947** [quicksilver/Quicksilver#2867]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Mac mini M1, OS 12.3.1, 16GB, QS 2.1.0 (4032). Have been using QS for several years. With latest update any launch of Notes.app from QS causes Notes to crash on launch. Notes will launch successfully when double-clicked from Finder. This is only app I have found this on, all other apps that I use routinely (Mail, Safari, Pages, BusyCal, PDFPro, Messages, etc) launch fine from QS. Crash report in attached file
[Notes Crash Report.pdf](https://github.com/quicksilver/Quicksilver/files/8645591/Notes.Crash.Report.pdf)
.

### Steps to reproduce

1. Press cmd-space to launch QS
2.Press "N" to select NOtes.app
3.Press <return> to launch Notes.app
4.Mac beeps and returns crash report indicating Notes has crashed.
5. Multiple attempts return same effect, including after computer restarts

### Expected behavior

Notes.app should launch successfully 100% of the time, just like other apps.

### MacOS Version

macOS 12

### Quicksilver Version

2.1.0

### Relevant Plugins

None that I know of are relevant -- however Maestral (Dropbox clone), Hazel, Backblaze, Default Folder X and Time Machine are all running.

### Crash Logs or Spindump

Attached above.

**Comment by n8henrie** [comment]
Launches Notes.app without trouble here (m1 mbp).

A few odd things:

```
EXC_CRASH (SIGKILL (Code Signature Invalid))
``` 

That seems odd -- how did you install quicksilver?

```
"procPath" : "\/Volumes\/VOLUME\/*\/Notes.app\/Contents\/MacOS\/Notes",
```

That doesn't look like the right path. Can you send me a screenshot of what QS looks like after step 2 but before step 3? Could you have something else mounted in `/Volumes` that is launching the wrong `Notes.app`?

For example:

<img width="368" alt="Screen Shot 2022-05-09 at 14 11 02" src="https://user-images.githubusercontent.com/1234956/167489585-18b0f773-cbf5-4aa5-beae-fbc30c054f55.png">

This shouldn't be right either, both Notes and QS should be running natively as arm64.

```
"cpuType" : "X86-64",
```

**Comment by PeterJ1947** [comment]
Nathan your note put me on the right path to solve this.

Here’s the screenshot you asked for:



This is pointing to the wrong volume and copy of Notes — this is a copy stored on a mounted backup disk which archived the contents of my wife’s old iMac and some legacy financial reports that we need to keep for tax purposes.

I can fix this! I navigate to the right copy of Notes (not the one built for an Intel CPU) and make that default…




Sorry for the trouble … next time I’ll check the path!

Peter


Peter Jones			
***@***.***	
571.490.5364

**Comment by n8henrie** [comment]
No trouble at all, glad to get it sorted out.

BTW, your screenshot didn't come through (maybe due to sending via email). However your full name and phone number did -- I updated your response to remove them and  deleted the revision that had them. Just FYI!

**Comment by PeterJ1947** [comment]
Thank you sir — both for the help and the courtesy!
