### ISSUE TITLE
[Bug]: Files dragged to the shelf don't stay there across sessions.

### ISSUE THREAD

**Issue by g1oria** [quicksilver/Quicksilver#2873]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Alias folders/files added to the shelf via the interface stay just fine in the shelf across sessions, but aliases added via drag & drop do not. See video for demo. 

https://user-images.githubusercontent.com/17694864/167720897-c715d093-2b70-4ef1-8a22-0bcc23bf10ad.mp4

### Steps to reproduce

1. Drag & drop an alias from Finder to shelf.
2. Relaunch QS.
3. Item isn't there.

### Expected behavior

Items added to the shelf via either method should stay across sessions.

### MacOS Version

macOS 10.15

### Quicksilver Version

2.1.0

### Relevant Plugins

Shelf

**Comment by pjrobertson** [comment]
Thanks for the video, Gloria. That's helped in isolating the issue. I've renamed and edited your Bug Report for clarity

**Comment by g1oria** [comment]
You're welcome & thanks! 😁Message ID:
***@***.***>

>

**Comment by pjrobertson** [comment]
Developer notes:

So this issue ultimately has to do with getting items off the clipboard in `QSObject_Pasteboard.m`, specifically `objectForPasteboardType`. Really, we should switch away from the hacks in there, to the newer `NSPasteboardWriting` and `NSPasteboardReading` protocols.
