### ISSUE TITLE
[Bug]: Version 2.2.0 is unpredictable

### ISSUE THREAD

**Issue by skurfer** [quicksilver/Quicksilver#2880]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

As far as I can tell, pressing ↩ to execute a command causes one or more panes to change to something else just before execution.

I’ve seen actions change to things that shouldn’t be allowed in the 2nd pane and I’ve seen the first pane change to and launch a different app.

The scary thing is, you don’t know what’s going to happen because everything is fine right up until you hit ↩.

#### Alternate actions

1. Select a Remote Host
2. Hold ⌘ to change the action to **SSH as Root**
3. Press ↩
4. The action switches from **SSH as Root** to **DuckDuckGo** which is my default web search.
5. Thankfully, nothing happens since that’s not an action.

1. Select a file (I had an `smb.conf` laying around that I used)
2. Hold ⌘ to change the action to **Reveal**
3. Press ↩
4. Earlier, the action would change to **Use as Remote Host** and run, but now it seems to change to **DuckDuckGo**

#### Launching Apps

I can’t reproduce this with all apps, but Little Snitch does it pretty regularly. I just launched Little Snitch 3 times and here’s what launched:

* Firefox Developer Edition
* Little Snitch
* Apple Music

### Expected behavior

Pressing ↩ should not change the selection in any of the panes.

I’m looking into this, but a lot has changed recently so if this sets off any lightbulbs, let me know.

### MacOS Version

macOS 12

### Quicksilver Version

2.2.0

**Comment by n8henrie** [comment]
Hmmm, yeah some funky stuff. I've been out of town and hadn't updated until I saw this.

Picked a URL -> `open url` and instead I saw this: 

<img width="1299" alt="Screen Shot 2022-05-23 at 15 58 04" src="https://user-images.githubusercontent.com/1234956/169912186-085df708-3621-4214-98b9-02482d117063.png">

Just did `google.com` -> `open url` a few times and it copied to clipboard instead. `google.com` -> `type text` worked. `google.com` -> `open url` again and it typed the text a second time.

You can *briefly* see it change as you hit enter.

We should probably keep the tag but take down the release (at least for the moment). I don't think this ever got pushed to `qsapp.com`.

**Comment by skurfer** [comment]
If it’s pre-release, maybe it’s OK to leave it for now? I haven’t looked lately at how many people are getting them. I’m getting Developer Previews, of course. I’ll go back to 2.1.0 while we investigate.

**Comment by kzykx** [comment]
alternative action ( triggered by Command + Enter) does not work properly.

**Comment by kzykx** [comment]
https://user-images.githubusercontent.com/102411489/170011408-0398b0bd-b81f-4b3d-9cc2-5cb8a131d497.mov

**Comment by pjrobertson** [comment]
I've just noticed this. I've dropped 2.2.0 back down to pre-release and will look into it today. My guess is it's to do with the search string clearing from #2642

**Comment by pjrobertson** [comment]
I found the issue, and fixed it in 39c50f2b22c45686e5930de8791d689f7f205d1d

**Comment by pjrobertson** [comment]
Please update to version 2.2.1, thanks!
