### ISSUE TITLE
[Bug]: Version 2.2.0 Menu appears, but no window

### ISSUE THREAD

**Issue by DougHockin** [quicksilver/Quicksilver#2881]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

I select an application with Quicksilver, the menu for that application appears, but not the application window. I have multiple desktops live and normally Quicksilver would switch to the desktop with the application window, but now I have to go searching myself for the desktop with the application window. It's really annoying as I can do that without Quicksilver.

### Steps to reproduce

1. Use Quicksilver to select an application who's window is not in the currently active desktop.
2. Observe the menu bar switches to the selected application
3. But the window for the application is not visible, because a switch to the desktop with the application did not happen.

### Expected behavior

Quicksilver should have switched to the desktop with the application in it.

### MacOS Version

macOS 11

### Quicksilver Version

2.2.0

**Comment by DougHockin** [comment]
I also think Quicksilver just crashed on me, because I had to restart it.

**Comment by DougHockin** [comment]
I have an older Macbook Pro (Retina, 13", late 2013), that's why the older OS.

**Comment by skurfer** [comment]
What do you have selected under Preferences → General → Extras → Reopening the current application?

**Comment by DougHockin** [comment]
Have tried all three settings, and they all behave the same. It opens the menu for (Thunderbird, e.g.) in the selected app in current desktop, but I have switch to a different desktop to find Thunderbird.

**Comment by kzykx** [comment]
confirmed on my MacBook Pro (Retina, 13-inch, Mid 2014) with macOS 11.6.6.
Quicksilver crashed when waked up from one night sleep.

**Comment by pjrobertson** [comment]
The crashes linked to by kzykx are being tracked in issue #2886.


@DougHockin  - can you please confirm what you mean when you say:

> 1. Use Quicksilver to select an application who's window is not in the currently active desktop.

Are you using the 'Open' action to 'open' the application? Or something else? If you are able to provide screenshots, that will also be very helpful.

Thank you

**Comment by pjrobertson** [comment]
Please try the latest version - v2.2.3 of Quicksilver and let us know if it works. I am going to close this issue now.

If you are still encountering problems, then please re-open a ticket, and provide answers to my question:

> Are you using the 'Open' action to 'open' the application? Or something else? If you are able to provide screenshots, that will also be very helpful.
