### ISSUE TITLE
[Bug]: Version 2.2.0 (4033) is crashing with sigsegv

### ISSUE THREAD

**Issue by DougHockin** [quicksilver/Quicksilver#2882]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Quicksilver crashes with SIGSEGV

### Steps to reproduce

1. Start Quicksilver and use it for a while
2. It crashes
3.

### Expected behavior

Shouldn't crash, but:

May 25 20:10:50 Dougs-MacBook-Pro com.apple.xpc.launchd[1] (application.com.blacktree.Quicksilver.8628724025.8628724030[18737]): Service exited due to SIGSEGV | sent by exc handler[18737]

### MacOS Version

macOS 11

### Quicksilver Version

2.2.0 (4033)

### Crash Logs or Spindump

No crash log available, just a message in system.log: May 25 20:10:50 Dougs-MacBook-Pro com.apple.xpc.launchd[1] (application.com.blacktree.Quicksilver.8628724025.8628724030[18737]): Service exited due to SIGSEGV | sent by exc handler[18737]

**Comment by fraserw** [comment]
Seeing the same behavior. OSX 11.6.5.

**Comment by pjrobertson** [comment]
Please try looking in Console.app here for a crash log, and then uploading it:
![Screen Region 2022-05-27 at 17 23 03](https://user-images.githubusercontent.com/150431/170671428-aece3f24-22b1-4c5c-8604-993da0f5ee3d.png)

**Comment by DougHockin** [comment]
I've looked. There are no crash reports. The SIGSEGV is happening repeatedly, a dozen times a day. My system has no User Reports (folder?) showing in the console, only Crash, Spin, Log, Diagnostic, Analytics and system.log. Is it possible some system configuration is (by default?) preventing it from creating crash reports?

**Comment by nevioth** [comment]
attaching txt of report [crash.txt](https://github.com/quicksilver/Quicksilver/files/8792384/crash.txt)

**Comment by DougHockin** [comment]
On both old and new hardware architectures. Looks like corruption of malloced memory pool.

**Comment by DougHockin** [comment]
Duplicate of bug report #2878.

**Comment by n8henrie** [comment]
I'll go ahead and close as duplicate as the other issue precedes this one, and the conversation seems to be consolidating there, and @pjrobertson has [submitted a potential fix](https://github.com/quicksilver/Quicksilver/issues/2878#issuecomment-1141559146) -- thank you @DougHockin and @nevioth, please let us know if this needs to be re-opened.
