### ISSUE TITLE
[Bug]: Ctrl-Space hotkey doesn't activate QS and non-hotkey activate QS v2.2.2

### ISSUE THREAD

**Issue by NaokiMatsuzaki** [quicksilver/Quicksilver#2885]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

I searched and found several closed issues on Ctrl-Space. But I couldn't find any open issue on the latest version. I set Ctrl-Space as a hotkey. When I use "ABC" layout, Ctrl-Space activate QS. But when I switch to "Dvorak" layout, Ctrl-Space doesn't activate QS. I assume that keyboard layouts are sane because when I set Ctrl-Space as a shortcut for Spotlight, it activates in both layouts.

I found that keys other than Space activate QS even if I don't set them as hotkeys. I use MacBookPro Japanese(JIS) keyboard. It has two keys for switching input sources. 
Japanese Eisuu key (a key between left-⌘ and space, labeled "英数"), keyCode: 102/0x66
Japanese Kana key (a key between right-⌘ and space, labeled "かな"), keyCode: 104/0x68
When I press these key with Ctrl key, QS is activated.

I run the following command in Terminal. Hotkey's keyCode is different from these keys.
> ❯ defaults read com.blacktree.Quicksilver QSActivationHotKey
>{
>    character = " ";
>   keyCode = 49;
>    modifiers = 262401;
>}

### Steps to reproduce

1. Switch input source to "ABC" layout.
2. Open QS and set Activation Shortcut to Ctrl-Space (shown as "⌃␣").
3. Press Ctrl-Space and confirm that QS is activated(expected).
4. Press Ctrl-Eisuu and confirm that QS is not activated(expected).
5. Press Ctrl-Kana and confirm that QS is activated(not expected).
6. Switch input source to "Dvorak" layout (Same behavior in "Dvorak - Qwerty ⌘" or "Colemak").
7. Press Ctrl-Space and confirm that QS is not activated(not expected).
8. Press Ctrl-Eisuu and confirm that QS is activated(not expected).
9. Press Ctrl-Kana and confirm that QS is activated(not expected).

### Expected behavior

QS is activated after pressing Ctrl-Space in both layouts.
QS is not activated after pressing Ctrl-Eisuu or Ctrl-Kana in both layouts.

### MacOS Version

macOS 12

### Quicksilver Version

2.2.2(4036)

### Additional info

For non-JIS keyboard, Eisuu / Kana keys are available via [Karabiner-Elements](https://karabiner-elements.pqrs.org).

**Comment by pjrobertson** [comment]
Thank you fr the very detailed bug report. I am unable to reproduce the issue, but have not tried using a JIS keyboard.

Before I do that - what happens if you enable the option in Quicksilver to always use a specific keyboard layout:
![Screen Region 2022-06-08 at 22 53 31](https://user-images.githubusercontent.com/150431/172648285-f5cc87c0-99bb-4ec5-ab65-e375975250d7.png)

**Comment by NaokiMatsuzaki** [comment]
Thank you for your reply. First I enabled the option and set it to switch "ABC". Next I set it "Dvorak". In each case the behavior of hotkeys was the same as my previous post. Once QS is activated, input source was switched to the corresponding layout properly.

I noticed that the behavior of hotkeys depends on the keyboard type of System Preferences. I connected BlueTooth wireless keyboards and tapped System Preferences > Keyboard > Change Keyboard Type and opened Keyboard Setup Assistant. Then I selected keyboard type in Select Keyboard Type menu. This menu seems unavailable to built-in keyboard. When I selected ANSI or ISO type, wireless keyboards' hotkey worked in both "ABC" and "Dvorak". When I selected JIS type, it didn't work in "Dvorak". I checked only Ctrl-Space key this time. MBP built-in JIS keyboard's behavior didn't change in all cases.

JIS keyboard + JIS type: didn't work in "Dvorak"
ANSI keybard + JIS type: didn't work in "Dvorak"
JIS keyboard + ANSI or ISO type: worked in both layouts
ANSI keyboard + ANSI or ISO type: worked in both layouts

**Comment by pjrobertson** [comment]
Thank you for the update, @NaokiMatsuzaki .

I am trying to understand the issue, and have enabled the JIS keyboard for me. Here is what I see:
![Screen Region 2022-06-10 at 21 42 39](https://user-images.githubusercontent.com/150431/173078859-7579f721-5a70-47a2-839b-56f1b837042a.png)

I do not see a Ctrl key on this keyboard layout. Can you please either link to an actual image of the keyboard you use, or let me know which key (highlight it in the image) when you say the 'Ctrl' key.

I am confident we will be able to fix this soon!

**Comment by NaokiMatsuzaki** [comment]
Thank you for your help. When I say "Ctrl" key, it means the left Control (⌃) key between Tab (⇥) and left Shift (⇧) key. Its position is swapped with Caps Lock (⇪) key.
![dvorak](https://user-images.githubusercontent.com/11068788/173148245-0c7c40d8-a0c5-407d-a6b1-aafde976b07c.png)

**Comment by pjrobertson** [comment]
I see, thank you for confirming.

I'm pleased to say that this issue should now be fixed, and will be out in the next release of Quicksilver soon. You can, however, confirm this has been fixed by downloading the Quicksilver-debug version from here and testing it: https://github.com/quicksilver/Quicksilver/actions/runs/2478332286

This was a very interesting problem to solve! Thank you again for your clear descriptions and responses.  ありがとう
