### ISSUE TITLE
[Bug]: Random crashes with SIGSEGV

### ISSUE THREAD

**Issue by DougHockin** [quicksilver/Quicksilver#2888]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Jun 12 21:03:46 Dougs-MacBook-Pro com.apple.xpc.launchd[1] (application.com.blacktree.Quicksilver.8629485942.8629485948[2362]): Service exited due to SIGSEGV | sent by exc handler[2362]

Version: 2.2.2 
OSX version: 11.6.7

The bug was closed, but it's still happening for me

See original report #2882

### Steps to reproduce

1. Go to use Quicksilver
2. Notice that it's not running
3. Have to restart it manually

### Expected behavior

Should not die repeatedly

### MacOS Version

macOS 11

### Quicksilver Version

2.2.2

### Relevant Plugins

None

### Crash Logs or Spindump

No crash log, just message in system.log:
Jun 12 21:03:46 Dougs-MacBook-Pro com.apple.xpc.launchd[1] (application.com.blacktree.Quicksilver.8629485942.8629485948[2362]): Service exited due to SIGSEGV | sent by exc handler[2362]

**Comment by pjrobertson** [comment]
Thanks for re-reporting Doug. Have you tried downloading version 2.2.3 and testing that?

**Comment by foodydude** [comment]
I'm having constant crashing issues (every minute or so), but I'm on 12.4 on an Apple Silicon Macbook Pro 14". I don't see documentation saying it's supported or not on M1 chip macs...

**Comment by n8henrie** [comment]
@foodydude I'm on 12.4 on an M1 MBP and QS is more stable than it's been in years here. Can you upload a spindump or crash log?

**Comment by foodydude** [comment]
Yep, that's what's causing it, I just tried to add a Safari plugin and it crashes instantly. I'm a new user so I was just trying plugins, maybe I don't even need those installed...

**Comment by n8henrie** [comment]
@foodydude Can you make a new issue? I'd like to look into the Safari plugin crash, but let's keep it separate from this.

**Comment by DougHockin** [comment]
I've been using 2.2.3 on my Macbook Pro. late 2013, 13" running 11.6.7 for a couple days now with no crashes. I'm ok with closing this issue as my problem seems fixed.

**Comment by n8henrie** [comment]
Thanks for the followup!

**Comment by DougHockin** [comment]
I'm running 2.4.0. The crashes are still happening for me, but very infrequently. Once every week or two.
