### ISSUE TITLE
[Bug]: "System Applications" catalog missing in 2.2.3 (4037)

### ISSUE THREAD

**Issue by fschulze** [quicksilver/Quicksilver#2890]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

With 2.2.3 (4037) the "System Applications" catalog is missing and apps like Messages and Terminal aren't picked up anymore. Downgrading to 2.2.2 (4036) restores the missing catalog and everything works as expected.

### Steps to reproduce

1. Install 2.2.3 (4037)
2. After restart the "System Applications" catalog is gone and the apps in it aren't selectable anymore
3. Downgrade to 2.2.2 (4036)
4. After restart everything is as expected again

### Expected behavior

The "System Applications" catalog should show up in current Quicksilver versions.

### MacOS Version

macOS 12

### Quicksilver Version

2.2.3 (4037)

**Comment by pjrobertson** [comment]
Thank you @fschulze for the bug report.

This was inadvertently removed in Quicksilver v2.2.3, but will be restored in the next version. In the meantime, you may download and use a copy of Quicksilver with this fixed from here: https://github.com/quicksilver/Quicksilver/actions/runs/2495484067
