### ISSUE TITLE
[Bug]: Crash when installing the Safari Plugin

### ISSUE THREAD

**Issue by foodydude** [quicksilver/Quicksilver#2891]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Every time I try to install the Safari plugin, it starts installing (progress bar) but then the entire Quicksilver app crashes. Running on M1 Pro processor Macbook Pro 12.4 OS and is 2.2.3 version of QS

### Steps to reproduce

1. Launch Quicksilver
2. Go into Plugins section, check the box for Safari Plugin
3.

### Expected behavior

Finish installing the plugin and let me use it without a crash

### MacOS Version

macOS 12

### Quicksilver Version

2.2.3

### Relevant Plugins

Safari Plugin...actually this happens with other plugins as well.

### Crash Logs or Spindump

{"app_name":"Quicksilver","timestamp":"2022-06-16 10:23:36.00 -0600","app_version":"2.2.3","slice_uuid":"53c8bf11-b4f4-3349-a562-e65ef8041d9c","build_version":"4037","platform":1,"bundleID":"com.blacktree.Quicksilver","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.4 (21F79)","incident_id":"BD501ADF-8B69-440C-A9D6-9E9704FB205B","name":"Quicksilver"}
{
  "uptime" : 140000,
  "procLaunch" : "2022-06-15 16:51:44.6626 -0600",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 503,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,3",
  "procStartAbsTime" : 3158445229979,
  "coalitionID" : 15799,
  "osVersion" : {
    "train" : "macOS 12.4",
    "build" : "21F79",
    "releaseType" : "User"
  },
  "captureTime" : "2022-06-16 10:23:33.5198 -0600",
  "incident" : "BD501ADF-8B69-440C-A9D6-9E9704FB205B",
  "bug_type" : "309",
  "pid" : 29798,
  "procExitAbsTime" : 3424016558659,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "Quicksilver",
  "procPath" : "\/Applications\/Quicksilver.app\/Contents\/MacOS\/Quicksilver",
  "bundleInfo" : {"CFBundleShortVersionString":"2.2.3","CFBundleVersion":"4037","CFBundleIdentifier":"com.blacktree.Quicksilver"},
  "storeInfo" : {"deviceIdentifierForVendor":"5C1579ED-F5BF-54F8-8F99-AA5A700430BD","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.blacktree.Quicksilver",
  "crashReporterKey" : "5377065A-3EFE-DEF9-7A16-A4567C0A6480",
  "wakeTime" : 8753,
  "sleepWakeUUID" : "8031767C-D4C5-4A1A-9245-83D16958CBE9",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000199c8b76c","rawCodes":[1,6875035500],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":29798},
  "asi" : {"libdispatch.dylib":["BUG IN CLIENT OF LIBDISPATCH: dispatch_sync called on queue already owned by current thread","Abort Cause 9005678836318464"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":1564270,"threadState":{"x":[{"value":6092115280},{"value":8368700608,"symbolLocation":0,"symbol":"_dispatch_main_q"},{"value":4377955128,"symbolLocation":0,"symbol":"__20-[QSTask setStatus:]_block_invoke"},{"value":2},{"value":8368700608,"symbolLocation":0,"symbol":"_dispatch_main_q"},{"value":18},{"value":115},{"value":0},{"value":9005678836318464},{"value":3},{"value":18410715414129541122},{"value":137438953474},{"value":68719476736},{"value":9005068950962176},{"value":2636531712},{"value":8363480144,"symbolLocation":0,"symbol":"OBJC_CLASS_$___NSCFString"},{"value":6875034768,"symbolLocation":0,"symbol":"_dispatch_async_and_wait_invoke"},{"value":8368698072,"symbolLocation":0,"symbol":"OBJC_CLASS_$_OS_dispatch_queue_main"},{"value":0},{"value":6092115280},{"value":8368700608,"symbolLocation":0,"symbol":"_dispatch_main_q"},{"value":6092115440},{"value":8368700608,"symbolLocation":0,"symbol":"_dispatch_main_q"},{"value":105553126218464},{"value":105553157140096},{"value":4378092344},{"value":764504178868},{"value":7168},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":13191184052931572396},"cpsr":{"value":1610616832},"fp":{"value":6092115264},"sp":{"value":6092115232},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":6875035500,"matchesCrashFrame":1},"far":{"value":5176143432}},"queue":"QSCatalogEntry scanQueue: QSPresetSafariBookmarks","frames":[{"imageOffset":79724,"symbol":"__DISPATCH_WAIT_FOR_QUEUE__","symbolLocation":476,"imageIndex":0},{"imageOffset":78508,"symbol":"_dispatch_sync_f_slow","symbolLocation":144,"imageIndex":0},{"imageOffset":78508,"symbol":"_dispatch_sync_f_slow","symbolLocation":144,"imageIndex":0},{"imageOffset":312072,"symbol":"-[QSTask setStatus:]","symbolLocation":132,"imageIndex":1},{"imageOffset":99480,"symbol":"-[QSLibrarian updateScanTask:]","symbolLocation":552,"imageIndex":1},{"imageOffset":496908,"symbol":"__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__","symbolLocation":28,"imageIndex":2},{"imageOffset":1170440,"symbol":"___CFXRegistrationPost_block_invoke","symbolLocation":52,"imageIndex":2},{"imageOffset":1170292,"symbol":"_CFXRegistrationPost","symbolLocation":456,"imageIndex":2},{"imageOffset":295344,"symbol":"_CFXNotificationPost","symbolLocation":732,"imageIndex":2},{"imageOffset":40136,"symbol":"-[NSNotificationCenter postNotificationName:object:userInfo:]","symbolLocation":96,"imageIndex":3},{"imageOffset":53448,"symbol":"__30-[QSCatalogEntry indexIsValid]_block_invoke","symbolLocation":84,"imageIndex":1},{"imageOffset":16820,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":0},{"imageOffset":78868,"symbol":"_dispatch_lane_barrier_sync_invoke_and_complete","symbolLocation":56,"imageIndex":0},{"imageOffset":49116,"symbol":"-[QSCatalogEntry indexIsValid]","symbolLocation":156,"imageIndex":1},{"imageOffset":50812,"symbol":"-[QSCatalogEntry scanForced:]","symbolLocation":340,"imageIndex":1},{"imageOffset":50732,"symbol":"-[QSCatalogEntry scanForced:]","symbolLocation":260,"imageIndex":1},{"imageOffset":94300,"symbol":"-[QSLibrarian registerPresets:inBundle:scan:]","symbolLocation":536,"imageIndex":1},{"imageOffset":109260,"symbol":"-[QSLibrarian(QSPlugInInfo) handleInfo:ofType:fromBundle:]","symbolLocation":36,"imageIndex":1},{"imageOffset":236384,"symbol":"-[QSPlugIn(Registry) _registerPlugIn]","symbolLocation":704,"imageIndex":1},{"imageOffset":237496,"symbol":"-[QSPlugIn(Registry) registerPlugIn]","symbolLocation":324,"imageIndex":1},{"imageOffset":245012,"symbol":"-[QSPlugInManager liveLoadPlugIn:]","symbolLocation":296,"imageIndex":1},{"imageOffset":257780,"symbol":"-[QSPlugInManager plugInWasInstalled:]","symbolLocation":220,"imageIndex":1},{"imageOffset":267316,"symbol":"__37-[QSPlugInManager downloadDidFinish:]_block_invoke","symbolLocation":204,"imageIndex":1},{"imageOffset":9712,"symbol":"_dispatch_call_block_and_release","symbolLocation":32,"imageIndex":0},{"imageOffset":16820,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":0},{"imageOffset":75468,"symbol":"_dispatch_main_queue_drain","symbolLocation":928,"imageIndex":0},{"imageOffset":74524,"symbol":"_dispatch_main_queue_callback_4CF","symbolLocation":44,"imageIndex":0},{"imageOffset":813596,"symbol":"__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__","symbolLocation":16,"imageIndex":2},{"imageOffset":539816,"symbol":"__CFRunLoopRun","symbolLocation":2532,"imageIndex":2},{"imageOffset":535332,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":2},{"imageOffset":205624,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":4},{"imageOffset":204980,"symbol":"ReceiveNextEventCommon","symbolLocation":564,"imageIndex":4},{"imageOffset":204392,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":72,"imageIndex":4},{"imageOffset":268172,"symbol":"_DPSNextEvent","symbolLocation":860,"imageIndex":5},{"imageOffset":262276,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":1328,"imageIndex":5},{"imageOffset":205392,"symbol":"-[NSApplication run]","symbolLocation":596,"imageIndex":5},{"imageOffset":14700,"symbol":"NSApplicationMain","symbolLocation":1132,"imageIndex":5},{"imageOffset":20620,"symbol":"start","symbolLocation":520,"imageIndex":6}]},{"id":1564293,"name":"com.apple.NSEventThread","frames":[{"imageOffset":6320,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":7},{"imageOffset":7456,"symbol":"mach_msg","symbolLocation":76,"imageIndex":7},{"imageOffset":545456,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":2},{"imageOffset":538464,"symbol":"__CFRunLoopRun","symbolLocation":1180,"imageIndex":2},{"imageOffset":535332,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":2},{"imageOffset":1762164,"symbol":"_NSEventThread","symbolLocation":196,"imageIndex":5},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":8},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":8}]},{"id":1564294,"name":"LocalStorage","frames":[{"imageOffset":21104,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":7},{"imageOffset":30780,"symbol":"_pthread_cond_wait","symbolLocation":1236,"imageIndex":8},{"imageOffset":1650804,"symbol":"WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)","symbolLocation":2076,"imageIndex":9},{"imageOffset":394428,"symbol":"bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&)","symbolLocation":248,"imageIndex":10},{"imageOffset":409648,"symbol":"WebCore::StorageThread::threadEntryPoint()","symbolLocation":296,"imageIndex":10},{"imageOffset":1767812,"symbol":"WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)","symbolLocation":244,"imageIndex":9},{"imageOffset":45456,"symbol":"WTF::wtfThreadEntryPoint(void*)","symbolLocation":16,"imageIndex":9},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":8},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":8}]},{"id":1564732,"name":"VDKQueue Watcher Thread","frames":[{"imageOffset":31776,"symbol":"kevent","symbolLocation":8,"imageIndex":7},{"imageOffset":337748,"symbol":"-[VDKQueue watcherThread:]","symbolLocation":260,"imageIndex":1},{"imageOffset":378428,"symbol":"__NSThread__start__","symbolLocation":808,"imageIndex":3},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":8},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":8}]},{"id":1565029,"name":"com.apple.CFStream.LegacyThread","frames":[{"imageOffset":6320,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":7},{"imageOffset":7456,"symbol":"mach_msg","symbolLocation":76,"imageIndex":7},{"imageOffset":545456,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":2},{"imageOffset":538464,"symbol":"__CFRunLoopRun","symbolLocation":1180,"imageIndex":2},{"imageOffset":535332,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":2},{"imageOffset":1070596,"symbol":"_legacyStreamRunLoop_workThread","symbolLocation":300,"imageIndex":2},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":8},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":8}]},{"id":1749337,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}]},{"id":1749350,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}]},{"id":1749529,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}]},{"id":1749723,"name":"JavaScriptCore libpas scavenger","frames":[{"imageOffset":21104,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":7},{"imageOffset":30780,"symbol":"_pthread_cond_wait","symbolLocation":1236,"imageIndex":8},{"imageOffset":2271276,"symbol":"scavenger_thread_main","symbolLocation":1088,"imageIndex":9},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":8},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":8}]},{"id":1749761,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6874955776,
    "size" : 290816,
    "uuid" : "f9300d47-d3db-3349-8a6d-acb68cd9983b",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4377640960,
    "CFBundleIdentifier" : "com.blacktree.QSCore",
    "size" : 442368,
    "uuid" : "7f652316-5216-3dc6-bb53-21b451f5dfd3",
    "path" : "\/Applications\/Quicksilver.app\/Contents\/Frameworks\/QSCore.framework\/Versions\/A\/QSCore",
    "name" : "QSCore",
    "CFBundleVersion" : "2.3"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6877118464,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5533696,
    "uuid" : "994db908-11a1-3e43-b7df-25c09d51368a",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1863"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6892859392,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 4136960,
    "uuid" : "a2e534d9-cdf0-397f-a41e-147559c83893",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "1863"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7024480256,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3358720,
    "uuid" : "f842b96a-54f3-36f3-9b94-b258fae1b7eb",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6922895360,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15433728,
    "uuid" : "a773dd23-b1c8-3c9b-9175-9a71d210ace0",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.50.132"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4379164672,
    "size" : 393216,
    "uuid" : "d9c2a46e-8dc4-3950-9d6a-f799e8ccb683",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6876565504,
    "size" : 229376,
    "uuid" : "03f48dc5-caa7-3678-af61-1a3c7fa8b06e",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6876794880,
    "size" : 53248,
    "uuid" : "42166a2c-89a9-3c38-a215-f028544cea23",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7284678656,
    "CFBundleShortVersionString" : "17613",
    "CFBundleIdentifier" : "com.apple.JavaScriptCore",
    "size" : 21479424,
    "uuid" : "0955690f-fafd-3963-ae7e-309049449fe2",
    "path" : "\/System\/Library\/Frameworks\/JavaScriptCore.framework\/Versions\/A\/JavaScriptCore",
    "name" : "JavaScriptCore",
    "CFBundleVersion" : "17613.2.7.1.8"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7252541440,
    "CFBundleShortVersionString" : "17613",
    "CFBundleIdentifier" : "com.apple.WebKitLegacy",
    "size" : 1835008,
    "uuid" : "c97ea816-7964-3818-bde2-23b350a97b1b",
    "path" : "\/System\/Library\/Frameworks\/WebKit.framework\/Versions\/A\/Frameworks\/WebKitLegacy.framework\/Versions\/A\/WebKitLegacy",
    "name" : "WebKitLegacy",
    "CFBundleVersion" : "17613.2.7.1.8"
  }
],
  "sharedCache" : {
  "base" : 6873497600,
  "size" : 3136077824,
  "uuid" : "513553bb-5ca5-3b9e-a613-b0603ffe3038"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=1.9G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.9G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework              2048K       16 \nActivity Tracing                   256K        1 \nCG backing stores                 5504K       16 \nCG image                          8560K      164 \nColorSync                          576K       29 \nCoreAnimation                     16.1M      342 \nCoreData                           128K        1 \nCoreData Object IDs               4112K        2 \nCoreGraphics                        80K        5 \nCoreImage                          256K       13 \nCoreServices                       624K        2 \nCoreUI image data                 5792K       62 \nFoundation                          48K        2 \nImage IO                          1392K       71 \nKernel Alloc Once                   32K        1 \nMALLOC                           424.5M       80 \nMALLOC guard page                  288K       14 \nMALLOC_MEDIUM (reserved)         840.0M        8         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nMemory Tag 244                      16K        1 \nSQLite page cache                 9472K      148 \nSTACK GUARD                       56.2M       10 \nStack                             12.8M       10 \nVM_ALLOCATE                        672K       41 \nWebKit Malloc                    192.0M        4 \n__AUTH                            2533K      310 \n__AUTH_CONST                      20.0M      508 \n__CTF                               756        1 \n__DATA                            15.5M      517 \n__DATA_CONST                      18.8M      532 \n__DATA_DIRTY                      1838K      218 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       578.8M       23 \n__OBJC_CONST                      3590K      285 \n__OBJC_RO                         83.0M        1 \n__OBJC_RW                         3152K        1 \n__TEXT                           490.6M      550 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nlibnetwork                        1664K       24 \nmapped file                      226.6M      115 \nshared memory                      976K       18 \n===========                     =======  ======= \nTOTAL                              3.3G     4150 \nTOTAL, minus reserved VM space     2.1G     4150 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "QSCatalogEntry scanQueue: QSPresetSafariBookmarks"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6112dda2fc54bc3389840642",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "628bd2fda5168570b594bb52"
      },
      "deploymentId" : 240000137
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    }
  ],
  "experiments" : [

  ]
}
}

System Profile:
Network Service: USB 10/100/1000 LAN, Ethernet, en6
Network Service: Wi-Fi, AirPort, en0
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Boot Volume File System Type: apfs
Memory Module: LPDDR5
USB Device: USB31Bus
USB Device: hub_device
USB Device: hub_device
USB Device: SoundSticks
USB Device: Dell Laser Mouse MS3220
USB Device: Keyboard Hub
USB Device: Apple Keyboard
USB Device: composite_device
USB Device: USB31Bus
USB Device: USB3.0 Hub
USB Device: Mass Storage Device
USB Device: USB 10/100/1000 LAN
USB Device: USB2.0 Hub
USB Device: USB 2.0 Hub
USB Device: USB Billboard Device
USB Device: USB31Bus
Display: DELL U2719DC, 2560 x 1440 (QHD/WQHD - Wide Quad High Definition), Main, MirrorOff, Online
Display: Color LCD, 3024 x 1964 Retina, MirrorOff, Online
Display: DELL U2410, 1200 x 1920, MirrorOff, Online
Model: MacBookPro18,3, BootROM 7459.121.3, proc 8:6:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
AirPort: Wi-Fi, wl0: Apr  6 2022 05:55:54 version 20.90.45.0.8.7.118 FWID 01-e7138ff2
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports

### Screenshots

![Screen Shot 2022-06-16 at 10 32 48 AM](https://user-images.githubusercontent.com/51799904/174120862-92842324-38b2-42a8-b2c7-338d006b73a8.png)
![Screen Shot 2022-06-16 at 10 32 36 AM](https://user-images.githubusercontent.com/51799904/174120881-e20d02a1-68d7-4fdc-adfa-0abcc0c965a4.png)

**Comment by pjrobertson** [comment]
Can you please try running the latest development version, which you can download from here: https://github.com/quicksilver/Quicksilver/suites/6960560153/artifacts/271719883

I believe this issue was fixed recently. Thanks

**Comment by pjrobertson** [comment]
Can you please try running the latest development version, which you can download from here: https://github.com/quicksilver/Quicksilver/suites/6960560153/artifacts/271719883

I believe this issue was fixed recently. Thanks

**Comment by foodydude** [comment]
That worked!! It did crash one more time on first launch but gave me the option to delete the plugin that caused it so I did...then after another launch it's stable, I can install plugins again with no crashes. Thank you!

**Comment by pjrobertson** [comment]
Great! Thanks for updating us.
