### ISSUE TITLE
make Latest Screenshot Proxy Object image-type configurable

### ISSUE THREAD

**Issue by anatomatic** [quicksilver/Quicksilver#2892]
I love the new [Latest Screenshot Proxy Object](https://github.com/quicksilver/Quicksilver/pull/2752). However, I generate a mix of .png, .jpg, and .gif files in my screenshots folder.

Is it possible to expand the image types the Proxy Object looks for? The Proxy Object seems to only find .png files at this point.

**Comment by pjrobertson** [comment]
The Latest Screenshot proxy uses Screenshot.app's settings to determine what type of screenshot it pics up.
The default of Screenshot.app is to create PNGs, but you can change this at any time by following the instructions here: https://www.laptopmag.com/uk/articles/change-default-screenshot-file-format-macos

**Comment by anatomatic** [comment]
Thank you — I switched the system default via the command line and it does correctly find the last screenshot JPG I took using the system command. However, that screenshot is years old because I use a screenshot utility.

This might be too niche to be useful to anyone else — but I guess my request is a way to configure the proxy object just search the screenshots folder for the latest image of any time. However it seems proxy objects aren't user-configurable in that way.

I'm also interested in attempting to "roll my own" — but not sure where to start with that.

**Comment by pjrobertson** [comment]
I've created another issue here: to make this a feature request, but currently it's not quite possible.

What you could do is use the QS Command line tool (install the plugin) to open the latest file:
```
ls -At /path/to/my/file/*{*,.*} | head -n1 | qs
```
