### ISSUE TITLE
CI Builds failing

### ISSUE THREAD

**Issue by pjrobertson** [quicksilver/Quicksilver#2895]
@n8henrie - looks like CI builds on the main repo are failing. Yesterday and today.

Error: HTTP status code: 403. A required agreement is missing or has expired. This request requires an in-effect agreement that has not been signed or has expired. Ensure your team has signed the necessary legal agreements and that they are not expired.

From [this post](https://github.com/fastlane/fastlane/issues/19750) it looks like it’s because we need to re-sign the latest Apple Developer agreement? But the plugins seem to be building fine: https://github.com/quicksilver/elements.websearch-qsplugin/actions/runs/2536130041

**Comment by n8henrie** [comment]
> it looks like it’s because we need to re-sign the latest Apple Developer agreement

Sounds like a likely explanation -- @skurfer can you log in at developer.apple.com and see if there is a pending notification?

> But the plugins seem to be building fine

Perhaps because they don't require the `notarytool` stuff, which requires the back-and-forth exchange with Apple.com

**Comment by skurfer** [comment]
I accepted the agreement. Let me know if it didn’t work.

**Comment by n8henrie** [comment]
Reran the most recent job, now succeeding: https://github.com/quicksilver/Quicksilver/actions/runs/2597336768

**Comment by pjrobertson** [comment]
Great! Thanks Rob :)
