### ISSUE TITLE
[Bug]: fn key for trigger hotkeys has two bugs. 

### ISSUE THREAD

**Issue by logiota** [quicksilver/Quicksilver#2897]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

The fn key appears in some hotkeys without adding it
eg: press cmd+alt+(right arrow) and it is confirmed as cmd+alt+fn+(right arrow)

the other thing is that fn hotkeys don't get activated as only the other keys
I will donate 30$ for this feature that has never worked

So wonderful to have QS back

I would also donate to reduced cpu usage!

### Steps to reproduce

1. activate hotkey shortcut recording
2. press cmd+alt+(right arrow)
3. it is confirmed as cmd+alt+fn+(right arrow)

### Expected behavior

it is confirmed as cmd+alt+(right arrow)

### MacOS Version

macOS 12

### Quicksilver Version

2.3.0

### Relevant Plugins

none

### Additional info

standard US keyboard

**Comment by logiota** [comment]
add trigger action seems bugged as well and default is group in third pane

**Comment by pjrobertson** [comment]
Thanks for the report, logiota. This has now fixed, and will be part of an upcoming Quicksilver release.

![Screen Region 2022-06-24 at 07 55 20](https://user-images.githubusercontent.com/150431/175433958-40766ddd-a1cb-4a35-8ca3-bb9087c639fb.png)

For this issue:
> the other thing is that fn hotkeys don't get activated as only the other keys

Can you please open another issue explaining more clearly what you mean, and how to reproduce it. Thanks!

**Comment by pjrobertson** [comment]
P.S. the next version of Quicksilver will also contain a lot of performance/cpu improvements :)
