### ISSUE TITLE
[Bug]: Current selection proxy broken again after update

### ISSUE THREAD

**Issue by g1oria** [quicksilver/Quicksilver#2900]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

This issue has happened before (see this post: https://groups.google.com/g/blacktree-quicksilver/c/51vFajh4kaw/m/XM89AEaqAQAJ) & it's happened again. The trigger I'm trying to use: Current Selection > Look Up in Dictionary.

See attached crash log.

### Steps to reproduce

1. Select text to define in the dictionary
2. Use trigger hotkeys
3. Quicksilver crashes

### Expected behavior

Hotkey should open the dictionary app to selected word

### MacOS Version

macOS 10.15

### Quicksilver Version

2.3.0 (4038)

### Crash Logs or Spindump

[Quicksilver_2022-07-01-130008_Gloria-MacMac.txt](https://github.com/quicksilver/Quicksilver/files/9031547/Quicksilver_2022-07-01-130008_Gloria-MacMac.txt)

**Comment by pjrobertson** [comment]
Thanks Gloria, this was very helpful. I was able to reproduce the bug now, and hopefully it should be fixed in the next version of Quicksilver. Can you please download the version here and confirm it works: https://github.com/quicksilver/Quicksilver/actions/runs/2599804021

Thanks!

**Comment by g1oria** [comment]
It works, thank you!

**Comment by pjrobertson** [comment]
Thanks Gloria.

That's a different and unrelated bug, but it should have now been fixed. You can try the latest build from:
https://github.com/quicksilver/Quicksilver/actions/runs/2626680107
