### ISSUE TITLE
[Bug]: Keyboard Maestro Text Expansion Doesn't Work Consistently In Quicksilver

### ISSUE THREAD

**Issue by g1oria** [quicksilver/Quicksilver#2901]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Keyboard Maestro Text Expansion Doesn't Work In Quicksilver consistently.

### Steps to reproduce

1. Type **.** to enter text in qs UI.
2. Enter text expansion string.
3. Should expand into specified text. Does not.

### Expected behavior

Entering text expansion string in the UI should expand into specified text. Does not. I've reverted to the previous version for now because it works.

### MacOS Version

macOS 10.15

### Quicksilver Version

2.3.0 & 2.2.3

### Screenshots

![screenshot-07-07-2022-15-11-58](https://user-images.githubusercontent.com/17694864/177880789-08c79ebe-db0e-4312-a625-c9b3ffd477f5.png)

**Comment by pjrobertson** [comment]
Hi Gloria,

Can you please update the bug report to clarify that this isn't a *new* issue, but is present also in 2.2.3?

Also, can you please provide the steps used to set up Keyboard Maestro to test this - I am not familiar with that software so would need instructions on how to set it up to reproduce the bug.

Thanks!

**Comment by g1oria** [comment]
@pjrobertson Done. Here's a screenshot of one of my Keyboard Maestro text expansion macros. I just type in the text string specified at the top & it pastes the text shown at the bottom.
![screenshot-07-08-2022-11-23-49](https://user-images.githubusercontent.com/17694864/178049696-6cf354b5-95e9-48df-8d60-11c6c5bf83cd.png)

**Comment by n8henrie** [comment]
FWIW, there's at least a chance that this is a Keyboard Maestro issue. I use (and recommend!) [Espanso](https://espanso.org/) for text expansion, and it works fine in the text pane of 2.3.0.

**Comment by g1oria** [comment]
@n8henrie It actually seems to be working consistently now. Hopefully, it stays that way.
