### ISSUE TITLE
Release build process should also push changelog to website

### ISSUE THREAD

**Issue by pjrobertson** [quicksilver/Quicksilver#2904]
Tagging @n8henrie for this one.

It's my bad, but I always forget to upload the latest `ChangesBare.html` file to the server (final step in the process [here](https://docs.qsapp.com/documentation/release_process#all-releases)). It'd be great if we could automate this, then we can remove it from the list!

**Comment by pjrobertson** [comment]
P.S. I'll try and get round to moving the QS server this week/next week sometime.

**Comment by n8henrie** [comment]
Hmm, I didn't initially realize that this file was gitignored, had planned to just have the server download it from GH.

Will try passing via stdin. May have a few fake tag pushes to trigger.

**Comment by n8henrie** [comment]
Looks like https://github.com/quicksilver/Quicksilver/commit/390ccafde656550126377be094a91358b3dd8831 broke our build.

**Comment by n8henrie** [comment]
Along with https://github.com/quicksilver/server-scripts/commit/0d6a4df33df9f4f3b806ff65d76c79077ace8dc9 I think this should work.

**Comment by n8henrie** [comment]
Also updated the relevant GHA secrets for https://github.com/quicksilver/QSApp.com/pull/34 and https://github.com/quicksilver/manual/pull/14

**Comment by pjrobertson** [comment]
> Looks like https://github.com/quicksilver/Quicksilver/commit/390ccafde656550126377be094a91358b3dd8831 broke our build.
Yeah, the lang files seem to have the wrong encoding. I will fix now.

**Comment by pjrobertson** [comment]
> Will try passing via stdin. May have a few fake tag pushes to trigger.

I was thinking of just scp-ing it at the end of the 'Release' build process. It looks like that's what you've done though, right?

**Comment by n8henrie** [comment]
That probably would have been fine, but I already have a locked-down SSH key for GHA use, so passing the file over stdin/stdout allowed me to reuse the existing setup instead of set up a separate key for SCP (or instead of relax the restrictions on the key).

**Comment by pjrobertson** [comment]
I don't really understand the difference, but if you've considered both options and picked this as the best - then all good!
