### ISSUE TITLE
[Bug]: MacOS Monterey: when update triggered the application hangs, needs to be manually killed and restarted

### ISSUE THREAD

**Issue by wandisco-dbr** [quicksilver/Quicksilver#2905]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Running Mac OS Monterey - latest patches installed.  M1 Mac Mini.

When I get prompted that there is an update, I respond with positive to the update.
Download goes fine (as far as I can tell).
Then the application hangs with the task viewer running.  The beach-ball of doom arrives shortly.  Waiting does not help: I have to kill it manually via Mac OS task manager and then restart.

This is the 3rd update that has hung in this way.

### Steps to reproduce

1. Get notified of new update
2. Tell it to proceed
3. QuickSilver will then hang

100% reproducible in the last 3 updates.

### Expected behavior

I expect the application to exit cleanly and restart itself.

### MacOS Version

macOS 12

### Quicksilver Version

2.0.0 (4027)

### Relevant Plugins

I have no plugins installed.

### Crash Logs or Spindump

Hangs so no crash.  Guess I'll try to get something next time (sorry).

**Comment by pjrobertson** [comment]
This is a known issue with version 2.0 of Quicksilver, and requires you to manually update to the latest version (v2.4.0), by download from https://qsapp.com

Once you've updated to the latest version, you will then be able to update automatically
