### ISSUE TITLE
[Bug]: Incorrect display of some icons

### ISSUE THREAD

**Issue by didaquis** [quicksilver/Quicksilver#2908]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Icons are displayed in some places in the application. Some of these icons are not displayed correctly. It looks as if the background of the icon is not transparent.

<img width="350" alt="Captura de Pantalla 2022-07-21 a las 23 44 04" src="https://user-images.githubusercontent.com/6883041/180321019-348d41bb-8c8f-4de6-8508-e106ef927973.png">

### Steps to reproduce

1. Open the window of preferences

### Expected behavior

The icons should be displayed correctly

### MacOS Version

macOS 12

### Quicksilver Version

2.4.0 (4039)

**Comment by ciltis** [comment]
This has been an issue for me for a couple of years now—any updates?

**Comment by pjrobertson** [comment]
Fixed as of 9bb9c057b312c8a10a30f2d40c8fe83242441d1b 

We will try to get a new release out soon.
<img width="187" alt="Screen Region 2023-08-21 at 18 55 06" src="https://github.com/quicksilver/Quicksilver/assets/150431/6c338517-758d-4a3b-96b6-e0c7a8ae2241">
