### ISSUE TITLE
[Bug]: Names of running background applications show incorrectly

### ISSUE THREAD

**Issue by g1oria** [quicksilver/Quicksilver#2917]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Why is it that when I "show contents" for "Running Applications & Processes" it shows several running Firefox apps in the results?

![unnamed](https://user-images.githubusercontent.com/17694864/183699966-614b81ae-f3cf-4b3b-8c76-777cceb6aa81.png)

![unnamed-1](https://user-images.githubusercontent.com/17694864/183700016-932a4124-e2b0-4207-92e9-702c3099ee74.png)

The weird thing is if I uncheck the box: Include background applications, Firefox doesn't show up at all.

![screenshot-08-08-2022-09-34-00](https://user-images.githubusercontent.com/17694864/183700111-48d87991-390e-460e-bdd5-684f9702f0f1.png)

You can see the conversation about this issue in the QS Google Group [here](https://groups.google.com/g/blacktree-quicksilver/c/2yQso_U647E).

### Steps to reproduce

1. Type "Running Applications" . . .
2. Choose "Show Contents" in 2nd pane
3. Multiple instances of Firefox show up in the results.

### Expected behavior

1 instance of Firefox, rather than many. 1 instance of Firefox even when "include background applications" is unchecked.

### MacOS Version

macOS 10.15

### Quicksilver Version

2.4.0 (4039)

**Comment by pjrobertson** [comment]
Thanks Gloria for reporting. This has now been fixed, see 8f1eb8a617952185abd7a921528dc7eb53a6b9be for full information

**Comment by g1oria** [comment]
Ok. Where do I get the update? Because, according to the releases on the
Github page, the last update was 29 days ago.

**Comment by pjrobertson** [comment]
We'll build and release a new version of Quicksilver in the coming days. If you really want to run it now, you can download a pre-release version from: https://github.com/quicksilver/Quicksilver/actions/runs/2825754664

**Comment by g1oria** [comment]
Ah, ok. Thank you.Message ID:
***@***.***>

>
