### ISSUE TITLE
[Bug]: "Show Menu Items" crashes Quicksilver

### ISSUE THREAD

**Issue by g1oria** [quicksilver/Quicksilver#2918]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Using the "Show Menu Items" action crashes Quicksilver. I have a "command palette" I made for all my apps using "Current Application" & "Show Menu Items" (see screenshot). The issue isn't with the proxy object, I can call that up w/o an issue, but, for some reason, the "Show Menu Items" action crashes Quicksilver. I've attached the crash log. Also, the "Run at Time" & "Run After Delay" items aren't working for some reason. They don't crash the app, they just don't do anything.

### Steps to reproduce

1. Use "Show Menu Items" action.
2. Quicksilver crashes.

### Expected behavior

Quicksilver shouldn't crash.

### MacOS Version

macOS 10.15

### Quicksilver Version

2.4.0 (4039)

### Relevant Plugins

User Interface

### Crash Logs or Spindump

[Quicksilver_2022-08-14-125852_Gloria-MacMac.txt](https://github.com/quicksilver/Quicksilver/files/9334044/Quicksilver_2022-08-14-125852_Gloria-MacMac.txt)

### Screenshots

![screenshot-08-14-2022-13-07-47](https://user-images.githubusercontent.com/17694864/184553354-3a411baa-065e-4ae1-98f5-079f6e358712.png)

**Comment by g1oria** [comment]
Just an update: I completely uninstalled (using the uninstall feature in the app) Quicksilver & then reinstalled it. That seems to have solved the problem.

**Comment by pjrobertson** [comment]
The likely culprit here is the extras setting "Run tasks and actions in the background". We recommend you keep that **unchecked** for stability.

**Comment by g1oria** [comment]
Good to know, thanks. 😁

[image: Headshot]

Regards,

Gloria (Peeps Graphics <http://www.peepsgraphics.com/>)

[image: Instagram] <https://www.instagram.com/peepsgrfx> [image: Facebook]
<https://www.facebook.com/peepsgraphics> [image: Etsy Shop]
<https://www.etsy.com/shop/peepsgraphics> [image: RedBubble Shop]
<https://www.redbubble.com/people/peepsgraphics/shop>
