### ISSUE TITLE
Crashing when computer goes to sleep

### ISSUE THREAD

**Issue by rsagall** [quicksilver/Quicksilver#2928]
Whenever my MacBook Pro goes to sleep Quick Silver crashes. I have the latest version of QS. This has happened for quite a while and doesn't seem to depend on which operating system I use. I always update QS when there's a new version - same for the OS>

**Comment by n8henrie** [comment]
Can you please be more specific about your setup (ideally by following the issue template)?

You may need to manually download a new QS version as there was some difficulty with the built-in updater for a version or two.

**Comment by n8henrie** [comment]
I haven't gotten a reply, so I'm closing this as dead. Please feel free to let me know if I should re-open.
