### ISSUE TITLE
[Bug]: QS stops running

### ISSUE THREAD

**Issue by jwombat** [quicksilver/Quicksilver#2929]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

QS stops running multiple times every day. I'm not sure that it's crashing, there's nothing in the system console log. After restarting it runs for a few hours and then silently quits.

### Steps to reproduce

1. Start QS
2. Wait a few hours
3.

### Expected behavior

QS keeps running.

### MacOS Version

macOS 12

### Quicksilver Version

2.4.0

### Additional info

M1 Mac mini, Monterey 12.6

**Comment by n8henrie** [comment]
Does QS report that it crashed whenever you restart it? (In which case it will usually offer to mail in a crash log.)

If not, I wonder if this might not be a Quicksilver issue, since there are no other indicators that it's crashing. Could something else be closing it?

**Comment by n8henrie** [comment]
> Could there be something in there which doesn’t like Quicksilver running?

It's hard to say.

Have you tried temporarily disabling your plugins to see if the behavior is any different?

Can you try running the binary directly from Terminal.app (and leave it running until this happens) to see what kind of output you get?

Should be able to
1. Quit Quicksilver
2. open Terminal.app
3. paste in `/Applications/Quicksilver.app/Contents/MacOS/Quicksilver` and hit <kbd>return</kbd>
4. It should launch, might give you the request for permissions

Whenever you notice that QS has died, go back to that Terminal window and:

- type `echo $?` <kbd>return</kbd> as the very *first* thing after the command above
- paste any output you find from both commands

**Comment by n8henrie** [comment]
I haven't gotten a reply, so I'm closing this as dead. Please feel free to let me know if I should re-open.
