### ISSUE TITLE
[Bug]: Icon Broken on Secondary Screen

### ISSUE THREAD

**Issue by kmf** [quicksilver/Quicksilver#2930]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

![2022-10-18 at 12 28 14](https://user-images.githubusercontent.com/78700/196456105-6cabbb56-ca47-4bb8-ba24-babcc2d2fabb.png)

<img width="921" alt="2022-10-18 at 16 17 09@2x" src="https://user-images.githubusercontent.com/78700/196456247-2e2ab80b-5bc8-405c-99e1-9e9769b4c2db.png">

If I open the Quicksilver dialog on my Secondary Screen the Icon is broken .... opening on my MacBook Pro's Screen it's fine. 

### Steps to reproduce

1. Open Quicksilver

### Expected behavior

Same Icon to be shown .....

### MacOS Version

macOS 12

### Quicksilver Version

2.4.0 (4039)

**Comment by pjrobertson** [comment]
This will be fixed in the next version of QS. Thanks for reporting.
