### ISSUE TITLE
QS 2.4.0 install woes

### ISSUE THREAD

**Issue by mongpa101** [quicksilver/Quicksilver#2935]
MATERIALS USED
Quicksilver 2.4.0
macOS 10.13.6
Mac Mini 2012

ISSUES
1. QS was installed. Automatic updates were selected but one to version 2.4.0 didn't happen.
2. I happened to do a manual check for updates (from within QS), I allowed all updates that were offered and QS installed version 2.4.0 successfully.
3. I tried to launch QS but the app told me it was incompatible with this version of macOS (10.13.6). I use this version on this computer for a reason.
4. I also have a 15" Mac Retina running macOS 10.14.6 and QS 1.6.0 (again for a good reason). In the process of doing a similar update on it, I chickened out and cancelled the update.
5. On the first computer, where the successful update wouldn't run, I deleted the app and restored version 1.5.5 from a backup. It runs.

RESIDUAL PROBLEMS
a) Should I expect odd behaviour with QS on that first computer, the one where I allowed all updates and then restored an old version of the app?
b) What would happen if I installed QS 2.4.0 on computer 2, running macOS 10.14.6?

Best wishes to the community and especially the developers who make this helpful app available to us. Long life to all!

**Comment by n8henrie** [comment]
> Should I expect odd behaviour with QS on that first computer, the one where I allowed all updates and then restored an old version of the app?

I'm not sure -- likely depends on what version you were running before, and whether any migrations happened of the various configuration files. Was this a QS popup with the version warning? Or an OSX popup? If the latter my guess is that things are probably ok. If the former it's hard to know -- it would be great if you could report back. If you run into issues and have backups (e.g. Time Machine enabled) you could probably restore `~Library/Application\ Support/Quicksilver` and `~/Library/Preferences/com.blacktree.Quicksilver.plist` from before the update.

> What would happen if I installed QS 2.4.0 on computer 2, running macOS 10.14.6?

I did my best to migrate the release notes and version requirements when we went to GitHub releases. It looks like >=2 requires 10.14: <https://github.com/quicksilver/Quicksilver/releases/tag/v2.0.0>

For command-line savvy users, one way to look for these notes in batch is using the GitHub API via their `gh` utility, perhaps piping to `grep -i requires`.

```console
$ gh api --paginate repos/quicksilver/quicksilver/releases --jq '.[] | "\(.name): \(.body)\n"' | grep -i requires
v2.0.0: Requires macOS 10.14
v1.6.0: Requires macOS 10.12
v1.5.7: Requires macOS 10.10
```

Thanks for your kind words! If this answers your concerns please close the issue.
