### ISSUE TITLE
[Bug]: old keybinds cause instant crash

### ISSUE THREAD

**Issue by bendavidson16** [quicksilver/Quicksilver#2948]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

After migrating to a new Mac, a couple of my main keybinds (cmd + spacebar, ctrl + "-") cause an instant crash.

I have since rebound the keyboard triggers to alternate keybinds, but my muscle memory remains and it is causing Quicksilver to constantly crash out. I also have no idea why these keybinds became corrupted within QSApp, and its ridiculously inconvenient that the keys I use most are the ones I now have to avoid.

To be clear, QS is still picking up these key combinations and crashing out, even though they are no longer bound to any triggers at all.

### Steps to reproduce

1. Migrate from 13" MacBook Pro 2017 to 13" MacBook Pro M2.
2. Utilize pre-existing keyboard triggers.

### Expected behavior

QS crashes out immediately, regardless of whether the keyboard triggers have been rebound to alternate keys.

### MacOS Version

macOS 12

### Quicksilver Version

2.0.3

**Comment by bendavidson16** [comment]
I just opened up my triggers plist, and found the source of the issue. Old triggers that I removed from the triggers GUI, had been retained in the plist, leading to crashes. Deleting these old triggers resolved the crashes.

I am leaving this issue open in hopes that this inconsistency between trigger plist/GUI can be addressed. For any user not willing/able to correct their plist manually, this issue might result in perpetual crashes, or the choice to reinstall a fresh version of quicksilver.

**Comment by bendavidson16** [comment]
I just opened up my triggers plist, and found the source of the issue. Old triggers that I removed from the triggers GUI, had been retained in the plist, leading to crashes. Deleting these old triggers resolved the crashes.

I am leaving this issue open in hopes that this inconsistency between trigger plist/GUI can be addressed. For any user not willing/able to correct their plist manually, this issue might result in perpetual crashes, or the choice to reinstall a fresh version of quicksilver.

**Comment by n8henrie** [comment]
I presume he's talking about `~/Library/Application Support/Quicksilver/Triggers.plist`

**Comment by n8henrie** [comment]
I'm not able to reproduce this crash. I tried changing my default <kbd>ctrl</kbd><kbd>space</kbd> to <kbd>ctrl</kbd><kbd>[</kbd>, using both the new and old triggers a bunch of times, relaunching QS, using both triggers a bunch of times, changing them back, using both a bunch of times, adding a new keyboard shortcut trigger, testing it, changing its hotkey, relaunching, testing it... no crashes with any of this.

Can you please retest with the latest release?

If still crashing, can you fill out your issue's `Crash Logs or Spindump` section?

**Comment by DaveEveritt** [comment]
I’m using Excel 16.77 (and Word) from the Office 365 suite on Mac OS Monterey 12.6.6. The annoying part is that there are *no crashes* on one laptop (MacBook Air, the one I’m using) but QS always crashes (either freezing or quitting) when I open the latest Excel or Word from the Office 365 suite on my MacBook Pro (same OS version). I don’t use any other MS apps. I’m out of the country right now with the laptop that *doesn’t* crash QS, so will get back early October with the crash logs (what’s a Spindump?) I’ve saved on the machine that *does* crash QS from Apple’s Activity Monitor.
