### ISSUE TITLE
Homebrew source build?

### ISSUE THREAD

**Issue by ylluminate** [quicksilver/Quicksilver#2950]
It could be useful to modify the Homebrew formula to incorporate a source head build so that folks can get always up-to-date builds since releases have slowed down for Quicksilver.

**Comment by n8henrie** [comment]
I agree!

The respective code is not managed by our org, so I'm going to close, but here is the cask if you want to work on a PR to homebrew. 

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/quicksilver.rb

**Comment by ylluminate** [comment]
Just to make a note, I won't be adding this head build to the Homebrew formula myself, so anyone who ever feels like doing this - please go ahead.
