### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by sambovermont** [quicksilver/Quicksilver#2951]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Been using Quicksilver for many many years....just migrated TMachine to a 2019 MBPro.....Quicksilver is massively memory leaking all of a sudden after years of flawless performance 
![Quicksilver Issue](https://github.com/quicksilver/Quicksilver/assets/9311611/9093a940-ae3b-449b-9af2-7ef2729c19d5)

### Steps to reproduce

1. Quit the app, relaunched, watched the memory usage spike immediately
2.
3.

### Expected behavior

Much less memory usage !

### MacOS Version

macOS 13

### Quicksilver Version

2.4.0

**Comment by n8henrie** [comment]
Have you been through https://qsapp.com/manual/FAQ/#quicksilver-uses-lots-of-memory-cpu-or-hangs ?

You left the plugins section of the template empty -- do you have any enabled? If so, I would recommend disabling them all, restart, and see if the issue is resolved, and then enabling them individually to narrow it down.

I realize this seems onerous, but I doubt we'll be able to remotely figure this out without more information.

**Comment by sambovermont** [comment]
> Have you been through https://qsapp.com/manual/FAQ/#quicksilver-uses-lots-of-memory-cpu-or-hangs ?
> 
> You left the plugins section of the template empty -- do you have any enabled? If so, I would recommend disabling them all, restart, and see if the issue is resolved, and then enabling them individually to narrow it down.
> 
> I realize this seems onerous, but I doubt we'll be able to remotely figure this out without more information.

That worked ! I disabled the plugins and my memory allocation is holding steady !  Super appreciative of the help here.

**Comment by n8henrie** [comment]
No problem! If you have the time and patience to go through and individually re-enable and test the plugins individually, it might be helpful for us to narrow down the issue (to see if we can replicate it). You might consider a "binary search" process -- enable the top half, see if it comes back, if so then subdivide that half in half, etc.

**Comment by eelcocramer** [comment]
@n8henrie when I enable the Safari plugin the cpu starts using 100% and instantly quicksilver starts eating up a lot of memory.
