### ISSUE TITLE
[Bug]: default verb for applications has changed from "Open" to "Run Shortcut" 

### ISSUE THREAD

**Issue by totallyGreg** [quicksilver/Quicksilver#2961]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Update to new version caused the default verb for all applications to change from "Open" to "Run Shortcut"

### Steps to reproduce

1. Update to latest Quicksilver
2. Activate Quicksilver
3. type application name
4. Hit return and watch nothing happen
5. Spend some time confused
6. Notice the verb has changed
7. spend a lot of time typing "open" after selecting an app

### Expected behavior

Default behavior for applications would remain "Open"

### MacOS Version

macOS 13

### Quicksilver Version

2.4.1 (4040)

### Relevant Plugins

<img width="846" alt="image" src="https://github.com/quicksilver/Quicksilver/assets/283704/4811139f-4e80-422f-85cb-fbfbd935c5d2">

### Screenshots

<img width="375" alt="image" src="https://github.com/quicksilver/Quicksilver/assets/283704/f04a04db-1ea1-4dde-89dc-93498c7b174a">

**Comment by pjrobertson** [comment]
This should now be fixed in the latest version of the Shortcuts Plugin. Please upgrade that
