### ISSUE TITLE
[Bug]: OS V14.0 windows fly around randomly

### ISSUE THREAD

**Issue by mactrash** [quicksilver/Quicksilver#2967]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Just updated to OS V14.0 and now Quicksilver fly outside the top left of the screen

### Steps to reproduce

1. Update OSX V14.0 as apple suggested
2. Launch Quicksilver

### Expected behavior

Working normally

### MacOS Version

Other

### Quicksilver Version

2.4.1

**Comment by phriedrich** [comment]
I noticed the same thing:

Quicksilver's start animation is in the very top left corner of the screen, as is the dropdown list from the Bezel or Primer interface.

After disabling "Superfluous visual effects" in the Appearance settings and restarting Quicksilver, it now works.

**Comment by mactrash** [comment]
@phriedrich thanks for your quick fix solution 

it's very difficult to click the Appearance settings indeed 🤪

Thx

**Comment by phriedrich** [comment]
@mactrash If you can invoke Quicksilver by the shortcut, then you can hit `⌘,` (Command + comma) and get to the settings, which should show normally.

**Comment by n8henrie** [comment]
Duplicate: https://github.com/quicksilver/Quicksilver/issues/2962

Please comment or subscribe to that issue to get updates.
