### ISSUE TITLE
[Bug]: 2.4.1 crashes often in Catalina

### ISSUE THREAD

**Issue by Calorion** [quicksilver/Quicksilver#2968]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

After I upgraded to 2.4.1, Quicksilver would crash often, several times a day. Reverting back to 2.4.0 fixed the issue. I’ve submitted several crash reports.

### Steps to reproduce

1. Install QS 2.4.1
2. Wait
3. Observe that QS is not responding to input because it is no longer active.
4. Relaunch QS
5. Note that there is a dialog inviting you to submit a crash report

### Expected behavior

Not crashing.

### MacOS Version

macOS 10.15

### Quicksilver Version

2.4.1

**Comment by Calorion** [comment]
On a separate note, I didn’t think it worthy of its own bug report, but the link to the FAQ at https://docs.qsapp.com/documentation/readme is broken.

**Comment by jorondo1** [comment]
I was having the same issue on Ventura 13.5.1. Since the 13.5.2 update, it doesn't crash, but it's extremely laggy, making most of my typing reflexes too fast for the prompt (I print the characters I want to pass to quicksilver in my currently running app instead). I run a brand new MBP with the M2 chip.

**Comment by v1adimir** [comment]
Me too. Mac mini 2018, Intel, Ventura 13.5.2.

**Comment by tbraas** [comment]
This happens all the time on Sonoma as well. MacBook Pro 16" M1

**Comment by Calorion** [comment]
Still happening in v2.4.2 (4041).

**Comment by n8henrie** [comment]
There are lots of crashes related to the process monitor plugin. Have you tried disabling that?

**Comment by Calorion** [comment]
I don’t know what that is or how to disable it. There’s no “process monitor” plugin in the list of available plugins.

**Comment by n8henrie** [comment]
Sorry, I misspoke, `QSProcessMonitor` is not a separate plugin -- try unchecking `Running Applications & Processes` in your catalog (and then probably relaunch QS).

**Comment by n8henrie** [comment]
Update: https://github.com/quicksilver/Quicksilver/issues/3008#issuecomment-2145307329

Closing the duplicate issues to track in that one.
