### ISSUE TITLE
[Bug]: Interfaces appear in the wrong location or not at all on Sonoma

### ISSUE THREAD

**Issue by skurfer** [quicksilver/Quicksilver#2969]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Nostromo, Primer, and perhaps other interfaces are appearing in the upper left corner of the screen. Sometimes, they don’t appear at all, other than a little flicker of the animation if you dismiss the interface.

This also seems to affect the About window and at one point, I couldn’t get the preferences to appear.

Bezel and Bezel Classic appear unaffected, so if we can figure out what’s different about them, we should be able to apply that to the ones that are acting up.

I have 2 external displays connected, which could be a factor.

### Steps to reproduce

1. Install macOS 14
2. Select Nostromo as your interface
3. Invoke Quicksilver

### Expected behavior

The interface should appear in the center of the active screen.

### MacOS Version

Other

### Quicksilver Version

2.4.1

### Relevant Plugins

Nostromo 1.4.1
Primer

### Screenshots

<img width="1728" alt="Screenshot 2023-09-28 at 11 44 04 AM" src="https://github.com/quicksilver/Quicksilver/assets/154676/04402b8f-d647-4b70-9b70-5e7cf30c1002">

**Comment by n8henrie** [comment]
Tempted to close as a duplicate of https://github.com/quicksilver/Quicksilver/issues/2962 😆

**Comment by aisrael** [comment]
+1 to this. I can't even click on "I have read and accept the terms on this license" on a fresh install of Quicksilver on macOS 14.0

**Comment by skurfer** [comment]
Yeah, it’s a dupe. Sorry.
