### ISSUE TITLE
[Bug]: Since 2.4.1 localized application names are not recognized anymore

### ISSUE THREAD

**Issue by DOCaCola** [quicksilver/Quicksilver#2975]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

After the update from 2.4.0 to 2.4.1 localized app names are not recognized anymore when typing.
In 2.4.0 i can type "Vorschau" (preview in german) to select Preview.app. Though i could also type "preview", where Preview.app would be selected.

Now if i type "Vorschau" it isn't recognized at all anymore. Only if i type "preview", then Preview.app gets selected.

I downgraded (after a month of using 2.4.1) back to 2.4.0 and the localized names were working right out of the box again.

### Steps to reproduce

In MacOS with german localization try to select an app via its localized name. The localized name seems to be unknown to Quicksilver 2.4.1
Working fine in 2.4.0

### Expected behavior

Quicksilver indexes localized App strings

### MacOS Version

macOS 13

**Comment by n8henrie** [comment]
This seems like a good candidate for a regression test once we get a fix!

**Comment by skurfer** [comment]
My guess is fixing this will fix #2970 or vice versa.

**Comment by DOCaCola** [comment]
> My guess is fixing this will fix #2970 or vice versa.

Agreed. That looks to be the same issue. I also only saw applications with their .app extension in 2.4.1 as described in #2970. Obviously this issue gets more apparent when used in non-english environments.

**Comment by ernstki** [comment]
@DOCaCola I wish I could tell you what I'd done (or hadn't done) to avoid this issue, because my Mac also has the German localization enabled, and either "Vors…" or "Prev…" brings up the app for me in 2.4.1.

<img src="https://github.com/quicksilver/Quicksilver/assets/4009681/027443fa-a68f-491e-b7c7-13456ad0dae7" width=400 />

**Comment by DOCaCola** [comment]
Strange. I updated today again to 2.4.1 and for some reason it works now for me as well. Let's wait and see if it stays that way...

**Comment by ernstki** [comment]
> Strange. I updated today again to 2.4.1 and for some reason it works now for me as well. Let's wait and see if it stays that way...

Call that a win, and yes, let's hope!

**Comment by DOCaCola** [comment]
Today i noticed that again localized names are again not recognized in 2.4.1. Restarting Quicksilver didn't help. I downgraded to 2.4.0 again and it worked right away.

**Comment by pjrobertson** [comment]
I started debugging this but my Xcode has now frozen/crashed and I can't continue. For those that can, here's how I would do it using `git bisect`

1. Change your system language to German (or any other language you know)
2. Restart your computer
3. Download v2.4.0 version of Quicksilver and make sure you can search for Preview in the local language
4. Go into the git directory and type `git bisect start v2.4.1 v2.4.0`
5. Build Quicksilver in Xcode and test - if it works properly (you can search for Preview in the local language), type `git bisect good` , if it doesn't work (you can't search) type `git bisect bad`
6. Repeat until `git` tells you the problematic commit.
7. Fix it! (Or post the commit here and I can help fix)
