### ISSUE TITLE
[Bug]: firefox bookmarks not loading

### ISSUE THREAD

**Issue by metropical** [quicksilver/Quicksilver#2983]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Firefox plug isn't finding Bookmarks

### Steps to reproduce

1. activate QS and enter a known FFx bookmark, nothing shows.
2. look at Catalog/Plugins/Firefox/Firefox Bookmarks shows 5.  I have 1000's
3. QS has no problem with Safari bookmarks
4. I just had to do a nuke & pave on my boot drive as I had some odd issue that was causing some apps to misbehave.
5. now on MacOS 12.7 

### Expected behavior

find a related Firefox bookmark.

### MacOS Version

macOS 12

### Quicksilver Version

2.4.1 - (4040)

### Relevant Plugins

Firefox 1.2.1

### Screenshots

![Screen Shot 2023-10-27 at 4 11 57 PM](https://github.com/quicksilver/Quicksilver/assets/38357022/7ba2aa0d-8244-4683-ad34-0448b613835f)

### Additional info

I tried quitting QS, removing the QS Ffx plugin, deleting caches, removing Catalog.plist, restarting QS, then re-adding the Firefox plugin.  same.

**Comment by n8henrie** [comment]
Thanks for making an issue.

In the listserve email I thought you had 0 found, now you have 5 -- what changed?

What firefox version are you running?

**Comment by metropical** [comment]
guess I wrote wrong.  It was always only 5.
FFx 119.

**Comment by n8henrie** [comment]
No, you provided a screenshot on 10/25, no number listed at that time.

**Comment by metropical** [comment]
Dunno.  Nothing I can think of.

**Comment by metropical** [comment]
decided that Firefox had to be at fault, either my install, or install 
sequence, or the cat ate my homework or other quantum surge in the universe.
I deleted FFx and the QS plug, keeping the FFx Profile folder, jic.
Reinstalled FFx then the QS plug.
All bookmarks are found.

**Comment by pjrobertson** [comment]
Great news. I can confirm that FF and QS FF plugin are correctly indexing catalog items here.
