### ISSUE TITLE
QS always shows at top left corner of the screen on first use after computer startup.[Bug]: 

### ISSUE THREAD

**Issue by LuisVxd** [quicksilver/Quicksilver#2984]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

After install Sonoma (14.0) QS shows at top left corner of the screen. Difficult to move to other position as QS window does not follow the cursor, it lags behind.
It always go back to top left corner of the screen at computers startup.

### Steps to reproduce

1. Start the computer
2. Trigger QS
3.

### Expected behavior

I am QS user since 2008. QS always kept window position where it was last closed even after computer restart.

### MacOS Version

Other

### Quicksilver Version

2.4.1 (4040)

### Relevant Plugins

No plugins installed

### Additional info

I have a 2019 Macbook Pro (Intel) with no extra displays and a resolution 1680x1050 (default).
This odd behavior started after install Sonoma. Previously all was ok.

**Comment by randomobject** [comment]
Same here. I'm using latest M1 MacBook. Also happened after upgrade to Sonoma. Previously all good.

**Comment by n8henrie** [comment]
Thanks for your report! This is already being tracked at https://github.com/quicksilver/Quicksilver/issues/2962

**Comment by n8henrie** [comment]
(I realize that this is about the QS interface and the former is about the results list, but I'm pretty sure it's the same underlying problem and fixing one should lead to a fix for the other. Unfortunately I'm having a hard time sorting out the root cause -- but I'm trying.)

**Comment by LuisVxd** [comment]
Yes, I got similar behavior with results list as former. It should be the same issue.
