### ISSUE TITLE
[Bug]: seems QS can't find mnemonics catalog

### ISSUE THREAD

**Issue by metropical** [quicksilver/Quicksilver#2987]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

I deleted the usual caches and tried a mnemonic.plist from a back up.
 
When I type a number expecting to see an acct folder, I get a printer.
~/Library/Printers/Canon
That has not really close to the acct #.
 
12.7, QS 2.41 (4040) 
 

### Steps to reproduce

1. launch QS
2. type in a number related to an acct
3. get my printer instead in results and nothing else.

### Expected behavior

When I type a number expecting to see a credit card folder, I get a printer.
~/Library/Printers/Canon
That has not really close to the acct #.

Before the wipe and reinstall this worked fine.

### MacOS Version

macOS 12

### Quicksilver Version

QS 2.41 (4040)

### Relevant Plugins

not plugs... but...

catalog.plist
mnemonics.plist

### Screenshots

![Screen Shot 2023-11-03 at 4 29 25 PM](https://github.com/quicksilver/Quicksilver/assets/38357022/ac915d02-1d63-4142-ad3c-cf4c6f43938a)

### Additional info

I had to wipe and reinstall my entire drive recently.
I reinstalled QS, did not drag the old app in from back up.
When I check the mnemonics.plist, all of what I'm looking for is there.

**Comment by n8henrie** [comment]
Thanks for making an issue! The screenshot really helps, I couldn't figure out what you were talking about.

What is a credit card folder? Can you go into a little more depth on the name / structure and why you expect typing in numbers to bring it up instead?

Does it appear lower down in your results?

**Comment by metropical** [comment]
bone head again.
I forgot to make copies of the Users/Docs into the custom folder.
All good.

**Comment by n8henrie** [comment]
Glad to hear it's sorted out!
