### ISSUE TITLE
Quicksilver's suggestion pane is detached, unstretchable, and has a totally garbled search...can I uninstall then reinstall without losing my 40 keyboard  command triggers

### ISSUE THREAD

**Issue by sambovermont** [quicksilver/Quicksilver#2989]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Quicksilver's suggestion pane is detached, unstretchable, and has a totally garbled search...can I uninstall then reinstall without losing my 40 keyboard  command triggers

### Steps to reproduce

1. Just basic use of the app....previous keyboard prompts yielded perfect results....seriously worked now
2.
3.

### Expected behavior

To work like before....

### MacOS Version

Other

### Quicksilver Version

Current, just checked for update

**Comment by jdortiz** [comment]
I have the same problem. It also has some problems with the preferences windows, that disappear from screen.

**Comment by pjrobertson** [comment]
To be able to help out you need to provide at least:

1. the Quicksilver version you are using
2. The version of macOS you are using
3. A screenshot of the issue.

**Comment by sambovermont** [comment]
OS : 14.1.1
Qsilver: 2.4.1

￼

**Comment by n8henrie** [comment]
@sambovermont

Quicksilver has several serious bugs on MacOS 14 (Sonoma). Please try the steps here to see if they help, and please report back: https://github.com/quicksilver/Quicksilver/issues/2994 . Thank you!

**Comment by sc8tty** [comment]
Disabling "superfluous visual effects" (linked in the previous post #2994) worked for me. I missed the note about it requiring a restart of QS so make sure you do that.

**Comment by sambovermont** [comment]
Boom ! Fixed ! Thank you so much !!!

**Comment by jonathanalevi** [comment]
Wasted an hour on this freaking problem before coming here. SO ANNOYED.

**Comment by n8henrie** [comment]
Looks like the recommendations worked around the issue for the OP and the newest release forces this behavior at launch-time so will close for now. (In the upcoming version I hope to remove the use of the private APIs which should more fully prevent the issue from cropping up again in the future.)
