### ISSUE TITLE
[Bug]: Results list appearing in upper left-hand corner of screen

### ISSUE THREAD

**Issue by manroygood** [quicksilver/Quicksilver#2991]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Results List appearing on top left of screen as shown in this screenshot. Can't get it to move, even after reinstalling

### Steps to reproduce

1. Run quicksilver
2. start searching a folder
3. notice the results screen is in the wrong spot, and I can't move the window.

### Expected behavior

The results screen is directly under the QS Pane.

### MacOS Version

Other

### Quicksilver Version

2.4.1

### Screenshots

![Screenshot 2023-11-29 at 10 04 52 AM](https://github.com/quicksilver/Quicksilver/assets/31519627/9a94290f-e96c-42bf-a5fc-157a8dd093cc)

### Additional info

Note using MacOS 14, not listed among the dropdown list.

**Comment by n8henrie** [comment]
Duplicate: https://github.com/quicksilver/Quicksilver/issues/2962

Workaround: settings -> appearance -> uncheck "superfluous effects"

Working on a better fix, but it's complicated due to use of private APIs.
