### ISSUE TITLE
[Bug]: Device not configured

### ISSUE THREAD

**Issue by tbird301** [quicksilver/Quicksilver#2997]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Downloaded Quicksilver 2.4.2, when it opened I got this Warning: The following disk images couldn't be opened.  Image: Quicksilver 2.4.2 dmg  Reason: Device not configured.
My OS is 10.14.6.  The Last version installed successfully is 2.4.1

### Steps to reproduce

1. I doubled clicked on Quick 2.2.4.dmg to open it & was going to install the application.
2. Then came the Warning window.
3.

### Expected behavior

Just like previous versions, Drag & Drop the application into the Applications folder.

### MacOS Version

macOS 10.14

### Quicksilver Version

Previous version is 2.4.1

### Screenshots

![Screen Shot](https://github.com/quicksilver/Quicksilver/assets/64787893/229df7f6-dfd7-4cad-a641-2474d501c550)

**Comment by n8henrie** [comment]
Sorry for the trouble, thanks for the report. I've never seen this error before, and the DMG works fine on my machine. Googling for that error reveals a few threads that you might read through:

- https://bugzilla.mozilla.org/show_bug.cgi?id=503338
- https://macosx.com/threads/disk-image-failed-to-mount-device-not-configured.265270/

It sounds like deleting the file, rebooting, redownloading, and trying again would be my first thought.

I don't think this is a Quicksilver issue, but I'll leave this open for a week or so in case other reports come in. Please report back if you find a solution or any additional information.

**Comment by tbird301** [comment]
Nathan,

I got it to open!  What I did was, after closing that message window.  I dbl clicked on the dmg a second time to see if would repeat the same message, this time it opened fire. This never happened with your application before.  Hope I didn’t waste too much of your time. And thank you for your reply.

Have a prosperous New Year,
Tom Fleck

**Comment by n8henrie** [comment]
Weird! Glad you got it to work :) Happy New Year!
