### ISSUE TITLE
[Bug]: v1.6.1 (4026) fresh install on fresh install of El Capitan 10.11.6 and no commands will execute with return key or execute button

### ISSUE THREAD

**Issue by Max-Intosh** [quicksilver/Quicksilver#3000]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Newly installed 10.11.6 and Quicksilver 1.6.1...
After the control space and a few text characters are pressed, and open or other action is selected, hitting enter/return does not execute the command, neither does pressing the execute button in the bezel Quicksilver window.

### Steps to reproduce

1. Rescanned the catalogue
2. Checked preferences, re-ran setup, disabled extensions, etc.
3. Manually selected application and then action and tried again, no luck.

### Expected behavior

The selected application should run/open when executed.

### MacOS Version

Other

### Quicksilver Version

1.6.1 (4028)

### Relevant Plugins

N/A

**Comment by Max-Intosh** [comment]
Also noted that if say Chrome was selected, there are no actions available in the second window of the bezel.

**Comment by n8henrie** [comment]
Sorry you're having trouble!

El Capitan was released in 2015 (and QS 1.6.1 in 2022), unfortunately I strongly doubt that anybody will have much of a chance at reproducing this issue.

Have you been through https://qsapp.com/manual/FAQ/ ? You might try:

1. Quit QS
2. Rename `~/Library/Application Support/Quicksilver` (to `Quicksilver.bak` or what have you)
3. Remove `~/Library/Caches/com.blacktree.Quicksilver` and `~/Library/Caches/Quicksilver`
4. Relaunch QS

That will lose all your settings. If it doesn't help, you should be able to reverse step 2 (will need to overwrite or first delete the new copy that gets created for you upon QS startup) to get things back.

**Comment by pjrobertson** [comment]
The latest version of Quicksilver that's compatible with El Capitan (macOS 10.11) is 1.5.9. You can download that version here: https://github.com/quicksilver/Quicksilver/releases/tag/v1.5.9

Quicksilver 1.6.0 and above requires macOS 10.12 or higher. I suggest you try downloading the 1.5.9 version and retrying.

Closing this bug now. Thanks!
