### ISSUE TITLE
Screen capture taking blank screen.

### ISSUE THREAD

**Issue by D-elias** [quicksilver/Quicksilver#3003]
I reinstalled QS and disabled and reinstalled the image capture plugin and it still takes a picture of a blank screen as if it was a separate monitor. Native Apple shortcuts to take a screenshot do not do this but Quicksilver captures the wallpaper image behind it.

MacBook Pro
16-inch, 2023
Apple M2 Pro
32 GB
14.3.1

Quicksilver 2.4.2

**Comment by n8henrie** [comment]
Go into system settings -> privacy & security -> Screen & system audio recording

- Remove Quicksilver (minus sign bottom left)
- Quit quicksilver
- Relaunch quicksilver
- Accept the permissions popup
- Recheck the settings and make sure enabled
- try again

**Comment by D-elias** [comment]
Thanks
