### ISSUE TITLE
[Bug]: Why not add support for rtc6705

### ISSUE THREAD

**Issue by Tang346** [quicksilver/Quicksilver#3007]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

I want to use RTC6705 to drive my vtx, but this firmware does not support it, do you have a way to add a driver for RTC6705

### Steps to reproduce

1.
2.
3.

### Expected behavior

，

### MacOS Version

None

### Relevant Plugins

，

### Crash Logs or Spindump

，

### Screenshots

，

### Additional info

，

**Comment by n8henrie** [comment]
Sorry, I think you have the wrong repo -- I have no idea what you're talking about.
