### ISSUE TITLE
[Bug]: Not running at all in Sonoma 14.6

### ISSUE THREAD

**Issue by manroygood** [quicksilver/Quicksilver#3015]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

 I upgraded to Sonoma 14.6. Quicksilver (v 2.4.2)  is a startup item on my Mac. It appears to run on startup but crashes immediately when I try to use it and then nothing happens at all when I try to open it again.

### Steps to reproduce

1. Try to run quicksilver on Sonoma 14.6

### Expected behavior

The program should run

### MacOS Version

macOS 10.14

### Quicksilver Version

2.4.2

**Comment by manroygood** [comment]
The problem is much weirder than I thought! Quicksilver is running, but the bezel and the QS menubar icon don't render. If I invoke Quicksilver and the item is the center of my screen is a dark color, I can see the words I type in white on top of it. If I then press the down arrow, I see a list of items as normal.

**Comment by mrlars** [comment]
Same version of SO 14.6 /app 2.4.2, same behavior. 
I use a laptop, if I attach an external display and use QS there, everything is fine.
If i restart the app everything works fine, for a while.

**Comment by n8henrie** [comment]
@manroygood @mrlars this sounds like it may be related to https://github.com/quicksilver/Quicksilver/issues/2994

Can you update to 2.4.3 and report back?

**Comment by manroygood** [comment]
The update seems to fix it. I'll let you know if anything fails. Thanks
