### ISSUE TITLE
Watch directories for modification

### ISSUE THREAD

**Issue by fheckl** [quicksilver/Quicksilver#330]
It may be desirable to have QS watch file system directories for modification to trigger a catalog update for that directory instead of forcing the user to invoke a rescan.
It was among the things I missed most prominently when switching from LaunchBar. E.g. when you install a new application and then want to do something with that  application you now have to wait until QS has picked it up into its catalog after some time.

**Comment by pjrobertson** [comment]
Adding an option in the catalog prefs to 'watch this folder for modifications' I think would be a great feature to add, and shouldn't be too much code.

**Comment by tiennou** [comment]
IIRC, we need to wrap some of the lower-level fs primitives with something that better fits the bill (as per the points made by @daniels220 above). For example, having a "watch" checkbox and a "depth" that don't care about each other feels to me like good UX.

Aaand I have something about that too ;-).
