### ISSUE TITLE
QS - Hide Dock Icon

### ISSUE THREAD

**Issue by pankajxmathur** [quicksilver/Quicksilver#356]
Hi

I would like to hide the dock icon.
I am unable to un-select the setting "Show Icon in Dock" as this setting is checked and disabled.
Can you please suggest how I could do this - this was possible in the earlier versions of QS.

Regards,

Pankaj Mathur

**Comment by 01GOD** [comment]
Confirming that the bool in the preferences to remove that from the dock is functioning in macOS 12.6.
