### ISSUE TITLE
Two Xcode plugins — need sorting

### ISSUE THREAD

**Issue by pjrobertson** [quicksilver/Quicksilver#406]
There is code for 2 Xcode plugins. One is titled com.apple.Xcode.devdocs-qsplugin whilst the other is titled com.apple.Xcode.application-qsplugin

I have a feeling the latter is non-functional, and should therefore be deleted. There's certainly no need for two plugins — it's just confusing.

**Comment by tiennou** [comment]
Closing because PR was merged.
