### ISSUE TITLE
Running Applications & Processes - complicated

### ISSUE THREAD

**Issue by pjrobertson** [quicksilver/Quicksilver#453]
The 'Running Applications & Processes' catalog entry doesn't include background apps as default.
This means you can't perform actions such as 'Quit' on menu-bar only apps (Caffeine, Twitterific etc.)

This seems absolutely ridiculous to me!
To simplify, I suggest this setting be removed and background apps be included by default. The user never needs to know about this...

**Comment by tiennou** [comment]
I think that can be closed, right ?

**Comment by pjrobertson** [comment]
The setting is still there in the 'Running applications and processes' catalog, so it's never been changed

**Comment by tiennou** [comment]
Oh right. Then the question becomes "Do we really want to show background-only applications", especially in the face of things like *hem* Google Chrome and Safari, using processes and sandboxes and whatnot ? :wink:

I know the Process object source is responsible for most of the spurious-look-im-empty pop ups of the Task Window when it's set to Automatically Show.

**Comment by pjrobertson** [comment]
Hmmm true. Revisiting this 5 years later was a good idea ;-)
Now I just see a load of xpc bundles from Sandboxing which are really annoying. But maybe the solution is to make the process object source smarter so it ignores these?

After seeing that I'm ok with leaving this as is for now :D

**Comment by tiennou** [comment]
I'll keep it open. I'm just not sure we can make it smarter. At least I know we can make it *not* deprecated, which would be nicer and less warning-y :laughing:.

**Comment by pjrobertson** [comment]
This seems to be working for me. I can quit Caffeine no problem :D
