### ISSUE TITLE
Allow more than one plugin to add actions for the same application

### ISSUE THREAD

**Issue by charles-e** [quicksilver/Quicksilver#460]
Right now when adding the application actions from a plugin's 
QSRegistry dictionary QS simply calls addEntriesFromDictionary.  What 
this means is that for a given application with a given bundle identifier 
only one plugin can add application actions.  And if two different 
plugins attempt to add application actions for a given app, which ever 
plugin is loaded/registered last "wins". 
I discovered this because I tried to write a little QSPlugin to add an 
update podcast application action for iTunes to sit along side the 
Previous/Next Track actions.

**Comment by pjrobertson** [comment]
It's been a while, @charles-e  - but this has now been fixed ;-)

Feel free to create plugins at ease  😆
