### ISSUE TITLE
Increase font size for cube interface

### ISSUE THREAD

**Issue by ralebaskinson** [quicksilver/Quicksilver#570]
(I submitted this at https://github.com/quicksilver/CubeInterface-qsplugin and got a reply, but then it got removed (apparently all issues should be posted here), so I am reposting here.)

The font size for the cube interface is too small to see comfortably on my screen. If the font size was increased, or if there was an option to specify the font size, it would be very helpful.

The reply I got previously said that I can just pick a different interface, but in my opinion cube is the best one and I would like to stick with it.

**Comment by pjrobertson** [comment]
The Cube interface is no longer supported by Quicksilver.
