### ISSUE TITLE
QS should only allow 1 instance of itself to run

### ISSUE THREAD

**Issue by pjrobertson** [quicksilver/Quicksilver#578]
Just putting out some feeler as to what everyone else thinks.

I often find that QS will magically launch 2 or even 3 copies of itself so I'll have multiple instances of QS running.

I propose sticking something in QSController.m:startQuicksivler that sniffs the currently running processes. If Quicksilver is there, then it Quits.

**Comment by pjrobertson** [comment]
A fairly easy thing to implement I think, but is definitely something that's needed. Assigned to Rob (incase you get time during the sprint!)

**Comment by tiennou** [comment]
I think the behavior I remember is the reverse : if QS detects (via process notifications) another instance of itself starting (e.g. after an update maybe ?) it should quit.

**Comment by skurfer** [comment]
OK, there is code to do this: `-[QSController startQuicksilver:]`

It’s triggered on `NSWorkspaceWillLaunchApplicationNotification`. From the documentation for that notification:

> The system does not post this notification for background apps or for apps that have the 
`LSUIElement` key in their `Info.plist` file.

So that’s why it isn’t working. There is a suggestion, though…

> If you want to know when all apps (including background apps) are launched or terminated, use key-value observing to monitor the value returned by the runningApplications method.

**Comment by pjrobertson** [comment]
I don't think KVO is really needed is it? Would it be as simple as doing something in `startQuicksilver` like:

```objective-c

if ([NSRunningApplication runningApplicationsWithBundleIdentifier:kQSIdentifier] count]) {
    // at least 1 QS instance is already running
    // [self quit]
}
```

**Comment by pjrobertson** [comment]
Going to close this. Most apps allow running multiple versions of themselves. Don't think it makes sense to implement.
