### ISSUE TITLE
Finder 'Sidebar Items' not being cataloged properly

### ISSUE THREAD

**Issue by pjrobertson** [quicksilver/Quicksilver#683]
If I have Catalog Pref Pane > Modules > Finder > Finder Sidebar Items checked, not all my sidebar seem to be indexed. Only 6 out of the eight.

Also, the 'Finder Sidebar Items' catalog entry doesn't have an icon

**Comment by bfulop** [comment]
For me it's `favoriteitems.CustomListItems.*.Alias` that worked (March 2015) – it lists stuff that I put under the Favorites section in Finder.
