### ISSUE TITLE
Plugin Request: Dropbox Plugin

### ISSUE THREAD

**Issue by pjrobertson** [quicksilver/Quicksilver#732]
Here are a list of desired features:
- Actions: Pause/Resume syncing **NOT POSSIBLE**
- Right arrow into Dropbox: Recently changed files 
- For files in the Dropbox folder, some possible actions:
  - Browse on Dropbox Website.
  - View Previous versions (file),
  - Share this folder... (folders) 
  - Get public link action
  - Show badges (you know, the green check mark for synced files, ...) 
    for dropbox files 
- Add dropbox folder to catalog (even if you changed the location) 

Notes:
- Not much is stored in the preferences file
- Most config files are stored in ~/.dropbox in QSLite3 format
- Some stuff is stored in ~/Library/Caches/com.getdropbox.dropbox/com.apple.opencl
- There's no scripting support

**Comment by anatomatic** [comment]
I imagine a full-featured plug-in is still a dead-end, but even a way to copy the Dropbox actions in a file's context menu would still be very useful. At one point there was a Dropbox "Public Link" action that worked before Dropbox's desktop client had a major overhaul, though I can't find the source for that action now.
