### ISSUE TITLE
Current Selection->Add to Things crashes QS

### ISSUE THREAD

**Issue by rasivasu** [quicksilver/Quicksilver#766]
Steps to reproduce the problem:
1.  Open Things.App
2.  Select text in safari browser (or the URL in the Safari address bar)
3.  Bring up QuickSilver by typing CMD-Space
4.  Type 'Current Selection' in the first pane
5.  Type 'Add to Things'

Instead of step 5, if I type 'Large Type', I just hear a beep.

**Comment by pjrobertson** [comment]
It's been a while, closing :)
