### ISSUE TITLE
New actions appear above the default action

### ISSUE THREAD

**Issue by lovequicksilver** [quicksilver/Quicksilver#797]
When adding scripts to ~/Library/Application Support/Quicksilver/Actions/ or when applications install new services, the new actions are often placed just one place above the default action I have set in Preferences>Actions.

Would it be possible to have them placed just below the default action? Or at the end of the Actions List? Then I can always be confident about which action will appear for each object type.

**Comment by studgeek** [comment]
This still is an ongoing issue.

**Comment by n8henrie** [comment]
@studgeek Can you give me a screenshot or a step-by-step on how to reproduce and what you're expecting?

I just typed in `test` and then when to actions and again wrote `test` and set `Paste as Plain Text` for the default action.

I then added a new script in `~/Library/Application Support/Quicksilver/Actions/`, relaunched QS so it would be detected, and repeated the above -- it correctly selected `Paste as Plain Text` as the default action. The newly created script does not appear at the top of my actions in preferences pane either.
