### ISSUE TITLE
Radial Menu Colors

### ISSUE THREAD

**Issue by raptor235** [quicksilver/Quicksilver#850]
I'm hoping that someone could quite easily take this on... the radial menu is quite amazing... I've been looking for this for a long time it reminds me of Maya 3D hotboxes... 

it's quite quick if you can get it configured right... right now the items get listed without issues but I'm hoping we can get finder colours for each item to show up as the background of the radial circle for that item... this would make it MUCH faster to select an item without reading the text... 

In my setup I have a set of shortcut folders which are aliases but I have to read each folder in order to make the selection... being able to select by just scanning for color would represent at least a 100% improvement in speed of selection...

thoughts?

**Comment by pjrobertson** [comment]
Unfortunately the source code for the 'radial menu' / 'constellation interface'  is not available so we're unable to make any changes to it.

If you're able to find out who made the plugin, and find the original source code then we would happily add it to the Quicksilver project and keep it updated!

**Comment by hmelman** [comment]
I could be wrong but I thought Alcor made it.

**Comment by pjrobertson** [comment]
It could be. The Info.plist marks the Plugin Author as:

```
		<key>author</key>
		<string>SAUI P4</string>
```

In any case, I couldn't find the source online.

**Comment by hmelman** [comment]
FWIW "SAUI P4" doesn't mean anything to me.  I looked at old email and as of 2008 (which I think is just after Alcor left QS) people could not find the Constellation source and it was buggy (causing crashes for some menus).  AFAIK it and Abracadabra were UI experiments that were available but didn't get a lot of use or maintenance.
