### ISSUE TITLE
LockScreen in Extra Scripts Plugin is PPC only

### ISSUE THREAD

**Issue by iandol** [quicksilver/Quicksilver#863]
Hi, first off, you guys are doing such great work on QS, it is wonderful to follow some of the github activity to see all the hard work that goes into each improvement.

I recently stated using Extra Scripts Plugin to replace the non-maintained Dockables. The LockScreen app doesn't work on my Intel machine. 

Launch of "LockScreen" failed: the PowerPC architecture is no longer supported.

I've made an Applescript version which is basically:

```applescript
do shell script "/System/Library/CoreServices/Menu\\ Extras/User.menu/Contents/Resources/CGSession -suspend"
```

Which works OK, not sure if there is a more elegant equivalent but it would be good to fix the old command. I used the LockScreen icon by dragging into the icon Get Info pane (which updates .DS_Store IINM) so both old and new commands have the same icon.

I've contacted the designer of the [Dockables](http://www.getdockables.com/) aquaslate icons to ask if they would be usable in QS.

Cheers, and keep up the great work!

Ian

**Comment by pjrobertson** [comment]
Fixed by quicksilver/ExtraScripts-qsplugin#3

**Comment by kellybyrd** [comment]
This doesn't appear to be available in the current version of the plugin. I'm using QS 1.5.2 and the version for "ExtraScripts" plugin is 1.0.1 updated on 4/29/12.

**Comment by skurfer** [comment]
Yikes. It looks like I was updating that plug-in and never finished, so the new version never got released. Thanks for the reminder @kellybyrd.

Anyone know how to tell which directory an AppleScript is running from (using the script itself)?

**Comment by iandol** [comment]
Hi Rob would this help (returns a POSIX path)

```applescript
tell application "Finder"
	set myPath to POSIX path of (container of (path to me) as text)
end tell
```

**Comment by skurfer** [comment]
That seems to work in a stand-alone script, but this thing runs without Finder’s dictionary, so `container` isn’t available. I might be able to do it as a Shell Script.
