### ISSUE TITLE
"Smarter" Spacebar behavior

### ISSUE THREAD

**Issue by sinewave** [quicksilver/Quicksilver#925]
I think it would be really awesome if you could add another option for a "smarter" search bar behavior to the preferences. A lot times i find myself wishing i could combine all the other options instead of having to choose between them. What i would suggest is for the behavior to be context sensitive based on the current selection in the first pane. 

For example pressing the spacebar would perform the following actions in order:

folders/files         - navigate into folder or file (ie show apps recent documents, txt files contents, etc..)
urls                       - jump to argument field 
files                       - quickview for any file that you can't typically navigate into

Other definitions could be made for other file types with the default behavior being show contents.  

It might sound a little confusing on paper but coming for Launchbar which has a similar behavior it actually feels *very* intuitive and definitely subscribes to the quicksilver philosophy :)

**Comment by skurfer** [comment]
This was implemented in #1803 and #2072
