### ISSUE TITLE
search keyword hits app name in English or local language

### ISSUE THREAD

**Issue by hirose31** [quicksilver/Quicksilver#952]
B67 and older: search keywords hits by application name in English. (eg: Calculator.app)
B68: search keywords hits by application name in local language. (eg: 計算機.app "計算機" means calculator in Japanese)

I like previous (B67 and older) behavior. Please rollback search keyword of application name if you will.

**Comment by n8henrie** [comment]
> Go into it and choose "Log Object to Console". 

Oh man, this is handy. Had to enable it in Actions.
