### ISSUE TITLE
File compression plugin should recognize more compressed formats

### ISSUE THREAD

**Issue by daniels220** [quicksilver/Quicksilver#953]
I'd appreciate it if the file compression plugin would recognize (to set "decompress" as an available action) more formats, and formats that have a different extension than standard—for instance, XAR files, but then also XPI files (which are actually Zip) and Safari Extensions (which are the aforementioned XAR).

**Comment by pjrobertson** [comment]
I renamed a .zip file to 'something.xpi' to see what programmes would register it. The Unarchiver didn't recognise the .xpi format. I'm inclined to close this as 'will not fix'. If other standard decompression utilities don't recognise these, then I'd be wary to have Quicksilver do the same - there's the possibility of non-standard files/formats causing issues with the plugin.
